// libs/angular-components/src/lib/components/form/public-form.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from "@angular/core";
import { GoabFormState, GoabPublicFormStatus } from "@abgov/ui-components-common";

@Component({
  selector: "goab-public-form",
  standalone: true,
  template: `
  <goa-public-form
    [attr.status]="status"
    [attr.name]="name"
    (_init)="_onInit($event)"
    (_complete)="_onComplete($event)"
    (_stateChange)="_onStateChange($event)"
  >
    <ng-content />
  </goa-public-form>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoabPublicForm {
  @Input() status?: GoabPublicFormStatus = "complete";
  @Input() name?: string;

  @Output() onInit = new EventEmitter<Event>();
  @Output() onComplete = new EventEmitter<GoabFormState>();
  @Output() onStateChange = new EventEmitter<GoabFormState>();


  _onInit(e: Event) {
    this.onInit.emit(e);
  }

  _onComplete(e: Event) {
    const detail = (e as CustomEvent).detail;
    this.onComplete.emit(detail);
  }

  _onStateChange(e: Event) {
    const detail = (e as CustomEvent).detail;
    this.onStateChange.emit(detail.data);
  }
}

// libs/vue-components/src/lib/form/public-form.vue
<script setup lang="ts">
import type { GoabFormState, GoabPublicFormStatus } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Sets the status. */
  status?: GoabPublicFormStatus;
  /** Sets the name. */
  name?: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  (e: "onInit", detail: Event): void;
  (e: "onComplete", detail: GoabFormState): void;
  (e: "onStateChange", detail: GoabFormState): void;
}>();

const wcProps = useWcProps(props);

function onInit(e: Event) {
  emit("onInit", e);
}

function onComplete(e: Event) {
  emit("onComplete", (e as CustomEvent<GoabFormState>).detail);
}

function onStateChange(e: Event) {
  emit("onStateChange", (e as CustomEvent<{ data: GoabFormState }>).detail.data);
}
</script>

<template>
  <goa-public-form v-bind="wcProps" @_init="onInit" @_complete="onComplete" @_stateChange="onStateChange">
    <slot />
  </goa-public-form>
</template>
