// libs/vue-components/src/lib/menu-button/menu-action.vue
<script setup lang="ts">
import type { GoabIconType } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required Display text for the menu action. */
  text: string;
  /** @required Action identifier included in the click event.  @default "default" */
  action: string;
  /** Icon displayed before the text. */
  icon?: GoabIconType;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, {
  renamedProps: { testId: "testid" },
});
</script>

<template>
  <goa-menu-action v-bind="wcProps" />
</template>

// libs/angular-components/src/lib/components/menu-button/menu-action.ts
import { GoabIconType } from "@abgov/ui-components-common";

import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  // eslint-disable-next-line @angular-eslint/component-selector
  selector: "goab-menu-action",
  template: `
    <goa-menu-action
      [attr.text]="text"
      [attr.action]="action"
      [attr.icon]="icon"
      [attr.testid]="testId"
    >
    </goa-menu-action>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabMenuAction {
  @Input({ required: true }) text!: string;
  @Input({ required: true }) action!: string;
  /** Icon displayed before the text. */
  @Input() icon?: GoabIconType;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  @Input() testId?: string;
}
