// apps/prs/angular/src/routes/docs/menu-button/menu-button.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { GoabMenuAction, GoabMenuButton } from "@abgov/angular-components";
import type { GoabMenuButtonOnActionDetail } from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "abgov-docs-menu-button",
  templateUrl: "./menu-button.component.html",
  imports: [CommonModule, GoabMenuButton, GoabMenuAction],
})
export class DocsMenuButtonComponent {
  handleAction(detail: GoabMenuButtonOnActionDetail): void {
    console.log("action", detail.action);
  }
}

<h2>Menu button</h2>

<h3>Basic menu button</h3>
<goab-menu-button text="Actions" (onAction)="handleAction($event)">
  <goab-menu-action text="Edit" action="edit"></goab-menu-action>
  <goab-menu-action text="Copy" action="copy"></goab-menu-action>
  <goab-menu-action text="Delete" action="delete"></goab-menu-action>
</goab-menu-button>

<h3>Types</h3>
<goab-menu-button text="Primary" type="primary" (onAction)="handleAction($event)">
  <goab-menu-action text="Action 1" action="a1"></goab-menu-action>
  <goab-menu-action text="Action 2" action="a2"></goab-menu-action>
</goab-menu-button>
<goab-menu-button text="Secondary" type="secondary" (onAction)="handleAction($event)">
  <goab-menu-action text="Action 1" action="a1"></goab-menu-action>
  <goab-menu-action text="Action 2" action="a2"></goab-menu-action>
</goab-menu-button>
<goab-menu-button text="Tertiary" type="tertiary" (onAction)="handleAction($event)">
  <goab-menu-action text="Action 1" action="a1"></goab-menu-action>
  <goab-menu-action text="Action 2" action="a2"></goab-menu-action>
</goab-menu-button>

<h3>Icon-only menu button</h3>
<goab-menu-button
  leadingIcon="ellipsis-horizontal"
  ariaLabel="More options"
  (onAction)="handleAction($event)">
  <goab-menu-action text="View details" action="view"></goab-menu-action>
  <goab-menu-action text="Edit" action="edit" icon="pencil"></goab-menu-action>
  <goab-menu-action text="Delete" action="delete" icon="trash"></goab-menu-action>
</goab-menu-button>

<h3>Items with icons</h3>
<goab-menu-button text="Options" (onAction)="handleAction($event)">
  <goab-menu-action text="Download" action="download" icon="download"></goab-menu-action>
  <goab-menu-action text="Share" action="share" icon="share"></goab-menu-action>
  <goab-menu-action text="Print" action="print" icon="print"></goab-menu-action>
</goab-menu-button>

<h3>Sizes</h3>
<goab-menu-button text="Normal" size="normal" (onAction)="handleAction($event)">
  <goab-menu-action text="Action 1" action="a1"></goab-menu-action>
  <goab-menu-action text="Action 2" action="a2"></goab-menu-action>
</goab-menu-button>
<goab-menu-button text="Compact" size="compact" (onAction)="handleAction($event)">
  <goab-menu-action text="Action 1" action="a1"></goab-menu-action>
  <goab-menu-action text="Action 2" action="a2"></goab-menu-action>
</goab-menu-button>

<h3>Destructive variant</h3>
<goab-menu-button text="Primary" variant="destructive" (onAction)="handleAction($event)">
  <goab-menu-action text="Delete item" action="delete" icon="trash"></goab-menu-action>
  <goab-menu-action text="Delete all" action="delete-all" icon="trash"></goab-menu-action>
</goab-menu-button>
<goab-menu-button text="Secondary" variant="destructive" type="secondary" (onAction)="handleAction($event)">
  <goab-menu-action text="Delete item" action="delete" icon="trash"></goab-menu-action>
  <goab-menu-action text="Delete all" action="delete-all" icon="trash"></goab-menu-action>
</goab-menu-button>
<goab-menu-button text="Tertiary" variant="destructive" type="tertiary" (onAction)="handleAction($event)">
  <goab-menu-action text="Delete item" action="delete" icon="trash"></goab-menu-action>
  <goab-menu-action text="Delete all" action="delete-all" icon="trash"></goab-menu-action>
</goab-menu-button>

// apps/prs/react/src/routes/docs/menu-button/menu-button.tsx
import { GoabMenuAction, GoabMenuButton } from "@abgov/react-components";
import type { GoabMenuButtonOnActionDetail } from "@abgov/ui-components-common";

export function DocsMenuButtonRoute() {
  function handleAction(detail: GoabMenuButtonOnActionDetail) {
    console.log("action", detail.action);
  }

  return (
    <div>
      <h2>Menu button</h2>

      <h3>Basic menu button</h3>
      <GoabMenuButton text="Actions" onAction={handleAction}>
        <GoabMenuAction text="Edit" action="edit" />
        <GoabMenuAction text="Copy" action="copy" />
        <GoabMenuAction text="Delete" action="delete" />
      </GoabMenuButton>

      <h3>Types</h3>
      <GoabMenuButton text="Primary" type="primary" onAction={handleAction}>
        <GoabMenuAction text="Action 1" action="a1" />
        <GoabMenuAction text="Action 2" action="a2" />
      </GoabMenuButton>
      <GoabMenuButton text="Secondary" type="secondary" onAction={handleAction}>
        <GoabMenuAction text="Action 1" action="a1" />
        <GoabMenuAction text="Action 2" action="a2" />
      </GoabMenuButton>
      <GoabMenuButton text="Tertiary" type="tertiary" onAction={handleAction}>
        <GoabMenuAction text="Action 1" action="a1" />
        <GoabMenuAction text="Action 2" action="a2" />
      </GoabMenuButton>

      <h3>Icon-only menu button</h3>
      <GoabMenuButton
        leadingIcon="ellipsis-horizontal"
        ariaLabel="More options"
        onAction={handleAction}
      >
        <GoabMenuAction text="View details" action="view" />
        <GoabMenuAction text="Edit" action="edit" icon="pencil" />
        <GoabMenuAction text="Delete" action="delete" icon="trash" />
      </GoabMenuButton>

      <h3>Items with icons</h3>
      <GoabMenuButton text="Options" onAction={handleAction}>
        <GoabMenuAction text="Download" action="download" icon="download" />
        <GoabMenuAction text="Share" action="share" icon="share" />
        <GoabMenuAction text="Print" action="print" icon="print" />
      </GoabMenuButton>

      <h3>Sizes</h3>
      <GoabMenuButton text="Normal" size="normal" onAction={handleAction}>
        <GoabMenuAction text="Action 1" action="a1" />
        <GoabMenuAction text="Action 2" action="a2" />
      </GoabMenuButton>
      <GoabMenuButton text="Compact" size="compact" onAction={handleAction}>
        <GoabMenuAction text="Action 1" action="a1" />
        <GoabMenuAction text="Action 2" action="a2" />
      </GoabMenuButton>

      <h3>Destructive variant</h3>
      <GoabMenuButton text="Primary" variant="destructive" onAction={handleAction}>
        <GoabMenuAction text="Delete item" action="delete" icon="trash" />
        <GoabMenuAction text="Delete all" action="delete-all" icon="trash" />
      </GoabMenuButton>
      <GoabMenuButton
        text="Secondary"
        variant="destructive"
        type="secondary"
        onAction={handleAction}
      >
        <GoabMenuAction text="Delete item" action="delete" icon="trash" />
        <GoabMenuAction text="Delete all" action="delete-all" icon="trash" />
      </GoabMenuButton>
      <GoabMenuButton
        text="Tertiary"
        variant="destructive"
        type="tertiary"
        onAction={handleAction}
      >
        <GoabMenuAction text="Delete item" action="delete" icon="trash" />
        <GoabMenuAction text="Delete all" action="delete-all" icon="trash" />
      </GoabMenuButton>
    </div>
  );
}
