// apps/prs/react/src/routes/docs/skeleton/skeleton.tsx
import { useState } from "react";
import {
  GoabAppFooter,
  GoabAppHeader,
  GoabButton,
  GoabFormStep,
  GoabFormStepper,
  GoabGrid,
  GoabOneColumnLayout,
  GoabPageBlock,
  GoabPages,
  GoabSkeleton,
  GoabSpacer,
} from "@abgov/react-components";
import type { GoabFormStepperOnChangeDetail } from "@abgov/ui-components-common";

export function DocsSkeletonRoute() {
  const [step, setStep] = useState(1);

  const setPage = (page: number) => {
    if (page < 1 || page > 4) return;
    setStep(page);
  };

  return (
    <div>
      <h2>Skeleton loader</h2>

      <h3>Text</h3>
      <GoabSkeleton type="text" mb="s" />
      <GoabSkeleton type="text" mb="s" />
      <GoabSkeleton type="text" mb="s" />
      <GoabSkeleton type="text" />

      <h3>Content types</h3>
      <GoabSkeleton type="text" mb="s" />
      <GoabSkeleton type="text-small" mb="s" />
      <GoabSkeleton type="title" mb="s" />
      <GoabSkeleton type="header" mb="s" />
      <GoabSkeleton type="paragraph" />

      <h3>Media types</h3>
      <GoabSkeleton type="avatar" mb="s" />
      <GoabSkeleton type="thumbnail" mb="s" />
      <GoabSkeleton type="image" size="2" />

      <h3>Composite types</h3>
      <GoabSkeleton type="lines" mb="l" />
      <GoabSkeleton type="profile" mb="l" />
      <GoabSkeleton type="card" mb="l" />
      <GoabSkeleton type="article" />

      <h2>Examples</h2>

      <h3>Basic page layout</h3>
      <GoabOneColumnLayout>
        <section slot="header">
          <GoabAppHeader url="/" heading="Service name">
            <a href="/login">Sign in</a>
          </GoabAppHeader>
        </section>
        <GoabPageBlock width="704px">
          <p>
            <GoabSkeleton type="header" size="4" />
            <GoabSkeleton type="text" size="1" />
          </p>
          <p>
            <GoabSkeleton type="header" size="4" />
            <GoabSkeleton type="text" size="1" />
          </p>
          <GoabGrid minChildWidth="30ch">
            <GoabSkeleton type="card" size="2" />
            <GoabSkeleton type="card" size="2" />
          </GoabGrid>
        </GoabPageBlock>
        <section slot="footer">
          <GoabAppFooter />
        </section>
      </GoabOneColumnLayout>

      <h3>Form stepper with controlled navigation</h3>
      <GoabFormStepper step={step} onChange={(event: GoabFormStepperOnChangeDetail) => setStep(event.step)}>
        <GoabFormStep text="Personal details" />
        <GoabFormStep text="Employment history" />
        <GoabFormStep text="References" />
        <GoabFormStep text="Review" />
      </GoabFormStepper>
      <GoabPages current={step} mb="3xl" mt="xl" mr="xl" ml="xl">
        <div>
          <GoabSkeleton type="article" />
        </div>
        <div>
          <GoabSkeleton type="header" size="2" />
          <GoabSkeleton type="text" />
          <GoabSkeleton type="header" size="2" />
          <GoabSkeleton type="text" />
        </div>
        <div>
          <GoabSkeleton type="text" />
          <GoabSpacer vSpacing="m" />
          <GoabSkeleton type="text" />
        </div>
        <div>
          <GoabSkeleton type="header" size="2" />
          <GoabSkeleton type="text" />
          <GoabSpacer vSpacing="m" />
          <GoabSkeleton type="text" />
        </div>
      </GoabPages>
      <div style={{ display: "flex", justifyContent: "space-between" }}>
        <GoabButton type="secondary" onClick={() => setPage(step - 1)}>
          Previous
        </GoabButton>
        <GoabButton type="primary" onClick={() => setPage(step + 1)}>
          Next
        </GoabButton>
      </div>
    </div>
  );
}

// apps/prs/angular/src/routes/docs/skeleton/skeleton.component.ts
import { Component } from "@angular/core";
import {
  GoabAppFooter, GoabAppHeader, GoabButton, GoabColumnLayout, GoabFormStep,
  GoabFormStepper, GoabGrid, GoabPageBlock, GoabPages, GoabSkeleton, GoabSpacer,
} from "@abgov/angular-components";
import type { GoabFormStepperOnChangeDetail } from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "abgov-docs-skeleton",
  templateUrl: "./skeleton.component.html",
  imports: [
    GoabAppFooter, GoabAppHeader, GoabButton, GoabColumnLayout, GoabFormStep,
    GoabFormStepper, GoabGrid, GoabPageBlock, GoabPages, GoabSkeleton, GoabSpacer,
  ],
})
export class DocsSkeletonComponent {
  step = 1;

  updateStep(event: GoabFormStepperOnChangeDetail): void {
    this.step = event.step;
  }

  setPage(page: number): void {
    if (page < 1 || page > 4) return;
    this.step = page;
  }
}

<h2>Skeleton loader</h2>

<h3>Text</h3>
<goab-skeleton type="text" mb="s"></goab-skeleton>
<goab-skeleton type="text" mb="s"></goab-skeleton>
<goab-skeleton type="text" mb="s"></goab-skeleton>
<goab-skeleton type="text"></goab-skeleton>

<h3>Content types</h3>
<goab-skeleton type="text" mb="s"></goab-skeleton>
<goab-skeleton type="text-small" mb="s"></goab-skeleton>
<goab-skeleton type="title" mb="s"></goab-skeleton>
<goab-skeleton type="header" mb="s"></goab-skeleton>
<goab-skeleton type="paragraph"></goab-skeleton>

<h3>Media types</h3>
<goab-skeleton type="avatar" mb="s"></goab-skeleton>
<goab-skeleton type="thumbnail" mb="s"></goab-skeleton>
<goab-skeleton type="image" size="2"></goab-skeleton>

<h3>Composite types</h3>
<goab-skeleton type="lines" mb="l"></goab-skeleton>
<goab-skeleton type="profile" mb="l"></goab-skeleton>
<goab-skeleton type="card" mb="l"></goab-skeleton>
<goab-skeleton type="article"></goab-skeleton>

<h2>Examples</h2>

<h3>Basic page layout</h3>
<goab-column-layout>
  <section slot="header">
    <header>
      <goab-app-header url="/" heading="Service name">
        <a href="/login">Sign in</a>
      </goab-app-header>
    </header>
  </section>
  <goab-page-block width="704px">
    <p>
      <goab-skeleton type="header" size="4"></goab-skeleton>
      <goab-skeleton type="text" size="1"></goab-skeleton>
    </p>
    <p>
      <goab-skeleton type="header" size="4"></goab-skeleton>
      <goab-skeleton type="text" size="1"></goab-skeleton>
    </p>
    <goab-grid minChildWidth="30ch">
      <goab-skeleton type="card" size="2"></goab-skeleton>
      <goab-skeleton type="card" size="2"></goab-skeleton>
    </goab-grid>
  </goab-page-block>
  <section slot="footer">
    <footer>
      <goab-app-footer></goab-app-footer>
    </footer>
  </section>
</goab-column-layout>

<h3>Form stepper with controlled navigation</h3>
<goab-form-stepper ml="s" mr="s" [step]="step" (onChange)="updateStep($event)">
  <goab-form-step text="Personal details"></goab-form-step>
  <goab-form-step text="Employment history"></goab-form-step>
  <goab-form-step text="References"></goab-form-step>
  <goab-form-step text="Review"></goab-form-step>
</goab-form-stepper>
<goab-pages [current]="step" mb="3xl" mt="xl" mr="xl" ml="xl">
  <div>
    <goab-skeleton type="article"></goab-skeleton>
  </div>
  <div>
    <goab-skeleton type="header" size="2"></goab-skeleton>
    <goab-skeleton type="text"></goab-skeleton>
    <goab-skeleton type="header" size="2"></goab-skeleton>
    <goab-skeleton type="text"></goab-skeleton>
  </div>
  <div>
    <goab-skeleton type="text"></goab-skeleton>
    <goab-spacer vSpacing="m"></goab-spacer>
    <goab-skeleton type="text"></goab-skeleton>
  </div>
  <div>
    <goab-skeleton type="header" size="2"></goab-skeleton>
    <goab-skeleton type="text"></goab-skeleton>
    <goab-spacer vSpacing="m"></goab-spacer>
    <goab-skeleton type="text"></goab-skeleton>
  </div>
</goab-pages>
<div style="display: flex; justify-content: space-between">
  <goab-button (onClick)="setPage(step - 1)" type="secondary">Previous</goab-button>
  <goab-button (onClick)="setPage(step + 1)" type="primary">Next</goab-button>
</div>
