// apps/prs/react/src/routes/features/feat1514.tsx
import { GoabBadge, GoabFilterChip, GoabText } from "@abgov/react-components";

export function Feat1514Route() {
  return (
    <div>
      <GoabText tag="h1" mt="m">
        Feature #1514: FilterChip rich content
      </GoabText>

      <GoabText tag="h3">1. Text content</GoabText>
      <GoabFilterChip content="Text only" />

      <GoabText tag="h3">2. Bold text</GoabText>
      <GoabFilterChip content={<strong>Bold text</strong>} />

      <GoabText tag="h3">3. Strikethrough text</GoabText>
      <GoabFilterChip content={<s>Strikethrough text</s>} />

      <GoabText tag="h3">4. Underline text</GoabText>
      <GoabFilterChip content={<u>Underline text</u>} />

      <div>
        <GoabText tag="h3">5. Text and badge</GoabText>
        <GoabFilterChip
          content={
            <>
              Application status
              <GoabBadge type="success" content="Active" />
            </>
          }
        />
      </div>
    </div>
  );
}

export default Feat1514Route;

// apps/prs/angular/src/routes/features/feat1514/feat1514.component.ts
import { Component } from "@angular/core";
import { GoabBadge, GoabFilterChip, GoabText } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-feat1514",
  templateUrl: "./feat1514.component.html",
  imports: [GoabBadge, GoabFilterChip, GoabText],
})
export class Feat1514Component {}

<goab-text tag="h1" mt="m">Feature #1514: FilterChip rich content</goab-text>

<goab-text tag="h3">1. Text content</goab-text>
<goab-filter-chip content="Text only" />

<goab-text tag="h3">2. Bold text</goab-text>
<goab-filter-chip [content]="boldContent" />

<goab-text tag="h3">3. Strikethrough text</goab-text>
<goab-filter-chip [content]="strikethroughContent" />

<goab-text tag="h3">4. Underline text</goab-text>
<goab-filter-chip [content]="underlineContent" />

<goab-text tag="h3">5. Text and badge</goab-text>
<goab-filter-chip [content]="badgeContent" />

<ng-template #boldContent>
  <strong>Bold text</strong>
</ng-template>

<ng-template #strikethroughContent>
  <s>Strikethrough text</s>
</ng-template>

<ng-template #underlineContent>
  <u>Underline text</u>
</ng-template>

<ng-template #badgeContent>
  Application status
  <goab-badge type="success" content="Active"></goab-badge>
</ng-template>
