// apps/prs/react/src/app/routes.tsx/bugs/bug2750.tsx
import { GoabFormItem, GoabDatePicker } from "@abgov/react-components";

export const Bug2750Route = () => {
  const dateToday = new Date(new Date().setFullYear(new Date().getFullYear() + 100));
  const date100YearsAgo = new Date(
    new Date().setFullYear(new Date().getFullYear() - 100),
  );

  return (
    <main>
      <GoabFormItem label="Date Picker using min" mb="l">
        <GoabDatePicker name="dob" min={date100YearsAgo} />
      </GoabFormItem>
      <GoabFormItem label="Date Picker using min and max" mb="l">
        <GoabDatePicker name="dob" min={date100YearsAgo} max={dateToday} />
      </GoabFormItem>
      <GoabFormItem label="Date picker using max">
        <GoabDatePicker name="dob" max={dateToday} />
      </GoabFormItem>
    </main>
  );
};

// apps/prs/angular/src/routes/bugs/2750/bug2750.component.ts
import { Component } from "@angular/core";
import { GoabFormItem, GoabDatePicker } from "@abgov/angular-components";
import { FormControl } from "@angular/forms";

@Component({
  selector: "abgov-accordion",
  standalone: true,
  templateUrl: "./bug2750.component.html",
  imports: [GoabFormItem, GoabDatePicker],
})
export class Bug2750Component {
  public readonly dateToday = new Date(
    new Date().setFullYear(new Date().getFullYear() + 100),
  );
  public readonly date100YearsAgo = new Date(
    new Date().setFullYear(new Date().getFullYear() - 100),
  );

  dob = new FormControl();
}
