// libs/vue-components/src/lib/spinner/spinner.vue
<script setup lang="ts">
import type { GoabSpinnerSize, GoabSpinnerType } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  type: GoabSpinnerType;
  size: GoabSpinnerSize;
  invert?: boolean;
  progress?: number;
  testId?: string;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, { booleanProps: ["invert"] });
</script>

<template>
  <goa-spinner v-bind="wcProps" />
</template>

// libs/angular-components/src/lib/components/spinner/spinner.ts
import { GoabSpinnerSize, GoabSpinnerType } from "@abgov/ui-components-common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-spinner",
  template: `
    <goa-spinner
      [attr.type]="type"
      [attr.size]="size"
      [attr.invert]="invert"
      [attr.progress]="progress"
      [attr.testid]="testId"
    >
    </goa-spinner>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoabSpinner {
  @Input() type?: GoabSpinnerType;
  @Input() size?: GoabSpinnerSize;
  @Input() invert?: boolean;
  @Input() progress?: number;
  @Input() testId?: string;
}
