// apps/prs/react/src/routes/bugs/bug2331.tsx
import React, { useState } from "react";
import {
  GoabBlock,
  GoabButton,
  GoabTabs,
  GoabTab,
  GoabText,
} from "@abgov/react-components";
import { GoabTabsOnChangeDetail } from "@abgov/ui-components-common";

export function Bug2331Route() {
  const [blockContent, setBlockContent] = useState<string | null>(null);
  const [dynamicTabContent, setDynamicTabContent] = useState<string | null>(null);

  const addBlockContent = () => {
    setBlockContent(`Content updated at ${new Date().toLocaleString()}`);
  };

  const updateDynamicTabContent = () => {
    setDynamicTabContent(`Content updated at ${new Date().toLocaleString()}`);
  };

  const onTabsChange = (detail: GoabTabsOnChangeDetail) => {
    console.log("Tab changed to", detail.tab);
  };

  return (
    <div style={{ width: "1024px", margin: "0 auto" }}>
      <GoabText size="heading-l" mb="xl">
        Bug #2331: Dynamic Data Test
      </GoabText>

      <GoabText size="body-m" mb="2xl">
        This test demonstrates the dynamic data issue with Block and Tab components. Click
        the buttons below to add content dynamically to empty components.
      </GoabText>

      {/* Block Component Test */}
      <GoabText size="heading-m" mb="l">
        GoabBlock Test
      </GoabText>
      <GoabText size="body-s" mb="m">
        Empty Block component
      </GoabText>

      <GoabBlock>{blockContent}</GoabBlock>

      <GoabButton type="secondary" onClick={addBlockContent} mb="2xl">
        Add Content to Block
      </GoabButton>

      {/* Tabs Component Test */}
      <GoabText size="heading-m" mb="l">
        GoabTabs Test
      </GoabText>
      <GoabText size="body-s" mb="m">
        Tabs component with one static and one dynamic tab
      </GoabText>

      <GoabTabs onChange={onTabsChange}>
        <GoabTab heading="Dynamic Content">{dynamicTabContent}</GoabTab>
        <GoabTab heading="Static Content">
          <GoabText size="body-m">Static tab content</GoabText>
        </GoabTab>
      </GoabTabs>

      <GoabButton type="secondary" onClick={updateDynamicTabContent}>
        Update Dynamic Tab Content
      </GoabButton>
    </div>
  );
}

// apps/prs/angular/src/routes/bugs/2331/bug2331.component.ts
import { Component } from "@angular/core";
import {
  GoabBlock,
  GoabButton,
  GoabTabs,
  GoabTab,
  GoabText,
} from "@abgov/angular-components";
import { GoabTabsOnChangeDetail } from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "abgov-bug2331",
  templateUrl: "./bug2331.component.html",
  imports: [GoabBlock, GoabButton, GoabTabs, GoabTab, GoabText],
})
export class Bug2331Component {
  blockContent: string | null = null;
  dynamicTabContent: string | null = null;

  addBlockContent(): void {
    this.blockContent = `Content updated at ${new Date().toLocaleString()}`;
  }

  updateDynamicTabContent(): void {
    this.dynamicTabContent = `Content updated at ${new Date().toLocaleString()}`;
  }

  onTabsChange(detail: GoabTabsOnChangeDetail): void {
    console.log("Tab changed to", detail.tab);
  }
}

<div style="width: 1024px; margin: 0 auto">
  <goab-text size="heading-l" mb="xl"> Bug #2331: Dynamic Data Test </goab-text>

  <goab-text size="body-m" mb="2xl">
    This test demonstrates the dynamic data issue with Block and Tab components. Click the
    buttons below to add content dynamically to empty components.
  </goab-text>

  <!-- Block Component Test -->
  <goab-text size="heading-m" mb="l"> GoabBlock Test </goab-text>
  <goab-text size="body-s" mb="m"> Empty Block component </goab-text>

  <goab-block>{{ blockContent }}</goab-block>

  <goab-button type="secondary" (click)="addBlockContent()" mb="2xl">
    Add Content to Block
  </goab-button>

  <!-- Tabs Component Test -->
  <goab-text size="heading-m" mb="l"> GoabTabs Test </goab-text>
  <goab-text size="body-s" mb="m">
    Tabs component with one static and one dynamic tab
  </goab-text>

  <goab-tabs (onChange)="onTabsChange($event)">
    <goab-tab heading="Dynamic Content">{{ dynamicTabContent }}</goab-tab>
    <goab-tab heading="Static Content">
      <goab-text size="body-m">Static tab content</goab-text>
    </goab-tab>
  </goab-tabs>

  <goab-button type="secondary" (click)="updateDynamicTabContent()">
    Update Dynamic Tab Content
  </goab-button>
</div>
