// libs/react-components/src/experimental/filter-chip/filter-chip.tsx
import { useEffect, useRef } from "react";
import {
  DataAttributes,
  GoabFilterChipTheme,
  GoabIconType,
  Margins,
} from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../../lib/common/extract-props";

interface WCProps extends Margins {
  icontheme: GoabFilterChipTheme;
  error?: string;
  content: string;
  secondarytext?: string;
  leadingicon?: GoabIconType;
  testid?: string;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-filter-chip": WCProps & React.HTMLAttributes<HTMLElement> & {
        ref: React.RefObject<HTMLElement | null>;
      };
    }
  }
}

export interface GoabxFilterChipProps extends Margins, DataAttributes {
  onClick?: () => void;
  iconTheme?: GoabFilterChipTheme;
  /**
   * Shows an error state.
   * @default false
   */
  error?: boolean;
  /**
   * Text label of the chip.
   * @required
   */
  content: string;
  /**
   * Secondary text displayed in a smaller size before the main content.
   * @default ""
   */
  secondaryText?: string;
  /** Icon displayed at the start of the chip. */
  leadingIcon?: GoabIconType;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
  version?: string;
}

export const GoabxFilterChip = ({
  iconTheme = "outline",
  error,
  onClick,
  version = "2",
  ...rest
}: GoabxFilterChipProps) => {
  const el = useRef<HTMLElement>(null);

  const _props = transformProps<WCProps>(
    { icontheme: iconTheme, ...rest },
    lowercase
  );

  useEffect(() => {
    if (!el.current) return;
    if (!onClick) return;

    const current = el.current;

    current.addEventListener("_click", onClick);
    return () => {
      current.removeEventListener("_click", onClick!);
    };
  }, [el, onClick]);

  return (
    <goa-filter-chip
      ref={el}
      error={error ? "true" : undefined}
      version={version}
      {..._props}
    />
  );
};

export default GoabxFilterChip;

// libs/vue-components/src/lib/filter-chip/filter-chip.vue
<script setup lang="ts">
import type { GoabFilterChipTheme, GoabIconType, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required Text label of the chip.  @default (required) */
  content: string;
  /** Theme style of the leading icon. @default "outline" */
  iconTheme?: GoabFilterChipTheme;
  /** Shows an error state.  @default "false" */
  error?: boolean;
  /** Secondary text displayed in a smaller size before the main content.  @default "" */
  secondaryText?: string;
  /** Icon displayed at the start of the chip.  @default null */
  leadingIcon?: GoabIconType;
  /** Sets a data-testid attribute for automated testing.  @default "" */
  testId?: string;
  /** Sets the mt.  @default null */
  mt?: Spacing;
  /** Sets the mr.  @default null */
  mr?: Spacing;
  /** Sets the mb.  @default null */
  mb?: Spacing;
  /** Sets the ml.  @default null */
  ml?: Spacing;
}

const props = withDefaults(defineProps<Props>(), {
  iconTheme: "outline",
});
const emit = defineEmits<{
  /** Callback fired when the filter chip is clicked to remove it. */
  onClick: [];
}>();

const wcProps = useWcProps(props, { booleanProps: ["error"] });
</script>

<template>
  <goa-filter-chip v-bind="wcProps" @_click="emit('onClick')" />
</template>
