// apps/react-demo/src/routes/formStepper.tsx
import {useState} from "react";
import {GoAButton, GoAFormStep, GoAFormStepper, GoAFormStepStatusType, GoAPages} from "@abgov/react-components";

export function FormStepperRoute() {
  const [step, setStep] = useState<number>(2);
// controlled by the user based on form completion
  const [status, setStatus] = useState<GoAFormStepStatusType[]>([
    "complete",
    "complete",
    "complete",
    "complete"
  ])
  function setPage(page: number) {
    if (page < 1 || page > 4) return;
    setStep(page);
  }
  return (
    <>
      <GoAFormStepper step={step} onChange={setStep}>
        <GoAFormStep text="Personal details" status={status[0]} />
        <GoAFormStep text="Employment history" status={status[1]} />
        <GoAFormStep text="References" status={status[2]} />
        <GoAFormStep text="Review" status={status[3]} />
      </GoAFormStepper>
      <GoAPages current={step} mb="xl">
        <div>1</div>
        <div>2</div>
        <div>3</div>
        <div>4</div>
      </GoAPages>
      <div style={{display: 'flex', justifyContent: 'space-between'}}>
        <GoAButton type="secondary" onClick={() => setPage(step - 1)}>Previous</GoAButton>
        <GoAButton type="primary" onClick={() => setPage(step + 1)}>Next</GoAButton>
      </div>
    </>
  )
}

// _templates/angular/src/app/form-stepper/form-stepper.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "goab-form-stepper",
  templateUrl: "./form-stepper.component.html",
})
export class FormStepperComponent {
  step = -1;

  // controlled by the user based on form completion
  status = ["complete", "complete", "incomplete"];

  updateStep(event: Event) {
    console.log((event as CustomEvent).detail)
    this.step = (event as CustomEvent).detail.step;
  }

  setPage(page: number) {
    console.log("setting page..", page)
    if (page < 1 || page > 4) return;
    this.step = page;
  }
}

<h1>Form Stepper</h1>

<h4>Free</h4>

<goab-form-stepper ml="s" mr="s" [step]="freeStep" (onChange)="updateFreeStep($event)">
  <goab-form-step text="Personal details" [status]="status[0]"></goab-form-step>
  <goab-form-step text="Employment history" [status]="status[1]"></goab-form-step>
  <goab-form-step text="References" [status]="status[2]"></goab-form-step>
  <goab-form-step text="Review" [status]="status[3]"></goab-form-step>
</goab-form-stepper>
<goab-pages [current]="freeStep">
  <div>Page 1 content</div>
  <div>Page 2 content</div>
  <div>Page 3 content</div>
  <div>Page 4 content</div>
</goab-pages>
<div style="display: flex; justify-content: space-between">
  <goab-button (onClick)="setFreePage(freeStep - 1)" type="secondary">Previous</goab-button>
  <goab-button (onClick)="setFreePage(freeStep + 1)" type="primary">Next</goab-button>
</div>

<h4>Contrained</h4>

<goab-form-stepper ml="s" mr="s" [step]="constrainedStep" (onChange)="updateConstrainedStep($event)">
  <goab-form-step text="Personal details" [status]="status[0]"></goab-form-step>
  <goab-form-step text="Employment history" [status]="status[1]"></goab-form-step>
  <goab-form-step text="References" [status]="status[2]"></goab-form-step>
  <goab-form-step text="Review" [status]="status[3]"></goab-form-step>
</goab-form-stepper>
<goab-pages [current]="constrainedStep">
  <div>Page 1 content</div>
  <div>Page 2 content</div>
  <div>Page 3 content</div>
  <div>Page 4 content</div>
</goab-pages>
<div style="display: flex; justify-content: space-between">
  <goab-button (onClick)="setConstrainedPage(constrainedStep - 1)" type="secondary">Previous</goab-button>
  <goab-button (onClick)="setConstrainedPage(constrainedStep + 1)" type="primary">Next</goab-button>
</div>
