// libs/react-components/src/lib/hero-banner/link/hero-banner-link.component.tsx
import React, { FC, Fragment } from 'react';
import './hero-banner-link.component.scss';

interface Props {
  linkText: string;
  linkUrl: string;
}

export const GoAHeroBannerLink: FC<Props> = ({ linkText, linkUrl }) => {
  return linkText && linkUrl ? (
    <div>
      <a className="goa-link-button right-arrow" href={linkUrl} role="link">
        {linkText}
      </a>
    </div>
    ) : <Fragment></Fragment>
  ;
};

// libs/angular-components/src/lib/hero-banner/link/hero-banner-link.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'goa-hero-banner-link',
  templateUrl: './hero-banner-link.component.html',
  styleUrls: ['./hero-banner-link.component.scss']
})
export class GoAHeroBannerLinkComponent implements OnInit {

  @Input() url: string;

  constructor() { }

  ngOnInit(): void {
  }

}

<ng-container>
  <a class="goa-link-button right-arrow" [href]="url" role="link">
    <ng-content></ng-content>
  </a>
</ng-container>
