// apps/prs/react/src/routes/docs/app-header/app-header.tsx
import {
  GoabAppHeader,
  GoabAppHeaderMenu,
  GoabBadge,
  GoabButton,
  GoabMenuAction,
  GoabMenuButton,
} from "@abgov/react-components";

export function DocsAppHeaderRoute() {
  return (
    <div>
      <h2>App header</h2>

      <h3>Basic app header</h3>
      <GoabAppHeader heading="My Application" />

      <h3>With home link</h3>
      <GoabAppHeader heading="My Application" url="/" />

      <h3>With secondary text</h3>
      <GoabAppHeader
        heading="My Application"
        secondaryText="Supporting information"
        url="/"
      />

      <h3>With utilities</h3>
      <GoabAppHeader
        heading="My Application"
        url="/"
        utilities={
          <>
            <GoabButton type="tertiary" size="compact">
              Help
            </GoabButton>
            <GoabButton type="tertiary" size="compact" leadingIcon="person">
              Sign in
            </GoabButton>
          </>
        }
      />

      <h3>With phase badge</h3>
      <GoabAppHeader
        heading="My Application"
        url="/"
        phase={<GoabBadge type="important" content="Service preview" />}
      />

      <h3>Internal testing banner</h3>
      <GoabAppHeader
        heading="My Application"
        url="/"
        banner={
          <span
            style={{
              textAlign: "right",
              width: "100%",
              fontSize: "12px",
              fontWeight: "normal",
            }}
          >
            v2.3.1 | UAT Environment
          </span>
        }
      />

      <h3>With navigation</h3>
      <GoabAppHeader
        heading="Service Portal"
        url="/"
        navigation={
          <>
            <a href="#">Dashboard</a>
            <GoabAppHeaderMenu heading="Applications">
              <a href="#">New application</a>
              <a href="#">Active</a>
              <a href="#">Archived</a>
            </GoabAppHeaderMenu>
            <a href="#">Reports</a>
            <a href="#">Settings</a>
          </>
        }
        utilities={
          <GoabMenuButton text="John Smith" type="tertiary" size="compact">
            <GoabMenuAction text="User settings" action="user-settings" />
            <GoabMenuAction text="Sign out" action="sign-out" />
          </GoabMenuButton>
        }
      />
    </div>
  );
}

// apps/prs/angular/src/routes/docs/app-header/app-header.component.ts
import { Component } from "@angular/core";
import {
  GoabAppHeader,
  GoabAppHeaderMenu,
  GoabBadge,
  GoabButton,
  GoabMenuAction,
  GoabMenuButton,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-app-header",
  templateUrl: "./app-header.component.html",
  imports: [
    GoabAppHeader,
    GoabAppHeaderMenu,
    GoabBadge,
    GoabButton,
    GoabMenuAction,
    GoabMenuButton,
  ],
})
export class DocsAppHeaderComponent {}

<ng-template #utilitiesTemplate1>
  <goab-button type="tertiary" size="compact">Help</goab-button>
  <goab-button type="tertiary" size="compact" leadingIcon="person">Sign in</goab-button>
</ng-template>

<ng-template #phaseTemplate>
  <goab-badge type="important" content="Service preview"></goab-badge>
</ng-template>

<ng-template #bannerTemplate>
  <span style="text-align: right; width: 100%; font-size: 12px; font-weight: normal">
    v2.3.1 | UAT Environment
  </span>
</ng-template>

<ng-template #navigationTemplate>
  <a href="#">Dashboard</a>
  <goab-app-header-menu heading="Applications">
    <a href="#">New application</a>
    <a href="#">Active</a>
    <a href="#">Archived</a>
  </goab-app-header-menu>
  <a href="#">Reports</a>
  <a href="#">Settings</a>
</ng-template>

<ng-template #utilitiesTemplate2>
  <goab-menu-button text="John Smith" type="tertiary" size="compact">
    <goab-menu-action text="User settings" action="user-settings"></goab-menu-action>
    <goab-menu-action text="Sign out" action="sign-out"></goab-menu-action>
  </goab-menu-button>
</ng-template>

<h2>App header</h2>

<h3>Basic app header</h3>
<header>
  <goab-app-header heading="My Application"></goab-app-header>
</header>

<h3>With home link</h3>
<header>
  <goab-app-header heading="My Application" url="/"></goab-app-header>
</header>

<h3>With secondary text</h3>
<header>
  <goab-app-header heading="My Application" secondaryText="Supporting information" url="/"></goab-app-header>
</header>

<h3>With utilities</h3>
<header>
  <goab-app-header
    heading="My Application"
    url="/"
    [utilities]="utilitiesTemplate1"
  ></goab-app-header>
</header>

<h3>With phase badge</h3>
<header>
  <goab-app-header
    heading="My Application"
    url="/"
    [phase]="phaseTemplate"
  ></goab-app-header>
</header>

<h3>Internal testing banner</h3>
<header>
  <goab-app-header
    heading="My Application"
    url="/"
    [banner]="bannerTemplate"
  ></goab-app-header>
</header>

<h3>With navigation</h3>
<header>
  <goab-app-header
    heading="Service Portal"
    url="/"
    [navigation]="navigationTemplate"
    [utilities]="utilitiesTemplate2"
  ></goab-app-header>
</header>
