// libs/react-components/src/experimental/skeleton/skeleton-element.tsx
import React from 'react';
import './skeleton-element.scss';

type indicatorType = 'text' | 'avatar' | 'title' | 'paragraph' | 'thumbnail' | 'card';

export interface SkeletonProps {
  type?: indicatorType;
}

export const GoASkeletonElement = ({ type = 'text' }: SkeletonProps) => {
  const classes = `skeleton ${type}`;

  return <div className={classes}></div>;
};

// libs/angular-components/src/experimental/skeleton/skeleton-element.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'goa-skeleton-element',
  templateUrl: './skeleton-element.component.html',
  styleUrls: ['./skeleton-element.component.scss'],
})
export class GoASkeletonElementComponent {
  @Input() type:
    | 'text'
    | 'avatar'
    | 'title'
    | 'paragraph'
    | 'thumbnail'
    | 'card' = 'text';

  constructor() {}

  get elementClass(): string {
    return `skeleton ${this.type}`;
  }

}
