// libs/vue-components/src/lib/skeleton/skeleton-image-content.vue
<template>
  <div class="skeleton-image-content">
    <goa-skeleton-element type="thumbnail" />
    <div class="skeleton-image-content__text">
      <goa-skeleton-element type="title" />
      <div v-for="row in rows" :key="row">
        <goa-skeleton-element type="text" />
      </div>
    </div>
  </div>
</template>

<script lang="typescript">

import GoASkeletonElement from './skeleton-element.vue';

export default {
  name: 'goa-skeleton-image-content',
  components: {
    'goa-skeleton-element': GoASkeletonElement,
  },
  props: {
    /**
     * The number of rows to display.
     */
    rows: {
      type: Number,
      default: 1,
      required: false,
      },
    }
}
</script>

<style lang="scss" scoped>
@import './skeleton-element.scss';
</style>

// libs/angular-components/src/experimental/skeleton/skeleton-image-content.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'goa-skeleton-image-content',
  templateUrl: './skeleton-image-content.component.html',
  styleUrls: ['./skeleton-element.component.scss'],
})
export class GoASkeletonImageContentComponent {
  @Input() rows = 1;

  arr = Array;
  constructor() {}


}

<div class="skeleton-image-content">
  <goa-skeleton-element type="thumbnail"></goa-skeleton-element>
  <div class="skeleton-image-content__text">
    <goa-skeleton-element
      type="title"
      *ngFor="let i of arr(rows).fill(1)"
    ></goa-skeleton-element>
  </div>
</div>
