// apps/prs/react/src/routes/bugs/bug4030.tsx
import { GoabAppFooter, GoabText } from "@abgov/react-components";

export function Bug4030Route() {
  return (
    <div>
      <GoabText tag="h1" mt="m" mb="m">
        Bug #4030: Footer copyright text
      </GoabText>
      <GoabText tag="p" mb="l">
        The V2 footer should show a single span "© 2026 Government of Alberta". The
        "This is a Government of Alberta Digital Service" span and the "GoA" abbreviation
        should both be removed.
      </GoabText>

      <GoabAppFooter version="2" />
    </div>
  );
}

export default Bug4030Route;

// apps/prs/angular/src/routes/bugs/4030/bug4030.component.ts
import { Component } from "@angular/core";
import { GoabAppFooter, GoabText } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug4030",
  templateUrl: "./bug4030.component.html",
  imports: [GoabAppFooter, GoabText],
})
export class Bug4030Component {}

<goab-text tag="h1" mt="m" mb="s">Bug 4030 - Footer: copyright text</goab-text>
<goab-text mb="l">
  The V2 footer should show a single span "© 2026 Government of Alberta".
  The "This is a Government of Alberta Digital Service" span and "GoA" abbreviation should both be removed.
</goab-text>

<goab-app-footer version="2" />
