// libs/vue-components/src/lib/card/card.vue
<template>
  <div class="goa-card" :style="{ width: this.getCardWidth }">
    <div class="goa-poster">
      <img v-if="this.hasImage" :src="this.cardImageUrl" alt="Card cardImageUrl" />
    </div>

    <div class="card-content">

       <a class="goa-title" v-if="this.hasTitleUrl" :href="this.titleUrl"> {{ title }} </a>
      <div class="goa-title" v-if="!this.hasTitleUrl">{{ title }} </div>

      <div class="goa-text">
        {{ description }}
      </div>
       <div  slot-scope class="goa-footer">
         <slot/>
       </div>
    </div>
  </div>
</template>
<script lang="typescript">
export default {
  name: 'goa-card',
  props: {
    /**
     * Card title.
     */
    title: {
      type: String,
      required: true,
    },
        /**
     * Card title url .
     */
    titleUrl: {
      type: String,
      required: false,
    },

    /**
     * Card description
     */
    description: {
      type: String,
      required: false,
    },
    /** Card image , display on top of title */
    cardImageUrl: {
      type: String,
      required: false,
    },
    /** Display card size to allow card responsively show in different device*/
    cardWidth: {
       type: [ String, Number],
       required: false,
       default:'auto',

    },
  },
  data() {
    return {

    };
  },
  computed: {
    hasImage() {
      return Boolean(this.cardImageUrl);
    },
    hasTitleUrl() {
      return Boolean(this.titleUrl);
    },

    getCardWidth(){
      if((typeof this.cardWidth) === "number"){
        return this.cardWidth+"px";
      }
     return (this.cardWidth==='full'? this.cardWidth:'auto');
    }
  },
};
</script>

// libs/react-components/src/lib/card/card.component.tsx
import React, { FC } from 'react';
import '../../theme.scss';
import './card.scss';
type CardWidth = 'full' | 'auto' | number;
interface Props {
  /** Card title, required */
  title: string;
  /** Card description */
  description?: JSX.Element | string;
  /** Card image , display on top of title */
  cardImageUrl?: string;
  /** Display card size to allow card responsively show in different device*/
  cardWidth?: CardWidth;
  /** Navigation to relate webside from Card title */
  titleUrl?: string;
  /** customize footer by passing react component code */
  children?: React.ReactNode;
}
export const GoACard: FC<Props> = ({
  title,
  description = null,
  cardImageUrl = null,
  cardWidth = 'auto',
  titleUrl = null,
  children = null,
}) => {
  return (
    <div className="goa-card" style={{ width: cardWidth }}>
      {cardImageUrl && (
        <div className="goa-poster">
          <img src={cardImageUrl} alt="Card cardImageUrl" />
        </div>
      )}
      <div className="card-content">
        <div className="goa-title">
          {titleUrl ? <a href={titleUrl}>{title}</a> : title}
        </div>
        <div className="goa-text">{description}</div>
        <div className="goa-footer">{children}</div>
      </div>
    </div>
  );
};

export default GoACard;
