// libs/react-components/src/lib/pagination/pagination.tsx
import { GoabPaginationOnChangeDetail, Margins } from "@abgov/ui-components-common";
import { useEffect, useRef } from "react";

interface WCProps extends Margins {
  ref?: React.RefObject<HTMLElement | null>;
  itemcount: number;
  perpagecount?: number;
  pagenumber: number;
  variant?: "all" | "links-only";
  testid?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-pagination": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoabPaginationProps extends Margins {
  /** @required Total number of data items within all pages. */
  itemCount: number;
  /** @required The current page being viewed (non-zero based). */
  pageNumber: number;
  /** @required Callback fired when the user navigates to a different page. */
  onChange: (detail: GoabPaginationOnChangeDetail) => void;
  /** Number of data items shown per page. @default 10 */
  perPageCount?: number;
  /** Controls which nav controls are visible. @default "all" */
  variant?: "all" | "links-only";
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
}

// legacy
export type PaginationProps = GoabPaginationProps;

/** Help users navigation between multiple pages or screens as part of a set. */
export function GoabPagination({ onChange, ...props }: GoabPaginationProps) {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!ref.current) {
      return;
    }
    const current = ref.current;
    const changeListener = (e: Event) => {
      const detail = (e as CustomEvent<GoabPaginationOnChangeDetail>).detail;
      onChange(detail);
    };

    current.addEventListener("_change", changeListener);
    return () => {
      current.removeEventListener("_change", changeListener);
    };
  }, [ref, onChange]);

  return (
    <goa-pagination
      ref={ref}
      itemcount={props.itemCount}
      perpagecount={props.perPageCount}
      pagenumber={props.pageNumber}
      variant={props.variant}
      mt={props.mt}
      mb={props.mb}
      ml={props.ml}
      mr={props.mr}
      testid={props.testId}
    />
  );
}

export default GoabPagination;

// libs/vue-components/src/lib/pagination/pagination.vue
<script setup lang="ts">
import type { GoabPaginationOnChangeDetail, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required Total number of data items within all pages.  @default (required) */
  itemCount: number;
  /** @required The current page being viewed (non-zero based).  @default (required) */
  pageNumber: number;
  /** Number of data items shown per page. @default 10 */
  perPageCount?: number;
  /** Controls which nav controls are visible. @default "all" */
  variant?: "all" | "links-only";
  /** Sets a data-testid attribute for automated testing.  @default "" */
  testId?: string;
  /** Sets the mt.  @default "none" */
  mt?: Spacing;
  /** Sets the mr.  @default "none" */
  mr?: Spacing;
  /** Sets the mb.  @default "m" */
  mb?: Spacing;
  /** Sets the ml.  @default "none" */
  ml?: Spacing;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  /** @required Callback fired when the user navigates to a different page. */
  onChange: [detail: GoabPaginationOnChangeDetail];
}>();

const wcProps = useWcProps(props);
</script>

<template>
  <goa-pagination v-bind="wcProps" @_change="emit('onChange', $event.detail)" />
</template>
