// libs/vue-components/src/lib/hero-banner/hero-banner-link.vue
<template>
  <div>
    <a class="goa-link-button right-arrow" :href='linkUrl' role="link">
      {{linkText}}
    </a>
  </div>
</template>
<script lang="typescript">

export default {
  name: 'goa-hero-banner-link',
  props: {
   /**
     * The text displaye for the link/button.
     */
    linkText: {
      type: String,
      required: false,
    },
    /**
     * The Url for the link/button.
     */
    linkUrl: {
      type: String,
      required: false,
    },
  },
  data() {
    return {

    };
  },
};
</script>

// libs/react-components/src/lib/hero-banner/link/hero-banner-link.component.tsx
import React, { FC, Fragment } from 'react';
import './hero-banner-link.component.scss';

interface Props {
  linkText: string;
  linkUrl: string;
}

export const GoAHeroBannerLink: FC<Props> = ({ linkText, linkUrl }) => {
  return linkText && linkUrl ? (
    <div>
      <a className="goa-link-button right-arrow" href={linkUrl} role="link">
        {linkText}
      </a>
    </div>
    ) : <Fragment></Fragment>
  ;
};
