// libs/vue-components/src/lib/block/block.vue
<script setup lang="ts">
import type { GoabBlockAlignment, GoabBlockDirection, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Sets the gap.  @default "m" */
  gap?: Spacing;
  /** Sets the direction.  @default "row" */
  direction?: GoabBlockDirection;
  /** Sets the alignment.  @default "normal" */
  alignment?: GoabBlockAlignment;
  /** Sets the min width.  @default "" */
  minWidth?: string;
  /** Sets the max width.  @default "" */
  maxWidth?: string;
  /** Sets the width.  @default "" */
  width?: string;
  /** Sets the test id.  @default "" */
  testId?: string;
  /** Sets the mt.  @default null */
  mt?: Spacing;
  /** Sets the mr.  @default null */
  mr?: Spacing;
  /** Sets the mb.  @default null */
  mb?: Spacing;
  /** Sets the ml.  @default null */
  ml?: Spacing;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, { 
  transform: "kebab",
  renamedProps: { testId: "testid" },
});
</script>

<template>
  <goa-block v-bind="wcProps">
    <slot />
  </goa-block>
</template>

// libs/web-components/src/components/block/Block.svelte
<svelte:options customElement={{
  tag: "goa-block",
  props: {
    minWidth: { type: "String", attribute: "min-width"},
  }
}} />

<script lang="ts">
  import { onMount } from "svelte";
  import { calculateMargin } from "../../common/styling";
  import type { Spacing } from "../../common/styling";
  import { ensureSlotExists } from "../../common/utils";
  import { style, styles } from "../../common/utils";

  export let gap: Spacing = "m";
  export let direction: "row" | "column" = "row";
  export let alignment: "center" | "start" | "end" | "normal" = "normal";
  export let testid: string = "";
  export let minWidth: string = "";

  $: _alignment =
    alignment === "start"
      ? "flex-start"
      : alignment === "end"
        ? "flex-end"
        : alignment === "center"
          ? "center"
          : "normal";

  // margin
  export let mt: Spacing = null;
  export let mr: Spacing = null;
  export let mb: Spacing = null;
  export let ml: Spacing = null;

  // Private

  let _rootEl: HTMLElement;

  // ========
  // Hooks
  // ========

  onMount(() => {
    ensureSlotExists(_rootEl);
  });
</script>

<div
  bind:this={_rootEl}
  data-testid={testid}
  class="block"
  style={`
    ${calculateMargin(mt, mr, mb, ml)}
    ${styles(
      style("min-width", minWidth),
      style("gap", gap),
      style("align-items", _alignment),
      style("flex-direction", direction),
    )}
  `}
>
  <slot />
</div>

<style>
  .block {
    display: flex;
    flex-direction: var(--direction);
    align-items: var(--alignment);
    gap: var(--gap);
  }
</style>
