// apps/angular-demo/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "abgov-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {}

<goa-two-column-layout maxcontentwidth="1400px" navcolumnwidth="30ch">
  <section slot="header">
    <goa-microsite-header
      type="alpha"
      level="alpha"
      version="UAT"
    ></goa-microsite-header>
    <goa-app-header
      heading="Design Systems"
      maxcontentwidth="1400px"
    ></goa-app-header>
  </section>

  <section slot="nav">
    <goa-sidebar>
      <goa-sidebar-group heading="Components">
        <a routerLink="/accordion"> Accordion </a>
        <a routerLink="/app-footer"> AppFooter </a>
        <a routerLink="/app-header"> App Header </a>
        <a routerLink="/badge"> Badge </a>
        <a routerLink="/button"> Button </a>
        <a routerLink="/button-group"> Button Group </a>
        <a routerLink="/callout"> Callout </a>
        <a routerLink="/checkbox"> Checkbox </a>
        <a routerLink="/chip"> Chip </a>
        <a routerLink="/circular-progress"> Circular Progress </a>
        <a routerLink="/container"> Container </a>
        <a routerLink="/dropdown"> Dropdown </a>
        <a routerLink="/detail"> Detail </a>
        <a routerLink="/file-upload"> File Upload </a>
        <a routerLink="/form-item"> Form Item </a>
        <a routerLink="/form-stepper"> Form Stepper </a>
        <a routerLink="/hero-banner"> Hero Banner </a>
        <a routerLink="/icon"> Icon </a>
        <a routerLink="/icon-button"> Icon Button </a>
        <a routerLink="/input"> Input </a>
        <a routerLink="/microsite-header"> Microsite header </a>
        <a routerLink="/modal"> Modal </a>
        <a routerLink="/notification-banner"> Notification Banner </a>
        <a routerLink="/paginate"> Pagination </a>
        <a routerLink="/popover"> Popover </a>
        <a routerLink="/radio"> Radio </a>
        <a routerLink="/skeleton"> Skeleton </a>
        <a routerLink="/table"> Table </a>
        <a routerLink="/textarea"> TextArea </a>
      </goa-sidebar-group>
      <goa-sidebar-group heading="Utils">
        <a routerLink="/spacing"> Spacing </a>
        <a routerLink="/grid"> Grid </a>
        <a routerLink="/styles"> Styles </a>
      </goa-sidebar-group>
      <goa-sidebar-group heading="Layouts">
        <a routerLink="/two-column-layout"> Two Column Layout </a>
        <a routerLink="/three-column-layout"> Three Column Layout </a>
      </goa-sidebar-group>
    </goa-sidebar>
  </section>

  <router-outlet></router-outlet>

  <goa-app-footer slot="footer" maxcontentwidth="1400px"></goa-app-footer>
</goa-two-column-layout>

// apps/react-demo/src/app/app.tsx
import { GoAAppHeader, GoAMicrositeHeader } from "@abgov/react-components";
import * as React from "react";
import { Outlet, Link } from "react-router-dom";
import "../styles.scss";

export default function App() {
  return (
    <>
      <GoAMicrositeHeader type="alpha" version="UAT"></GoAMicrositeHeader>

      <GoAAppHeader url="#" heading="Design Systems"></GoAAppHeader>

      <div className="container">
        <div className="navigation-bar">
          <nav>
            <Link className="navigation-link" to="/accordion">
              Accordion
            </Link>
            <Link className="navigation-link" to="/app-footer">
              AppFooter
            </Link>
            <Link className="navigation-link" to="/app-header">
              App Header
            </Link>
            <Link className="navigation-link" to="/badge">
              Badge
            </Link>
            <Link className="navigation-link" to="/button">
              Button
            </Link>
            <Link className="navigation-link" to="/button-group">
              Button Group
            </Link>
            <Link className="navigation-link" to="/callout">
              Callout
            </Link>
            <Link className="navigation-link" to="/checkbox">
              Checkbox
            </Link>
            <Link className="navigation-link" to="/chip">
              Chip
            </Link>
            <Link className="navigation-link" to="/circular-progress">
              Circular Progress
            </Link>
            <Link className="navigation-link" to="/container">
              Container
            </Link>
            <Link className="navigation-link" to="/divider">
              Divider
            </Link>
            <Link className="navigation-link" to="/dropdown">
              Dropdown
            </Link>
            <Link className="navigation-link" to="/file-upload">
              File Upload
            </Link>
            <Link className="navigation-link" to="/form-item">
              Form Item
            </Link>
            <Link className="navigation-link" to="/hero-banner">
              Hero Banner
            </Link>
            <Link className="navigation-link" to="/icon">
              Icon
            </Link>
            <Link className="navigation-link" to="/icon-button">
              Icon Button
            </Link>
            <Link className="navigation-link" to="/input">
              Input
            </Link>
            <Link className="navigation-link" to="/microsite-header">
              Microsite header
            </Link>
            <Link className="navigation-link" to="/modal">
              Modal
            </Link>
            <Link className="navigation-link" to="/notification-banner">
              Notification Banner
            </Link>
            <Link className="navigation-link" to="/pagination">
              Pagination
            </Link>
            <Link className="navigation-link" to="/popover">
              Popover
            </Link>
            <Link className="navigation-link" to="/radio">
              Radio
            </Link>
            <Link className="navigation-link" to="/skeleton">
              Skeleton
            </Link>
            <Link className="navigation-link" to="/styles">
              Styles
            </Link>
            <Link className="navigation-link" to="/table">
              Table
            </Link>
            <Link className="navigation-link" to="/textarea">
              TextArea
            </Link>
            <Link className="navigation-link" to="/three-column-layout">
              Three Column Layout
            </Link>
          </nav>
        </div>

        <div className="content">
          <Outlet />
        </div>
      </div>
    </>
  );
}
