// apps/angular-tests/src/app/app.component.ts
import {
  GoabAppFooter,
  GoabAppHeader,
  GoabAppHeaderMenu,
  GoabColumnLayout,
  GoabMicrositeHeader,
  GoabSideMenu,
  GoabSideMenuGroup,
} from "@abgov/angular-components";
import { Component, OnInit } from "@angular/core";
import { FormBuilder, FormControl, FormGroup } from "@angular/forms";
import { Countries, CountrySubdivisions } from "./countries.data";
import { RouterLink, RouterOutlet } from "@angular/router";

import "@abgov/web-components";

@Component({
  standalone: true,
  selector: "app-root",
  templateUrl: "./app.component.html",
  imports: [
    GoabAppHeader,
    GoabAppHeaderMenu,
    GoabAppFooter,
    GoabMicrositeHeader,
    GoabSideMenu,
    GoabSideMenuGroup,
    GoabColumnLayout,
    RouterOutlet,
    RouterLink,
  ],
})
export class AppComponent implements OnInit {
  countries = Countries;
  subdivisions = CountrySubdivisions;

  fg: FormGroup<{
    businessName: FormControl<string | null>;
    address1: FormControl<string | null>;
    address2: FormControl<string | null>;
    locality: FormControl<string | null>;
    region: FormControl<string | null>;
    country: FormControl<string | null>;
    postalCode: FormControl<string | null>;
  }>;

  constructor(private fb: FormBuilder) {
    this.fg = this.fb.group({
      businessName: [null as string | null, []],
      address1: [null as string | null, []],
      address2: [null as string | null, []],
      locality: [null as string | null, []],
      region: [null as string | null, []],
      country: [null as string | null, []],
      postalCode: [null as string | null, []],
    });
  }
  ngOnInit() {
    this.fg.get("country")?.valueChanges.subscribe((value) => {
      console.log("Hey country is changed ", value);
    });
    this.fg.get("region")?.valueChanges.subscribe((value) => {
      console.log("region is changed  ", value);
    });
  }

  submit() {
    console.log("Form  value is ", this.fg.value);
  }
}

<goab-column-layout>
  <section slot="header">
    <goab-microsite-header type="alpha" level="alpha" version="UAT"></goab-microsite-header>
    <goab-app-header heading="Design Systems" maxContentWidth="1500px">
      <a href="/get-started">Get started
      </a>
      <a href="/patterns">Patterns and templates</a>
      <a href="/components">Components</a>
      <a href="/design-tokens">Styles</a>
      <a href="/content/capitalization">Content</a>
      <a href="/support">Support</a>
      <a href="https://github.com/GovAlta/ui-components/issues/new/choose" target="_blank">
        Report a bug
      </a>
      <a href="#">Support</a>
      <goab-app-header-menu heading="Tickets" leadingIcon="ticket">
        <a href="#">Cases</a>
        <a href="#">Payments</a>
        <a href="#">Outstanding</a>
      </goab-app-header-menu>
      <a href="#" className="interactive">Sign in</a>
    </goab-app-header>
  </section>

  <section style="display:flex">
    <goab-side-menu style="flex: 0 0 240px; margin-bottom: 2rem;">
      <goab-side-menu-group heading="Bugs">
        <a routerLink="/bug-1734">Bug 1734</a>
        <a routerLink="/bug-1756">Bug 1756</a>
      </goab-side-menu-group>
      <goab-side-menu-group heading="Components">
        <a routerLink="/accordion">Accordion</a>
        <a routerLink="/app-footer">AppFooter</a>
        <a routerLink="/app-header">App Header</a>
        <a routerLink="/badge">Badge</a>
        <a routerLink="/button">Button</a>
        <a routerLink="/button-group">Button Group</a>
        <a routerLink="/callout">Callout</a>
        <a routerLink="/checkbox">Checkbox</a>
        <a routerLink="/chip">Chip</a>
        <a routerLink="/circular-progress">Circular Progress</a>
        <a routerLink="/container">Container</a>
        <a routerLink="/divider">Divider</a>
        <a routerLink="/dropdown">Dropdown</a>
        <a routerLink="/detail">Detail</a>
        <a routerLink="/file-upload">File Upload</a>
        <a routerLink="/form-item">Form Item</a>
        <a routerLink="/form-stepper">Form Stepper</a>
        <a routerLink="/hero-banner">Hero Banner</a>
        <a routerLink="/icon">Icon</a>
        <a routerLink="/icon-button">Icon Button</a>
        <a routerLink="/input">Input</a>
        <a routerLink="/microsite-header">Microsite header</a>
        <a routerLink="/modal">Modal</a>
        <a routerLink="/notification-banner">Notification Banner</a>
        <a routerLink="/paginate">Pagination</a>
        <a routerLink="/popover">Popover</a>
        <a routerLink="/radio">Radio</a>
        <a routerLink="/side-menu">Side Menu</a>
        <a routerLink="/skeleton">Skeleton</a>
        <a routerLink="/table">Table</a>
        <a routerLink="/textarea">TextArea</a>
        <a routerLink="/tooltip">Tooltip</a>
        <a routerLink="/tabs">Tabs</a>
     </goab-side-menu-group>
      <goab-side-menu-group heading="Utils">
        <a routerLink="/spacing">Spacing</a>
        <a routerLink="/grid">Grid</a>
        <a routerLink="/styles">Styles</a>
      </goab-side-menu-group>
    </goab-side-menu>

    <div class="container" style="padding: 0 2rem; flex: 1 1 auto">
      <router-outlet></router-outlet>
    </div>
  </section>

  <goab-app-footer slot="footer" maxContentWidth="1400px"></goab-app-footer>
</goab-column-layout>

// apps/react-demo/src/app/app.tsx
import { GoAAppHeader, GoAMicrositeHeader } from "@abgov/react-components";
import * as React from "react";
import { Outlet, Link } from "react-router-dom";
import "../styles.scss";

export default function App() {
  return (
    <>
      <GoAMicrositeHeader type="alpha" version="UAT"></GoAMicrositeHeader>

      <GoAAppHeader url="#" heading="Design Systems"></GoAAppHeader>

      <div className="container">
        <div className="navigation-bar">
          <nav>
            <Link className="navigation-link" to="/accordion">
              Accordion
            </Link>
            <Link className="navigation-link" to="/app-footer">
              AppFooter
            </Link>
            <Link className="navigation-link" to="/app-header">
              App Header
            </Link>
            <Link className="navigation-link" to="/badge">
              Badge
            </Link>
            <Link className="navigation-link" to="/button">
              Button
            </Link>
            <Link className="navigation-link" to="/button-group">
              Button Group
            </Link>
            <Link className="navigation-link" to="/callout">
              Callout
            </Link>
            <Link className="navigation-link" to="/checkbox">
              Checkbox
            </Link>
            <Link className="navigation-link" to="/chip">
              Chip
            </Link>
            <Link className="navigation-link" to="/circular-progress">
              Circular Progress
            </Link>
            <Link className="navigation-link" to="/container">
              Container
            </Link>
            <Link className="navigation-link" to="/divider">
              Divider
            </Link>
            <Link className="navigation-link" to="/dropdown">
              Dropdown
            </Link>
            <Link className="navigation-link" to="/file-upload">
              File Upload
            </Link>
            <Link className="navigation-link" to="/form-item">
              Form Item
            </Link>
            <Link className="navigation-link" to="/hero-banner">
              Hero Banner
            </Link>
            <Link className="navigation-link" to="/icon">
              Icon
            </Link>
            <Link className="navigation-link" to="/icon-button">
              Icon Button
            </Link>
            <Link className="navigation-link" to="/input">
              Input
            </Link>
            <Link className="navigation-link" to="/microsite-header">
              Microsite header
            </Link>
            <Link className="navigation-link" to="/modal">
              Modal
            </Link>
            <Link className="navigation-link" to="/notification-banner">
              Notification Banner
            </Link>
            <Link className="navigation-link" to="/pagination">
              Pagination
            </Link>
            <Link className="navigation-link" to="/popover">
              Popover
            </Link>
            <Link className="navigation-link" to="/radio">
              Radio
            </Link>
            <Link className="navigation-link" to="/skeleton">
              Skeleton
            </Link>
            <Link className="navigation-link" to="/styles">
              Styles
            </Link>
            <Link className="navigation-link" to="/table">
              Table
            </Link>
            <Link className="navigation-link" to="/textarea">
              TextArea
            </Link>
            <Link className="navigation-link" to="/three-column-layout">
              Three Column Layout
            </Link>
          </nav>
        </div>

        <div className="content">
          <Outlet />
        </div>
      </div>
    </>
  );
}
