// libs/react-components/src/lib/footer-nav-section/footer-nav-section.tsx
import { ReactNode } from "react";
import { DataAttributes } from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../common/extract-props";

interface WCProps {
  maxcolumncount?: number;
  heading?: string;
  testid?: string;
}

/* eslint-disable-next-line */
export interface GoabFooterNavSectionProps extends DataAttributes {
  /**
   * Maximum number of columns to display links in on larger screens.
   * @default 1
   */
  maxColumnCount?: number;
  /**
   * The section heading displayed above the navigation links.
   * @default ""
   */
  heading?: string;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
  /** TO DO: Write a description */
  children?: ReactNode;
}

export function GoabAppFooterNavSection({
  children,
  ...rest
}: GoabFooterNavSectionProps) {
  const _props = transformProps<WCProps>(rest, lowercase);

  return (
    <goa-app-footer-nav-section slot="nav" {..._props}>
      {children}
    </goa-app-footer-nav-section>
  );
}

export default GoabAppFooterNavSection;

// libs/angular-components/src/lib/components/footer-nav-section/footer-nav-section.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-app-footer-nav-section",
  template: `@if (isReady) {
    <goa-app-footer-nav-section
      [attr.maxcolumncount]="maxColumnCount"
      [attr.heading]="heading"
      [attr.testid]="testId"
    >
      <ng-content />
    </goa-app-footer-nav-section>
  }`,
  styles: [":host { width: 100%; }"],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabAppFooterNavSection implements OnInit {
  /** The section heading displayed above the navigation links. */
  @Input() heading?: string;
  /** Maximum number of columns to display links in on larger screens. @default 1 */
  @Input() maxColumnCount? = 1;
  /** Sets a data-testid attribute for automated testing. */
  @Input() testId?: string;
  /** @required Sets the slot to "nav" to render the section in the correct footer position. */
  @Input({ required: true }) slot!: "nav";

  isReady = false;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    // For Angular 20, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }
}
