// libs/angular-components/src/experimental/date-picker/date-picker.ts
import {
  CalendarDate,
  GoabDatePickerInputType,
  GoabDatePickerOnChangeDetail,
  Once,
} from "@abgov/ui-components-common";
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  EventEmitter,
  Input,
  Output,
  forwardRef,
  ElementRef,
  HostListener,
  OnInit,
  ChangeDetectorRef,
  Renderer2,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import { GoabControlValueAccessor } from "../base.component";

@Component({
  standalone: true,
  selector: "goabx-date-picker",

  template: `@if (isReady) {
    <goa-date-picker
      #goaComponentRef
      [attr.name]="name"
      [attr.value]="valueString()"
      [attr.min]="minString()"
      [attr.max]="maxString()"
      [attr.error]="error"
      [attr.disabled]="disabled"
      [attr.relative]="relative"
      [attr.type]="type"
      [attr.testid]="testId"
      [attr.width]="width"
      [attr.mt]="mt"
      [attr.mb]="mb"
      [attr.ml]="ml"
      [attr.mr]="mr"
      [attr.version]="version"
      (_change)="_onChange($event)"
    >
    </goa-date-picker>
  }`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      multi: true,
      useExisting: forwardRef(() => GoabxDatePicker),
    },
  ],
})
export class GoabxDatePicker extends GoabControlValueAccessor implements OnInit {
  isReady = false;
  version = 2;

  /**
   * Name of the date field.
   * @default ""
   */
  @Input() name?: string;
  @Input() override value?: Date | string | null | undefined;
  /**
   * Minimum date value allowed.
   * @default ""
   */
  @Input() min?: Date | string;
  /**
   * Maximum date value allowed.
   * @default ""
   */
  @Input() max?: Date | string;
  /**
   * Sets the date picker type. 'calendar' shows a calendar popup, 'input' shows just a date input.
   * @default "calendar"
   */
  @Input() type?: GoabDatePickerInputType;
  /***
   * @deprecated This property has no effect and will be removed in a future version
   */
  @Input() relative?: boolean;
  /**
   * Sets the width of the date picker input.
   * @default ""
   */
  @Input() width?: string;

  @Output() onChange = new EventEmitter<GoabDatePickerOnChangeDetail>();

  private once: Once = new Once();

  private formatValue(param: string, val: Date | string | null | undefined): string {
    if (!val) return "";

    this.once.when(val instanceof Date).do(param, () => {
      console.warn(
        `GoabxDatePicker: Using Date for '${param}' is deprecated. Use a string in YYYY-MM-DD format instead.`,
      );
    });

    return new CalendarDate(val).toString();
  }

  valueString(): string {
    return this.formatValue("value", this.value);
  }

  minString(): string {
    return this.formatValue("min", this.min);
  }

  maxString(): string {
    return this.formatValue("max", this.max);
  }

  _onChange(e: Event) {
    const detail = {
      ...(e as CustomEvent<GoabDatePickerOnChangeDetail>).detail,
      event: e,
    };
    this.onChange.emit(detail);
    this.markAsTouched();
    this.fcChange?.(detail.value);
  }

  constructor(
    protected elementRef: ElementRef,
    private cdr: ChangeDetectorRef,
    renderer: Renderer2,
  ) {
    super(renderer);
  }

  ngOnInit(): void {
    // For Angular 20, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);

    if (this.value && typeof this.value !== "string") {
      console.warn(
        "Using a `Date` type for value is deprecated. Instead use a string of the format `yyyy-mm-dd`",
      );
    }
  }

  override setDisabledState(isDisabled: boolean) {
    this.disabled = isDisabled;
    this.elementRef.nativeElement.disabled = isDisabled;
  }

  @HostListener("disabledChange", ["$event"])
  listenDisabledChange(event: Event) {
    const isDisabled = (event as CustomEvent<{ disabled: boolean }>).detail.disabled;
    this.setDisabledState(isDisabled);
  }

  override writeValue(value: Date | null): void {
    this.value = value;

    const datePickerEl = this.goaComponentRef?.nativeElement as HTMLElement | undefined;
    if (datePickerEl) {
      if (!value) {
        this.renderer.setAttribute(datePickerEl, "value", "");
      } else {
        this.renderer.setAttribute(
          datePickerEl,
          "value",
          value instanceof Date ? new CalendarDate(value).toString() : value,
        );
      }
    }
  }
}

// libs/react-components/src/experimental/date-picker/date-picker.tsx
import { useEffect, useRef, type JSX } from "react";
import {
  CalendarDate,
  GoabDatePickerInputType,
  GoabDatePickerOnChangeDetail,
  Margins,
  DataAttributes,
} from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../../lib/common/extract-props";

interface WCProps extends Margins {
  name?: string;
  value?: string;
  error?: string;
  min?: string;
  max?: string;
  type?: string;
  relative?: string;
  disabled?: string;
  testid?: string;
  width?: string;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-date-picker": WCProps &
        React.HTMLAttributes<HTMLElement> & {
          ref: React.RefObject<HTMLElement | null>;
        };
    }
  }
}

export interface GoabxDatePickerProps extends Margins, DataAttributes {
  /**
   * Name of the date field.
   * @default ""
   */
  name?: string;
  /**
   * Value of the calendar date.
   * @default ""
   */
  value?: Date | string | undefined;
  /**
   * Sets the input to an error state.
   * @default false
   */
  error?: boolean;
  /**
   * Minimum date value allowed.
   * @default ""
   */
  min?: Date | string;
  /**
   * Maximum date value allowed.
   * @default ""
   */
  max?: Date | string;
  /**
   * Sets the date picker type. 'calendar' shows a calendar popup, 'input' shows just a date input.
   * @default "calendar"
   */
  type?: GoabDatePickerInputType;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
  /***
   * @deprecated This property has no effect and will be removed in a future version
   */
  relative?: boolean;
  /**
   * Disables the date picker.
   * @default false
   */
  disabled?: boolean;
  /**
   * Sets the width of the date picker input.
   * @default ""
   */
  width?: string;
  version?: string;
  onChange?: (detail: GoabDatePickerOnChangeDetail) => void;
}

export function GoabxDatePicker({
  value,
  error,
  min,
  max,
  disabled,
  relative,
  version = "2",
  onChange,
  ...rest
}: GoabxDatePickerProps): JSX.Element {
  const ref = useRef<HTMLInputElement>(null);

  const _props = transformProps<WCProps>(rest, lowercase);

  useEffect(() => {
    if (value && typeof value !== "string") {
      console.warn(
        "Using a `Date` type for value is deprecated. Instead use a string of the format `yyyy-mm-dd`",
      );
    }
  }, []);

  useEffect(() => {
    if (!ref.current) {
      return;
    }
    const current = ref.current;

    const handleChange = (e: Event) => {
      const detail = (e as CustomEvent<GoabDatePickerOnChangeDetail>).detail;
      onChange?.({ ...detail, event: e });
    };

    if (onChange) {
      current.addEventListener("_change", handleChange);
    }

    return () => {
      if (onChange) {
        current.removeEventListener("_change", handleChange);
      }
    };
  }, [onChange]);

  const formatValue = (val: Date | string | undefined) => {
    if (!val) return "";

    if (val instanceof Date) {
      return new CalendarDate(val).toString();
    }

    return val;
  };

  return (
    <goa-date-picker
      ref={ref}
      value={formatValue(value) || undefined}
      error={error ? "true" : undefined}
      disabled={disabled ? "true" : undefined}
      min={formatValue(min) || undefined}
      max={formatValue(max) || undefined}
      relative={relative ? "true" : undefined}
      version={version}
      {..._props}
    />
  );
}

export default GoabxDatePicker;
