// apps/prs/react/src/routes/bugs/bug3497.tsx
import { GoabBlock, GoabCalendar, GoabText } from "@abgov/react-components";

export function Bug3497Route() {
  const today = new Date();

  const noop = () => {
    return null;
  };

  return (
    <GoabBlock direction="column" gap="l">
      <GoabText tag="h1">Bug 3497 Calendar Years Empty</GoabText>

      <GoabText tag="p">
        When min or max is set to today then the year dropdown is empty and doesn't show
        anything.
      </GoabText>

      <GoabText tag="h2">min test</GoabText>
      <GoabCalendar name="minTest" min={today.toISOString()} onChange={noop} />

      <GoabText tag="h2">max test</GoabText>
      <GoabCalendar name="maxTest" max={today.toISOString()} onChange={noop} />

      <GoabText tag="h2">ordinary</GoabText>
      <GoabCalendar name="ordinaryTest" value={today.toISOString()} onChange={noop} />
    </GoabBlock>
  );
}

// apps/prs/angular/src/routes/bugs/3497/bug3497.component.ts
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { GoabCalendar } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3497",
  templateUrl: "./bug3497.component.html",
  imports: [CommonModule, GoabCalendar],
})
export class Bug3497Component implements OnInit {
  today = new Date();

  ngOnInit() {
    console.log("today", this.today);
  }
}

<h1>Bug 3497 Calendar Years Empty</h1>
<p>
  When [min] or [max] is set to today then the year dropdown is empty and doesn't show
  anything.
</p>
<h2>min test</h2>
<goab-calendar name="minTest" [min]="today"></goab-calendar>
<h2>max test</h2>
<goab-calendar name="maxTest" [max]="today"></goab-calendar>
<h2>ordinary</h2>
<goab-calendar name="ordinaryTest" [value]="today"></goab-calendar>
