// apps/prs/react/src/routes/docs/hero-banner/hero-banner.tsx
import {
  GoabButton,
  GoabButtonGroup,
  GoabHeroBanner,
  GoabHeroBannerActions,
} from "@abgov/react-components";

export function DocsHeroBannerRoute() {
  return (
    <div>
      <h2>Hero Banner</h2>

      <h3>Basic hero banner</h3>
      <GoabHeroBanner heading="Start your application">
        <p>Apply for government services quickly and easily online.</p>
        <GoabButtonGroup alignment="start" mt="l">
          <GoabButton>Get started</GoabButton>
          <GoabButton type="secondary">Learn more</GoabButton>
        </GoabButtonGroup>
      </GoabHeroBanner>

      <h3>With background image</h3>
      <GoabHeroBanner
        heading="Explore Alberta"
        backgroundUrl="/images/alberta-landscape.jpg"
      />

      <h3>Background color</h3>
      <GoabHeroBanner
        heading="Community services"
        backgroundColor="#1a3d5c"
        textColor="#ffffff"
      >
        <p>Find resources and support in your community.</p>
      </GoabHeroBanner>

      <h3>Custom height</h3>
      <GoabHeroBanner
        heading="Full viewport hero"
        minHeight="400px"
        backgroundUrl="/images/hero-bg.jpg"
      >
        <p>Large hero for landing pages.</p>
      </GoabHeroBanner>

      <h2>Examples</h2>

      <h3>Hero banner with actions</h3>
      <GoabHeroBanner heading="Supporting Businesses">
        Resources are available to help Alberta entrepreneurs and small businesses
        start, grow and succeed.
        <GoabHeroBannerActions>
          <GoabButton type="start" onClick={() => console.log("Call to action clicked")}>
            Call to action
          </GoabButton>
        </GoabHeroBannerActions>
      </GoabHeroBanner>
    </div>
  );
}

// apps/prs/angular/src/routes/docs/hero-banner/hero-banner.component.ts
import { Component } from "@angular/core";
import { GoabButton, GoabButtonGroup, GoabHeroBanner } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-hero-banner",
  templateUrl: "./hero-banner.component.html",
  imports: [GoabButton, GoabButtonGroup, GoabHeroBanner],
})
export class DocsHeroBannerComponent {
  onHeroBannerClick(): void {
    console.log("Call to action clicked");
  }
}

<h2>Hero Banner</h2>

<h3>Basic hero banner</h3>
<goab-hero-banner heading="Start your application">
  <p>Apply for government services quickly and easily online.</p>
  <goab-button-group alignment="start" mt="l">
    <goab-button>Get started</goab-button>
    <goab-button type="secondary">Learn more</goab-button>
  </goab-button-group>
</goab-hero-banner>

<h3>With background image</h3>
<goab-hero-banner
  heading="Explore Alberta"
  backgroundUrl="/images/alberta-landscape.jpg"
>
</goab-hero-banner>

<h3>Background color</h3>
<goab-hero-banner
  heading="Community services"
  backgroundColor="#1a3d5c"
  textColor="#ffffff"
>
  <p>Find resources and support in your community.</p>
</goab-hero-banner>

<h3>Custom height</h3>
<goab-hero-banner
  heading="Full viewport hero"
  minHeight="400px"
  backgroundUrl="/images/hero-bg.jpg"
>
  <p>Large hero for landing pages.</p>
</goab-hero-banner>

<h2>Examples</h2>

<h3>Hero banner with actions</h3>
<goab-hero-banner
  heading="Supporting Businesses"
  [actions]="heroBannerActionTemplate"
>
  Resources are available to help Alberta entrepreneurs and small businesses
  start, grow and succeed.
  <ng-template #heroBannerActionTemplate>
    <goab-button type="start" (onClick)="onHeroBannerClick()">Call to action</goab-button>
  </ng-template>
</goab-hero-banner>
