// libs/vue-components/src/lib/block/block.vue
<script setup lang="ts">
import type { GoabBlockAlignment, GoabBlockDirection, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Sets the gap.  @default "m" */
  gap?: Spacing;
  /** Sets the direction.  @default "row" */
  direction?: GoabBlockDirection;
  /** Sets the alignment.  @default "normal" */
  alignment?: GoabBlockAlignment;
  /** Sets the min width.  @default "" */
  minWidth?: string;
  /** Sets the max width.  @default "" */
  maxWidth?: string;
  /** Sets the width.  @default "" */
  width?: string;
  /** Sets the test id.  @default "" */
  testId?: string;
  /** Sets the mt.  @default null */
  mt?: Spacing;
  /** Sets the mr.  @default null */
  mr?: Spacing;
  /** Sets the mb.  @default null */
  mb?: Spacing;
  /** Sets the ml.  @default null */
  ml?: Spacing;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, { 
  transform: "kebab",
  renamedProps: { testId: "testid" },
});
</script>

<template>
  <goa-block v-bind="wcProps">
    <slot />
  </goa-block>
</template>

// libs/react-components/src/lib/block/block.tsx
import {
  GoabBlockAlignment,
  GoabBlockDirection,
  Margins, DataAttributes,
  Spacing,
} from "@abgov/ui-components-common";
import { ReactNode } from "react";
import { transformProps, kebab } from "../common/extract-props";

export interface WCProps extends Margins {
  gap?: Spacing;
  direction?: GoabBlockDirection;
  alignment?: GoabBlockAlignment;
  "min-width"?: string;
  "max-width"?: string;
  width?: string;
  testid?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-block": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoabBlockProps extends Margins, DataAttributes {
  gap?: Spacing;
  direction?: GoabBlockDirection;
  alignment?: GoabBlockAlignment;
  minWidth?: string;
  maxWidth?: string;
  width?: string;
  testId?: string;
  children?: ReactNode;
}

export function GoabBlock({
  testId,
  children,
  ...rest
}: GoabBlockProps) {
  const _props = transformProps<WCProps>(
    { testid: testId, ...rest },
    kebab
  );

  return (
    <goa-block {..._props}>
      {children}
    </goa-block>
  );
}
