// libs/vue-components/src/lib/app-header/app-header.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import { useWcProps } from "../common/useWcProps";

interface Slots {
  default?: () => unknown;
  /** Content rendered in the "banner" named slot. */
  banner?: () => unknown;
  /** Content rendered in the "navigation" named slot. */
  navigation?: () => unknown;
  /** Content rendered in the "phase" named slot. */
  phase?: () => unknown;
  /** Content rendered in the "utilities" named slot. */
  utilities?: () => unknown;
}

interface Props {
  /** Set the service name to display in the app header. */
  heading?: string;
  /** V2 only: Secondary text displayed under the service name. */
  secondaryText?: string;
  /** Set the URL to link from the alberta.ca logo. A full url is required. */
  url?: string;
  /** Maximum width of the content area. */
  maxContentWidth?: string;
  /** Sets the breakpoint in px for the full menu to display.  @default TABLET_BP */
  fullMenuBreakpoint?: number;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Callback fired when the menu button is clicked. When provided, clicking the menu button dispatches a custom event instead of toggling the menu. */
  onMenuClick?: () => void;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, {
  booleanProps: ["onMenuClick"],
  renamedProps: { onMenuClick: "hasmenuclickhandler" },
});
const slots = useSlots() as Slots;
</script>

<template>
  <goa-app-header v-bind="wcProps" @_menuClick="props.onMenuClick?.()">
    <div v-if="slots.banner" slot="banner">
      <slot name="banner" />
    </div>
    <div v-if="slots.phase" slot="phase">
      <slot name="phase" />
    </div>
    <div v-if="slots.utilities" slot="utilities">
      <slot name="utilities" />
    </div>
    <div v-if="slots.navigation" slot="navigation">
      <slot name="navigation" />
    </div>
    <slot />
  </goa-app-header>
</template>

// libs/react-components/src/experimental/app-header/app-header.tsx
import { useEffect, useRef, type JSX } from "react";
import { DataAttributes } from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../../lib/common/extract-props";

interface WCProps {
  heading?: string;
  secondarytext?: string;
  url?: string;
  maxcontentwidth?: string;
  fullmenubreakpoint?: number;
  hasmenuclickhandler?: string;
  testid?: string;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-app-header": WCProps &
        React.HTMLAttributes<HTMLElement> & {
          ref: React.RefObject<HTMLElement | null>;
        };
    }
  }
}

export interface GoabxAppHeaderProps extends DataAttributes {
  /**
   * Set the service name to display in the app header.
   * @default ""
   */
  heading?: string;
  /**
   * V2 only: Secondary text displayed under the service name.
   * @default ""
   */
  secondaryText?: string;
  /**
   * Set the URL to link from the alberta.ca logo. A full url is required.
   * @default ""
   */
  url?: string;
  /**
   * Maximum width of the content area.
   * @default ""
   */
  maxContentWidth?: string;
  /**
   * Sets the breakpoint in px for the full menu to display.
   * @default TABLET_BP
   */
  fullMenuBreakpoint?: number;
  children?: React.ReactNode;
  onMenuClick?: () => void;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
}

export function GoabxAppHeader({
  onMenuClick,
  children,
  secondaryText,
  ...rest
}: GoabxAppHeaderProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  const _props = transformProps<WCProps>(rest, lowercase);

  useEffect(() => {
    if (!el.current) {
      return;
    }
    if (!onMenuClick) {
      return;
    }
    const current = el.current;
    const listener = () => {
      onMenuClick?.();
    };
    current.addEventListener("_menuClick", listener);
    return () => {
      current.removeEventListener("_menuClick", listener);
    };
  }, [el, onMenuClick]);

  return (
    <goa-app-header
      ref={el}
      hasmenuclickhandler={onMenuClick ? "true" : "false"}
      secondarytext={secondaryText}
      {..._props}
      version="2"
    >
      {children}
    </goa-app-header>
  );
}
