// libs/vue-components/src/lib/work-side-notification-panel/work-side-notification-panel.vue
<script setup lang="ts">
import type { GoabWorkSideNotificationActiveTabType } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  heading?: string;
  activeTab?: GoabWorkSideNotificationActiveTabType;
  testId?: string;
}

const props = withDefaults(defineProps<Props>(), {
  heading: "Notifications",
  activeTab: "unread",
});
const emit = defineEmits<{
  onMarkAllRead: [];
  onViewAll: [];
}>();

const wcProps = useWcProps(props);
</script>

<template>
  <goa-work-side-notification-panel v-bind="wcProps" :active-tab="activeTab" @_markAllRead="emit('onMarkAllRead')" @_viewAll="emit('onViewAll')">
    <slot />
  </goa-work-side-notification-panel>
</template>

// libs/react-components/src/experimental/work-side-notification-panel/work-side-notification-panel.tsx
import { ReactNode, useEffect, useRef, type JSX } from "react";
import { GoabWorkSideNotificationActiveTabType } from "@abgov/ui-components-common";

interface WCProps {
  heading?: string;
  "active-tab"?: GoabWorkSideNotificationActiveTabType;
  testid?: string;
  ref: React.RefObject<HTMLElement | null>;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-work-side-notification-panel": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabWorkSideNotificationPanelProps {
  heading?: string;
  activeTab?: GoabWorkSideNotificationActiveTabType;
  testId?: string;
  children?: ReactNode;
  onMarkAllRead?: () => void;
  onViewAll?: () => void;
}

export function GoabxWorkSideNotificationPanel({
  heading,
  activeTab,
  testId,
  children,
  onMarkAllRead,
  onViewAll,
}: GoabWorkSideNotificationPanelProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el.current) return;

    const handleMarkAllRead = () => {
      onMarkAllRead?.();
    };

    const handleViewAll = () => {
      onViewAll?.();
    };

    el.current.addEventListener("_markAllRead", handleMarkAllRead);
    el.current.addEventListener("_viewAll", handleViewAll);

    return () => {
      el.current?.removeEventListener("_markAllRead", handleMarkAllRead);
      el.current?.removeEventListener("_viewAll", handleViewAll);
    };
  }, [el, onMarkAllRead, onViewAll]);

  return (
    <goa-work-side-notification-panel
      ref={el}
      heading={heading}
      active-tab={activeTab}
      testid={testId}
    >
      {children}
    </goa-work-side-notification-panel>
  );
}

export default GoabxWorkSideNotificationPanel;
