// libs/angular-components/src/lib/components/notification/notification.ts
import {
  GoabAriaLiveType,
  GoabNotificationEmphasis,
  GoabNotificationType,
} from "@abgov/ui-components-common";
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  EventEmitter,
  Input,
  Output,
  OnInit,
  ChangeDetectorRef,
  booleanAttribute,
  inject,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-notification",
  template: `
    @if (isReady) {
      <goa-notification
        [attr.type]="type"
        [attr.arialive]="ariaLive"
        [attr.maxcontentwidth]="maxContentWidth"
        [attr.emphasis]="emphasis"
        [attr.compact]="compact"
        [attr.testid]="testId"
        (_dismiss)="_onDismiss()"
      >
        <ng-content />
      </goa-notification>
    }
  `,

  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
/** Display important page level information or notifications. */
export class GoabNotification implements OnInit {
  private cdr = inject(ChangeDetectorRef);

  isReady = false;
  /** Define the context and colour of the notification. @default "information" */
  @Input() type?: GoabNotificationType = "information";
  /** Indicates how assistive technology should handle updates to the live region. */
  @Input() ariaLive?: GoabAriaLiveType;
  /** Maximum width of the content area. */
  @Input() maxContentWidth?: string;
  /** Sets the visual prominence. 'high' for full background, 'low' for medium. @default "high" */
  @Input() emphasis?: GoabNotificationEmphasis = "high";
  /** When true, reduces padding for a more compact notification. */
  @Input({ transform: booleanAttribute }) compact?: boolean;
  /** Sets a data-testid attribute for automated testing. */
  @Input() testId?: string;

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    });
  }

  /** Emits when the notification is dismissed. */
  @Output() onDismiss = new EventEmitter();

  _onDismiss() {
    this.onDismiss.emit();
  }
}

// libs/vue-components/src/lib/notification/notification.vue
<script setup lang="ts">
import type {
  GoabAriaLiveType,
  GoabNotificationEmphasis,
  GoabNotificationType,
} from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Define the context and colour of the notification.  @default "information" */
  type?: GoabNotificationType;
  /** Indicates how assistive technology should handle updates to the live region. @default "polite" */
  ariaLive?: GoabAriaLiveType;
  /** Maximum width of the content area. @default undefined */
  maxContentWidth?: string;
  /** Sets the visual prominence. 'high' for full background, 'low' for a bordered style. @default "high" */
  emphasis?: GoabNotificationEmphasis;
  /** When true, reduces padding for a more compact notification.  @default false */
  compact?: boolean;
  /** Sets a data-testid attribute for automated testing.  @default "" */
  testId?: string;
}

const props = withDefaults(defineProps<Props>(), {
  type: "information",
  emphasis: "high",
});
const emit = defineEmits<{
  /** Callback fired when the notification is dismissed. */
  onDismiss: [];
}>();

const wcProps = useWcProps(props, { booleanProps: ["compact"] });
</script>

<template>
  <goa-notification v-bind="wcProps" @_dismiss="emit('onDismiss')">
    <slot />
  </goa-notification>
</template>
