// apps/react-demo/src/routes/sideMenu.tsx
import { GoASideMenu, GoASideMenuGroup, GoASideMenuHeading } from "@abgov/react-components";

export function SideMenu() {
  return (
    <GoASideMenu>
      <GoASideMenuHeading>Nav section 1</GoASideMenuHeading>
      <a href="#about">Home</a>
      <a href="#contact">Profile</a>
      <GoASideMenuHeading>Nav section 2</GoASideMenuHeading>
      <a href="#about">About</a>
      <a href="#contact">Contact</a>
      <GoASideMenuGroup heading="Links">
        <GoASideMenuHeading>Nav section 3</GoASideMenuHeading>
        <a href="#foo">Foo</a>
        <a href="#bar">Bar</a>
        <GoASideMenuGroup heading="More Links">
          <GoASideMenuHeading>Nav section 4</GoASideMenuHeading>
          <a href="#more-foo">More Foo</a>
          <a href="#more-bar">More Bar</a>
        </GoASideMenuGroup>
      </GoASideMenuGroup>
    </GoASideMenu>
  );
}

export default SideMenu;

// apps/angular-demo/src/app/sidemenu/sidemenu.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "abgov-sidemenu",
  templateUrl: "./sidemenu.component.html",
})
export class SideMenuComponent {
  constructor() { }
}

<h2>Side Menu</h2>
<goa-side-menu>
  <goa-side-menu-heading>Nav section 1</goa-side-menu-heading>
  <a href="#home">Home</a>
  <a href="#profile">Profile</a>
  <goa-side-menu-heading>Nav section 2</goa-side-menu-heading>
  <a href="#about">About</a>
  <a href="#contact">Contact</a>
  <goa-side-menu-group heading="Links">
    <goa-side-menu-heading>Nav section 3</goa-side-menu-heading>
    <a href="#foo">Foo</a>
    <a href="#bar">Bar</a>
    <goa-side-menu-group heading="More Links">
      <goa-side-menu-heading>Nav section 4</goa-side-menu-heading>
      <a href="#more-foo">More Foo</a>
      <a href="#more-bar">More Bar</a>
    </goa-side-menu-group>
  </goa-side-menu-group>
</goa-side-menu>
