// libs/react-components/src/lib/link-button/link-button.tsx
import { ReactNode } from "react";
import {
  DataAttributes,
  GoabIconType,
  GoabLinkButtonType,
  Margins,
} from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../common/extract-props";

interface WCProps extends Margins {
  type?: GoabLinkButtonType;
  leadingicon?: GoabIconType;
  trailingicon?: GoabIconType;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-link-button": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface GoALinkButtonProps extends Margins, DataAttributes {
  type?: GoabLinkButtonType;
  leadingIcon?: GoabIconType;
  trailingIcon?: GoabIconType;
  children: ReactNode;
}

export function GoALinkButton({
  type = "primary",
  children,
  ...rest
}: GoALinkButtonProps) {
  const _props = transformProps<WCProps>({ type, ...rest }, lowercase);

  return <goa-link-button {..._props}>{children}</goa-link-button>;
}

export default GoALinkButton;

// libs/vue-components/src/lib/link-button/link-button.vue
<script setup lang="ts">
import type { GoabIconType, GoabLinkButtonType, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  type?: GoabLinkButtonType;
  leadingIcon?: GoabIconType;
  trailingIcon?: GoabIconType;
  mt?: Spacing;
  mr?: Spacing;
  mb?: Spacing;
  ml?: Spacing;
}

const props = defineProps<Props>();

const wcProps = useWcProps(props);
</script>

<template>
  <goa-link-button v-bind="wcProps">
    <slot />
  </goa-link-button>
</template>
