// apps/react-demo/src/routes/badge.tsx
import { GoABadge, GoAInfoBadge } from "@abgov/react-components";
import * as React from "react";

export default function Badge() {
  return (
    <>
      <h1>Badges</h1>
      <h2>Important</h2>
      <GoABadge type="important" content="Important" icon={true}></GoABadge>
      <GoABadge type="important" content="Important"></GoABadge>
      <GoABadge type="important" icon={true}></GoABadge>

      <h2>Success</h2>
      <GoABadge type="success" content="Success" icon={true}></GoABadge>
      <GoABadge type="success" content="Success"></GoABadge>
      <GoABadge type="success" icon={true}></GoABadge>

      <h2>Information</h2>
      <GoABadge type="information" icon={true}></GoABadge>
      <GoABadge type="information" content="Information"></GoABadge>
      <GoABadge type="information" icon={true}></GoABadge>

      <h2>Emergency</h2>
      <GoABadge type="emergency" content="Emergency" icon={true}></GoABadge>
      <GoABadge type="emergency" content="Emergency"></GoABadge>
      <GoABadge type="emergency" icon={true}></GoABadge>

      <h2>Dark</h2>
      <GoABadge type="dark" content="Dark" icon={true}></GoABadge>
      <GoABadge type="dark" content="Dark"></GoABadge>
      <GoABadge type="dark" icon={true}></GoABadge>

      <h2>Midtone</h2>
      <GoABadge type="midtone" content="Midtone" icon={true}></GoABadge>
      <GoABadge type="midtone" content="Midtone"></GoABadge>
      <GoABadge type="midtone" icon={true}></GoABadge>

      <h2>Light</h2>
      <GoABadge type="light" content="Light" icon={true}></GoABadge>
      <GoABadge type="light" content="Light"></GoABadge>
      <GoABadge type="light" icon={true}></GoABadge>

      <h2>Margin Spacing</h2>
      <GoABadge
        mt="m"
        mb="xs"
        ml="xl"
        mr="2xl"
        type="important"
        content="Important"
        icon={true}
      ></GoABadge>
    </>
  );
}

// apps/angular-tests/src/app/badge/badge.component.ts
import { GoabBadge } from "@abgov/angular-components";
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-badge",
  templateUrl: "./badge.component.html",
  imports: [
    GoabBadge
  ]
})
export class BadgeComponent {
  constructor() { }
}

// FIXME: there is an issue with the `icon` prop binding

<h1>Badge</h1>

<h2>Important</h2>
<goab-badge type="important" content="Important"></goab-badge>
<goab-badge type="important" arialabel="important"></goab-badge>

<h2>Success</h2>
<goab-badge type="success" content="Success"></goab-badge>
<goab-badge type="success" content="Success"></goab-badge>
<goab-badge type="success"></goab-badge>

<h2>Information</h2>
<goab-badge type="information" content="Information"></goab-badge>
<goab-badge type="information" content="Information"></goab-badge>
<goab-badge type="information"></goab-badge>

<h2>Emergency</h2>
<goab-badge type="emergency" content="Emergency"></goab-badge>
<goab-badge type="emergency" content="Emergency"></goab-badge>
<goab-badge type="emergency"></goab-badge>

<h2>Dark</h2>
<goab-badge type="dark" content="Dark"></goab-badge>
<goab-badge type="dark" content="Dark"></goab-badge>
<goab-badge type="dark"></goab-badge>

<h2>Midtone</h2>
<goab-badge type="midtone" content="Midtone"></goab-badge>
<goab-badge type="midtone" content="Midtone"></goab-badge>
<goab-badge type="midtone"></goab-badge>

<h2>Light</h2>
<goab-badge type="light" content="Light"></goab-badge>
<goab-badge type="light" content="Light"></goab-badge>
<goab-badge type="light"></goab-badge>

<h2>Margin Spacing</h2>
<goab-badge mt="m" mb="xs" ml="xl" mr="2xl" type="important" content="Important"></goab-badge>
