// libs/vue-components/src/lib/hero-banner/hero-banner.vue
<script setup lang="ts">
import { useSlots } from "vue";
import { useWcProps } from "../common/useWcProps";

interface Slots {
  default?: () => unknown;
  /** Content rendered in the "actions" named slot. */
  actions?: () => unknown;
}

interface Props {
  /** @required Main heading text.  @default (required) */
  heading: string;
  /** Background image url.  @default undefined */
  backgroundUrl?: string;
  /** Minimum height of the hero banner. Defaults to 600px when a background image is provided.  @default undefined */
  minHeight?: string;
  /** Sets a data-testid attribute for automated testing.  @default "background" */
  testId?: string;
  /** Maximum width of the content area. @default undefined */
  maxContentWidth?: string;
  /** Hero Banner background color when no background image is provided. @default "#f8f8f8" */
  backgroundColor?: string;
  /** Text color within the hero banner.  @default "" */
  textColor?: string;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props);
const slots = useSlots() as Slots;
</script>

<template>
  <goa-hero-banner v-bind="wcProps">
    <slot />
    <div v-if="slots.actions" slot="actions">
      <slot name="actions" />
    </div>
  </goa-hero-banner>
</template>

// libs/react-components/src/lib/hero-banner/hero-banner.tsx
import type { JSX } from "react";
interface WCProps {
  heading: string;
  backgroundurl?: string;
  minheight?: string;
  maxcontentwidth?: string;
  backgroundcolor?: string;
  textcolor?: string;
  testid?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-hero-banner": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabHeroBannerProps {
  /** @required Main heading text. */
  heading: string;
  /** Background image url. */
  backgroundUrl?: string;
  /** Minimum height of the hero banner. Defaults to 600px when a background image is provided. */
  minHeight?: string;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Content rendered inside the hero banner body. */
  children?: React.ReactNode;
  /** Content rendered in the actions slot. */
  actions?: React.ReactNode;
  /** Maximum width of the content area. @default "100%" */
  maxContentWidth?: string;
  /** Hero Banner background color when no background image is provided. @default "#f8f8f8" */
  backgroundColor?: string;
  /** Text color within the hero banner. */
  textColor?: string;
}

/** A visual band of text, including an image and a call to action. */
export function GoabHeroBanner({
  heading,
  backgroundUrl,
  minHeight,
  maxContentWidth,
  backgroundColor,
  textColor,
  children,
  actions,
  testId,
}: GoabHeroBannerProps): JSX.Element {
  return (
    <goa-hero-banner
      heading={heading}
      backgroundurl={backgroundUrl}
      minheight={minHeight}
      maxcontentwidth={maxContentWidth}
      backgroundcolor={backgroundColor}
      textcolor={textColor}
      testid={testId}
    >
      {children}
      {actions && <div slot="actions">{actions}</div>}
    </goa-hero-banner>
  );
}

export default GoabHeroBanner;
