// apps/react-demo/src/routes/heroBanner.tsx
import {
  GoAButton,
  GoAButtonGroup,
  GoAHeroBanner,
} from "@abgov/react-components";
import * as React from "react";

export default function HeroBanner() {
  return (
    <>
      <h1>Hero Banner</h1>
      <h2>Default</h2>
      <GoAHeroBanner
        heading="Hero Banner"
        backgroundUrl="https://i.picsum.photos/id/1076/600/400.jpg?hmac=iLAZWoEDYRRPGnsbx7aWOGf-olRn3R5eOLDgH_IfXRw"
      >
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur
        optio, eius expedita, quasi vero maxime, laudantium voluptates eaque
        illum officiis hic!
      </GoAHeroBanner>

      <br />
      <h2>With Actions</h2>
      <GoAHeroBanner
        heading="Hero Banner"
        backgroundUrl="https://i.picsum.photos/id/1076/600/400.jpg?hmac=iLAZWoEDYRRPGnsbx7aWOGf-olRn3R5eOLDgH_IfXRw"
      >
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur
        optio, eius expedita, quasi vero maxime, laudantium voluptates eaque
        illum officiis hic!
        <div slot="actions">
          <GoAButtonGroup alignment="start">
            <GoAButton onClick={() => void 0}>Action</GoAButton>
            <GoAButton onClick={() => void 0} type="secondary">
              Other Action
            </GoAButton>
          </GoAButtonGroup>
        </div>
      </GoAHeroBanner>
      <br />
      <h2>Min Height</h2>
      <GoAHeroBanner
        heading="Hero Banner"
        backgroundUrl="https://i.picsum.photos/id/1076/600/400.jpg?hmac=iLAZWoEDYRRPGnsbx7aWOGf-olRn3R5eOLDgH_IfXRw"
        minHeight="700px"
      >
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur
        optio, eius expedita, quasi vero maxime, laudantium voluptates eaque
        illum officiis hic!
      </GoAHeroBanner>
    </>
  );
}

// apps/angular-demo/src/app/hero-banner/hero-banner.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "abgov-hero-banner",
  templateUrl: "./hero-banner.component.html",
  styleUrls: ["./hero-banner.component.css"],
})
export class HeroBannerComponent {
  constructor() {}
}

<h1>Hero Banner</h1>

<h2>Default</h2>
<goa-hero-banner
  heading="Hero Banner"
  backgroundurl="https://i.picsum.photos/id/1076/600/400.jpg?hmac=iLAZWoEDYRRPGnsbx7aWOGf-olRn3R5eOLDgH_IfXRw"
>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur optio,
  eius expedita, quasi vero maxime, laudantium voluptates eaque illum officiis
  hic!
</goa-hero-banner>

<h2>With Actions</h2>
<goa-hero-banner
  heading="Hero Banner"
  backgroundurl="https://i.picsum.photos/id/1076/600/400.jpg?hmac=iLAZWoEDYRRPGnsbx7aWOGf-olRn3R5eOLDgH_IfXRw"
>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur optio,
  eius expedita, quasi vero maxime, laudantium voluptates eaque illum officiis
  hic!
  <div slot="actions">
    <goa-button-group>
      <goa-button>Action</goa-button>
      <goa-button type="secondary">Other Action</goa-button>
    </goa-button-group>
  </div>
</goa-hero-banner>

<h2>Min Height</h2>
<goa-hero-banner
  heading="Hero Banner"
  backgroundurl="https://i.picsum.photos/id/1076/600/400.jpg?hmac=iLAZWoEDYRRPGnsbx7aWOGf-olRn3R5eOLDgH_IfXRw"
  minHeight="700px"
>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur optio,
  eius expedita, quasi vero maxime, laudantium voluptates eaque illum officiis
  hic!
</goa-hero-banner>
