// libs/react-components/src/lib/tab/tab.tsx
import type { JSX } from "react";

interface WCProps {
  heading?: string | React.ReactNode;
  disabled?: string;
  slug?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-tab": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabTabItemProps {
  /** The text label for this tab. Can also pass React nodes for custom heading content. */
  heading?: string | React.ReactNode;
  /** When true, disables the tab so it cannot be selected. */
  disabled?: boolean;
  /** Content rendered inside the tab panel. */
  children?: React.ReactNode;
  /** URL-friendly identifier for the tab, used for hash-based navigation. */
  slug?: string;
}

/** Individual tab within a tabs component. */
export function GoabTab({
  heading,
  disabled,
  slug,
  children,
}: GoabTabItemProps): JSX.Element {
  return (
    <goa-tab
      slug={slug}
      disabled={disabled ? "true" : undefined}
      heading={typeof heading === "string" ? heading : undefined}
    >
      {typeof heading !== "string" && <span slot="heading">{heading}</span>}
      {children}
    </goa-tab>
  );
}

// libs/angular-components/src/lib/components/tab/tab.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  TemplateRef,
  OnInit,
  ChangeDetectorRef,
  booleanAttribute,
  inject,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

@Component({
  standalone: true,
  selector: "goab-tab",
  template: `
    @if (isReady) {
      <goa-tab
        [attr.slug]="slug"
        [attr.disabled]="disabled || null"
        [attr.heading]="getHeadingAsString()"
      >
        <ng-content />
        @if (typeof heading !== "string") {
          <div slot="heading">
            <ng-container [ngTemplateOutlet]="getHeadingAsTemplate()"></ng-container>
          </div>
        }
      </goa-tab>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [NgTemplateOutlet],
})
/** Individual tab within a tabs component. */
export class GoabTab implements OnInit {
  private cdr = inject(ChangeDetectorRef);

  isReady = false;
  /** The text label for this tab. Can also use the heading slot for custom content. */
  @Input() heading!: string | TemplateRef<any>;
  /** When true, disables the tab. */
  @Input({ transform: booleanAttribute }) disabled?: boolean;
  /** Sets the URL slug for the tab. */
  @Input() slug?: string;

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    });
  }

  getHeadingAsString(): string {
    return this.heading instanceof TemplateRef ? "" : this.heading;
  }

  getHeadingAsTemplate(): TemplateRef<any> | null {
    if (!this.heading) return null;
    return this.heading instanceof TemplateRef ? this.heading : null;
  }
}
