// libs/angular-components/src/lib/components/form-step/form-step.ts
import { GoABFormStepStatus } from "@abgov/ui-components-common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-form-step",
  template: ` <goa-form-step [attr.text]="text" [attr.status]="status"></goa-form-step> `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoABFormStep {
  @Input() text?: string;
  @Input() status?: GoABFormStepStatus;
}

// libs/vue-components/src/lib/form-step/form-step.vue
<script setup lang="ts">
import type { GoabFormStepStatus } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  text: string;
  status?: GoabFormStepStatus;
  disabled?: boolean;
  testId?: string;
}

const props = defineProps<Props>();

const wcProps = useWcProps(props, { booleanProps: ["disabled"] });
</script>

<template>
  <goa-form-step v-bind="wcProps" />
</template>
