// apps/prs/angular/src/routes/docs/file-uploader/file-uploader.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  GoabFileUploadCard,
  GoabFileUploadInput,
  GoabFormItem,
} from "@abgov/angular-components";
import type {
  GoabFileUploadInputOnSelectFileDetail,
  GoabFileUploadOnDeleteDetail,
} from "@abgov/ui-components-common";

interface UploadedFile {
  id: string;
  filename: string;
  size: number;
  type?: string;
  progress: number;
}

@Component({
  standalone: true,
  selector: "abgov-docs-file-uploader",
  templateUrl: "./file-uploader.component.html",
  imports: [CommonModule, GoabFileUploadCard, GoabFileUploadInput, GoabFormItem],
})
export class DocsFileUploaderComponent {
  basicFiles: UploadedFile[] = [];
  imageFiles: UploadedFile[] = [];
  pdfFiles: UploadedFile[] = [];
  smallFiles: UploadedFile[] = [];
  largeFiles: UploadedFile[] = [];
  buttonFiles: UploadedFile[] = [];
  dragdropFiles: UploadedFile[] = [];

  private simulateUpload(
    detail: GoabFileUploadInputOnSelectFileDetail,
    getList: () => UploadedFile[],
    setList: (next: UploadedFile[]) => void,
  ): void {
    const file = detail.file;
    const id = `${file.name}-${Date.now()}`;
    const uploaded: UploadedFile = {
      id,
      filename: file.name,
      size: file.size,
      type: file.type,
      progress: 0,
    };
    setList([...getList(), uploaded]);

    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.random() * 30 + 10;
      if (progress >= 100) {
        setList(
          getList().map((f) => (f.id === id ? { ...f, progress: -1 } : f)),
        );
        clearInterval(interval);
      } else {
        setList(
          getList().map((f) =>
            f.id === id ? { ...f, progress: Math.round(progress) } : f,
          ),
        );
      }
    }, 300);
  }

  uploadBasic(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.basicFiles, (next) => (this.basicFiles = next));
  }
  deleteBasic(detail: GoabFileUploadOnDeleteDetail): void {
    this.basicFiles = this.basicFiles.filter((f) => f.filename !== detail.filename);
  }

  uploadImage(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.imageFiles, (next) => (this.imageFiles = next));
  }
  deleteImage(detail: GoabFileUploadOnDeleteDetail): void {
    this.imageFiles = this.imageFiles.filter((f) => f.filename !== detail.filename);
  }

  uploadPdf(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.pdfFiles, (next) => (this.pdfFiles = next));
  }
  deletePdf(detail: GoabFileUploadOnDeleteDetail): void {
    this.pdfFiles = this.pdfFiles.filter((f) => f.filename !== detail.filename);
  }

  uploadSmall(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.smallFiles, (next) => (this.smallFiles = next));
  }
  deleteSmall(detail: GoabFileUploadOnDeleteDetail): void {
    this.smallFiles = this.smallFiles.filter((f) => f.filename !== detail.filename);
  }

  uploadLarge(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.largeFiles, (next) => (this.largeFiles = next));
  }
  deleteLarge(detail: GoabFileUploadOnDeleteDetail): void {
    this.largeFiles = this.largeFiles.filter((f) => f.filename !== detail.filename);
  }

  uploadButton(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.buttonFiles, (next) => (this.buttonFiles = next));
  }
  deleteButton(detail: GoabFileUploadOnDeleteDetail): void {
    this.buttonFiles = this.buttonFiles.filter((f) => f.filename !== detail.filename);
  }

  uploadDragdrop(detail: GoabFileUploadInputOnSelectFileDetail): void {
    this.simulateUpload(detail, () => this.dragdropFiles, (next) => (this.dragdropFiles = next));
  }
  deleteDragdrop(detail: GoabFileUploadOnDeleteDetail): void {
    this.dragdropFiles = this.dragdropFiles.filter((f) => f.filename !== detail.filename);
  }

  handleCardDelete(detail: GoabFileUploadOnDeleteDetail): void {
    console.log("delete", detail);
  }
}

<h2>File uploader</h2>

<h3>Basic file upload</h3>
<goab-form-item label="Upload document" mb="l">
  <goab-file-upload-input
    variant="dragdrop"
    (onSelectFile)="uploadBasic($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of basicFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deleteBasic($event)">
  </goab-file-upload-card>
}

<h3>Accepted file types</h3>
<goab-form-item label="Upload image" mb="l">
  <goab-file-upload-input
    variant="dragdrop"
    accept="image/*"
    (onSelectFile)="uploadImage($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of imageFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deleteImage($event)">
  </goab-file-upload-card>
}
<goab-form-item label="Upload PDF" mb="l">
  <goab-file-upload-input
    variant="dragdrop"
    accept=".pdf"
    (onSelectFile)="uploadPdf($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of pdfFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deletePdf($event)">
  </goab-file-upload-card>
}

<h3>Max file size</h3>
<goab-form-item label="Small file (100KB limit)" mb="l">
  <goab-file-upload-input
    variant="dragdrop"
    maxFileSize="100KB"
    (onSelectFile)="uploadSmall($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of smallFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deleteSmall($event)">
  </goab-file-upload-card>
}
<goab-form-item label="Large file (50MB limit)" mb="l">
  <goab-file-upload-input
    variant="dragdrop"
    maxFileSize="50MB"
    (onSelectFile)="uploadLarge($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of largeFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deleteLarge($event)">
  </goab-file-upload-card>
}

<h3>Variants</h3>
<goab-form-item label="Button variant" mb="l">
  <goab-file-upload-input
    variant="button"
    (onSelectFile)="uploadButton($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of buttonFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deleteButton($event)">
  </goab-file-upload-card>
}
<goab-form-item label="Dragdrop variant" mb="l">
  <goab-file-upload-input
    variant="dragdrop"
    (onSelectFile)="uploadDragdrop($event)">
  </goab-file-upload-input>
</goab-form-item>
@for (f of dragdropFiles; track f.id) {
  <goab-file-upload-card
    [filename]="f.filename"
    [size]="f.size"
    [type]="f.type"
    [progress]="f.progress"
    (onDelete)="deleteDragdrop($event)">
  </goab-file-upload-card>
}

<h2>File upload card</h2>

<h3>Basic file upload card</h3>
<goab-file-upload-card
  filename="document.pdf"
  [size]="1024000"
  (onDelete)="handleCardDelete($event)">
</goab-file-upload-card>

<h3>File types</h3>
<goab-file-upload-card filename="report.pdf" type="application/pdf" [size]="256000" (onDelete)="handleCardDelete($event)"></goab-file-upload-card>
<goab-file-upload-card filename="photo.jpg" type="image/jpeg" [size]="1024000" (onDelete)="handleCardDelete($event)"></goab-file-upload-card>
<goab-file-upload-card filename="data.csv" type="text/csv" [size]="48000" (onDelete)="handleCardDelete($event)"></goab-file-upload-card>

<h3>With upload progress</h3>
<goab-file-upload-card
  filename="image.png"
  [size]="2048000"
  [progress]="65">
</goab-file-upload-card>

<h3>Error state</h3>
<goab-file-upload-card
  filename="large-file.zip"
  [size]="104857600"
  error="File exceeds maximum size limit"
  (onDelete)="handleCardDelete($event)">
</goab-file-upload-card>

// apps/prs/react/src/routes/docs/file-uploader/file-uploader.tsx
import { useState } from "react";
import {
  GoabFileUploadCard,
  GoabFileUploadInput,
  GoabFormItem,
} from "@abgov/react-components";
import type {
  GoabFileUploadInputOnSelectFileDetail,
  GoabFileUploadOnDeleteDetail,
} from "@abgov/ui-components-common";

type UploadedFile = {
  id: string;
  filename: string;
  size: number;
  type?: string;
  progress: number;
};

export function DocsFileUploaderRoute() {
  const [basicFiles, setBasicFiles] = useState<UploadedFile[]>([]);
  const [imageFiles, setImageFiles] = useState<UploadedFile[]>([]);
  const [pdfFiles, setPdfFiles] = useState<UploadedFile[]>([]);
  const [smallFiles, setSmallFiles] = useState<UploadedFile[]>([]);
  const [largeFiles, setLargeFiles] = useState<UploadedFile[]>([]);
  const [buttonFiles, setButtonFiles] = useState<UploadedFile[]>([]);
  const [dragdropFiles, setDragdropFiles] = useState<UploadedFile[]>([]);

  function uploadFile(
    detail: GoabFileUploadInputOnSelectFileDetail,
    setFiles: React.Dispatch<React.SetStateAction<UploadedFile[]>>,
  ) {
    const file = detail.file;
    const id = `${file.name}-${Date.now()}`;
    const uploaded: UploadedFile = {
      id,
      filename: file.name,
      size: file.size,
      type: file.type,
      progress: 0,
    };
    setFiles((prev) => [...prev, uploaded]);

    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.random() * 30 + 10;
      if (progress >= 100) {
        setFiles((prev) =>
          prev.map((f) => (f.id === id ? { ...f, progress: -1 } : f)),
        );
        clearInterval(interval);
      } else {
        setFiles((prev) =>
          prev.map((f) =>
            f.id === id ? { ...f, progress: Math.round(progress) } : f,
          ),
        );
      }
    }, 300);
  }

  function deleteFile(
    detail: GoabFileUploadOnDeleteDetail,
    setFiles: React.Dispatch<React.SetStateAction<UploadedFile[]>>,
  ) {
    setFiles((prev) => prev.filter((f) => f.filename !== detail.filename));
  }

  return (
    <div>
      <h2>File uploader</h2>

      <h3>Basic file upload</h3>
      <GoabFormItem label="Upload document" mb="l">
        <GoabFileUploadInput
          onSelectFile={(detail) => uploadFile(detail, setBasicFiles)}
        />
      </GoabFormItem>
      {basicFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setBasicFiles)}
        />
      ))}

      <h3>Accepted file types</h3>
      <GoabFormItem label="Upload image" mb="l">
        <GoabFileUploadInput
          accept="image/*"
          onSelectFile={(detail) => uploadFile(detail, setImageFiles)}
        />
      </GoabFormItem>
      {imageFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setImageFiles)}
        />
      ))}
      <GoabFormItem label="Upload PDF" mb="l">
        <GoabFileUploadInput
          accept=".pdf"
          onSelectFile={(detail) => uploadFile(detail, setPdfFiles)}
        />
      </GoabFormItem>
      {pdfFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setPdfFiles)}
        />
      ))}

      <h3>Max file size</h3>
      <GoabFormItem label="Small file (100KB limit)" mb="l">
        <GoabFileUploadInput
          maxFileSize="100KB"
          onSelectFile={(detail) => uploadFile(detail, setSmallFiles)}
        />
      </GoabFormItem>
      {smallFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setSmallFiles)}
        />
      ))}
      <GoabFormItem label="Large file (50MB limit)" mb="l">
        <GoabFileUploadInput
          maxFileSize="50MB"
          onSelectFile={(detail) => uploadFile(detail, setLargeFiles)}
        />
      </GoabFormItem>
      {largeFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setLargeFiles)}
        />
      ))}

      <h3>Variants</h3>
      <GoabFormItem label="Button variant" mb="l">
        <GoabFileUploadInput
          variant="button"
          onSelectFile={(detail) => uploadFile(detail, setButtonFiles)}
        />
      </GoabFormItem>
      {buttonFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setButtonFiles)}
        />
      ))}
      <GoabFormItem label="Dragdrop variant" mb="l">
        <GoabFileUploadInput
          variant="dragdrop"
          onSelectFile={(detail) => uploadFile(detail, setDragdropFiles)}
        />
      </GoabFormItem>
      {dragdropFiles.map((f) => (
        <GoabFileUploadCard
          key={f.id}
          filename={f.filename}
          size={f.size}
          type={f.type}
          progress={f.progress}
          onDelete={(detail) => deleteFile(detail, setDragdropFiles)}
        />
      ))}

      <h2>File upload card</h2>

      <h3>Basic file upload card</h3>
      <GoabFileUploadCard
        filename="document.pdf"
        size={1024000}
        onDelete={(detail) => console.log("delete", detail)}
      />

      <h3>File types</h3>
      <GoabFileUploadCard
        filename="report.pdf"
        type="application/pdf"
        size={256000}
        onDelete={(detail) => console.log("delete", detail)}
      />
      <GoabFileUploadCard
        filename="photo.jpg"
        type="image/jpeg"
        size={1024000}
        onDelete={(detail) => console.log("delete", detail)}
      />
      <GoabFileUploadCard
        filename="data.csv"
        type="text/csv"
        size={48000}
        onDelete={(detail) => console.log("delete", detail)}
      />

      <h3>With upload progress</h3>
      <GoabFileUploadCard filename="image.png" size={2048000} progress={65} />

      <h3>Error state</h3>
      <GoabFileUploadCard
        filename="large-file.zip"
        size={104857600}
        error="File exceeds maximum size limit"
        onDelete={(detail) => console.log("delete", detail)}
      />
    </div>
  );
}
