// apps/prs/react/src/routes/docs/block/block.tsx
import { GoabBlock, GoabContainer } from "@abgov/react-components";

export function DocsBlockRoute() {
  return (
    <div>
      <h2>Block</h2>

      <h3>Basic block</h3>
      <GoabBlock>
        <GoabContainer type="non-interactive"><p>First item</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Second item</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Third item</p></GoabContainer>
      </GoabBlock>

      <h3>Gap sizes</h3>
      <GoabBlock gap="xs" mb="l">
        <GoabContainer type="non-interactive"><p>Extra small gap</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Item 2</p></GoabContainer>
      </GoabBlock>
      <GoabBlock gap="m" mb="l">
        <GoabContainer type="non-interactive"><p>Medium gap</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Item 2</p></GoabContainer>
      </GoabBlock>
      <GoabBlock gap="xl">
        <GoabContainer type="non-interactive"><p>Extra large gap</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Item 2</p></GoabContainer>
      </GoabBlock>

      <h3>Alignment</h3>
      <GoabBlock alignment="start" mb="m" direction="column" width="100%">
        <GoabContainer type="non-interactive" width="content"><p>Start aligned</p></GoabContainer>
      </GoabBlock>
      <GoabBlock alignment="center" mb="m" direction="column" width="100%">
        <GoabContainer type="non-interactive" width="content"><p>Center aligned</p></GoabContainer>
      </GoabBlock>
      <GoabBlock alignment="end" direction="column" width="100%">
        <GoabContainer type="non-interactive" width="content"><p>End aligned</p></GoabContainer>
      </GoabBlock>

      <h3>Direction</h3>
      <GoabBlock direction="row" gap="l" mb="l">
        <GoabContainer type="non-interactive"><p>Row item 1</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Row item 2</p></GoabContainer>
      </GoabBlock>
      <GoabBlock direction="column" gap="m">
        <GoabContainer type="non-interactive"><p>Column item 1</p></GoabContainer>
        <GoabContainer type="non-interactive"><p>Column item 2</p></GoabContainer>
      </GoabBlock>
    </div>
  );
}

// apps/prs/angular/src/routes/docs/block/block.component.ts
import { Component } from "@angular/core";
import { GoabBlock, GoabContainer } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-block",
  templateUrl: "./block.component.html",
  imports: [GoabBlock, GoabContainer],
})
export class DocsBlockComponent {}

<h2>Block</h2>

<h3>Basic block</h3>
<goab-block>
  <goab-container type="non-interactive"><p>First item</p></goab-container>
  <goab-container type="non-interactive"><p>Second item</p></goab-container>
  <goab-container type="non-interactive"><p>Third item</p></goab-container>
</goab-block>

<h3>Gap sizes</h3>
<goab-block gap="xs" mb="l">
  <goab-container type="non-interactive"><p>Extra small gap</p></goab-container>
  <goab-container type="non-interactive"><p>Item 2</p></goab-container>
</goab-block>
<goab-block gap="m" mb="l">
  <goab-container type="non-interactive"><p>Medium gap</p></goab-container>
  <goab-container type="non-interactive"><p>Item 2</p></goab-container>
</goab-block>
<goab-block gap="xl">
  <goab-container type="non-interactive"><p>Extra large gap</p></goab-container>
  <goab-container type="non-interactive"><p>Item 2</p></goab-container>
</goab-block>

<h3>Alignment</h3>
<goab-block alignment="start" mb="m" direction="column" width="100%">
  <goab-container type="non-interactive" width="content"><p>Start aligned</p></goab-container>
</goab-block>
<goab-block alignment="center" mb="m" direction="column" width="100%">
  <goab-container type="non-interactive" width="content"><p>Center aligned</p></goab-container>
</goab-block>
<goab-block alignment="end" direction="column" width="100%">
  <goab-container type="non-interactive" width="content"><p>End aligned</p></goab-container>
</goab-block>

<h3>Direction</h3>
<goab-block direction="row" gap="l" mb="l">
  <goab-container type="non-interactive"><p>Row item 1</p></goab-container>
  <goab-container type="non-interactive"><p>Row item 2</p></goab-container>
</goab-block>
<goab-block direction="column" gap="m">
  <goab-container type="non-interactive"><p>Column item 1</p></goab-container>
  <goab-container type="non-interactive"><p>Column item 2</p></goab-container>
</goab-block>
