// apps/react-demo/src/routes/notificationBanner.tsx
import {
  GoANotification
} from '@abgov/react-components';

export default function NotificationBanner() {
  return (
    <>
      <h1>Notification Banner</h1>

      <h2>Information</h2>
        <GoANotification type="information">Lorem ipsum dolor <a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a> Lorem ipsum dolor</GoANotification>
      <h2>Important</h2>
        <GoANotification type="important"><a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></GoANotification>
      <h2>Emergency</h2>
        <GoANotification type="emergency"><a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></GoANotification>
      <h2>Event</h2>
        <GoANotification type="event">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</GoANotification>
   </>
  );
}

// apps/angular-demo/src/app/notification-banner/notification-banner.component.ts
import { Component } from '@angular/core';

@Component({
  selector: "abgov-notification-banner",
  templateUrl: "./notification-banner.component.html",
  styleUrls: ["./notification-banner.component.css"]
})
export class NotificationBannerComponent {

  constructor() { }

}

<h1>Notification Banner</h1>

<h2>Information</h2>
<goa-notification type="information">Lorem ipsum dolor <a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a> Lorem ipsum dolor</goa-notification>
<h2>Important</h2>
<goa-notification type="important"><a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></goa-notification>
<h2>Emergency</h2>
<goa-notification type="emergency"><a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></goa-notification>
<h2>Event</h2>
<goa-notification type="event">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</goa-notification>
