// apps/prs/angular/src/routes/docs/link/link.component.ts
import { Component } from "@angular/core";
import { GoabLink } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-link",
  templateUrl: "./link.component.html",
  imports: [GoabLink],
})
export class DocsLinkComponent {}

<h2>Link</h2>

<h3>Basic link</h3>
<goab-link><a href="/about">Learn more about our services</a></goab-link>

<h3>External link</h3>
<goab-link trailingIcon="open">
  <a href="https://www.alberta.ca">Visit Alberta.ca</a>
</goab-link>

<h3>Colors</h3>
<div style="margin-bottom: var(--goa-space-m);">
  <goab-link color="interactive"><a href="#">Interactive (default)</a></goab-link>
</div>
<div style="margin-bottom: var(--goa-space-m);">
  <goab-link color="dark"><a href="#">Dark</a></goab-link>
</div>
<div style="background-color: var(--goa-color-greyscale-700); padding: var(--goa-space-m);">
  <goab-link color="light"><a href="#">Light</a></goab-link>
</div>

<h3>Sizes</h3>
<div><goab-link size="xsmall" mb="xs"><a href="#">Extra small link</a></goab-link></div>
<div><goab-link size="small" mb="xs"><a href="#">Small link</a></goab-link></div>
<div><goab-link size="medium" mb="xs"><a href="#">Medium link (default)</a></goab-link></div>
<div><goab-link size="large"><a href="#">Large link</a></goab-link></div>

<h3>With icons</h3>
<div><goab-link leadingIcon="download" mb="xs"><a href="#">Download form</a></goab-link></div>
<div><goab-link trailingIcon="arrow-forward"><a href="#">Continue to next step</a></goab-link></div>

// apps/prs/react/src/routes/docs/link/link.tsx
import { GoabLink } from "@abgov/react-components";

export function DocsLinkRoute() {
  return (
    <div>
      <h2>Link</h2>

      <h3>Basic link</h3>
      <GoabLink>
        <a href="/about">Learn more about our services</a>
      </GoabLink>

      <h3>External link</h3>
      <GoabLink trailingIcon="open">
        <a href="https://www.alberta.ca">Visit Alberta.ca</a>
      </GoabLink>

      <h3>Colors</h3>
      <div style={{ marginBottom: "var(--goa-space-m)" }}>
        <GoabLink color="interactive">
          <a href="#">Interactive (default)</a>
        </GoabLink>
      </div>
      <div style={{ marginBottom: "var(--goa-space-m)" }}>
        <GoabLink color="dark">
          <a href="#">Dark</a>
        </GoabLink>
      </div>
      <div
        style={{
          backgroundColor: "var(--goa-color-greyscale-700)",
          padding: "var(--goa-space-m)",
        }}
      >
        <GoabLink color="light">
          <a href="#">Light</a>
        </GoabLink>
      </div>

      <h3>Sizes</h3>
      <div>
        <GoabLink size="xsmall" mb="xs">
          <a href="#">Extra small link</a>
        </GoabLink>
      </div>
      <div>
        <GoabLink size="small" mb="xs">
          <a href="#">Small link</a>
        </GoabLink>
      </div>
      <div>
        <GoabLink size="medium" mb="xs">
          <a href="#">Medium link (default)</a>
        </GoabLink>
      </div>
      <div>
        <GoabLink size="large">
          <a href="#">Large link</a>
        </GoabLink>
      </div>

      <h3>With icons</h3>
      <div>
        <GoabLink leadingIcon="download" mb="xs">
          <a href="#">Download form</a>
        </GoabLink>
      </div>
      <div>
        <GoabLink trailingIcon="arrow-forward">
          <a href="#">Continue to next step</a>
        </GoabLink>
      </div>
    </div>
  );
}
