// apps/prs/react/src/routes/docs/tabs/tabs.tsx
import {
  GoabBadge,
  GoabButton,
  GoabTab,
  GoabTabs,
  GoabText,
} from "@abgov/react-components";

export function DocsTabsRoute() {
  const activateDetailsTab = () => {
    window.location.hash = "button-example-details";
  };

  return (
    <div>
      <h2>Tabs</h2>

      <h3>Basic tabs</h3>
      <GoabTabs initialTab={1}>
        <GoabTab heading="Overview">
          <p>Overview content goes here.</p>
        </GoabTab>
        <GoabTab heading="Details">
          <p>Detailed information goes here.</p>
        </GoabTab>
        <GoabTab heading="History">
          <p>Historical data goes here.</p>
        </GoabTab>
      </GoabTabs>

      <h3>Segmented variant</h3>
      <GoabTabs variant="segmented">
        <GoabTab heading="Day">Daily view</GoabTab>
        <GoabTab heading="Week">Weekly view</GoabTab>
        <GoabTab heading="Month">Monthly view</GoabTab>
      </GoabTabs>

      <h3>Initial tab</h3>
      <GoabTabs initialTab={2}>
        <GoabTab heading="First">First tab content.</GoabTab>
        <GoabTab heading="Second">Second tab content (initially shown).</GoabTab>
        <GoabTab heading="Third">Third tab content.</GoabTab>
      </GoabTabs>

      <h3>Activate a tab with a button</h3>
      <GoabButton onClick={activateDetailsTab}>Open details</GoabButton>
      <GoabTabs>
        <GoabTab heading="Summary" slug="button-example-summary">
          Summary content goes here.
        </GoabTab>
        <GoabTab heading="Details" slug="button-example-details">
          Detailed information goes here.
        </GoabTab>
      </GoabTabs>

      <h3>With badge in heading</h3>
      <GoabTabs>
        <GoabTab heading="Messages">
          <GoabText>Your messages will appear here.</GoabText>
        </GoabTab>
        <GoabTab
          heading={
            <>
              Notifications{" "}
              <GoabBadge type="default" emphasis="subtle" icon={false} content="3" />
            </>
          }
        >
          <GoabText>You have 3 unread notifications.</GoabText>
        </GoabTab>
        <GoabTab heading="Settings">
          <GoabText>Manage your preferences.</GoabText>
        </GoabTab>
      </GoabTabs>

      <h3>Disabled tab</h3>
      <GoabTabs>
        <GoabTab heading="Active">
          <GoabText>This tab is active.</GoabText>
        </GoabTab>
        <GoabTab heading="Disabled" disabled>
          <GoabText>This content is not accessible.</GoabText>
        </GoabTab>
        <GoabTab heading="Another tab">
          <GoabText>This tab is also available.</GoabText>
        </GoabTab>
      </GoabTabs>

      <h3>Horizontal on mobile</h3>
      <GoabTabs initialTab={1} orientation="horizontal">
        <GoabTab heading="Tab 1">Content 1</GoabTab>
        <GoabTab heading="Tab 2">Content 2</GoabTab>
        <GoabTab heading="Tab 3">Content 3</GoabTab>
      </GoabTabs>
    </div>
  );
}

// apps/prs/angular/src/routes/docs/tabs/tabs.component.ts
import { Component } from "@angular/core";
import {
  GoabBadge,
  GoabButton,
  GoabTab,
  GoabTabs,
  GoabText,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-tabs",
  templateUrl: "./tabs.component.html",
  imports: [GoabBadge, GoabButton, GoabTab, GoabTabs, GoabText],
})
export class DocsTabsComponent {
  activateDetailsTab(): void {
    window.location.hash = "button-example-details";
  }
}

<h2>Tabs</h2>

<h3>Basic tabs</h3>
<goab-tabs [initialTab]="1">
  <goab-tab heading="Overview">
    <p>Overview content goes here.</p>
  </goab-tab>
  <goab-tab heading="Details">
    <p>Detailed information goes here.</p>
  </goab-tab>
  <goab-tab heading="History">
    <p>Historical data goes here.</p>
  </goab-tab>
</goab-tabs>

<h3>Segmented variant</h3>
<goab-tabs variant="segmented">
  <goab-tab heading="Day">Daily view</goab-tab>
  <goab-tab heading="Week">Weekly view</goab-tab>
  <goab-tab heading="Month">Monthly view</goab-tab>
</goab-tabs>

<h3>Initial tab</h3>
<goab-tabs [initialTab]="2">
  <goab-tab heading="First">First tab content.</goab-tab>
  <goab-tab heading="Second">Second tab content (initially shown).</goab-tab>
  <goab-tab heading="Third">Third tab content.</goab-tab>
</goab-tabs>

<h3>Activate a tab with a button</h3>
<goab-button (onClick)="activateDetailsTab()">Open details</goab-button>
<goab-tabs>
  <goab-tab heading="Summary" slug="button-example-summary">
    Summary content goes here.
  </goab-tab>
  <goab-tab heading="Details" slug="button-example-details">
    Detailed information goes here.
  </goab-tab>
</goab-tabs>

<h3>With badge in heading</h3>
<goab-tabs>
  <goab-tab heading="Messages">
    <goab-text>Your messages will appear here.</goab-text>
  </goab-tab>
  <goab-tab [heading]="notifHeadingTpl">
    <ng-template #notifHeadingTpl>Notifications <goab-badge type="default" emphasis="subtle" [icon]="false" content="3"></goab-badge></ng-template>
    <goab-text>You have 3 unread notifications.</goab-text>
  </goab-tab>
  <goab-tab heading="Settings">
    <goab-text>Manage your preferences.</goab-text>
  </goab-tab>
</goab-tabs>

<h3>Disabled tab</h3>
<goab-tabs>
  <goab-tab heading="Active">
    <goab-text>This tab is active.</goab-text>
  </goab-tab>
  <goab-tab heading="Disabled" [disabled]="true">
    <goab-text>This content is not accessible.</goab-text>
  </goab-tab>
  <goab-tab heading="Another tab">
    <goab-text>This tab is also available.</goab-text>
  </goab-tab>
</goab-tabs>

<h3>Horizontal on mobile</h3>
<goab-tabs [initialTab]="1" orientation="horizontal">
  <goab-tab heading="Tab 1">Content 1</goab-tab>
  <goab-tab heading="Tab 2">Content 2</goab-tab>
  <goab-tab heading="Tab 3">Content 3</goab-tab>
</goab-tabs>
