// libs/vue-components/src/lib/work-side-notification-panel/work-side-notification-panel.vue
<script setup lang="ts">
import type { GoabWorkSideNotificationActiveTabType } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Sets the panel heading text. @default "Notifications" */
  heading?: string;
  /** Sets the initially active tab. @default "unread" */
  activeTab?: GoabWorkSideNotificationActiveTabType;
  /** Sets a data-testid attribute for automated testing.  @default "" */
  testId?: string;
}

const props = withDefaults(defineProps<Props>(), {
  heading: "Notifications",
  activeTab: "unread",
});
const emit = defineEmits<{
  /** Callback fired when the "Mark all as read" button is clicked. */
  onMarkAllRead: [];
  /** Callback fired when the "View all" button is clicked. */
  onViewAll: [];
}>();

const wcProps = useWcProps(props, { renamedProps: { activeTab: "active-tab" } });
</script>

<template>
  <goa-work-side-notification-panel v-bind="wcProps" @_markAllRead="emit('onMarkAllRead')" @_viewAll="emit('onViewAll')">
    <slot />
  </goa-work-side-notification-panel>
</template>

// libs/angular-components/src/lib/components/work-side-notification-panel/work-side-notification-panel.ts
import { GoabWorkSideNotificationActiveTabType } from "@abgov/ui-components-common";
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  ChangeDetectorRef,
  inject,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-work-side-notification-panel", // eslint-disable-line
  template: `
    @if (isReady) {
      <goa-work-side-notification-panel
        [attr.heading]="heading"
        [attr.active-tab]="activeTab"
        [attr.testid]="testId"
        (_markAllRead)="_onMarkAllRead()"
        (_viewAll)="_onViewAll()"
      >
        <ng-content />
      </goa-work-side-notification-panel>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
/** Displays a panel of work-side notifications. */
export class GoabWorkSideNotificationPanel implements OnInit {
  private cdr = inject(ChangeDetectorRef);

  /** The heading text displayed at the top of the notification panel. */
  @Input() heading?: string;
  /** Sets the initially active tab in the notification panel. */
  @Input() activeTab?: GoabWorkSideNotificationActiveTabType;
  /** Sets a data-testid attribute for automated testing. */
  @Input() testId?: string;

  /** Emits when the user clicks "Mark all as read". */
  @Output() onMarkAllRead = new EventEmitter<void>();
  /** Emits when the user clicks "View all". */
  @Output() onViewAll = new EventEmitter<void>();

  isReady = false;

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }

  _onMarkAllRead() {
    this.onMarkAllRead.emit();
  }

  _onViewAll() {
    this.onViewAll.emit();
  }
}
