// libs/react-components/src/lib/form/fieldset.tsx
import { ReactNode, useEffect, useRef } from "react";
import {
  GoabFieldsetOnChangeDetail,
  GoabFieldsetOnContinueDetail,
  GoabFormDispatchOn,
  Margins,
} from "@abgov/ui-components-common";

interface WCProps extends Margins {
  ref?: React.RefObject<HTMLElement | null>;
  id?: string;
  "section-title"?: string;
  "dispatch-on"?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-fieldset": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface GoabFieldsetProps extends Margins {
  id?: string;
  sectionTitle?: string;
  dispatchOn?: GoabFormDispatchOn;
  onContinue?: (event: GoabFieldsetOnContinueDetail) => void;
  onChange?: (event: GoabFieldsetOnChangeDetail) => void;
  children: ReactNode;
}

export function GoabFieldset({
  id,
  sectionTitle,
  dispatchOn,
  onContinue,
  onChange,
  children,

}: GoabFieldsetProps) {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!ref.current) return;
    const current = ref.current;

    const changeListener = (e: unknown) => {
      const detail = (e as CustomEvent<GoabFieldsetOnChangeDetail>).detail;
      onChange?.(detail);
    }
    const continueListener = (e: Event) => {
      const event = (e as CustomEvent<GoabFieldsetOnContinueDetail>).detail;
      return onContinue?.(event);
    };

    if (onContinue) {
      current.addEventListener("_continue", continueListener);
    }
    if (onChange) {
      current.addEventListener("_change", changeListener);
    }

    return () => {
      if (onContinue) {
        current.removeEventListener("_continue", continueListener);
      }
      if (onChange) {
        current.removeEventListener("_change", changeListener);
      }
    };
  }, [ref, onContinue]);

  return (
    <goa-fieldset
      ref={ref}
      id={id}
      section-title={sectionTitle}
      dispatch-on={dispatchOn}
    >
      {children}
    </goa-fieldset>
  );
}

export default GoabFieldset;

// libs/angular-components/src/lib/components/form/fieldset.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, Output, EventEmitter } from "@angular/core";
import { GoabFormDispatchOn, GoabFieldsetOnChangeDetail, GoabFieldsetOnContinueDetail } from "@abgov/ui-components-common";

@Component({
  selector: 'goab-fieldset',
  template: `
    <goa-fieldset
      [attr.section-title]="sectionTitle"
      [attr.dispatch-on]="dispatchOn"
      [attr.id]="id"
      (_change)="_onChange($event)"
      (_continue)="_onContinue($event)"
    >
      <ng-content></ng-content>
    </goa-fieldset>`,
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabFieldset {
  @Input() id?: string;
  @Input() sectionTitle?: string;
  @Input() dispatchOn: GoabFormDispatchOn = "continue";

  @Output() onChange = new EventEmitter<GoabFieldsetOnChangeDetail>();
  @Output() onContinue = new EventEmitter<GoabFieldsetOnContinueDetail>();

  _onChange(event: Event) {
    const detail = (event as CustomEvent).detail;
    this.onChange.emit(detail);
  }

  _onContinue(event: Event) {
    const detail = (event as CustomEvent).detail;
    this.onContinue.emit(detail);
  }
}
