// libs/vue-components/src/lib/form/public-form-page.vue
<script setup lang="ts">
import type { GoabPublicFormPageButtonVisibility, GoabPublicFormPageStep, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Sets the id.  @default "" */
  id?: string;
  /** Sets the heading.  @default undefined */
  heading?: string;
  /** Sets the sub heading.  @default undefined */
  subHeading?: string;
  /** Sets the summary heading.  @default undefined */
  summaryHeading?: string;
  /** Sets the section title.  @default undefined */
  sectionTitle?: string;
  /** Sets the back url.  @default undefined */
  backUrl?: string;
  /** Sets the type.  @default undefined */
  type?: GoabPublicFormPageStep;
  /** Sets the button text.  @default undefined */
  buttonText?: string;
  /** Sets the button visibility.  @default undefined */
  buttonVisibility?: GoabPublicFormPageButtonVisibility;
  /** Sets the mt.  @default undefined */
  mt?: Spacing;
  /** Sets the mr.  @default undefined */
  mr?: Spacing;
  /** Sets the mb.  @default undefined */
  mb?: Spacing;
  /** Sets the ml.  @default undefined */
  ml?: Spacing;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  (e: "onContinue", detail: Event): void;
}>();

const wcProps = useWcProps(props, { transform: "kebab" });
</script>

<template>
  <goa-public-form-page v-bind="wcProps" @_continue="emit('onContinue', $event)">
    <slot />
  </goa-public-form-page>
</template>

// libs/angular-components/src/lib/components/form/public-form-page.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  EventEmitter,
  Input,
  Output,
} from "@angular/core";
import { GoabBaseComponent } from "../base.component";
import {
  GoabPublicFormPageButtonVisibility,
  GoabPublicFormPageStep,
} from "@abgov/ui-components-common";

@Component({
 selector: "goab-public-form-page",
 standalone: true,
 template: `
   <goa-public-form-page
     [id]="id"
     [attr.heading]="heading"
     [attr.sub-heading]="subHeading"
     [attr.section-title]="sectionTitle"
     [attr.back-url]="backUrl"
     [attr.type]="type"
     [attr.button-text]="buttonText"
     [attr.button-visibility]="buttonVisibility"
     [attr.summary-heading]="summaryHeading"
     [attr.mt]="mt"
     [attr.mr]="mr"
     [attr.mb]="mb"
     [attr.ml]="ml"
     (_continue)="_onContinue($event)"
   >
     <ng-content></ng-content>
   </goa-public-form-page>
 `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoabPublicFormPage extends GoabBaseComponent {
  @Input() id = "";
  @Input() heading = "";
  @Input() subHeading = "";
  @Input() summaryHeading = "";
  @Input() sectionTitle = "";
  @Input() backUrl = "";
  @Input() type: GoabPublicFormPageStep = "step";
  @Input() buttonText = "";
  @Input() buttonVisibility : GoabPublicFormPageButtonVisibility = "visible";

  /**
   * triggers when the form page continues to the next step
   */
  @Output() onContinue = new EventEmitter<Event>();

  _onContinue(event: Event) {
    this.onContinue.emit(event);
  }
}
