// apps/react-demo/src/routes/fileUpload.tsx
import { GoAFileUploadCard, GoAFileUploadInput } from "@abgov/react-components";
import * as React from "react";
import { useState } from "react";
import { MockUploader, Upload } from "@abgov/shared/common";

export default function FileUpload() {
  const [uploads, setUploads] = useState<Upload[]>([]);
  const [progressList, setProgressList] = useState<Record<string, number>>({});
  function uploadFile(file: File) {
    const reader = new FileReader();
    reader.onload = (e: ProgressEvent<FileReader>) => {
      if (!e.target) return;
      const url = e.target.result;
      const uploader = new MockUploader();

      setUploads((old) => [...old, { file, uploader }]);

      uploader.onabort = () => console.log("Aborting upload");
      uploader.onfail = (err) => console.log("Upload failed: ", err);
      uploader.oncomplete = () => console.log("File upload complete");
      uploader.onprogress = (percent) => {
        setProgressList((old) => ({ ...old, [file.name]: percent }));
      };
      if (url) {
        uploader.upload(url);
      }
    };
    reader.readAsDataURL(file);
  }
  function deleteFile(upload: Upload) {
    upload.uploader.abort();
    setUploads([...uploads].filter((u) => u.file.name !== upload.file.name));
  }
  return (
    <>
      <GoAFileUploadInput onSelectFile={uploadFile} />
      {uploads.map((upload) => (
        <GoAFileUploadCard
          key={upload.file.name}
          filename={upload.file.name}
          type={upload.file.type}
          size={upload.file.size}
          progress={progressList[upload.file.name]}
          onDelete={() => deleteFile(upload)}
          onCancel={() => deleteFile(upload)}
        />
      ))}
    </>
  );
}

// apps/angular-tests/src/app/file-upload/file-upload.ts
import { GoABFileUploadCard, GoABFileUploadInput } from "@abgov/angular-components";
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import { ReactiveFormsModule } from "@angular/forms";

interface Uploader {
  upload: (url: string | ArrayBuffer) => void;
  abort: () => void;
}

interface Upload {
  file: File;
  uploader: Uploader;
}

class MockUploader implements Uploader {
  public onprogress: (percent: number) => void = (_: number) => { };
  public onabort: () => void = () => { };
  public onfail: (err: string) => void = (_: string) => { };
  public oncomplete: () => void = () => { };

  upload(_url: string | ArrayBuffer) {
    // implement your logic to upload files
  }

  abort() {
    // implement your logic to abort file upload
  }
}

@Component({
  standalone: true,
  selector: "abgov-file-upload",
  templateUrl: "./file-upload.html",
  imports: [
    GoABFileUploadInput,
    GoABFileUploadCard,
    CommonModule,
  ],
})
export class FileUploadComponent {
  uploads: Upload[] = [];
  progressList: Record<string, number> = {};

  uploadFile(e: any) {
    const { file } = e;
    const reader = new FileReader();
    reader.onload = (ev) => {
      if (!ev.target || !ev.target.result) {
        return;
      }

      const url = ev.target.result;
      const uploader = new MockUploader();

      this.uploads = [...this.uploads, { file, uploader }];

      uploader.oncomplete = () => console.log("File upload complete");
      uploader.onprogress = (percent: number) =>
        (this.progressList[file.name] = percent);
      uploader.onabort = () => console.log("Aborting upload");
      uploader.onfail = (err: string) => console.log("Upload failed: ", err);

      if (url) {
        uploader.upload(url);
      }
    };
    reader.readAsDataURL(file);
  }

  deleteFile(upload: Upload) {
    upload.uploader.abort();
    this.uploads = [...this.uploads].filter(
      (u) => u.file.name !== upload.file.name
    );
  }
}
