// libs/vue-components/src/lib/page-load-indicator/page-load-indicator.vue
<template>
  <div v-if="visible" :class="`progress-container--${sizeType}`">
    <svg
      :class="[svgClass]"
      fill="none"
      viewBox="0 0 100 100"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle className="base-circle" cx="50" cy="50" r="45" />
      <circle
        :class="[circleType]"
        cx="50"
        cy="50"
        r="45"
        :style="`strokeDashoffset:${strokeDashoffset}`"
      />
    </svg>
    <span :class="`progress-message--${sizeType}`">{{ message }}</span>
  </div>
</template>

<script lang="typescript">
export default {
  name: 'goa-page-load-indicator-component',
  props: {
    /**
     * The type of indicator - "progress", "infinite".
     */
    type: {
      type: String,
      default: 'progress',
      required: false,
      validator: (value) => {
        return ['progress', 'infinite'].includes(value);
      },
    },
    /**
     * The message to display while loading.
     */
    message: {
      type: String,
      required: true,
    },
    /**
     * Sets the percentage value of the page loader while set to progress type, 0 - 100 percent.
     */
    value: {
      type: Number,
    },
    /**
     * Sets the page to locked and does not accept user input. When not set the component can be used as a child element without blocking user input.
     */
    pagelock: {
      type: Boolean,
      default: true,
    },
    /**
     * Sets the page loader visibility state.
     */
    visible: {
      type: Boolean,
      default: true,
    },
    /**
    * Sets the progress indicator display type size.
    */
    displayType: {
      type: String,
      default: 'large',
      required: false,
      validator: (value) => {
        return ['large', 'small'].includes(value);
      },
    },
  },
  data() {
    const circleType =
      this.type === 'progress'
        ? 'progress-circle'
        : 'progress-circle--infinite';
    /**
     * Set defaults
     */
    const progressMaxValue = 283;
    const svgClass = this.displayType === 'large' ? 'svg' : 'svg--small';
    const sizeType = this.displayType;

    let strokeDashoffset = 0;

    if (this.pagelock) {
      document.body.style.height = '100%';
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.removeProperty('height');
      document.body.style.removeProperty('overflow');
    }

    if (this.type === 'progress') {
      if (this.value === 0) {
        strokeDashoffset = progressMaxValue;
        return;
      }

      if (this.value >= 100) {
        return;
      }

      const value =
        progressMaxValue - Math.round((progressMaxValue * this.value) / 100);

      strokeDashoffset = value;
    }

    return {
      progressMaxValue,
      strokeDashoffset,
      circleType,
      svgClass,
      sizeType
    };
  },
};
</script>

<style lang="scss" scoped>
@import './page-load-indicator.scss';
</style>

// libs/angular-components/src/lib/page-load-indicator/page-load-indicator.component.ts
import { HostListener, OnDestroy } from '@angular/core';

import {
  Component,
  Input,
  OnChanges,
  OnInit,
  SimpleChanges,
} from '@angular/core';
import { __values } from 'tslib';

/**
 * A page load indicator component with Government of Alberta styling.
 * selector: goa-page-load-indicator
 */
@Component({
  selector: 'goa-page-load-indicator',
  templateUrl: './page-load-indicator.component.html',
  styleUrls: ['./page-load-indicator.component.scss'],
})
export class GoAPageLoadIndicatorComponent implements OnInit, OnChanges, OnDestroy {

  constructor() {
  }

  /**
   * Sets the page loader visibility state.
   */
  @Input() visible = false;

  /**
   * The type of page loader, deterministic and indeterministic.
   */
  @Input() type: 'progress' | 'infinite' = 'infinite';

  /**
  * The message to display while loading.
  */
  @Input() message = '';

  /**
   * Sets the percentage value of the page loader while set to progress type, 0 - 100 percent.
   */
  @Input() value = 0;

  /**
   * Sets the page to locked and does not accept user input. When not set the component
   * can be used as a child element without blocking user input.
   */
  @Input()
  pagelock = true;

  /**
   * Sets the progress indicator display type size.
   */
  @Input() displayType: 'large' | 'small' = 'large';

  /**
   * Set defaults
   */
  strokeDashoffsetDefault = 280;
  progressMaxValue = 283;
  strokeDashoffset = 0;

  ngOnInit(): void {
    if (this.type !== 'progress') {
      this.strokeDashoffset = this.strokeDashoffsetDefault;
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes.visible) {
      this.blockScrollingToggle(changes.visible.currentValue);
    }
    if (changes.value) {
      if (this.type === 'progress') {
        this.setProgress(changes.value.currentValue);
      }
    }
  }

  /**
   * Toggles the page scrolling based on page load indicator's visibility.
   * @param isBlock The flag to enable/disable page scroll.
   * @ignore
   */
  private blockScrollingToggle(isBlock: boolean): void {
    if (!isBlock || !this.pagelock) {
      document.body.style.removeProperty('height');
      document.body.style.removeProperty('overflow');
    } else {
      document.body.style.height = '100%';
      document.body.style.overflow = 'hidden';
    }
  }

  /**
   * Blocks the keyboard input when page load indicator is visible.
   * @ignore
   */
  @HostListener('document:keydown', ['$event'])
  disableKeyboardInputHandler(event: KeyboardEvent) {
    if (this.visible) {
      event.returnValue = false;
      event.preventDefault();
    }
  }

  ngOnDestroy(): void {
    this.blockScrollingToggle(false);
  }

  setProgress(progress: number): void {
    if (this.type !== 'progress') {
      return;
    };

    if (progress === 0) {
      this.strokeDashoffset = this.progressMaxValue;
      return;
    }

    if (progress >= 100) {
      return;
    }

    const value = this.progressMaxValue - Math.round(this.progressMaxValue * progress / 100);
    this.strokeDashoffset = value;
  }
}

<div *ngIf="visible" class="progress-container--{{ displayType }}">
  <svg
    [ngClass]="{
            'svg': displayType === 'large',
            'svg--small': displayType === 'small'
          }"
    fill="none"
    viewBox="0 0 100 100"
    xmlns="http://www.w3.org/2000/svg">
    <circle class="base-circle" cx="50" cy="50" r="45"/>
    <circle
      [ngClass]="{
        'progress-circle--infinite': type === 'infinite',
        'progress-circle': type === 'progress'
      }"
      cx="50"
      cy="50"
      r="45"
      [style.stroke-dashoffset]="strokeDashoffset"/>
  </svg>

  <span class="progress-message--{{ displayType }}">
    {{ message }}
  </span>
</div>
