// _templates/angular/src/app/circular-progress/circular-progress.component.ts
import { GoabButton, GoabCircularProgress } from "@abgov/angular-components";
import { Component, OnInit } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-circular-progress",
  templateUrl: "./circular-progress.component.html",
  imports: [
    GoabCircularProgress,
    GoabButton,
  ]
})
export class CircularProgressComponent implements OnInit {
  progress = 0;
  message = "Progress starting";

  fullScreenProgress = 0;
  fullScreenMessage = "Progress starting";

  fullscreenInfiniteVisible = false;
  showFullscreenInfiniteInterval: any;

  fullscreenProgressVisible = false;
  showFullscreenProgressInterval: any;

  constructor() { }

  ngOnInit() {
    setInterval(() => {
      if (this.progress >= 100) {
        this.progress = 0;
      } else {
        this.progress += 10;
      }
      this.message = "Progress at " + this.progress;

      if (this.fullScreenProgress >= 100) {
        this.fullScreenProgress = 0;
        this.fullscreenProgressVisible = false;
      } else {
        this.fullScreenProgress += 10;
      }
      this.fullScreenMessage = "Progress at " + this.fullScreenProgress;
    }, 1000);
  }

  showFullscreenInfinite() {
    this.fullscreenInfiniteVisible = true;

    this.showFullscreenInfiniteInterval = setInterval(() => {
      this.fullscreenInfiniteVisible = false;
      clearInterval(this.showFullscreenInfiniteInterval);
    }, 3000);
  }

  showFullscreenProgress() {
    this.fullscreenProgressVisible = true;
  }
}

<h1>Circular Progress</h1>

<h2>Sizes - Small</h2>
<goab-circular-progress variant="inline" size="small" [visible]="true">
</goab-circular-progress>

<h2>Sizes - Large</h2>
<goab-circular-progress variant="inline" size="large" [visible]="true">
</goab-circular-progress>

<h2>Sizes - Small with message</h2>
<goab-circular-progress
  variant="inline"
  size="small"
  message="Loading the small circular progress with message"
  [visible]="true"
>
</goab-circular-progress>

<h2>Sizes - Large with message</h2>
<goab-circular-progress
  variant="inline"
  size="large"
  message="Loading the large circular progress with message"
  [visible]="true"
>
</goab-circular-progress>

<h2>Inline infinite</h2>
<goab-circular-progress variant="inline" size="large" [visible]="true">
</goab-circular-progress>

<h2>Inline progress</h2>
<goab-circular-progress
  variant="inline"
  size="large"
  [progress]="progress"
  [message]="message"
  [visible]="true"
>
</goab-circular-progress>

<h2>Fullscreen infinite</h2>
<goab-button (onClick)="showFullscreenInfinite()"
  >Show Fullscreen infinite progress
</goab-button>
<goab-circular-progress
  variant="fullscreen"
  size="large"
  [visible]="fullscreenInfiniteVisible"
></goab-circular-progress>

<h2>Fullscreen progress</h2>
<goab-button (onClick)="showFullscreenProgress()">Show Fullscreen progress </goab-button>
<goab-circular-progress
  variant="fullscreen"
  [progress]="fullScreenProgress"
  [message]="fullScreenMessage"
  [visible]="fullscreenProgressVisible"
></goab-circular-progress>

// apps/prs/react/src/routes/docs/circular-progress/circular-progress.tsx
import { GoabCircularProgress } from "@abgov/react-components";

export function DocsCircularProgressRoute() {
  return (
    <div>
      <h2>Circular progress indicator</h2>

      <h3>Basic progress</h3>
      <GoabCircularProgress variant="inline" size="large" message="Loading message..." visible={true} />

      <h3>Sizes</h3>
      <GoabCircularProgress variant="inline" size="small" message="Loading message..." visible={true} />
      <GoabCircularProgress variant="inline" size="large" message="Loading message..." visible={true} />

      <h3>With progress value</h3>
      <GoabCircularProgress variant="inline" size="large" progress={75} message="75% complete" visible={true} />
    </div>
  );
}
