// apps/prs/react/src/app/routes.tsx/features/feat1813.tsx
import { useLayoutEffect, useMemo, useState } from "react";
import {
  GoabDatePicker,
  GoabBlock,
  GoabText,
  GoabPopover,
  GoabButton,
  GoabFormItem,
  GoabDropdown,
  GoabDropdownItem,
} from "@abgov/react-components";
import { GoabDropdownOnChangeDetail } from "@abgov/ui-components-common";
import { GoabDatePickerOnChangeDetail } from "@abgov/ui-components-common";

type DatePickerScenario = {
  id: string;
  label: string;
  width?: string;
  containerWidth?: string;
  type?: "calendar" | "input";
  description: string;
  emphasis?: string;
};

type ScenarioMeasurement = {
  hostWidth?: number;
  inputWidth?: number;
  widthAttr?: string | null;
};

export function Feat1813Route() {
  const [lastSelectedDate, setLastSelectedDate] = useState<string>("");
  const [lastSelectedDropdown, setLastSelectedDropdown] = useState<string>("");
  const [dropdownValue, setDropdownValue] = useState<string>("");
  const [measurements, setMeasurements] = useState<Record<string, ScenarioMeasurement>>(
    {},
  );

  const scenarios = useMemo<DatePickerScenario[]>(
    () => [
      {
        id: "default",
        label: "Default (no width provided)",
        description: "Falls back to the shared 16ch default like other inputs.",
      },
      {
        id: "ch-24",
        label: "Character width (24ch)",
        width: "24ch",
        description: "Confirms ch units make it through to the rendered input.",
      },
      {
        id: "px-360",
        label: "Fixed width (360px)",
        width: "360px",
        description: "Validates px widths while keeping the popover aligned.",
      },
      {
        id: "percent-80",
        label: "Relative width (80% of 560px container)",
        width: "80%",
        containerWidth: "560px",
        description: "Ensures percentage widths respect their parent container.",
      },
      {
        id: "clamp-small",
        label: "Requested width below minimum (8ch in a 120px slot)",
        width: "8ch",
        containerWidth: "120px",
        description: "Should never shrink below the minimum readable width (≈16ch).",
        emphasis: "Must clamp ≥ 16ch so the date stays legible.",
      },
      {
        id: "input-segments",
        label: "Type “input” with explicit width (340px)",
        width: "340px",
        type: "input",
        description:
          "Segmented month/day/year inputs should line up within the requested width.",
      },
    ],
    [],
  );

  const onDateChange = (details: GoabDatePickerOnChangeDetail) => {
    console.log("Date changed:", details);
    setLastSelectedDate(
      details.value ? new Date(details.value).toLocaleDateString() : "None",
    );
  };

  const dropdownChange = (details: GoabDropdownOnChangeDetail) => {
    if (!details.value) {
      console.log("Value empty");
      setDropdownValue(lastSelectedDropdown);
    } else {
      console.log("Value changed: ", details.value);
      setLastSelectedDropdown(details.value);
      setDropdownValue(details.value);
    }
  };

  useLayoutEffect(() => {
    const readMeasurements = (): Record<string, ScenarioMeasurement> => {
      const result: Record<string, ScenarioMeasurement> = {};

      scenarios.forEach((scenario) => {
        const wrapper = document.querySelector<HTMLElement>(
          `[data-scenario="${scenario.id}"]`,
        );
        const host = wrapper?.querySelector<HTMLElement>("goa-date-picker") ?? undefined;
        const hostWidth = host?.getBoundingClientRect().width;

        const popover = host?.shadowRoot?.querySelector<HTMLElement>("goa-popover");
        const goaInput = popover?.querySelector<HTMLElement>("goa-input");
        const widthAttr = goaInput?.getAttribute("width") ?? null;
        const inputElement =
          goaInput?.shadowRoot?.querySelector<HTMLElement>("input") ??
          goaInput ??
          undefined;
        const inputWidth = inputElement?.getBoundingClientRect().width;

        if (scenario.type === "input" && !goaInput) {
          const formItem = host?.shadowRoot?.querySelector<HTMLElement>("goa-form-item");
          result[scenario.id] = {
            hostWidth: hostWidth ? Math.round(hostWidth) : undefined,
            inputWidth: formItem
              ? Math.round(formItem.getBoundingClientRect().width)
              : undefined,
            widthAttr,
          };
          return;
        }

        result[scenario.id] = {
          hostWidth: hostWidth ? Math.round(hostWidth) : undefined,
          inputWidth: inputWidth ? Math.round(inputWidth) : undefined,
          widthAttr,
        };
      });

      return result;
    };

    const equalMeasurements = (
      prev: Record<string, ScenarioMeasurement>,
      next: Record<string, ScenarioMeasurement>,
    ) => {
      const prevKeys = Object.keys(prev);
      const nextKeys = Object.keys(next);
      if (prevKeys.length !== nextKeys.length) {
        return false;
      }
      return prevKeys.every((key) => {
        const prevValue = prev[key];
        const nextValue = next[key];
        if (!prevValue && !nextValue) {
          return true;
        }
        if (!prevValue || !nextValue) {
          return false;
        }
        return (
          prevValue.hostWidth === nextValue.hostWidth &&
          prevValue.inputWidth === nextValue.inputWidth &&
          prevValue.widthAttr === nextValue.widthAttr
        );
      });
    };

    const update = () => {
      requestAnimationFrame(() => {
        setMeasurements((prev) => {
          const next = readMeasurements();
          if (equalMeasurements(prev, next)) {
            return prev;
          }
          return next;
        });
      });
    };

    update();
    window.addEventListener("resize", update);
    return () => {
      window.removeEventListener("resize", update);
    };
  }, [scenarios]);

  return (
    <main>
      <GoabText tag="h1" size="heading-l">
        Date Picker width property
      </GoabText>
      <GoabText tag="p" size="body-m">
        Exercises fixed, relative, and constrained widths for the calendar view and
        segmented input flavour. Measurements capture what the DOM reports so regressions
        are easy to spot.
      </GoabText>

      <GoabBlock gap="2xl" direction="column">
        <GoabBlock direction="column" gap="l">
          {scenarios.map((scenario) => (
            <div
              key={scenario.id}
              data-scenario={scenario.id}
              style={{
                width: scenario.containerWidth,
              }}
            >
              <GoabBlock direction="column" gap="s">
                <GoabText tag="h3" size="heading-s">
                  {scenario.label}
                </GoabText>
                <GoabText tag="p" size="body-s">
                  {scenario.description}
                </GoabText>
                {scenario.emphasis ? (
                  <GoabText tag="p" size="body-s">
                    {scenario.emphasis}
                  </GoabText>
                ) : null}

                <GoabFormItem label={scenario.label}>
                  <GoabDatePicker
                    name={scenario.id}
                    width={scenario.width}
                    type={scenario.type}
                    onChange={onDateChange}
                  />
                </GoabFormItem>

                <GoabText tag="p" size="body-s">
                  Host width:
                  {measurements[scenario.id]?.hostWidth !== undefined
                    ? ` ${measurements[scenario.id]?.hostWidth}px`
                    : " –"}
                  {" · "}Input width:
                  {measurements[scenario.id]?.inputWidth !== undefined
                    ? ` ${measurements[scenario.id]?.inputWidth}px`
                    : " –"}
                </GoabText>
                <GoabText tag="p" size="body-s">
                  Input width attribute:
                  {measurements[scenario.id]?.widthAttr !== undefined
                    ? ` ${measurements[scenario.id]?.widthAttr || "none"}`
                    : " –"}
                </GoabText>
              </GoabBlock>
            </div>
          ))}
        </GoabBlock>

        <section>
          <GoabText tag="h4">Popover</GoabText>
          <GoabPopover
            target={
              <GoabButton type="secondary" size="compact">
                Popover Test
              </GoabButton>
            }
          >
            <p>This is a popover</p>
            <p>It can be used for a number of different contexts</p>
          </GoabPopover>
        </section>

        <section>
          <GoabFormItem label="Dropdown">
            <GoabDropdown
              name="item"
              value={dropdownValue}
              onChange={(details) => dropdownChange(details)}
              width="300px"
              filterable={true}
            >
              <GoabDropdownItem value="red" label="Red" />
              <GoabDropdownItem value="green" label="Green" />
              <GoabDropdownItem value="blue" label="Blue" />
              <GoabDropdownItem value="black" label="Black" />
              <GoabDropdownItem value="white" label="White" />
              <GoabDropdownItem value="yellow" label="Yellow" />
              <GoabDropdownItem value="magenta" label="Magenta" />
              <GoabDropdownItem value="purple" label="Purple" />
            </GoabDropdown>
          </GoabFormItem>
        </section>

        <section>
          <h2>Test Results</h2>
          <GoabText tag="p">
            Last selected date: {lastSelectedDate || "None selected"}
          </GoabText>
          <GoabText tag="p">
            Last selected dropdown: {lastSelectedDropdown || "None selected"}
          </GoabText>
        </section>
      </GoabBlock>
    </main>
  );
}

// apps/prs/angular/src/app/features/feat1813/feat1813.component.ts
import {
  AfterViewInit,
  ChangeDetectorRef,
  Component,
  OnDestroy,
  OnInit,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  GoabDatePicker,
  GoabDatePickerOnChangeDetail,
  GoabPopover,
  GoabButton,
  GoabFormItem,
  GoabDropdown,
  GoabDropdownItem,
  GoabText,
  GoabBlock,
} from "@abgov/angular-components";
import { FormControl, FormGroup, ReactiveFormsModule, FormsModule } from "@angular/forms";

interface DatePickerScenario {
  id: string;
  label: string;
  width?: string;
  containerWidth?: string;
  type?: "calendar" | "input";
  description: string;
  emphasis?: string;
}

interface ScenarioMeasurement {
  hostWidth?: number;
  inputWidth?: number;
  widthAttr?: string | null;
}

@Component({
  standalone: true,
  selector: "abgov-feat1813",
  templateUrl: "./feat1813.component.html",
  styleUrls: ["./feat1813.component.css"],
  imports: [
    CommonModule,
    GoabDatePicker,
    GoabPopover,
    GoabButton,
    GoabFormItem,
    GoabDropdown,
    GoabDropdownItem,
    GoabText,
    ReactiveFormsModule,
    FormsModule,
    GoabBlock,
  ],
})
export class Feat1813Component implements OnInit, AfterViewInit, OnDestroy {
  lastSelectedDate = "";
  lastSelectedDropdown: string | null = "red";
  dropdownGroup = new FormGroup({
    dropdownCtrl: new FormControl("red"),
  });
  measurements: Record<string, ScenarioMeasurement> = {};

  readonly scenarios: DatePickerScenario[] = [
    {
      id: "default",
      label: "Default (no width provided)",
      description: "Should fall back to the shared default 16ch width like GoA inputs.",
    },
    {
      id: "ch-24",
      label: "Character width (24ch)",
      width: "24ch",
      description:
        "Ensures ch units are preserved and forwarded to the underlying GoA input.",
    },
    {
      id: "px-360",
      label: "Fixed width (360px)",
      width: "360px",
      description: "Checks pixel widths and ensures popover content fits target.",
    },
    {
      id: "percent-80",
      label: "Relative width (80% inside 560px container)",
      width: "80%",
      containerWidth: "560px",
      description: "Validates percentage widths respect the parent container.",
    },
    {
      id: "clamp-small",
      label: "Requested width below minimum (8ch in a 120px slot)",
      width: "8ch",
      containerWidth: "120px",
      description:
        "Should not shrink below the minimum readable width; expect ≥ 16ch (~160px).",
      emphasis: "Must stay readable",
    },
    {
      id: "input-segments",
      label: "Type “input” with explicit width (340px)",
      width: "340px",
      type: "input",
      description:
        "Ensures segmented date input respects width and keeps month/day/year layout aligned.",
    },
  ];

  private resizeHandler = () => this.scheduleMeasurement();

  constructor(private readonly cdr: ChangeDetectorRef) {}

  onDateChange(details: GoabDatePickerOnChangeDetail) {
    console.log("Date changed:", details);
    this.lastSelectedDate = details.value
      ? new Date(details.value).toLocaleDateString()
      : "None";
  }

  ngOnInit() {
    this.dropdownGroup.controls["dropdownCtrl"].valueChanges.subscribe((value) => {
      if (!value) {
        console.log("Value empty");
        this.dropdownGroup.controls["dropdownCtrl"].setValue(this.lastSelectedDropdown);
      } else {
        console.log("Value changed: ", value);
        this.lastSelectedDropdown = value;
      }
    });
  }

  ngAfterViewInit(): void {
    this.scheduleMeasurement();
    window.addEventListener("resize", this.resizeHandler, { passive: true });
  }

  ngOnDestroy(): void {
    window.removeEventListener("resize", this.resizeHandler);
  }

  trackByScenarioId(_: number, scenario: DatePickerScenario): string {
    return scenario.id;
  }

  private scheduleMeasurement(): void {
    requestAnimationFrame(() => {
      setTimeout(() => {
        this.measurements = this.collectMeasurements();
        this.cdr.markForCheck();
      }, 0);
    });
  }

  private collectMeasurements(): Record<string, ScenarioMeasurement> {
    const readings: Record<string, ScenarioMeasurement> = {};

    for (const scenario of this.scenarios) {
      const wrapper = document.querySelector<HTMLElement>(
        `[data-scenario="${scenario.id}"]`,
      );

      const host = wrapper?.querySelector<HTMLElement>("goa-date-picker") ?? undefined;

      const hostWidth = host?.getBoundingClientRect().width;

      const popover = host?.shadowRoot?.querySelector<HTMLElement>("goa-popover");
      const goaInput = popover?.querySelector<HTMLElement>("goa-input");
      const widthAttr = goaInput?.getAttribute("width") ?? null;
      const inputElement =
        goaInput?.shadowRoot?.querySelector<HTMLElement>("input") ?? goaInput;
      const inputWidth = inputElement?.getBoundingClientRect().width;

      if (scenario.type === "input" && !goaInput) {
        const formItem = host?.shadowRoot?.querySelector<HTMLElement>("goa-form-item");
        readings[scenario.id] = {
          hostWidth: hostWidth ? Math.round(hostWidth) : undefined,
          inputWidth: formItem
            ? Math.round(formItem.getBoundingClientRect().width)
            : undefined,
          widthAttr,
        };
        continue;
      }

      readings[scenario.id] = {
        hostWidth: hostWidth ? Math.round(hostWidth) : undefined,
        inputWidth: inputWidth ? Math.round(inputWidth) : undefined,
        widthAttr,
      };
    }

    return readings;
  }
}
