// apps/prs/react/src/routes/bugs/bug3625.tsx
import {
  GoabAccordion,
  GoabBadge,
  GoabBlock,
  GoabButton,
  GoabDropdown,
  GoabDropdownItem,
  GoabFormItem,
  GoabText,
} from "@abgov/react-components";
import { useState } from "react";

export function Bug3625Route() {
  const [controlledOpen, setControlledOpen] = useState(false);

  return (
    <div>
      <h1>Bug 3625: Accordion Refinement</h1>
      <GoabAccordion heading="Small heading" headingSize="small">
        Content with small heading.
      </GoabAccordion>
      <GoabAccordion heading="Medium heading" headingSize="medium">
        Content with medium heading.
      </GoabAccordion>
      <GoabAccordion
        heading="Small heading"
        secondaryText="Secondary Text"
        headingSize="small"
      >
        Content with small heading.
      </GoabAccordion>
      <GoabAccordion
        heading="Medium heading"
        secondaryText="Secondary Text"
        headingSize="medium"
      >
        Content with medium heading.
      </GoabAccordion>
      <div style={{ display: "flex", gap: "1rem" }}>
        <div style={{ width: "50%" }}>
          <GoabAccordion
            heading="Small heading"
            headingContent={<GoabBadge type="important" content="Updated" />}
            headingSize="small"
          >
            Content with small heading.
          </GoabAccordion>
        </div>
        <div style={{ width: "50%" }}>
          <GoabAccordion
            heading="Medium heading"
            headingContent={<GoabBadge type="important" content="Updated" />}
            headingSize="medium"
          >
            Content with medium heading.
          </GoabAccordion>
        </div>
      </div>
      <GoabAccordion heading="Small Controls" headingSize="small" iconPosition="right">
        <GoabBlock direction="column" gap="s">
          <GoabText tag="p">Content with small heading.</GoabText>
          <GoabBlock direction="column" gap="s">
            <GoabText tag="p">Nested block content.</GoabText>
            <GoabFormItem label="Colour Dropdown">
              <GoabDropdown width="500px">
                <GoabDropdownItem value="red" label="Red" />
                <GoabDropdownItem value="green" label="Green" />
                <GoabDropdownItem value="blue" label="Blue" />
              </GoabDropdown>
            </GoabFormItem>
          </GoabBlock>
        </GoabBlock>
      </GoabAccordion>
      <GoabAccordion heading="Medium Controls" headingSize="medium" iconPosition="right">
        <GoabBlock direction="column" gap="s">
          <GoabText tag="p">Content with medium heading.</GoabText>
          <GoabFormItem label="Colour Dropdown" maxWidth="100%">
            <GoabDropdown width="500px">
              <GoabDropdownItem value="red" label="Red" />
              <GoabDropdownItem value="green" label="Green" />
              <GoabDropdownItem value="blue" label="Blue" />
            </GoabDropdown>
          </GoabFormItem>
        </GoabBlock>
      </GoabAccordion>
      <GoabAccordion
        heading="Verification checklist"
        secondaryText="From Bug 2873 - open on start"
        open={true}
      >
        <GoabBlock direction="column" gap="s">
          <GoabText tag="p" maxWidth="400px">
            Expand and collapse this accordion to confirm that layout changes do not jump
            the scroll position unexpectedly.
          </GoabText>
          <GoabText tag="p" maxWidth="400px">
            Keep the content long enough to require scrolling before and after the
            accordion section.
          </GoabText>
        </GoabBlock>
      </GoabAccordion>
      <GoabAccordion
        heading="Clickable Element in Heading"
        headingSize="medium"
        headingContent={
          <GoabButton
            onClick={() => console.log("Button in heading clicked")}
            size="compact"
          >
            This is a button
          </GoabButton>
        }
        onChange={() => console.log("Accordion toggled")}
      >
        <p>
          In the JavaScript console the text "Accordion toggled" will not appear if the
          button is clicked, only if other parts of the heading are clicked.
        </p>
      </GoabAccordion>

      <h2>Controlled Accordion (toggle via button)</h2>
      <GoabText tag="p">
        Parent state: <strong>{controlledOpen ? "open" : "closed"}</strong>
      </GoabText>
      <GoabBlock direction="row" gap="s" mb="m">
        <GoabButton onClick={() => setControlledOpen((v) => !v)}>
          {controlledOpen ? "Collapse" : "Expand"}
        </GoabButton>
        <GoabButton type="secondary" onClick={() => setControlledOpen(false)}>
          Force close
        </GoabButton>
        <GoabButton type="secondary" onClick={() => setControlledOpen(true)}>
          Force open
        </GoabButton>
      </GoabBlock>
      <GoabAccordion
        heading="Controlled Accordion"
        secondaryText="open prop is bound to parent state"
        open={controlledOpen}
        onChange={(open) => {
          console.log("Accordion onChange → open:", open);
          setControlledOpen(open);
        }}
      >
        <GoabText tag="p">
          Test the controlled pattern: click the accordion summary, click the buttons
          above, and watch whether the parent state stays in sync with the visible UI
          state.
        </GoabText>
      </GoabAccordion>
    </div>
  );
}

// apps/prs/angular/src/routes/bugs/3625/bug3625.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  GoabAccordion,
  GoabBadge,
  GoabBlock,
  GoabButton,
  GoabDropdown,
  GoabDropdownItem,
  GoabFormItem,
  GoabText,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3625",
  templateUrl: "./bug3625.component.html",
  imports: [
    CommonModule,
    GoabAccordion,
    GoabBadge,
    GoabBlock,
    GoabButton,
    GoabDropdown,
    GoabDropdownItem,
    GoabFormItem,
    GoabText,
  ],
})
export class Bug3625Component {
  controlledOpen = false;

  onAccordionChange() {
    console.log("Accordion toggled");
  }

  onButtonClicked() {
    console.log("Button in heading clicked");
  }

  toggleControlled() {
    this.controlledOpen = !this.controlledOpen;
  }

  onControlledChange(open: boolean) {
    this.controlledOpen = open;
  }
}

<div>
  <h1>Bug 3625: Accordion Refinement</h1>
  <goab-accordion heading="Small heading" headingSize="small">
    Content with small heading.
  </goab-accordion>
  <goab-accordion heading="Medium heading" headingSize="medium">
    Content with medium heading.
  </goab-accordion>
  <goab-accordion
    heading="Small heading"
    secondaryText="Secondary Text"
    headingSize="small"
  >
    Content with small heading.
  </goab-accordion>
  <goab-accordion
    heading="Medium heading"
    secondaryText="Secondary Text"
    headingSize="medium"
  >
    Content with medium heading.
  </goab-accordion>
  <div style="display: flex; gap: 1rem">
    <div style="width: 50%">
      <goab-accordion
        heading="Small heading"
        [headingContent]="importantBadge"
        headingSize="small"
      >
        <ng-template #importantBadge>
          <goab-badge type="important" content="Updated"></goab-badge>
        </ng-template>
        Content with small heading.
      </goab-accordion>
    </div>
    <div style="width: 50%">
      <goab-accordion
        heading="Medium heading"
        [headingContent]="importantBadge"
        headingSize="medium"
      >
        <ng-template #importantBadge>
          <goab-badge type="important" content="Updated"></goab-badge>
        </ng-template>
        Content with medium heading.
      </goab-accordion>
    </div>
  </div>
  <goab-accordion heading="Small Controls" headingSize="small" iconPosition="right">
    <goab-block direction="column" gap="s">
      <goab-text tag="p">Content with small heading.</goab-text>
      <goab-block direction="column" gap="s">
        <goab-text tag="p">Nested block content.</goab-text>
        <goab-form-item label="Colour Dropdown">
          <goab-dropdown width="500px">
            <goab-dropdown-item value="red" label="Red" />
            <goab-dropdown-item value="green" label="Green" />
            <goab-dropdown-item value="blue" label="Blue" />
          </goab-dropdown>
        </goab-form-item>
      </goab-block>
    </goab-block>
  </goab-accordion>
  <goab-accordion heading="Medium Controls" headingSize="medium" iconPosition="right">
    <goab-block direction="column" gap="s">
      <goab-text tag="p">Content with medium heading.</goab-text>
      <goab-form-item label="Colour Dropdown" maxWidth="100%">
        <goab-dropdown width="500px">
          <goab-dropdown-item value="red" label="Red" />
          <goab-dropdown-item value="green" label="Green" />
          <goab-dropdown-item value="blue" label="Blue" />
        </goab-dropdown>
      </goab-form-item>
    </goab-block>
  </goab-accordion>

  <goab-accordion
    heading="Verification checklist"
    secondaryText="From Bug 2873 - open on start"
    [open]="true"
  >
    <goab-block direction="column" gap="s">
      <goab-text tag="p" maxWidth="400px">
        Expand and collapse this accordion to confirm that layout changes do not jump the
        scroll position unexpectedly.
      </goab-text>
      <goab-text tag="p" maxWidth="400px">
        Keep the content long enough to require scrolling before and after the accordion
        section.
      </goab-text>
    </goab-block>
  </goab-accordion>

  <goab-accordion
    heading="Clickable Element in Heading"
    headingSize="medium"
    [headingContent]="buttonTemplate"
    (onChange)="onAccordionChange()"
  >
    <ng-template #buttonTemplate>
      <goab-button (click)="onButtonClicked()" size="compact">
        This is a button
      </goab-button>
    </ng-template>
    <p>
      In the JavaScript console the text "Accordion toggled" will not appear if the button
      is clicked, only if other parts of the heading are clicked.
    </p>
  </goab-accordion>

  <h2>Controlled Accordion (toggle via button)</h2>
  <goab-text tag="p">
    Parent state: <strong>{{ controlledOpen ? "open" : "closed" }}</strong>
  </goab-text>
  <goab-block direction="row" gap="s" mb="m">
    <goab-button (onClick)="toggleControlled()">
      {{ controlledOpen ? "Collapse" : "Expand" }}
    </goab-button>
    <goab-button type="secondary" (onClick)="controlledOpen = false">
      Force close
    </goab-button>
    <goab-button type="secondary" (onClick)="controlledOpen = true">
      Force open
    </goab-button>
  </goab-block>
  <goab-accordion
    heading="Controlled Accordion"
    secondaryText="open prop is bound to parent state"
    [open]="controlledOpen"
    (onChange)="onControlledChange($event)"
  >
    <goab-text tag="p">
      Test the controlled pattern: click the accordion summary, click the buttons above,
      and watch whether the parent state stays in sync with the visible UI state.
    </goab-text>
  </goab-accordion>
</div>
