// apps/prs/angular/src/routes/features/feat3370/feat3370.component.ts
import { Component } from "@angular/core";
import {
  GoabButton,
  GoabButtonGroup,
  GoabCalendar,
  GoabDatePicker,
} from "@abgov/angular-components";
import {
  GoabCalendarOnChangeDetail,
  GoabDatePickerOnChangeDetail,
} from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "abgov-feat3370",
  templateUrl: "./feat3370.component.html",
  imports: [GoabButton, GoabButtonGroup, GoabCalendar, GoabDatePicker],
})
export class Feat3370Component {
  calendarValue: Date | string = "";
  datePickerValue = "";

  handleOnChange(details: GoabCalendarOnChangeDetail): void {
    this.calendarValue = details.value;
  }

  handleDatePickerChange(details: GoabDatePickerOnChangeDetail): void {
    this.datePickerValue = details.valueStr;
  }

  clearCalendarValue(): void {
    this.calendarValue = "";
  }

  clearDatePickerValue(): void {
    this.datePickerValue = "";
  }

  toCalendarDateValue(): void {
    if (this.datePickerValue) {
      this.calendarValue = new Date(`${this.datePickerValue}T00:00:00`);
    }
  }

  toCalendarStringValue(): void {
    if (this.datePickerValue) {
      this.calendarValue = this.datePickerValue;
    }
  }
}

<div>
  <h1>
    <a
      href="https://github.com/GovAlta/ui-components/issues/3370"
      target="_blank"
      rel="noreferrer"
    >
      Feature 3370
    </a>
  </h1>
  <div>
    <h2>Clear calendar day selection when year and/or month changes</h2>
    <goab-calendar (onChange)="handleOnChange($event)" [value]="calendarValue" />
    <p>Selected Date: {{ calendarValue || "none" }}</p>
    <goab-button (onClick)="clearCalendarValue()">Clear Selection</goab-button>
  </div>
  <div>
    <goab-date-picker
      (onChange)="handleDatePickerChange($event)"
      [value]="datePickerValue"
    />
    <p>Selected Date: {{ datePickerValue || "none" }}</p>
    <goab-button-group>
      <goab-button (onClick)="clearDatePickerValue()">Clear Selection</goab-button>
      <goab-button (onClick)="toCalendarDateValue()">To Calendar as Date</goab-button>
      <goab-button (onClick)="toCalendarStringValue()">To Calendar as String</goab-button>
    </goab-button-group>
  </div>
</div>

// apps/prs/react/src/routes/features/feat3370.tsx
import { GoabButton, GoabCalendar, GoabDatePicker } from "@abgov/react-components";
import {
  GoabCalendarOnChangeDetail,
  GoabDatePickerOnChangeDetail,
} from "@abgov/ui-components-common";
import React, { useState } from "react";

export function Feat3370Route() {
  const [calendarValue, setCalendarValue] = useState("");
  const [datePickerValue, setDatePickerValue] = useState("");

  function handleOnChange(details: GoabCalendarOnChangeDetail) {
    setCalendarValue(details.value);
  }

  function handleDatePickerChange(details: GoabDatePickerOnChangeDetail) {
    setDatePickerValue(details.valueStr);
  }

  return (
    <div>
      <h1>
        <a
          href="https://github.com/GovAlta/ui-components/issues/3370"
          target="_blank"
          rel="noreferrer"
        >
          Feature 3370
        </a>
      </h1>
      <div>
        <h2>Clear calendar day selection when year and/or month changes</h2>
        <GoabCalendar onChange={handleOnChange} value={calendarValue} />
        <p>Selected Date: {calendarValue || "none"}</p>
        <GoabButton onClick={() => setCalendarValue("")}>Clear Selection</GoabButton>
      </div>
      <div>
        <GoabDatePicker onChange={handleDatePickerChange} value={datePickerValue} />
        <p>Selected Date: {datePickerValue || "none"}</p>
        <GoabButton onClick={() => setDatePickerValue("")}>Clear Selection</GoabButton>
      </div>
    </div>
  );
}
