// apps/prs/angular/src/routes/features/feat3544/feat3544.component.ts
import { Component } from "@angular/core";
import {
  GoabContainer,
  GoabText,
  GoabWorkSideMenu,
  GoabWorkSideMenuGroup,
  GoabWorkSideMenuItem,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-feat3544",
  templateUrl: "./feat3544.component.html",
  imports: [
    GoabContainer,
    GoabText,
    GoabWorkSideMenu,
    GoabWorkSideMenuGroup,
    GoabWorkSideMenuItem,
  ],
})
export class Feat3544Component {}

<div style="display: flex; flex-direction: column; gap: var(--goa-spacing-l)">
  <goab-text tag="h1">Feature 3544: Optional Side Menu Icons</goab-text>
  <goab-text>
    Both menus below use the same structure in primary content: one item and one group.
    The left menu includes icons, and the right menu does not.
  </goab-text>

  <div
    style="
      display: grid;
      gap: var(--goa-spacing-l);
      grid-template-columns: repeat(auto-fit, minmax(340px, 1fr));
    "
  >
    <goab-container>
      <goab-text tag="h2">With icons</goab-text>
      <div style="height: 380px; overflow: hidden">
        <goabx-work-side-menu
          heading="Test Menu"
          url="/"
          [open]="true"
          [primaryContent]="withIconsTemplate"
        ></goabx-work-side-menu>
      </div>
    </goab-container>

    <goab-container>
      <goab-text tag="h2">Without icons</goab-text>
      <div style="height: 380px; overflow: hidden">
        <goabx-work-side-menu
          heading="Test Menu"
          url="/"
          [open]="true"
          [primaryContent]="withoutIconsTemplate"
        ></goabx-work-side-menu>
      </div>
    </goab-container>
  </div>
</div>

<ng-template #withIconsTemplate>
  <goabx-work-side-menu-item
    label="Standalone item"
    url="/features/3544"
    icon="home"
  ></goabx-work-side-menu-item>
  <goabx-work-side-menu-group heading="Grouped items" icon="folder">
    <goabx-work-side-menu-item
      label="Group child"
      url="/features/3544"
      icon="document"
    ></goabx-work-side-menu-item>
  </goabx-work-side-menu-group>
</ng-template>

<ng-template #withoutIconsTemplate>
  <goabx-work-side-menu-item
    label="Standalone item"
    url="/features/3544"
  ></goabx-work-side-menu-item>
  <goabx-work-side-menu-group heading="Grouped items">
    <goabx-work-side-menu-item
      label="Group child"
      url="/features/3544"
    ></goabx-work-side-menu-item>
  </goabx-work-side-menu-group>
</ng-template>

// apps/prs/react/src/routes/features/feat3544.tsx
import {
  GoabContainer,
  GoabText,
  GoabWorkSideMenu,
  GoabWorkSideMenuGroup,
  GoabWorkSideMenuItem,
} from "@abgov/react-components";

export function Feat3544Route() {
  return (
    <div
      style={{ display: "flex", flexDirection: "column", gap: "var(--goa-spacing-l)" }}
    >
      <GoabText tag="h1">Feature 3544: Optional Side Menu Icons</GoabText>
      <GoabText>
        Both menus below use the same structure in primary content: one item and one
        group. The left menu includes icons, and the right menu does not.
      </GoabText>

      <div
        style={{
          display: "grid",
          gap: "var(--goa-spacing-l)",
          gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
        }}
      >
        <GoabContainer>
          <GoabText tag="h2">With icons</GoabText>
          <div style={{ height: "380px", overflow: "hidden" }}>
            <GoabWorkSideMenu
              heading="Test Menu"
              url="/"
              open={true}
              primaryContent={
                <>
                  <GoabWorkSideMenuItem
                    label="Standalone item"
                    url="/features/3544"
                    icon="home"
                  />
                  <GoabWorkSideMenuGroup heading="Grouped items" icon="folder">
                    <GoabWorkSideMenuItem
                      label="Group child"
                      url="/features/3544"
                      icon="document"
                    />
                  </GoabWorkSideMenuGroup>
                </>
              }
            />
          </div>
        </GoabContainer>

        <GoabContainer>
          <GoabText tag="h2">Without icons</GoabText>
          <div style={{ height: "380px", overflow: "hidden" }}>
            <GoabWorkSideMenu
              heading="Test Menu"
              url="/"
              open={true}
              primaryContent={
                <>
                  <GoabWorkSideMenuItem label="Standalone item" url="/features/3544" />
                  <GoabWorkSideMenuGroup heading="Grouped items">
                    <GoabWorkSideMenuItem label="Group child" url="/features/3544" />
                  </GoabWorkSideMenuGroup>
                </>
              }
            />
          </div>
        </GoabContainer>

        <GoabContainer>
          <GoabText tag="h2">Mixed: back icon + no icons</GoabText>
          <div style={{ height: "380px", overflow: "hidden" }}>
            <GoabWorkSideMenu
              heading="Test Menu"
              url="/"
              open={true}
              primaryContent={
                <>
                  <GoabWorkSideMenuItem label="All" url="/features/3544" icon="arrow-back" />
                  <GoabWorkSideMenuItem label="All Components" url="/features/3544" />
                  <GoabWorkSideMenuGroup heading="Content layout">
                    <GoabWorkSideMenuItem label="Container" url="/features/3544" />
                    <GoabWorkSideMenuItem label="Divider" url="/features/3544" />
                    <GoabWorkSideMenuItem label="Grid" url="/features/3544" />
                  </GoabWorkSideMenuGroup>
                  <GoabWorkSideMenuGroup heading="Inputs and actions">
                    <GoabWorkSideMenuItem label="Button" url="/features/3544" />
                    <GoabWorkSideMenuItem label="Input" url="/features/3544" />
                  </GoabWorkSideMenuGroup>
                </>
              }
            />
          </div>
        </GoabContainer>
      </div>
    </div>
  );
}
