// libs/angular-components/src/lib/components/app-header/app-header.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  Output,
  EventEmitter,
  numberAttribute,
  OnInit,
  ChangeDetectorRef,
  inject,
  TemplateRef,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

@Component({
  standalone: true,
  selector: "goab-app-header",
  imports: [NgTemplateOutlet],
  template: `@if (isReady) {
    <goa-app-header
      [attr.url]="url"
      [attr.heading]="heading"
      [attr.secondarytext]="secondaryText"
      [attr.maxcontentwidth]="maxContentWidth"
      [attr.fullmenubreakpoint]="fullMenuBreakpoint"
      [attr.testid]="testId"
      [attr.hasmenuclickhandler]="onMenuClick.observed ? 'true' : 'false'"
      [attr.version]="version"
      (_menuClick)="_onMenuClick()"
    >
      @if (this.banner) {
        <div slot="banner">
          <ng-container [ngTemplateOutlet]="banner"></ng-container>
        </div>
      }
      @if (this.phase) {
        <div slot="phase">
          <ng-container [ngTemplateOutlet]="phase"></ng-container>
        </div>
      }
      @if (this.navigation) {
        <div slot="navigation">
          <ng-container [ngTemplateOutlet]="navigation"></ng-container>
        </div>
      }
      @if (this.utilities) {
        <div slot="utilities">
          <ng-container [ngTemplateOutlet]="utilities"></ng-container>
        </div>
      }
      <ng-content />
    </goa-app-header>
  }`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
/** Provide structure to help users find their way around the service. */
export class GoabAppHeader implements OnInit {
  private cdr = inject(ChangeDetectorRef);

  /** Sets the URL to link from the alberta.ca logo. A full url is required. */
  @Input() url?: string;
  /** Sets the service name to display in the app header. */
  @Input() heading?: string;
  /** Secondary text displayed under the service name. */
  @Input() secondaryText?: string;
  /** Maximum width of the content area. */
  @Input() maxContentWidth?: string;
  /** Sets the breakpoint in px for the full menu to display. */
  @Input({ transform: numberAttribute }) fullMenuBreakpoint?: number;
  /** Sets a data-testid attribute for automated testing. */
  @Input() testId?: string;
  /** Banner content displayed above the header. */
  @Input() banner?: TemplateRef<any>;
  /** Phase badge content displayed beside the service name. */
  @Input() phase?: TemplateRef<any>;
  /** Links and app header menus appear in the navigation bar below the header. Use plain links for single items and app header menu for grouped items with a dropdown. */
  @Input() navigation?: TemplateRef<any>;
  /** Actions like user account menus appear on the right side of the header. Use menu button for dropdowns with actions. */
  @Input() utilities?: TemplateRef<any>;

  isReady = false;
  version = "2";

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }

  /** Emits when the menu button is clicked. Used for custom menu handling. */
  @Output() onMenuClick = new EventEmitter();

  _onMenuClick() {
    this.onMenuClick.emit();
  }
}

// libs/vue-components/src/lib/app-header/app-header.vue
<script setup lang="ts">
import { computed, useSlots } from "vue";
import { useWcProps } from "../common/useWcProps";

interface Slots {
  default?: () => unknown;
  /** Content rendered in the "banner" named slot. */
  banner?: () => unknown;
  /** Content rendered in the "navigation" named slot. */
  navigation?: () => unknown;
  /** Content rendered in the "phase" named slot. */
  phase?: () => unknown;
  /** Content rendered in the "utilities" named slot. */
  utilities?: () => unknown;
}

interface Props {
  /** Set the service name to display in the app header. */
  heading?: string;
  /** V2 only: Secondary text displayed under the service name. */
  secondaryText?: string;
  /** Set the URL to link from the alberta.ca logo. A full url is required. */
  url?: string;
  /** Maximum width of the content area. */
  maxContentWidth?: string;
  /** Sets the breakpoint in px for the full menu to display.  @default TABLET_BP */
  fullMenuBreakpoint?: number;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Callback fired when the menu button is clicked. When provided, clicking the menu button dispatches a custom event instead of toggling the menu. */
  onMenuClick?: () => void;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, {
  booleanProps: ["onMenuClick"],
  renamedProps: { onMenuClick: "hasmenuclickhandler" },
});
const slots = useSlots() as Slots;
</script>

<template>
  <goa-app-header v-bind="wcProps" @_menuClick="props.onMenuClick?.()">
    <div v-if="slots.banner" slot="banner">
      <slot name="banner" />
    </div>
    <div v-if="slots.phase" slot="phase">
      <slot name="phase" />
    </div>
    <div v-if="slots.utilities" slot="utilities">
      <slot name="utilities" />
    </div>
    <div v-if="slots.navigation" slot="navigation">
      <slot name="navigation" />
    </div>
    <slot />
  </goa-app-header>
</template>
