// libs/react-components/src/experimental/push-drawer/push-drawer.tsx
import { ReactNode, useEffect, useRef, type JSX } from "react";

interface WCProps {
  open?: boolean;
  heading?: string;
  width?: string;
  testid?: string;
  version?: string;
  ref: React.RefObject<HTMLElement | null>;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-push-drawer": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabxPushDrawerProps {
  open?: boolean;
  /** TO REVIEW: Custom heading content rendered as a template. Use this when the heading requires rich content beyond plain text. */
  heading?: string | ReactNode;
  width?: string;
  testId?: string;
  /** TO REVIEW: Action buttons or elements displayed in the component's action area. */
  actions?: ReactNode;
  /** TO REVIEW: The content rendered inside the push drawer body. */
  children: ReactNode;
  onClose: () => void;
  version?: string;
}

export function GoabxPushDrawer({
  open,
  heading,
  width,
  testId,
  actions,
  children,
  onClose,
  version = "2",
}: GoabxPushDrawerProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el?.current || !onClose) {
      return;
    }
    el.current?.addEventListener("_close", onClose);
    return () => {
      el.current?.removeEventListener("_close", onClose);
    };
  }, [el, onClose]);

  return (
    <goa-push-drawer
      ref={el}
      open={open ? true : undefined}
      heading={typeof heading === "string" ? heading : undefined}
      width={width}
      testid={testId}
      version={version}
    >
      {heading && typeof heading !== "string" && <div slot="heading">{heading}</div>}
      {actions && <div slot="actions">{actions}</div>}
      {children}
    </goa-push-drawer>
  );
}

export default GoabxPushDrawer;

// libs/angular-components/src/experimental/push-drawer/push-drawer.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  booleanAttribute,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goabx-push-drawer",
  imports: [NgTemplateOutlet],
  template: `@if (isReady) {
    <goa-push-drawer
      [open]="open"
      [attr.heading]="getHeadingAsString()"
      [attr.testid]="testId"
      [attr.width]="width"
      [attr.version]="version"
      (_close)="_onClose()"
    >
      <ng-content></ng-content>
      <div slot="heading">
        <ng-container [ngTemplateOutlet]="getHeadingAsTemplate()"></ng-container>
      </div>
      @if (actions) {
        <div slot="actions">
          <ng-container [ngTemplateOutlet]="actions"></ng-container>
        </div>
      }
    </goa-push-drawer>
  } `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabxPushDrawer implements OnInit {
  version = "2";

  @Input({ transform: booleanAttribute }) open?: boolean;
  /** TO REVIEW: Custom heading content rendered as a template. Use this when the heading requires rich content beyond plain text. */
  @Input() heading!: string | TemplateRef<any>;
  @Input() width?: string;
  @Input() testId?: string;
  /** TO REVIEW: Action buttons or elements displayed in the component's action area. */
  @Input() actions!: TemplateRef<any>;
  @Output() onClose = new EventEmitter();

  isReady = false;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }

  _onClose() {
    this.onClose.emit();
  }

  getHeadingAsString(): string {
    return this.heading instanceof TemplateRef ? "" : this.heading;
  }

  getHeadingAsTemplate(): TemplateRef<any> | null {
    if (!this.heading) return null;
    return this.heading instanceof TemplateRef ? this.heading : null;
  }
}
