// apps/prs/react/src/routes/bugs/bug3667.tsx
import {
  GoabBlock,
  GoabText,
  GoabDivider,
  GoabDetails,
  GoabLink,
  GoabNotification,
} from "@abgov/react-components";

export function Bug3667Route() {
  return (
    <div>
      <GoabText tag="h1" mt="m">
        Bug #3667: Notification banner refinements
      </GoabText>

      <GoabBlock>
        <GoabLink trailingIcon="open">
          <a
            href="https://github.com/GovAlta/ui-components/issues/3667"
            target="_blank"
            rel="noopener"
          >
            View on GitHub
          </a>
        </GoabLink>

        <GoabDetails heading="Issue Description">
          <GoabText tag="p">
            Notification banner height refinements. Compact should be 64px (currently
            ~66px), default should be 80px (currently ~82px). Also need to verify vertical
            centering of content (icon, text, dismiss button) at both sizes. The Event
            type should be silently undocumented (docs removal only, no code change
            needed).
          </GoabText>
        </GoabDetails>
      </GoabBlock>

      <GoabDivider mt="l" mb="l" />

      <GoabText tag="h2">Test Cases</GoabText>

      {/* ── Test 1: Height measurements ── */}
      <GoabText tag="h3">Test 1: Height at default and compact sizes</GoabText>
      <GoabText tag="p">
        Measure the rendered height of each banner. Default should be 80px, compact should
        be 64px. Use browser dev tools to inspect the goa-notification element and measure
        the outer height.
      </GoabText>

      <GoabText tag="h4" mt="m">
        Default size (target: 80px)
      </GoabText>
      <GoabNotification type="information">
        Default information banner for height measurement.
      </GoabNotification>

      <GoabText tag="h4" mt="m">
        Compact size (target: 64px)
      </GoabText>
      <GoabNotification type="information" compact={true}>
        Compact information banner for height measurement.
      </GoabNotification>

      <GoabText tag="h4" mt="m">
        Default important (target: 80px)
      </GoabText>
      <GoabNotification type="important">
        Default important banner for height measurement.
      </GoabNotification>

      <GoabText tag="h4" mt="m">
        Compact important (target: 64px)
      </GoabText>
      <GoabNotification type="important" compact={true}>
        Compact important banner for height measurement.
      </GoabNotification>

      <GoabDivider mt="l" mb="l" />

      {/* ── Test 2: Vertical centering ── */}
      <GoabText tag="h3">Test 2: Vertical centering of content</GoabText>
      <GoabText tag="p">
        Check that the icon, text, and close button are vertically centered at both sizes.
      </GoabText>

      <GoabText tag="h4" mt="m">
        Default emergency
      </GoabText>
      <GoabNotification type="emergency">
        Emergency banner. Check vertical alignment of icon, text, and close button.
      </GoabNotification>

      <GoabText tag="h4" mt="m">
        Compact emergency
      </GoabText>
      <GoabNotification type="emergency" compact={true}>
        Compact emergency. Check vertical alignment.
      </GoabNotification>

      <GoabDivider mt="l" mb="l" />

      {/* ── Test 3: Event type reference ── */}
      <GoabText tag="h3">Test 3: Event type banner (to be undocumented)</GoabText>
      <GoabText tag="p">
        The Event type should be silently removed from documentation only (no code
        change). Showing it here for reference to confirm it still renders correctly.
      </GoabText>

      <GoabText tag="h4" mt="m">
        Default event
      </GoabText>
      <GoabNotification type="event">
        Event banner at default size. This type will be removed from docs but the code
        stays.
      </GoabNotification>

      <GoabText tag="h4" mt="m">
        Compact event
      </GoabText>
      <GoabNotification type="event" compact={true}>
        Event banner at compact size.
      </GoabNotification>
    </div>
  );
}

export default Bug3667Route;

// apps/prs/angular/src/routes/bugs/3667/bug3667.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from "@angular/core";
import {
  GoabBlock,
  GoabDetails,
  GoabDivider,
  GoabLink,
  GoabNotification,
  GoabText,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3667",
  templateUrl: "./bug3667.component.html",
  imports: [GoabBlock, GoabDetails, GoabDivider, GoabLink, GoabNotification, GoabText],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Bug3667Component {}

<div>
  <goab-text tag="h1" mt="m">Bug #3667: Notification banner refinements</goab-text>

  <goab-block>
    <goab-link trailingIcon="open">
      <a
        href="https://github.com/GovAlta/ui-components/issues/3667"
        target="_blank"
        rel="noopener"
      >
        View on GitHub
      </a>
    </goab-link>

    <goab-details heading="Issue Description">
      <goab-text tag="p">
        Notification banner height refinements. Compact should be 64px (currently ~66px),
        default should be 80px (currently ~82px). Also need to verify vertical centering of
        content (icon, text, dismiss button) at both sizes. The Event type should be silently
        undocumented (docs removal only, no code change needed).
      </goab-text>
    </goab-details>
  </goab-block>

  <goab-divider mt="l" mb="l"></goab-divider>

  <goab-text tag="h2">Test Cases</goab-text>

  <!-- Test 1: Height measurements -->
  <goab-text tag="h3">Test 1: Height at default and compact sizes</goab-text>
  <goab-text tag="p">
    Measure the rendered height of each banner. Default should be 80px, compact should be
    64px. Use browser dev tools to inspect the goa-notification element and measure the outer
    height.
  </goab-text>

  <goab-text tag="h4" mt="m">Default size (target: 80px)</goab-text>
  <goab-notification type="information">
    Default information banner for height measurement.
  </goab-notification>

  <goab-text tag="h4" mt="m">Compact size (target: 64px)</goab-text>
  <goab-notification type="information" [compact]="true">
    Compact information banner for height measurement.
  </goab-notification>

  <goab-text tag="h4" mt="m">Default important (target: 80px)</goab-text>
  <goab-notification type="important">
    Default important banner for height measurement.
  </goab-notification>

  <goab-text tag="h4" mt="m">Compact important (target: 64px)</goab-text>
  <goab-notification type="important" [compact]="true">
    Compact important banner for height measurement.
  </goab-notification>

  <goab-divider mt="l" mb="l"></goab-divider>

  <!-- Test 2: Vertical centering -->
  <goab-text tag="h3">Test 2: Vertical centering of content</goab-text>
  <goab-text tag="p">
    Check that the icon, text, and close button are vertically centered at both sizes.
  </goab-text>

  <goab-text tag="h4" mt="m">Default emergency</goab-text>
  <goab-notification type="emergency">
    Emergency banner. Check vertical alignment of icon, text, and close button.
  </goab-notification>

  <goab-text tag="h4" mt="m">Compact emergency</goab-text>
  <goab-notification type="emergency" [compact]="true">
    Compact emergency. Check vertical alignment.
  </goab-notification>

  <goab-divider mt="l" mb="l"></goab-divider>

  <!-- Test 3: Event type reference -->
  <goab-text tag="h3">Test 3: Event type banner (to be undocumented)</goab-text>
  <goab-text tag="p">
    The Event type should be silently removed from documentation only (no code change).
    Showing it here for reference to confirm it still renders correctly.
  </goab-text>

  <goab-text tag="h4" mt="m">Default event</goab-text>
  <goab-notification type="event">
    Event banner at default size. This type will be removed from docs but the code stays.
  </goab-notification>

  <goab-text tag="h4" mt="m">Compact event</goab-text>
  <goab-notification type="event" [compact]="true">
    Event banner at compact size.
  </goab-notification>
</div>
