// libs/vue-components/src/lib/form-stepper/form-stepper.vue
<script setup lang="ts">
import type { GoabFormStepperOnChangeDetail, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  step?: number;
  testId?: string;
  mt?: Spacing;
  mr?: Spacing;
  mb?: Spacing;
  ml?: Spacing;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  onChange: [detail: GoabFormStepperOnChangeDetail];
}>();

const wcProps = useWcProps(props);

function onChange(e: Event) {
  const detail = (e as CustomEvent<GoabFormStepperOnChangeDetail>).detail;
  emit("onChange", detail);
}
</script>

<template>
  <goa-form-stepper v-bind="wcProps" @_change="onChange">
    <slot />
  </goa-form-stepper>
</template>

// libs/angular-components/src/lib/components/form-stepper/form-stepper.ts
import { GoABFormStepperOnChangeDetail, Spacing } from "@abgov/ui-components-common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-form-stepper",
  template: `
    <goa-form-stepper
      [attr.step]="step"
      [attr.testid]="testId"
      [attr.mt]="mt"
      [attr.mb]="mb"
      [attr.ml]="ml"
      [attr.mr]="mr"
      (_change)="onchange($event)"
    >
      <ng-content />
    </goa-form-stepper>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoABFormStepper {
  @Input() step?: number = -1;
  @Input() testId?: string;
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() ml?: Spacing;
  @Input() mr?: Spacing;

  @Output() onChange = new EventEmitter<GoABFormStepperOnChangeDetail>();

  onchange(e: Event) {
    const detail = (e as CustomEvent<GoABFormStepperOnChangeDetail>).detail;
    this.onChange.emit(detail);
  }
}
