// apps/react-demo/src/routes/textarea.tsx
import * as React from "react";
import { useState } from "react";
import {
  GoATextArea,
  GoAInput,
  GoAFormItem,
  GoAGrid,
} from "@abgov/react-components";

export default function TextArea() {
  const [value, setValue] = useState("Initial value");
  const [value4, setValue4] = useState("");
  const [value5, setValue5] = useState("");
  const [value6, setValue6] = useState("");
  const [value7, setValue7] = useState("");

  function onChange(name: string, value: string) {
    setValue(value);
    console.log(name, value);
  }

  function onKeyPress(name: string, value: string, key: string) {
    setValue(value);
    console.log(name, value, key);
  }

  function onChange4(name: string, value: string) {
    setValue4(value);
    console.log(name, value);
  }

  function onChange5(name: string, value: string) {
    setValue5(value);
    console.log(name, value);
  }

  function onChange6(name: string, value: string) {
    setValue6(value);
    console.log(name, value);
  }

  function onChange7(name: string, value: string) {
    setValue7(value);
    console.log(name, value);
  }

  return (
    <>
      <h1>TextArea</h1>
      <h2>Basic</h2>
      <GoATextArea name="comment-basic" value={value} onChange={onChange} />

      <h2>Disabled</h2>
      <GoATextArea
        name="comment-disabled"
        value={value4}
        onChange={onChange4}
        disabled={true}
      />

      <h2>Placeholder</h2>
      <GoATextArea
        placeholder="Tell us what you think.."
        name="comment"
        value={value5}
        onChange={onChange5}
      />

      <h2>Rows</h2>
      <GoATextArea
        rows={4}
        name="comment"
        value={value6}
        onChange={onChange6}
      />

      <h2>Error state</h2>
      <GoATextArea
        error={true}
        name="comment"
        value={value7}
        onChange={onChange7}
      />

      <h2>Aria Label</h2>
      <GoATextArea
        rows={4}
        name="aria"
        value={value6}
        onChange={onChange6}
        ariaLabel="Some random aria label here"
      />
      <h2>Margin Spacing</h2>
      <GoATextArea
        name="comment-basic"
        value={value}
        onChange={onChange}
        mt="m"
        mb="xs"
        ml="xl"
        mr="2xl"
      />

      <h2>on Key Press</h2>
      <GoATextArea
        rows={4}
        name="comment"
        value={value6}
        onChange={onChange6}
        onKeyPress={onKeyPress}
      />
    </>
  );
}

// _templates/angular/src/app/text-area/text-area.component.ts
import { Component } from "@angular/core";
import {FormControl, FormGroup} from "@angular/forms";

@Component({
  selector: "goab-text-area",
  templateUrl: "./text-area.component.html",
})
export class TextAreaComponent {
  boundVal = "";
  reactiveFormCtrl = new FormControl();
  form = new FormGroup({
    textarea: new FormControl(),
    input: new FormControl(),
  })

  constructor() { }

  onChange(e: any) {
    console.log("changed", e.detail.name, e.detail.value);
  }

  onKeyPress(e: any) {
    console.log("changed", e.detail.name, e.detail.value, e.detail.key);
  }
}

<h1>Text Area</h1>

<div [formGroup]="form" style="border: 1px solid red; width: 30ch">
  <goa-form-item>
    <goa-textarea goaValue formControlName="textarea" showcount="true" countby="character" maxcount="100" width="auto"></goa-textarea>
  </goa-form-item>
  <goa-form-item>
    <goa-input goaValue formControlName="input"></goa-input>
  </goa-form-item>
  Textarea Value: {{ form.controls["textarea"].value | json }}
  Input Value: {{ form.controls["input"].value | json }}
</div>



<h2>Basic</h2>
<goa-textarea
  name="comment-basic"
  (_change)="onChange($event)"
  value="Initial value"
></goa-textarea>

<h2>Disabled</h2>
<goa-textarea name="comment-disabled" disabled></goa-textarea>

<h2>Placeholder</h2>
<goa-textarea
  placeholder="Tell us what you think.."
  name="comment"
></goa-textarea>

<h2>Rows</h2>
<goa-textarea rows="4" name="comment"></goa-textarea>

<h2>Error state</h2>
<goa-textarea error name="comment"></goa-textarea>

<h2>Binding</h2>
{{ boundVal }}
<goa-textarea goaValue name="binding" [(ngModel)]="boundVal"></goa-textarea>

<h2>Margin Spacing</h2>
<goa-textarea
  mt="m"
  mb="xs"
  ml="xl"
  mr="2xl"
  name="comment-basic"
  (_change)="onChange($event)"
  value="Initial value"
></goa-textarea>

<h2>Reactive Binding</h2>
{{ reactiveFormCtrl.value }}
<goa-textarea
  goaValue
  name="binding"
  [formControl]="reactiveFormCtrl"
  [value]="reactiveFormCtrl.value"
></goa-textarea>

<h2>Reactive Binding - Disabled</h2>
<goa-textarea
  name="comment"
  goaValue
  [formControl]="reactiveFormCtrl"
  [attr.disabled]="true"
></goa-textarea>

<h2>On Key Press</h2>
<goa-textarea
  name="comment-basic"
  (_keyPress)="onKeyPress($event)"
  value="Initial value"
></goa-textarea>
<goa-form-item label="Basic" labelsize="regular">
  <goa-textarea width="60ch" showcount="true" countby="character" maxcount="100" (_change)="onChange($event)"></goa-textarea>
</goa-form-item>
