// libs/angular-components/src/lib/components/data-grid/data-grid.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  ChangeDetectorRef,
  OnInit,
  inject,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-data-grid",

  template: `
    @if (isReady) {
      <goa-data-grid
        [attr.keyboard-icon-visibility]="keyboardIconVisibility"
        [attr.keyboard-icon-position]="keyboardIconPosition"
        [attr.keyboard-nav]="keyboardNav"
      >
        <ng-content></ng-content>
      </goa-data-grid>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
/** Advanced table with sorting and selection. */
export class GoabDataGrid implements OnInit {
  private cdr = inject(ChangeDetectorRef);

  /** Controls visibility of the keyboard navigation indicator icon. Use "visible" to show or "hidden" to hide. @default "visible" */
  @Input() keyboardIconVisibility: "visible" | "hidden" = "visible";
  /** Position of the keyboard navigation indicator icon. @default "left" */
  @Input() keyboardIconPosition: "left" | "right" = "left";
  /** @required Navigation mode. "table" navigates like a table (up/down between rows), "layout" allows wrapping between rows with left/right arrows. */
  @Input({ required: true }) keyboardNav!: "layout" | "table";

  isReady = false;

  ngOnInit(): void {
    // For Angular, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }
}

// libs/react-components/src/lib/data-grid/data-grid.tsx
import React from "react";

interface WCProps {
  "keyboard-icon-visibility"?: "visible" | "hidden";
  "keyboard-icon-position"?: "left" | "right";
  "keyboard-nav"?: "layout" | "table";
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-data-grid": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabDataGridProps {
  /** @required Navigation mode. 'table' navigates like a table (up/down between rows), 'layout' allows wrapping between rows with left/right arrows. */
  keyboardNav: "layout" | "table";
  /** Controls visibility of the keyboard navigation indicator icon. @default "visible" */
  keyboardIconVisibility?: "visible" | "hidden";
  /** Position of the keyboard navigation indicator icon. @default "left" */
  keyboardIconPosition?: "left" | "right";
  /** Content rendered inside the data grid, typically rows and cells. */
  children?: React.ReactNode;
}

/** Advanced table with sorting and selection. */
export function GoabDataGrid({
  keyboardIconVisibility = "visible",
  keyboardIconPosition = "left",
  keyboardNav,
  children,
}: GoabDataGridProps) {
  return (
    <goa-data-grid
      keyboard-icon-visibility={keyboardIconVisibility}
      keyboard-icon-position={keyboardIconPosition}
      keyboard-nav={keyboardNav}
    >
      {children}
    </goa-data-grid>
  );
}

export default GoabDataGrid;
