// libs/react-components/src/lib/scroll-panel/scroll-panel.tsx
import { DataAttributes, GoabScrollPanelDirectionType } from "@abgov/ui-components-common";
import React, { ReactNode, type JSX } from "react";

interface WCProps {
  height?: string;
  testid?: string;
  direction?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-scroll-panel": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabScrollPanelProps extends DataAttributes {
  /** Content rendered in the sticky header region. */
  header?: ReactNode;
  /** Content rendered in the scrollable body region. */
  children?: ReactNode;
  /** Content rendered in the sticky footer region. */
  footer?: ReactNode;
  /**
   * Sets the height of the panel. Accepts any valid CSS height value, including
   * calc()/min()/clamp() and viewport units (e.g. "400px", "100%", "100vh",
   * "calc(100vh - 4rem)"). Invalid values fall back to "100%". Defaults to "100%".
   * The parent element must establish a height context for "100%" to resolve.
   */
  height?: string;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /**
   * The scroll direction(s). When content overflows, enables scrolling and shadow
   * indicators for the specified direction(s). Accepts "vertical", "horizontal", or "both".
   * Defaults to "vertical".
   */
  direction?: GoabScrollPanelDirectionType;
}

export function GoabScrollPanel({
  header,
  children,
  footer,
  height,
  testId,
  direction = "vertical",
  ...rest
}: GoabScrollPanelProps): JSX.Element {
  const hostStyle = height ? ({ height } as React.CSSProperties) : undefined;

  return (
    <goa-scroll-panel
      height={height}
      testid={testId}
      direction={direction}
      style={hostStyle}
      {...rest}
    >
      {header && <div slot="header">{header}</div>}
      {children}
      {footer && <div slot="footer">{footer}</div>}
    </goa-scroll-panel>
  );
}

export default GoabScrollPanel;

// libs/angular-components/src/lib/components/scroll-panel/scroll-panel.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectorRef,
  Component,
  Input,
  OnInit,
  TemplateRef,
  inject,
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";
import { GoabScrollPanelDirectionType } from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "goab-scroll-panel",
  imports: [NgTemplateOutlet],
  template: `@if (isReady) {
    <goa-scroll-panel
      [attr.height]="height"
      [attr.testid]="testId"
      [attr.direction]="direction"
      [style.height]="height"
    >
      @if (header) {
        <div slot="header">
          <ng-container [ngTemplateOutlet]="header"></ng-container>
        </div>
      }
      <ng-content />
      @if (footer) {
        <div slot="footer">
          <ng-container [ngTemplateOutlet]="footer"></ng-container>
        </div>
      }
    </goa-scroll-panel>
  }`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabScrollPanel implements OnInit {
  /**
   * Sets the height of the panel. Accepts any valid CSS height value, including
   * calc()/min()/clamp() and viewport units (e.g. "400px", "100%", "100vh",
   * "calc(100vh - 4rem)"). Invalid values fall back to "100%". Defaults to "100%".
   * The parent element must establish a height context for "100%" to resolve.
   */
  @Input() height?: string;
  /** Template ref for the sticky header region. */
  @Input() header?: TemplateRef<unknown>;
  /** Template ref for the sticky footer region. */
  @Input() footer?: TemplateRef<unknown>;
  /** Sets the data-testid attribute for automated testing. */
  @Input() testId?: string;
  /**
   * The scroll direction(s). When content overflows, enables scrolling and shadow
   * indicators for the specified direction(s). Accepts "vertical", "horizontal", or "both".
   * Defaults to "vertical".
   */
  @Input() direction: GoabScrollPanelDirectionType = "vertical";

  isReady = false;

  private cdr = inject(ChangeDetectorRef);

  ngOnInit(): void {
    // For Angular, delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }
}
