// apps/prs/react/src/app/routes.tsx/bugs/bug2502.tsx
import React from "react";
import {
  GoabBlock,
  GoabFormItem,
  GoabDropdown,
  GoabDropdownItem,
} from "@abgov/react-components";
import { GoabDropdownOnChangeDetail } from "@abgov/ui-components-common";

export function Bug2502Route() {
  const onDropdownChange = (details: GoabDropdownOnChangeDetail) => {
    console.log(`Dropdown ${details.name} selected value:`, details.value);
  };

  return (
    <main>
      <h3>Bug 2502 - Dropdown Test</h3>

      <GoabBlock gap="m" direction="row">
        <GoabFormItem label="Native Dropdown">
          <GoabDropdown name="nativeDropdown" onChange={onDropdownChange} native={true}>
            <GoabDropdownItem value="red" label="Red" />
            <GoabDropdownItem value="green" label="Green" />
            <GoabDropdownItem value="blue" label="Blue" />
          </GoabDropdown>
        </GoabFormItem>

        <GoabFormItem label="Custom Dropdown">
          <GoabDropdown name="customDropdown" onChange={onDropdownChange} native={false}>
            <GoabDropdownItem value="red" label="Red" />
            <GoabDropdownItem value="green" label="Green" />
            <GoabDropdownItem value="blue" label="Blue" />
          </GoabDropdown>
        </GoabFormItem>
      </GoabBlock>
    </main>
  );
}

// apps/prs/angular/src/routes/bugs/2502/bug2502.component.ts
import { Component } from "@angular/core";
import {
  GoabBlock,
  GoabFormItem,
  GoabDropdown,
  GoabDropdownItem,
  GoabDropdownOnChangeDetail,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug2502",
  templateUrl: "./bug2502.component.html",
  imports: [GoabBlock, GoabFormItem, GoabDropdown, GoabDropdownItem],
})
export class Bug2502Component {
  onDropdownChange(details: GoabDropdownOnChangeDetail) {
    console.log(`Dropdown ${details.name} selected value:`, details.value);
  }
}

<main>
  <h3>Bug 2502 - Dropdown Test</h3>

  <goab-block gap="m" direction="row">
    <goab-form-item label="Native Dropdown">
      <goab-dropdown
        name="nativeDropdown"
        (onChange)="onDropdownChange($event)"
        [native]="true"
      >
        <goab-dropdown-item value="red" label="Red" />
        <goab-dropdown-item value="green" label="Green" />
        <goab-dropdown-item value="blue" label="Blue" />
      </goab-dropdown>
    </goab-form-item>

    <goab-form-item label="Custom Dropdown">
      <goab-dropdown name="customDropdown" (onChange)="onDropdownChange($event)">
        <goab-dropdown-item value="red" label="Red" />
        <goab-dropdown-item value="green" label="Green" />
        <goab-dropdown-item value="blue" label="Blue" />
      </goab-dropdown>
    </goab-form-item>
  </goab-block>
</main>
