// libs/vue-components/src/lib/tabs/tabs.vue
<script setup lang="ts">
import type {
  GoabTabsNavigation,
  GoabTabsOnChangeDetail,
  GoabTabsOrientation,
  GoabTabsVariant,
} from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** The initially active tab (1-based index). If not set, the first tab is active.  @default -1 */
  initialTab?: number;
  /** Sets a data-testid attribute for automated testing.  @default "" */
  testId?: string;
  /** Visual style variant. "segmented" shows pill-style tabs with animation. @default "default" */
  variant?: GoabTabsVariant;
  /** Tab layout orientation. "auto" stacks vertically on mobile, "horizontal" keeps horizontal on all screen sizes. @default "auto" */
  orientation?: GoabTabsOrientation;
  /** Controls URL navigation mode on tab change. @default "hash" */
  navigation?: GoabTabsNavigation;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  /** Callback fired when the active tab changes. */
  onChange: [detail: GoabTabsOnChangeDetail];
}>();

const wcProps = useWcProps(props);
</script>

<template>
  <goa-tabs v-bind="wcProps" @_change="emit('onChange', $event.detail)">
    <slot />
  </goa-tabs>
</template>

// libs/react-components/src/experimental/tabs/tabs.tsx
import React, { useEffect, useRef, type JSX } from "react";
import {
  GoabTabsOnChangeDetail,
  GoabTabsOrientation,
  GoabTabsVariant,
  GoabTabsNavigation,
} from "@abgov/ui-components-common";

interface WCProps {
  initialtab?: number;
  ref: React.RefObject<HTMLElement | null>;
  onChange?: (tab: number) => void;
  testid?: string;
  variant?: GoabTabsVariant;
  navigation?: GoabTabsNavigation;
  version?: string;
  orientation?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-tabs": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabxTabsProps {
  /**
   * The initially active tab (1-based index). If not set, the first tab is active.
   * @default -1
   */
  initialTab?: number;
  children?: React.ReactNode;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
  /**
   * Visual style variant. "segmented" shows pill-style tabs with animation.
   * @default "default"
   */
  variant?: GoabTabsVariant;
  /** Tab layout orientation. "auto" stacks vertically on mobile (default), "horizontal" keeps horizontal on all screen sizes. */
  orientation?: GoabTabsOrientation;
  navigation?: GoabTabsNavigation;
  onChange?: (detail: GoabTabsOnChangeDetail) => void;
}

export function GoabxTabs({
  initialTab,
  children,
  testId,
  onChange,
  variant,
  orientation,
  navigation,
}: GoabxTabsProps): JSX.Element {
  const ref = useRef<HTMLElement>(null);

  useEffect(() => {
    const element = ref.current;
    if (element && onChange) {
      const handler = (event: Event) => {
        const detail = (event as CustomEvent<GoabTabsOnChangeDetail>).detail;
        onChange(detail);
      };
      element.addEventListener("_change", handler);
      return () => {
        element.removeEventListener("_change", handler);
      };
    }
  }, [onChange]);

  return (
    <goa-tabs
      ref={ref}
      initialtab={initialTab}
      testid={testId}
      variant={variant}
      version="2"
      orientation={orientation}
      navigation={navigation}
    >
      {children}
    </goa-tabs>
  );
}

export default GoabxTabs;
