// apps/react-demo/src/routes/sideMenu.tsx
import { GoASideMenu, GoASideMenuGroup, GoASideMenuHeading } from "@abgov/react-components";

export function SideMenu() {
  return (
    <GoASideMenu>
      <GoASideMenuHeading>Nav section 1</GoASideMenuHeading>
      <a href="#about">Home</a>
      <a href="#contact">Profile</a>
      <GoASideMenuHeading>Nav section 2</GoASideMenuHeading>
      <a href="#about">About</a>
      <a href="#contact">Contact</a>
      <GoASideMenuGroup heading="Links">
        <GoASideMenuHeading>Nav section 3</GoASideMenuHeading>
        <a href="#foo">Foo</a>
        <a href="#bar">Bar</a>
        <GoASideMenuGroup heading="More Links">
          <GoASideMenuHeading>Nav section 4</GoASideMenuHeading>
          <a href="#more-foo">More Foo</a>
          <a href="#more-bar">More Bar</a>
        </GoASideMenuGroup>
      </GoASideMenuGroup>
    </GoASideMenu>
  );
}

export default SideMenu;

// _templates/angular/src/app/sidemenu/sidemenu.component.ts
import { GoABSideMenu, GoABSideMenuGroup, GoABSideMenuHeading } from "@abgov/angular-components";
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-sidemenu",
  templateUrl: "./sidemenu.component.html",
  imports: [
    GoABSideMenu,
    GoABSideMenuGroup,
    GoABSideMenuHeading,
  ]
})
export class SideMenuComponent {
  constructor() { }
}

<h2>Side Menu</h2>
<goab-side-menu>
  <goab-side-menu-heading icon="home">Nav section 1</goab-side-menu-heading>
  <a href="#home">Home</a>
  <a href="#profile">Profile</a>
  <goab-side-menu-heading icon="home" [meta]="meta">Nav section 2
    <ng-template #meta><goab-badge type="midtone" content="Details"></goab-badge></ng-template>
  </goab-side-menu-heading>
  <a href="#about">About</a>
  <a href="#contact">Contact</a>
  <goab-side-menu-group heading="Links">
    <goab-side-menu-heading>Nav section 3</goab-side-menu-heading>
    <a href="#foo">Foo</a>
    <a href="#bar">Bar</a>
    <goab-side-menu-group heading="More Links">
      <goab-side-menu-heading>Nav section 4</goab-side-menu-heading>
      <a href="#more-foo">More Foo</a>
      <a href="#more-bar">More Bar</a>
    </goab-side-menu-group>
  </goab-side-menu-group>
</goab-side-menu>
