// apps/react-demo/src/routes/micrositeHeader.tsx
import { GoAMicrositeHeader } from "@abgov/react-components";
import * as React from "react";

export default function MicrositeHeader() {
  return (
    <>
      <h1>Microsite Header</h1>
      <h2>Alpha</h2>
      <GoAMicrositeHeader type="alpha"></GoAMicrositeHeader>

      <br />
      <h2>Beta</h2>
      <GoAMicrositeHeader type="beta"></GoAMicrositeHeader>

      <br />
      <h2>Live</h2>
      <GoAMicrositeHeader type="live"></GoAMicrositeHeader>

      <br />
      <h2>Version</h2>
      <GoAMicrositeHeader type="alpha" version="v1.2.3"></GoAMicrositeHeader>

      <br />
      <h2>Feedback Url</h2>
      <GoAMicrositeHeader
        type="alpha"
        version="v1.2.3"
        feedbackUrl="https://example.com/feedback"
      ></GoAMicrositeHeader>
    </>
  );
}

// apps/angular-demo/src/app/microsite-header/microsite-header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'abgov-microsite-header',
  templateUrl: './microsite-header.component.html',
  styleUrls: ['./microsite-header.component.css']
})
export class MicrositeHeaderComponent {

  constructor() { }

}

<h3>Alpha</h3>
<goa-microsite-header level="alpha" version="v1.2.3"></goa-microsite-header>

<br />
<h3>Beta</h3>
<goa-microsite-header level="beta"></goa-microsite-header>

<br />
<h3>Live</h3>
<goa-microsite-header level="live"></goa-microsite-header>

<br />
<h3>Version</h3>
<goa-microsite-header level="alpha" version="v1.2.3"></goa-microsite-header>

<br />
<h3>Feedback Url</h3>
<goa-microsite-header
  level="alpha"
  version="v1.2.3"
  feedbackurl="https://example.com/feedback"
></goa-microsite-header>
