// libs/vue-components/src/lib/card-group/card.group.vue
<template>
  <div class="goa-card-group">
    <div class="card-group-title">{{ title }}</div>
    <div v-if="!hasCardItems" slot-scope :class="[cardGroupClass]">
      <slot />
    </div>
    <div v-if="hasCardItems" :class="[cardGroupClass]">
      <div>
        <goa-card
          v-for="(card, index) in cardItems"
          :key="index"
          :title="card.title"
          :title-url="card.titleUrl"
          :description="card.description"
          :card-image-url="card.cardImageUrl"
          :card-width="card.cardWidth"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import GoACard from '../card/card.vue';

export default {
  name: 'goa-card-group',
  components: {
    'goa-card': GoACard,
  },
  props: {
    /**
     * Card group title.
     */
    title: {
      type: String,
      required: true,
    },
    /**
     * Card layout: basic and column .
     */
    layout: {
      type: String,
      required: false,
      default: 'basic',
      validator: (prop: string): boolean => ['basic', 'column'].includes(prop),
    },
    /** Card group json data pass in*/
    cardItems: {
      type: Array,
      default: null,
    },
  },
  data(): unknown {
    return {
      cardGroupClass: `card-group-${this.layout}-vue`,
    };
  },
  computed: {
    hasCardItems(): boolean {
      return Boolean(this.cardItems);
    },
  },
};
</script>

<style lang="scss" module>
@import './card.group.scss';
</style>

// libs/react-components/src/lib/card-group/card.group.component.tsx
import React, { Children, ReactNode, FC } from 'react';
import { GoACard } from '../card/card';
import './card.group.scss';

type CardGroupLayout = 'basic' | 'column';

interface CardItem {
  title: string;
  /** Card description */
  description?: string;
  /** Card image , display on top of title */
  cardImageUrl?: string;
  /** Display card size to allow card responsively show in different device*/
  cardWidth?: number;
  /** Navigation to relate webside from Card title */
  titleUrl?: string;
  /** customize footer by passing react component code */
  children?: React.ReactNode;
}

interface Props {
  title?: string;
  children?: React.ReactNode;
  layout: CardGroupLayout;
  cardItems?: CardItem[];
}
export const GoACardGroup: FC<Props> = ({
  title = null,
  children = null,
  layout = 'basic',
  cardItems = null,
}) => {
  function getCards() {
    if (children) {
      return children;
    }

    return cardItems.map((item: CardItem, index: number) => {
      return (
        <GoACard {...item} key={index}>
          {item.children}
        </GoACard>
      );
    });
  }

  return (
    <div className="goa-card-group">
      <div className="card-group-title">{title}</div>
      <div className={`card-group-${layout}`}>{getCards()}</div>
    </div>
  );
};

export default GoACardGroup;
