// libs/vue-components/src/lib/text/text.vue
<script setup lang="ts">
import type { GoabTextMaxWidth, GoabTextHeadingElement, GoabTextTextElement, GoabTextSize, GoabTextColor, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  tag?: GoabTextTextElement | GoabTextHeadingElement;
  size?: GoabTextSize;
  maxWidth?: GoabTextMaxWidth;
  color?: GoabTextColor;
  id?: string;
  mt?: Spacing;
  mr?: Spacing;
  mb?: Spacing;
  ml?: Spacing;
}

const props = defineProps<Props>();
const { tag, ...rest } = props;
const wcProps = useWcProps(rest);
</script>

<template>
  <goa-text :as="tag" v-bind="wcProps">
    <slot />
  </goa-text>
</template>

// libs/angular-components/src/lib/components/text/text.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import {
  GoabTextColor,
  GoabTextHeadingElement,
  GoabTextMaxWidth,
  GoabTextSize,
  GoabTextTextElement, Spacing,
} from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: 'goab-text',
  template: `
    <goa-text
      [attr.as]="tag"
      [attr.size]="size"
      [attr.maxwidth]="maxWidth"
      [attr.color]="color"
      [attr.id]="id"
      [attr.mt]="mt"
      [attr.mb]="mb"
      [attr.ml]="ml"
      [attr.mr]="mr">
      <ng-content />
    </goa-text>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoabText {
  @Input() tag?: GoabTextTextElement | GoabTextHeadingElement;
  @Input() size?: GoabTextSize;
  @Input() maxWidth?: GoabTextMaxWidth;
  @Input() color?: GoabTextColor;
  @Input() id?: string;
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() ml?: Spacing;
  @Input() mr?: Spacing;
}
