// libs/react-components/src/lib/checkbox-list/checkbox-list-item.tsx
import { type JSX } from "react";

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-checkbox-list-item": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface WCProps {
  value: string;
  text?: string;
  disabled?: string;
  testid?: string;
  arialabel?: string;
}

export interface GoabCheckboxListItemProps {
  value: string;
  text?: string;
  disabled?: boolean;
  testId?: string;
  ariaLabel?: string;
  children?: React.ReactNode;
}

export function GoabCheckboxListItem({
  value,
  text,
  disabled,
  testId,
  ariaLabel,
  children,
}: GoabCheckboxListItemProps): JSX.Element {
  return (
    <goa-checkbox-list-item
      value={value}
      text={text}
      disabled={disabled ? "true" : undefined}
      testid={testId}
      arialabel={ariaLabel}
    >
      {children}
    </goa-checkbox-list-item>
  );
}

export default GoabCheckboxListItem;

// libs/angular-components/src/lib/components/checkbox-list-item/checkbox-list-item.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-checkbox-list-item",
  template: `
    <goa-checkbox-list-item
      [attr.value]="value"
      [attr.text]="text"
      [attr.disabled]="disabled ? 'true' : 'false'"
      [attr.testid]="testId"
      [attr.arialabel]="ariaLabel"
    >
      <ng-content />
    </goa-checkbox-list-item>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoabCheckboxListItem {
  @Input() value?: string;
  @Input() text?: string;
  @Input() disabled?: boolean;
  @Input() testId?: string;
  @Input() ariaLabel?: string;
}
