// libs/angular-components/src/lib/components/form/task-list.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from "@angular/core";
import { GoabBaseComponent } from "../base.component";

@Component({
  selector: "goab-public-form-task-list",
  standalone: true,
  template: `
    <goa-public-form-task-list
      [attr.heading]="heading"
      [attr.mt]="mt"
      [attr.mr]="mr"
      [attr.mb]="mb"
      [attr.ml]="ml"
    >
      <ng-content />
    </goa-public-form-task-list>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
/** Container for form inputs and validation. */
export class GoabPublicFormTaskList extends GoabBaseComponent {
  /** Sets the heading text displayed above the task list. */
  @Input() heading?: string;
}

// libs/react-components/src/lib/form/task-list.tsx
import { ReactNode } from "react";
import { Margins, DataAttributes } from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../common/extract-props";

interface WCProps extends Margins {
  heading?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-public-form-task-list": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface GoabPublicFormTaskListProps extends Margins, DataAttributes {
  /** Content rendered inside the task list, typically GoabPublicFormTask items. */
  children: ReactNode;
  /** Sets the heading text displayed above the task list. */
  heading?: string;
}

/** Container for form inputs and validation. */
export function GoabPublicFormTaskList({
  children,
  ...rest
}: GoabPublicFormTaskListProps) {
  const _props = transformProps<WCProps>(rest, lowercase);

  return <goa-public-form-task-list {..._props}>{children}</goa-public-form-task-list>;
}

export default GoabPublicFormTaskList;
