// libs/vue-components/src/lib/linear-progress/linear-progress.vue
<script setup lang="ts">
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** Progress value (0-100). When undefined, shows an indeterminate loading animation.  @default undefined */
  progress?: number | null;
  /** Controls visibility of the percentage text. @default "visible" */
  percentVisibility?: "visible" | "hidden";
  /** Accessible label for the progress bar.  @default undefined */
  ariaLabel?: string;
  /** ID of the element that labels this progress bar.  @default undefined */
  ariaLabelledBy?: string;
  /** Sets a data-testid attribute for automated testing.  @default undefined */
  testId?: string;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props, { 
  renamedProps: {
    ariaLabel: "aria-label",
    ariaLabelledBy: "aria-labelledby",
    percentVisibility: "percent-visibility",
    testId: "testid",
  },
});
</script>

<template>
  <goa-linear-progress v-bind="wcProps" />
</template>

// libs/angular-components/src/lib/components/linear-progress/linear-progress.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";
@Component({
  standalone: true,
  selector: "goab-linear-progress",
  template: `
    @if (isReady) {
      <goa-linear-progress
        [attr.progress]="progress"
        [attr.percent-visibility]="percentVisibility"
        [attr.aria-label]="ariaLabel"
        [attr.aria-labelledby]="ariaLabelledBy"
        [attr.testid]="testid"
      >
      </goa-linear-progress>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabLinearProgress implements OnInit {
  /** Progress value (0-100). When undefined, shows an indeterminate loading animation. */
  @Input() progress?: number | null | undefined;
  /** Controls visibility of the percentage text. */
  @Input() percentVisibility?: "visible" | "hidden" | undefined;
  /** Accessible label for the progress bar. */
  @Input() ariaLabel?: string;
  /** ID of the element that labels this progress bar. */
  @Input() ariaLabelledBy?: string;
  /** Sets a data-testid attribute for automated testing. */
  @Input() testid?: string;

  isReady = false;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    // For Angular 20, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }
}
