// libs/react-components/src/lib/two-column-layout/two-column-layout.tsx
import React, { ReactNode } from "react";

interface WCProps {
  navcolumnwidth?: string;
  maxcontentwidth?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-two-column-layout": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface Props {
  navColumnWidth?: string;
  maxContentWidth?: string;
  header: ReactNode;
  footer: ReactNode;
  nav: ReactNode;
  children: ReactNode;
}

export function GoATwoColumnLayout(props: Props) {
  return (
    <goa-two-column-layout
      navcolumnwidth={props.navColumnWidth}
      maxcontentwidth={props.maxContentWidth}
    >
      {props.header && <div slot="header">{props.header}</div>}
      {props.nav && <div slot="nav">{props.nav}</div>}
      {props.children}
      {props.footer && <div slot="footer">{props.footer}</div>}
    </goa-two-column-layout>
  );
}

export default GoATwoColumnLayout;

// libs/vue-components/src/lib/two-column-layout/two-column-layout.vue
<script setup lang="ts">
import { useSlots } from "vue";
import { useWcProps } from "../common/useWcProps";

interface Props {
  navColumnWidth?: string;
  maxContentWidth?: string;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props);
const slots = useSlots();
</script>

<template>
  <goa-two-column-layout v-bind="wcProps">
    <div v-if="slots.header" slot="header">
      <slot name="header" />
    </div>
    <div v-if="slots.nav" slot="nav">
      <slot name="nav" />
    </div>
    <slot />
    <div v-if="slots.footer" slot="footer">
      <slot name="footer" />
    </div>
  </goa-two-column-layout>
</template>
