// libs/react-components/src/experimental/drawer/drawer.tsx
import { ReactNode, useEffect, useRef, type JSX } from "react";
import { GoabDrawerPosition, GoabDrawerSize } from "@abgov/ui-components-common";

interface WCProps {
  position: GoabDrawerPosition;
  open?: boolean;
  heading?: string;
  maxsize?: GoabDrawerSize;
  testid?: string;
  ref: React.RefObject<HTMLElement | null>;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-drawer": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabxDrawerProps {
  /**
   * The position of the drawer.
   * @required
   */
  position: GoabDrawerPosition;
  /**
   * Whether the drawer is open.
   * @default false
   */
  open?: boolean;
  /**
   * The heading text displayed at the top of the drawer.
   * @default ""
   */
  heading?: string | ReactNode;
  /** Sets max height on bottom position, sets width on left and right position. */
  maxSize?: GoabDrawerSize;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default "drawer"
   */
  testId?: string;
  /** TO REVIEW: Action buttons or elements displayed in the component's action area. */
  actions?: ReactNode;
  /**
   * TO REVIEW: The content rendered inside the drawer body.
   * @required
   */
  children: ReactNode;
  onClose: () => void;
  version?: string;
}

export function GoabxDrawer({
  position,
  open,
  heading,
  maxSize,
  testId,
  actions,
  children,
  onClose,
  version = "2",
}: GoabxDrawerProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el?.current || !onClose) {
      return;
    }
    el.current?.addEventListener("_close", onClose);
    return () => {
      el.current?.removeEventListener("_close", onClose);
    };
  }, [el, onClose]);

  return (
    <goa-drawer
      ref={el}
      position={position}
      open={open ? true : undefined}
      heading={typeof heading === "string" ? heading : undefined}
      maxsize={maxSize}
      testid={testId}
      version={version}
    >
      {heading && typeof heading !== "string" && <div slot="heading">{heading}</div>}
      {actions && <div slot="actions">{actions}</div>}
      {children}
    </goa-drawer>
  );
}

export default GoabxDrawer;

// libs/vue-components/src/lib/drawer/drawer.vue
<script setup lang="ts">
import type { GoabDrawerPosition, GoabDrawerSize } from "@abgov/ui-components-common";
import { useSlots } from "vue";
import { useWcProps } from "../common/useWcProps";

interface Slots {
  default?: () => unknown;
  /** Content rendered in the "actions" named slot. */
  actions?: () => unknown;
  /** Content rendered in the "heading" named slot. */
  heading?: () => unknown;
}

interface Props {
  /** @required The position of the drawer.  @default undefined */
  position: GoabDrawerPosition;
  /** Whether the drawer is open.  @default undefined */
  open?: boolean;
  /** The heading text displayed at the top of the drawer. Accepts a string or a ReactNode for custom heading content.  @default "" */
  heading?: string;
  /** Sets max height on bottom position, sets width on left and right position.  @default undefined */
  maxSize?: GoabDrawerSize;
  /** Sets a data-testid attribute for automated testing.  @default "drawer" */
  testId?: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  /** @required Callback fired when the drawer requests to be closed. */
  onClose: [];
}>();

const wcProps = useWcProps(props, { 
  booleanProps: ["open"],
});
const slots = useSlots() as Slots;

function onClose(e: Event) {
  if (e.target !== e.currentTarget) return;
  emit("onClose");
}
</script>

<template>
  <goa-drawer v-bind="wcProps" @_close="onClose">
    <div v-if="slots.heading" slot="heading">
      <slot name="heading" />
    </div>
    <div v-if="slots.actions" slot="actions">
      <slot name="actions" />
    </div>
    <slot />
  </goa-drawer>
</template>
