// apps/prs/angular/src/routes/docs/modal/modal.component.ts
import { Component } from "@angular/core";
import {
  GoabButton, GoabButtonGroup, GoabDropdown, GoabDropdownItem,
  GoabFormItem, GoabInput, GoabModal, GoabTextArea,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-modal",
  templateUrl: "./modal.component.html",
  imports: [
    GoabButton, GoabButtonGroup, GoabDropdown, GoabDropdownItem,
    GoabFormItem, GoabInput, GoabModal, GoabTextArea,
  ],
})
export class DocsModalComponent {
  basicOpen = false;
  dismissableOpen = false;
  destructiveOpen = false;
  importantOpen = false;
  infoOpen = false;
  successOpen = false;
  eventOpen = false;
  wideOpen = false;

  addItemOpen = false;
  itemType: string | undefined = "";
  itemName = "";
  itemDescription = "";

  deleteOpen = false;
  navigateOpen = false;
  requireOpen = false;

  openBasic(): void { this.basicOpen = true; }
  closeBasic(): void { this.basicOpen = false; }

  openDismissable(): void { this.dismissableOpen = true; }
  closeDismissable(): void { this.dismissableOpen = false; }

  openDestructive(): void { this.destructiveOpen = true; }
  closeDestructive(): void { this.destructiveOpen = false; }

  openImportant(): void { this.importantOpen = true; }
  closeImportant(): void { this.importantOpen = false; }

  openInfo(): void { this.infoOpen = true; }
  closeInfo(): void { this.infoOpen = false; }

  openSuccess(): void { this.successOpen = true; }
  closeSuccess(): void { this.successOpen = false; }

  openEvent(): void { this.eventOpen = true; }
  closeEvent(): void { this.eventOpen = false; }

  openWide(): void { this.wideOpen = true; }
  closeWide(): void { this.wideOpen = false; }

  toggleAddItemModal(): void { this.addItemOpen = !this.addItemOpen; }
  updateType(event: any): void { this.itemType = event.value; }
  updateName(event: any): void { this.itemName = event.value; }
  updateDescription(event: any): void { this.itemDescription = event.value; }

  toggleDeleteModal(): void { this.deleteOpen = !this.deleteOpen; }

  openNavigate(): void { this.navigateOpen = true; }
  closeNavigate(): void { this.navigateOpen = false; }
  onChangeRoute(): void {
    this.navigateOpen = false;
    console.log("Navigating to new route...");
  }

  toggleRequireModal(): void { this.requireOpen = !this.requireOpen; }
}

<h2>Modal</h2>

<h3>Basic modal</h3>
<goab-button (onClick)="openBasic()">Open basic modal</goab-button>
<goab-modal heading="Confirm action" [open]="basicOpen">
  <p>Are you sure you want to proceed with this action?</p>
  <goab-button-group alignment="end" mt="l">
    <goab-button type="secondary" size="compact" (onClick)="closeBasic()"
      >Cancel</goab-button
    >
    <goab-button size="compact" (onClick)="closeBasic()">Confirm</goab-button>
  </goab-button-group>
</goab-modal>

<h3>Dismissable</h3>
<goab-button (onClick)="openDismissable()">Open dismissable modal</goab-button>
<goab-modal heading="Information" [open]="dismissableOpen" (onClose)="closeDismissable()">
  <p>You can close this modal with the X button or by clicking the backdrop.</p>
</goab-modal>

<h3>Destructive action</h3>
<goab-button (onClick)="openDestructive()">Open destructive modal</goab-button>
<goab-modal
  heading="Are you sure you want to delete this item?"
  [open]="destructiveOpen"
  calloutVariant="emergency"
>
  <p>This action cannot be undone. The item will be permanently removed.</p>
  <goab-button-group alignment="end" mt="l">
    <goab-button type="secondary" size="compact" (onClick)="closeDestructive()"
      >Cancel</goab-button
    >
    <goab-button variant="destructive" size="compact" (onClick)="closeDestructive()"
      >Delete</goab-button
    >
  </goab-button-group>
</goab-modal>

<h3>Important callout</h3>
<goab-button (onClick)="openImportant()">Open important modal</goab-button>
<goab-modal
  heading="Your session is about to expire"
  [open]="importantOpen"
  calloutVariant="important"
>
  <p>You will be logged out in 5 minutes due to inactivity.</p>
  <goab-button-group alignment="end" mt="l">
    <goab-button size="compact" (onClick)="closeImportant()">Stay logged in</goab-button>
  </goab-button-group>
</goab-modal>

<h3>Information callout</h3>
<goab-button (onClick)="openInfo()">Open info modal</goab-button>
<goab-modal
  heading="New features available"
  [open]="infoOpen"
  calloutVariant="information"
  (onClose)="closeInfo()"
>
  <p>
    We have updated the application with new features. Review the changes to get started.
  </p>
</goab-modal>

<h3>Success callout</h3>
<goab-button (onClick)="openSuccess()">Open success modal</goab-button>
<goab-modal
  heading="Application submitted"
  [open]="successOpen"
  calloutVariant="success"
  (onClose)="closeSuccess()"
>
  <p>
    Your application has been successfully submitted. You will receive a confirmation
    email shortly.
  </p>
</goab-modal>

<h3>Event callout</h3>
<goab-button (onClick)="openEvent()">Open event modal</goab-button>
<goab-modal
  heading="Scheduled maintenance"
  [open]="eventOpen"
  calloutVariant="event"
  (onClose)="closeEvent()"
>
  <p>
    The system will be unavailable on March 28 from 10:00 PM to 2:00 AM for scheduled
    maintenance.
  </p>
</goab-modal>

<h3>Custom width</h3>
<goab-button (onClick)="openWide()">Open wide modal</goab-button>
<goab-modal
  heading="Wide modal"
  [open]="wideOpen"
  maxWidth="80ch"
  (onClose)="closeWide()"
>
  <p>This modal has a wider maximum width for more content.</p>
</goab-modal>

<h2>Examples</h2>

<h3>Add another item in a modal</h3>
<goab-button type="tertiary" leadingIcon="add" (onClick)="toggleAddItemModal()"
  >Add another item</goab-button
>
<goab-modal
  [open]="addItemOpen"
  (onClose)="toggleAddItemModal()"
  heading="Add a new item"
  [actions]="addItemActions"
>
  <p>Fill in the information to create a new item</p>
  <goab-form-item label="Type" mt="l">
    <goab-dropdown (onChange)="updateType($event)" [value]="itemType">
      <goab-dropdown-item value="1" label="Option 1"></goab-dropdown-item>
      <goab-dropdown-item value="2" label="Option 2"></goab-dropdown-item>
    </goab-dropdown>
  </goab-form-item>
  <goab-form-item label="Name" mt="l">
    <goab-input
      name="name"
      width="100%"
      (onChange)="updateName($event)"
      [value]="itemName"
    ></goab-input>
  </goab-form-item>
  <goab-form-item label="Description" mt="l">
    <goab-textarea
      name="description"
      width="100%"
      [rows]="3"
      (onChange)="updateDescription($event)"
      [value]="itemDescription"
    ></goab-textarea>
  </goab-form-item>
  <ng-template #addItemActions>
    <goab-button-group alignment="end">
      <goab-button type="tertiary" size="compact" (onClick)="toggleAddItemModal()"
        >Cancel</goab-button
      >
      <goab-button type="primary" size="compact" (onClick)="toggleAddItemModal()"
        >Save new item</goab-button
      >
    </goab-button-group>
  </ng-template>
</goab-modal>

<h3>Confirm a destructive action</h3>
<goab-button type="tertiary" leadingIcon="trash" (onClick)="toggleDeleteModal()"
  >Delete record</goab-button
>
<goab-modal
  [open]="deleteOpen"
  (onClose)="toggleDeleteModal()"
  heading="Are you sure you want to delete this record?"
  [actions]="deleteActions"
>
  <p>This action cannot be undone.</p>
  <ng-template #deleteActions>
    <goab-button-group alignment="end">
      <goab-button type="tertiary" size="compact" (onClick)="toggleDeleteModal()"
        >Cancel</goab-button
      >
      <goab-button
        type="primary"
        variant="destructive"
        size="compact"
        (onClick)="toggleDeleteModal()"
        >Delete record</goab-button
      >
    </goab-button-group>
  </ng-template>
</goab-modal>

<h3>Confirm before navigating away</h3>
<goab-button (onClick)="openNavigate()">Open</goab-button>
<goab-modal
  [open]="navigateOpen"
  heading="Are you sure you want to change route?"
  [actions]="navigateActions"
>
  <ng-template #navigateActions>
    <goab-button-group alignment="end">
      <goab-button type="secondary" size="compact" (onClick)="closeNavigate()"
        >Cancel</goab-button
      >
      <goab-button type="primary" size="compact" (onClick)="onChangeRoute()"
        >Change route</goab-button
      >
    </goab-button-group>
  </ng-template>
</goab-modal>

<h3>Require user action before continuing</h3>
<goab-button (onClick)="toggleRequireModal()">Open Basic Modal</goab-button>
<goab-modal
  [open]="requireOpen"
  (onClose)="toggleRequireModal()"
  heading="Are you sure you want to continue?"
  [actions]="requireActions"
>
  <p>You cannot return to this page.</p>
  <ng-template #requireActions>
    <goab-button-group alignment="end">
      <goab-button type="secondary" size="compact" (onClick)="toggleRequireModal()"
        >Back</goab-button
      >
      <goab-button type="primary" size="compact" (onClick)="toggleRequireModal()"
        >Continue</goab-button
      >
    </goab-button-group>
  </ng-template>
</goab-modal>

// apps/prs/react/src/routes/docs/modal/modal.tsx
import { useState } from "react";
import {
  GoabButton,
  GoabButtonGroup,
  GoabDropdown,
  GoabDropdownItem,
  GoabFormItem,
  GoabInput,
  GoabModal,
  GoabTextArea,
} from "@abgov/react-components";

export function DocsModalRoute() {
  const [basicOpen, setBasicOpen] = useState(false);
  const [dismissableOpen, setDismissableOpen] = useState(false);
  const [destructiveOpen, setDestructiveOpen] = useState(false);
  const [importantOpen, setImportantOpen] = useState(false);
  const [infoOpen, setInfoOpen] = useState(false);
  const [successOpen, setSuccessOpen] = useState(false);
  const [eventOpen, setEventOpen] = useState(false);
  const [wideOpen, setWideOpen] = useState(false);

  // Add another item
  const [addItemOpen, setAddItemOpen] = useState(false);
  const [type, setType] = useState<string>();
  const [name, setName] = useState<string>();
  const [description, setDescription] = useState<string>();

  // Destructive
  const [deleteOpen, setDeleteOpen] = useState(false);

  // Navigate away
  const [navigateOpen, setNavigateOpen] = useState(false);
  const handleChangeRoute = () => {
    setNavigateOpen(false);
    console.log("Navigating to new route...");
  };

  // Require action
  const [requireOpen, setRequireOpen] = useState(false);

  const handleConfirm = () => setBasicOpen(false);
  const handleDelete = () => setDestructiveOpen(false);
  const handleExtend = () => setImportantOpen(false);

  return (
    <div>
      <h2>Modal</h2>

      <h3>Basic modal</h3>
      <GoabButton onClick={() => setBasicOpen(true)}>Open basic modal</GoabButton>
      <GoabModal heading="Confirm action" open={basicOpen}>
        <p>Are you sure you want to proceed with this action?</p>
        <GoabButtonGroup alignment="end" mt="l">
          <GoabButton type="secondary" size="compact" onClick={() => setBasicOpen(false)}>Cancel</GoabButton>
          <GoabButton size="compact" onClick={handleConfirm}>Confirm</GoabButton>
        </GoabButtonGroup>
      </GoabModal>

      <h3>Dismissable</h3>
      <GoabButton onClick={() => setDismissableOpen(true)}>Open dismissable modal</GoabButton>
      <GoabModal heading="Information" open={dismissableOpen} onClose={() => setDismissableOpen(false)}>
        <p>You can close this modal with the X button or by clicking the backdrop.</p>
      </GoabModal>

      <h3>Destructive action</h3>
      <GoabButton onClick={() => setDestructiveOpen(true)}>Open destructive modal</GoabButton>
      <GoabModal heading="Are you sure you want to delete this item?" open={destructiveOpen} calloutVariant="emergency">
        <p>This action cannot be undone. The item will be permanently removed.</p>
        <GoabButtonGroup alignment="end" mt="l">
          <GoabButton type="secondary" size="compact" onClick={() => setDestructiveOpen(false)}>Cancel</GoabButton>
          <GoabButton variant="destructive" size="compact" onClick={handleDelete}>Delete</GoabButton>
        </GoabButtonGroup>
      </GoabModal>

      <h3>Important callout</h3>
      <GoabButton onClick={() => setImportantOpen(true)}>Open important modal</GoabButton>
      <GoabModal heading="Your session is about to expire" open={importantOpen} calloutVariant="important">
        <p>You will be logged out in 5 minutes due to inactivity.</p>
        <GoabButtonGroup alignment="end" mt="l">
          <GoabButton size="compact" onClick={handleExtend}>Stay logged in</GoabButton>
        </GoabButtonGroup>
      </GoabModal>

      <h3>Information callout</h3>
      <GoabButton onClick={() => setInfoOpen(true)}>Open info modal</GoabButton>
      <GoabModal heading="New features available" open={infoOpen} calloutVariant="information" onClose={() => setInfoOpen(false)}>
        <p>We have updated the application with new features. Review the changes to get started.</p>
      </GoabModal>

      <h3>Success callout</h3>
      <GoabButton onClick={() => setSuccessOpen(true)}>Open success modal</GoabButton>
      <GoabModal heading="Application submitted" open={successOpen} calloutVariant="success" onClose={() => setSuccessOpen(false)}>
        <p>Your application has been successfully submitted. You will receive a confirmation email shortly.</p>
      </GoabModal>

      <h3>Event callout</h3>
      <GoabButton onClick={() => setEventOpen(true)}>Open event modal</GoabButton>
      <GoabModal heading="Scheduled maintenance" open={eventOpen} calloutVariant="event" onClose={() => setEventOpen(false)}>
        <p>The system will be unavailable on March 28 from 10:00 PM to 2:00 AM for scheduled maintenance.</p>
      </GoabModal>

      <h3>Custom width</h3>
      <GoabButton onClick={() => setWideOpen(true)}>Open wide modal</GoabButton>
      <GoabModal heading="Wide modal" open={wideOpen} maxWidth="80ch" onClose={() => setWideOpen(false)}>
        <p>This modal has a wider maximum width for more content.</p>
      </GoabModal>

      <h2>Examples</h2>

      <h3>Add another item in a modal</h3>
      <GoabButton type="tertiary" leadingIcon="add" onClick={() => setAddItemOpen(true)}>
        Add another item
      </GoabButton>
      <GoabModal
        heading="Add a new item"
        open={addItemOpen}
        actions={
          <GoabButtonGroup alignment="end">
            <GoabButton type="tertiary" size="compact" onClick={() => setAddItemOpen(false)}>
              Cancel
            </GoabButton>
            <GoabButton type="primary" size="compact" onClick={() => setAddItemOpen(false)}>
              Save new item
            </GoabButton>
          </GoabButtonGroup>
        }
      >
        <p>Fill in the information to create a new item</p>
        <GoabFormItem label="Type" mt="l">
          <GoabDropdown onChange={(e) => setType(e.value)} value={type}>
            <GoabDropdownItem value="1" label="Option 1" />
            <GoabDropdownItem value="2" label="Option 2" />
          </GoabDropdown>
        </GoabFormItem>
        <GoabFormItem label="Name" mt="l">
          <GoabInput onChange={(e) => setName(e.value)} value={name} name="name" width="100%" />
        </GoabFormItem>
        <GoabFormItem label="Description" mt="l">
          <GoabTextArea
            name="description"
            rows={3}
            width="100%"
            onChange={(e) => setDescription(e.value)}
            value={description}
          />
        </GoabFormItem>
      </GoabModal>

      <h3>Confirm a destructive action</h3>
      <GoabButton type="tertiary" leadingIcon="trash" onClick={() => setDeleteOpen(true)}>
        Delete record
      </GoabButton>
      <GoabModal
        heading="Are you sure you want to delete this record?"
        open={deleteOpen}
        onClose={() => setDeleteOpen(false)}
        actions={
          <GoabButtonGroup alignment="end">
            <GoabButton type="tertiary" size="compact" onClick={() => setDeleteOpen(false)}>
              Cancel
            </GoabButton>
            <GoabButton
              type="primary"
              variant="destructive"
              size="compact"
              onClick={() => setDeleteOpen(false)}
            >
              Delete record
            </GoabButton>
          </GoabButtonGroup>
        }
      >
        <p>This action cannot be undone.</p>
      </GoabModal>

      <h3>Confirm before navigating away</h3>
      <GoabButton onClick={() => setNavigateOpen(true)}>Open</GoabButton>
      <GoabModal
        heading="Are you sure you want to change route?"
        open={navigateOpen}
        onClose={() => setNavigateOpen(false)}
        actions={
          <GoabButtonGroup alignment="end">
            <GoabButton type="secondary" size="compact" onClick={() => setNavigateOpen(false)}>
              Cancel
            </GoabButton>
            <GoabButton type="primary" size="compact" onClick={handleChangeRoute}>
              Change route
            </GoabButton>
          </GoabButtonGroup>
        }
      />

      <h3>Require user action before continuing</h3>
      <GoabButton onClick={() => setRequireOpen(true)}>Open Basic Modal</GoabButton>
      <GoabModal
        heading="Are you sure you want to continue?"
        open={requireOpen}
        onClose={() => setRequireOpen(false)}
        actions={
          <GoabButtonGroup alignment="end">
            <GoabButton type="secondary" size="compact" onClick={() => setRequireOpen(false)}>
              Back
            </GoabButton>
            <GoabButton type="primary" size="compact" onClick={() => setRequireOpen(false)}>
              Continue
            </GoabButton>
          </GoabButtonGroup>
        }
      >
        <p>You cannot return to this page.</p>
      </GoabModal>
    </div>
  );
}
