// apps/prs/react/src/routes/features/feat1741.tsx
import { GoabBlock, GoabIcon, GoabText } from "@abgov/react-components";

export function Feat1741Route() {
  return (
    <div>
      <GoabText tag="h1" mt="m">
        Feature #1741: Icon aria-hidden label
      </GoabText>

      <GoabText tag="h2">Test Cases</GoabText>

      <GoabText tag="p">
        Test both icons with a screen reader. The 1st one has ariaLabel set to "Applicaton
        saved icon" and it shouldn't be read. The second one has ariaLabel set to
        "Important information" and it should be read.
      </GoabText>

      <GoabText tag="h3">Test 1: Decorative icon is hidden</GoabText>

      <GoabBlock direction="row" alignment="center">
        <GoabIcon
          type="checkmark-circle"
          ariaHidden={true}
          ariaLabel="Application saved icon"
        />
        <span>Application saved</span>
      </GoabBlock>

      <GoabText tag="h3">Test 2: Default icon remains accessible</GoabText>
      <GoabIcon type="information-circle" ariaLabel="Important information" />
    </div>
  );
}

export default Feat1741Route;

// apps/prs/angular/src/routes/features/feat1741/feat1741.component.ts
import { Component } from "@angular/core";
import { GoabBlock, GoabIcon, GoabText } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-feat1741",
  templateUrl: "./feat1741.component.html",
  imports: [GoabBlock, GoabIcon, GoabText],
})
export class Feat1741Component {}

<goab-text tag="h1" mt="m">Feature #1741: Icon aria-hidden label</goab-text>

<goab-text tag="h2">Test Cases</goab-text>

<goab-text tag="p">
  Test both icons with a screen reader. The 1st one has ariaLabel set to "Applicaton saved
  icon" and it shouldn't be read. The second one has ariaLabel set to "Important
  information" and it should be read.
</goab-text>

<goab-text tag="h3">Test 1: Decorative icon is hidden</goab-text>

<goab-block direction="row" alignment="center">
  <goab-icon
    type="checkmark-circle"
    [ariaHidden]="true"
    ariaLabel="Application saved icon"
  />
  <span>Application saved</span>
</goab-block>

<goab-text tag="h3">Test 2: Default icon remains accessible</goab-text>
<goab-icon type="information-circle" ariaLabel="Important information" />
