// libs/angular-components/src/lib/components/side-menu-group/side-menu-group.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";
import { GoabIconType } from "@abgov/ui-components-common";
import { GoabBaseComponent } from "../base.component";

@Component({
  standalone: true,
  selector: "goab-side-menu-group",
  template: `
    @if (isReady) {
      <goa-side-menu-group
        [attr.heading]="heading"
        [attr.testid]="testId"
        [attr.icon]="icon"
        [attr.mt]="mt"
        [attr.mb]="mb"
        [attr.ml]="ml"
        [attr.mr]="mr"
      >
        <ng-content />
      </goa-side-menu-group>
    }
  `,

  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabSideMenuGroup extends GoabBaseComponent implements OnInit {
  isReady = false;
  /** The heading text for the menu group. */
  @Input({ required: true }) heading!: string;
  /** Icon displayed alongside the heading. */
  @Input() icon?: GoabIconType;

  constructor(private cdr: ChangeDetectorRef) {
    super();
  }

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    });
  }
}

// libs/vue-components/src/lib/side-menu-group/side-menu-group.vue
<script setup lang="ts">
import type { GoabIconType, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required The heading text for the menu group. */
  heading: string;
  /** Icon displayed alongside the heading.  @default null */
  icon?: GoabIconType;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Sets the mt.  @default null */
  mt?: Spacing;
  /** Sets the mr.  @default null */
  mr?: Spacing;
  /** Sets the mb.  @default null */
  mb?: Spacing;
  /** Sets the ml.  @default null */
  ml?: Spacing;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props);
</script>

<template>
  <goa-side-menu-group v-bind="wcProps">
    <slot />
  </goa-side-menu-group>
</template>
