// libs/react-components/src/experimental/side-menu-group/side-menu-group.tsx
import { ReactNode, type JSX } from "react";
import { GoabIconType, Margins } from "@abgov/ui-components-common";

interface WCProps extends Margins {
  heading: string;
  icon?: GoabIconType;
  testid?: string;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-side-menu-group": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoabxSideMenuGroupProps extends Margins {
  /** The heading text for the menu group. */
  heading: string;
  /** Icon displayed alongside the heading. */
  icon?: GoabIconType;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
  children?: ReactNode;
  version?: string;
}

export function GoabxSideMenuGroup({
  heading,
  icon,
  testId,
  children,
  mt,
  mr,
  mb,
  ml,
  version = "2",
}: GoabxSideMenuGroupProps): JSX.Element {
  return (
    <goa-side-menu-group
      heading={heading}
      icon={icon}
      testid={testId}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
      version={version}
    >
      {children}
    </goa-side-menu-group>
  );
}

export default GoabxSideMenuGroup;

// libs/vue-components/src/lib/side-menu-group/side-menu-group.vue
<script setup lang="ts">
import type { GoabIconType, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required The heading text for the menu group. */
  heading: string;
  /** Icon displayed alongside the heading.  @default null */
  icon?: GoabIconType;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Sets the mt.  @default null */
  mt?: Spacing;
  /** Sets the mr.  @default null */
  mr?: Spacing;
  /** Sets the mb.  @default null */
  mb?: Spacing;
  /** Sets the ml.  @default null */
  ml?: Spacing;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props);
</script>

<template>
  <goa-side-menu-group v-bind="wcProps">
    <slot />
  </goa-side-menu-group>
</template>
