// apps/prs/angular/src/routes/bugs/bug2378/bug2378.component.ts
import { Component } from "@angular/core";
import { GoabAccordion, GoabDetails, GoabText } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug2378",
  templateUrl: "./bug2378.component.html",
  imports: [GoabAccordion, GoabDetails, GoabText],
})
export class Bug2378Component {}

<main>
  <goab-text tag="h1">Bug #2378: Expanded content is not read</goab-text>

  <goab-text tag="h3">Details</goab-text>
  <goab-details heading="Supporting details">
    <goab-text tag="p">
      This Details content should be announced when the component expands.
    </goab-text>
  </goab-details>

  <goab-text tag="h3">Accordion</goab-text>
  <goab-accordion heading="Supporting information">
    <goab-text tag="p">
      This Accordion content should be announced when the component expands.
    </goab-text>
  </goab-accordion>
</main>

// apps/prs/react/src/routes/bugs/bug2378.tsx
import { GoabAccordion, GoabDetails, GoabText } from "@abgov/react-components";

export function Bug2378Route() {
  return (
    <main>
      <GoabText tag="h1">Bug #2378: Expanded content is not read</GoabText>

      <GoabText tag="h3">Details</GoabText>
      <GoabDetails heading="Supporting details">
        <GoabText tag="p">
          This Details content should be announced when the component expands.
        </GoabText>
      </GoabDetails>

      <GoabText tag="h3">Accordion</GoabText>
      <GoabAccordion heading="Supporting information">
        <GoabText tag="p">
          This Accordion content should be announced when the component expands.
        </GoabText>
      </GoabAccordion>
    </main>
  );
}
