// apps/prs/angular/src/routes/bugs/bug3323/bug3323.component.ts
import { Component } from "@angular/core";
import {
  GoabButton,
  GoabCallout,
  GoabContainer,
  GoabIcon,
  GoabTooltip,
  GoabText,
  GoabGrid,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3323",
  templateUrl: "./bug3323.component.html",
  imports: [
    GoabButton,
    GoabCallout,
    GoabContainer,
    GoabIcon,
    GoabTooltip,
    GoabText,
    GoabGrid,
  ],
})
export class Bug3323Component {
  readonly supportsCssAnchorPositioning =
    typeof CSS !== "undefined" &&
    typeof CSS.supports === "function" &&
    CSS.supports("anchor-name: --goa-tooltip-target");
}

<goab-text tag="h1" mt="m" mb="s">Fix 3323 - Tooltip with fixed positioning</goab-text>
<goab-text>
  CSS anchor positioning support in this browser:
  <strong>{{ supportsCssAnchorPositioning ? "Supported" : "Not supported" }}</strong
  >.
</goab-text>

<goab-text tag="h2" mt="m" mb="s">Tooltip in callout</goab-text>
<goab-callout emphasis="low">
  <goab-tooltip content="This tooltip shoudn't be cut off">
    <goab-button type="tertiary" size="compact">Hover me</goab-button>
  </goab-tooltip>
</goab-callout>

<goab-text tag="h2" mt="m" mb="s">Tooltip in container</goab-text>
<goab-container>
  <goab-tooltip content="This tooltip shoudn't be cut off">
    <goab-icon type="information-circle"></goab-icon>
  </goab-tooltip>
</goab-container>

<goab-text tag="h2" mt="m" mb="s">Basic tooltip</goab-text>
<goab-tooltip content="Additional information about this item">
  <goab-button type="secondary">Hover me</goab-button>
</goab-tooltip>

<goab-text tag="h2" mt="m" mb="s">Horizontal alignment</goab-text>
<goab-grid minChildWidth="60px">
  <goab-tooltip content="Left aligned tooltip" hAlign="left">
    <goab-icon type="information-circle" />
  </goab-tooltip>
  <goab-tooltip content="Center aligned tooltip" hAlign="center">
    <goab-icon type="information-circle" />
  </goab-tooltip>
  <goab-tooltip content="Right aligned tooltip" hAlign="right">
    <goab-icon type="information-circle" />
  </goab-tooltip>
</goab-grid>

<goab-text tag="h2" mt="m" mb="s"> Long Tooltip </goab-text>
<goab-tooltip
  content="This is a deliberately long tooltip message that should render at a readable width, wrap naturally, and not collapse into a one-pixel column on first hover."
  maxWidth="320px"
>
  <goab-button type="tertiary" size="compact"> Long tooltip </goab-button>
</goab-tooltip>

// apps/prs/react/src/routes/bugs/bug3323.tsx
import type { CSSProperties } from "react";
import {
  GoabButton,
  GoabCallout,
  GoabTooltip,
  GoabIcon,
  GoabContainer,
  GoabText,
  GoabGrid,
} from "@abgov/react-components";

const supportsCssAnchorPositioning =
  typeof CSS !== "undefined" &&
  typeof CSS.supports === "function" &&
  CSS.supports("anchor-name: --goa-tooltip-target");

export function Bug3323Route() {
  return (
    <>
      <GoabText tag="h1" mt="m" mb="s">
        Fix 3323 - Tooltip with fixed positioning
      </GoabText>
      <GoabText>
        CSS anchor positioning support in this browser:{" "}
        <strong>{supportsCssAnchorPositioning ? "Supported" : "Not supported"}</strong>.
      </GoabText>

      <GoabText tag="h2" mt="l" mb="s">
        Tooltip in callout
      </GoabText>
      <GoabCallout emphasis="low">
        <GoabTooltip content="This tooltip shoudn't be cut off">
          <GoabButton type="tertiary" size="compact">
            Hover me
          </GoabButton>
        </GoabTooltip>
      </GoabCallout>

      <GoabText tag="h2" mt="l" mb="s">
        Tooltip in container
      </GoabText>
      <GoabContainer>
        <GoabTooltip content="This tooltip shoudn't be cut off">
          <GoabIcon type="information-circle" />
        </GoabTooltip>
      </GoabContainer>

      <GoabText tag="h2" mt="l" mb="s">
        Basic tooltip
      </GoabText>
      <GoabTooltip content="Additional information about this item">
        <GoabButton type="secondary">Hover me</GoabButton>
      </GoabTooltip>

      <GoabText tag="h2" mt="l" mb="s">
        Horizontal alignment
      </GoabText>
      <GoabGrid minChildWidth="60px">
        <GoabTooltip content="Left aligned tooltip" hAlign="left">
          <GoabIcon type="information-circle" />
        </GoabTooltip>
        <GoabTooltip content="Center aligned tooltip" hAlign="center">
          <GoabIcon type="information-circle" />
        </GoabTooltip>
        <GoabTooltip content="Right aligned tooltip" hAlign="right">
          <GoabIcon type="information-circle" />
        </GoabTooltip>
      </GoabGrid>

      <GoabText tag="h2" mt="l" mb="s">
        Long Tooltip
      </GoabText>
      <GoabTooltip
        content="This is a deliberately long tooltip message that should render at a readable width, wrap naturally, and not collapse into a one-pixel column on first hover."
        maxWidth="320px"
      >
        <GoabButton type="tertiary" size="compact">
          Long tooltip
        </GoabButton>
      </GoabTooltip>
    </>
  );
}
