// apps/prs/angular/src/routes/bugs/3627/bug3627.component.ts
import { Component } from "@angular/core";
import { GoabContainer } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3627",
  templateUrl: "./bug3627.component.html",
  imports: [GoabContainer],
})
export class Bug3627Component {}

<div>
  <h1>3627 - Container refinements</h1>
  <p>
    <a
      href="https://github.com/GovAlta/ui-components/issues/3627"
      target="_blank"
      rel="noopener"
    >
      View on GitHub
    </a>
  </p>

  <h2>Test 1: Basic containers (shadow should be removed)</h2>
  <goab-container [title]="interactiveTitle" mb="l">
    <p>Check for bottom shadow. Should be none.</p>
  </goab-container>
  <ng-template #interactiveTitle>Interactive (default)</ng-template>

  <goab-container [title]="nonInteractiveTitle" type="non-interactive" mb="l">
    <p>Non-interactive container for comparison.</p>
  </goab-container>
  <ng-template #nonInteractiveTitle>Non-interactive</ng-template>

  <div style="display: flex; gap: 1rem; margin-bottom: 2rem">
    <goab-container [title]="thickTitle" accent="thick">
      <p>Accent: thick</p>
    </goab-container>
    <ng-template #thickTitle>Thick accent</ng-template>

    <goab-container [title]="thinTitle" accent="thin">
      <p>Accent: thin</p>
    </goab-container>
    <ng-template #thinTitle>Thin accent</ng-template>

    <goab-container accent="filled">
      <p>Accent: filled</p>
    </goab-container>
  </div>

  <h2>Test 2: Status type containers (silently undocumented)</h2>
  <p>These remain functional but are removed from docs.</p>
  <goab-container [title]="infoTitle" type="info" mb="l">
    <p>Type: info</p>
  </goab-container>
  <ng-template #infoTitle>Info</ng-template>

  <goab-container [title]="errorTitle" type="error" mb="l">
    <p>Type: error</p>
  </goab-container>
  <ng-template #errorTitle>Error</ng-template>

  <goab-container [title]="successTitle" type="success" mb="l">
    <p>Type: success</p>
  </goab-container>
  <ng-template #successTitle>Success</ng-template>

  <goab-container [title]="importantTitle" type="important" mb="l">
    <p>Type: important</p>
  </goab-container>
  <ng-template #importantTitle>Important</ng-template>
</div>

// apps/prs/react/src/routes/bugs/bug3627.tsx
import {
  GoabBlock,
  GoabText,
  GoabDivider,
  GoabDetails,
  GoabLink,
  GoabContainer,
} from "@abgov/react-components";

export function Bug3627Route() {
  return (
    <div>
      <GoabText tag="h1" mt="m">
        Bug #3627: Container refinements
      </GoabText>

      <GoabBlock>
        <GoabLink trailingIcon="open">
          <a
            href="https://github.com/GovAlta/ui-components/issues/3627"
            target="_blank"
            rel="noopener"
          >
            View on GitHub
          </a>
        </GoabLink>

        <GoabDetails heading="Issue Description">
          <GoabText tag="p">
            Discrepancies between Container browser implementation and Figma design specs.
            1) Remove the bottom shadow from the container (Figma has no shadow). 2)
            Quietly remove documentation for info, error, success, and important types.
            Keep the component code so existing implementations don't break. These types
            duplicate Callout functionality and have accessibility concerns.
          </GoabText>
        </GoabDetails>
      </GoabBlock>

      <GoabDivider mt="l" mb="l" />

      <GoabText tag="h2">Test Cases</GoabText>

      <GoabText tag="h3">
        Test 1: Basic Container (check for bottom shadow in V2)
      </GoabText>
      <GoabText tag="p">
        Inspect the container below. In V2 tokens, the bottom shadow should be removed per
        Figma. Check DevTools for box-shadow on the container element.
      </GoabText>
      <GoabContainer heading="Interactive (default)" mb="l">
        <GoabText tag="p">
          This is a basic interactive container. Inspect whether there is a bottom shadow
          applied. The shadow should be removed in V2.
        </GoabText>
      </GoabContainer>

      <GoabContainer heading="Non-interactive" type="non-interactive" mb="l">
        <GoabText tag="p">Non-interactive container for comparison.</GoabText>
      </GoabContainer>

      <GoabBlock gap="m" direction="row" mb="l">
        <GoabContainer heading="Thick accent" accent="thick">
          <GoabText tag="p">Accent: thick</GoabText>
        </GoabContainer>
        <GoabContainer heading="Thin accent" accent="thin">
          <GoabText tag="p">Accent: thin</GoabText>
        </GoabContainer>
        <GoabContainer accent="filled">
          <GoabText tag="p">Accent: filled (no heading bar)</GoabText>
        </GoabContainer>
      </GoabBlock>

      <GoabDivider mt="l" mb="l" />

      <GoabText tag="h3">
        Test 2: Status type containers (to be silently undocumented)
      </GoabText>
      <GoabText tag="p">
        These status types (info, error, success, important) will be silently removed from
        docs but remain functional. Shown here for reference and regression testing.
      </GoabText>

      <GoabContainer heading="Info container" type="info" mb="l">
        <GoabText tag="p">Type: info</GoabText>
      </GoabContainer>

      <GoabContainer heading="Error container" type="error" mb="l">
        <GoabText tag="p">Type: error</GoabText>
      </GoabContainer>

      <GoabContainer heading="Success container" type="success" mb="l">
        <GoabText tag="p">Type: success</GoabText>
      </GoabContainer>

      <GoabContainer heading="Important container" type="important" mb="l">
        <GoabText tag="p">Type: important</GoabText>
      </GoabContainer>
    </div>
  );
}

export default Bug3627Route;
