// apps/prs/angular/src/routes/bugs/3635/bug3635.component.ts
import { Component } from "@angular/core";
import {
  GoabInput,
  GoabFormItem,
  GoabText,
  GoabInputOnBlurDetail,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3635",
  templateUrl: "./bug3635.component.html",
  imports: [GoabInput, GoabText, GoabFormItem],
})
export class Bug3635Component {
  inputValue = "";

  inputBlur(details: GoabInputOnBlurDetail) {
    this.inputValue = details.value;
  }
}

<goab-text tag="h1">Bug 3635 - Input: Leading icon color</goab-text>

<goab-form-item label="Leading Icon Input" mb="xl">
  <goab-input
    name="autocomplete-test-v2"
    leadingIcon="search"
    (onBlur)="inputBlur($event)"
    [value]="inputValue"
  />
</goab-form-item>
<goab-form-item label="Leading Icon Input - Compact" mb="xl">
  <goab-input
    name="autocomplete-test-v2"
    leadingIcon="search"
    size="compact"
    (onBlur)="inputBlur($event)"
    [value]="inputValue"
  />
</goab-form-item>

// apps/prs/react/src/routes/bugs/bug3635.tsx
import { GoabText, GoabFormItem, GoabInput } from "@abgov/react-components";
import { GoabInputOnBlurDetail } from "@abgov/ui-components-common";
import { useState } from "react";

export function Bug3635Route() {
  const [inputValue, setInputValue] = useState<string>("");

  function inputBlur(details: GoabInputOnBlurDetail) {
    setInputValue(details.value);
  }

  return (
    <>
      <GoabText tag="h1">Bug 3635 - Input: Leading icon color</GoabText>
      <GoabFormItem label="Leading Icon Input" mb="xl">
        <GoabInput
          name="autocomplete-test-v2"
          leadingIcon="search"
          onBlur={(e) => inputBlur(e)}
          value={inputValue}
        />
      </GoabFormItem>
      <GoabFormItem label="Leading Icon Input - Compact" mb="xl">
        <GoabInput
          name="autocomplete-test-v2"
          size="compact"
          leadingIcon="search"
          onBlur={(e) => inputBlur(e)}
          value={inputValue}
        />
      </GoabFormItem>
    </>
  );
}
