// apps/prs/react/src/routes/features/feat3398.tsx
import React, { useState } from "react";
import {
  GoabButton,
  GoabText,
  GoabWorkSideMenu,
  GoabWorkSideMenuGroup,
  GoabWorkSideMenuItem,
} from "@abgov/react-components";

export function Feat3398Route() {
  const [groupOpen, setGroupOpen] = useState(false);

  return (
    <div>
      <GoabText tag="h1">Feature 3398: Work Side Menu Group open prop</GoabText>
      <GoabText>
        Use the button below to toggle the side menu group open and closed.
      </GoabText>

      <GoabText tag="h2">Scenario 1: Open and close a group</GoabText>
      <GoabText>The button should toggle the group open and closed.</GoabText>

      <div style={{ display: "flex", height: "310px", overflow: "hidden" }}>
        <GoabWorkSideMenu
          heading="Design System"
          url="/"
          userName="John Doe"
          userSecondaryText="john.doe@example.com"
          open={true}
          primaryContent={
            <>
              <GoabButton
                size="compact"
                type="secondary"
                width="100%"
                onClick={() => setGroupOpen(!groupOpen)}
              >
                {groupOpen ? "Close group" : "Open group"}
              </GoabButton>
              <GoabWorkSideMenuGroup
                heading="Get Started"
                icon="school"
                open={groupOpen}
              >
                <GoabWorkSideMenuItem
                  label="Early Adopters"
                  url="/get-started/early-adopters"
                />
                <GoabWorkSideMenuItem label="Designers" url="/get-started/designers" />
                <GoabWorkSideMenuItem label="Developers" url="/get-started/developers" />
              </GoabWorkSideMenuGroup>
            </>
          }
        />
      </div>

      <GoabText tag="h2">Scenario 2: Open a group with a current item</GoabText>
      <GoabText>
        The <b>Features</b> group should be open because it has a current menu item. The{" "}
        <b>Bugs</b> group should remain closed.
      </GoabText>

      <div style={{ display: "flex", height: "500px", overflow: "hidden" }}>
        <GoabWorkSideMenu
          heading="UI Components Playground"
          url="/"
          userName="John Doe"
          userSecondaryText="john.doe@example.com"
          open={true}
          primaryContent={
            <>
              <GoabWorkSideMenuGroup heading="Enhancements" icon="rocket">
                <GoabWorkSideMenuItem label="Item 1" url="/items/1" />
                <GoabWorkSideMenuGroup heading="Features" icon="star">
                  <GoabWorkSideMenuItem label="1908" url="/features/1908" />
                  <GoabWorkSideMenuItem label="3398" url="/features/3398" />
                </GoabWorkSideMenuGroup>
              </GoabWorkSideMenuGroup>
              <GoabWorkSideMenuGroup heading="Bugs" icon="bug">
                <GoabWorkSideMenuItem label="2152" url="/bugs/2152" />
                <GoabWorkSideMenuItem label="2331" url="/bugs/2331" />
              </GoabWorkSideMenuGroup>
            </>
          }
        />
      </div>
    </div>
  );
}

// apps/prs/angular/src/routes/features/feat3398/feat3398.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";
import {
  GoabButton,
  GoabText,
  GoabWorkSideMenu,
  GoabWorkSideMenuGroup,
  GoabWorkSideMenuItem,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-feat3398",
  templateUrl: "./feat3398.component.html",
  imports: [
    CommonModule,
    GoabButton,
    GoabText,
    GoabWorkSideMenu,
    GoabWorkSideMenuGroup,
    GoabWorkSideMenuItem,
  ],
})
export class Feat3398Component {
  groupOpen = false;

  toggleGroup(): void {
    this.groupOpen = !this.groupOpen;
  }
}

<div>
  <goab-text tag="h1">Feature 3398: Work Side Menu Group open prop</goab-text>
  <goab-text>
    Use the button below to toggle the side menu group open and closed.
  </goab-text>

  <goab-text tag="h2">Scenario 1: Open and close a group</goab-text>
  <goab-text>The button should toggle the group open and closed.</goab-text>

  <div style="display: flex; height: 310px; overflow: hidden">
    <goabx-work-side-menu
      heading="Design System"
      url="/"
      userName="John Doe"
      userSecondaryText="john.doe@example.com"
      [open]="true"
      [primaryContent]="scenario1Template"
    ></goabx-work-side-menu>
  </div>

  <ng-template #scenario1Template>
    <goab-button size="compact" type="secondary" width="100%" (onClick)="toggleGroup()">
      {{ groupOpen ? "Close group" : "Open group" }}
    </goab-button>
    <goabx-work-side-menu-group heading="Get Started" icon="school" [open]="groupOpen">
      <goabx-work-side-menu-item
        label="Early Adopters"
        url="/get-started/early-adopters"
      />
      <goabx-work-side-menu-item label="Designers" url="/get-started/designers" />
      <goabx-work-side-menu-item label="Developers" url="/get-started/developers" />
    </goabx-work-side-menu-group>
  </ng-template>

  <goab-text tag="h2">Scenario 2: Open a group with a current item</goab-text>
  <goab-text>
    The <b>Features</b> group should be open because it has a current menu item. The
    <b>Bugs</b> group should remain closed.
  </goab-text>

  <div style="display: flex; height: 500px; overflow: hidden">
    <goabx-work-side-menu
      heading="UI Components Playground"
      url="/"
      userName="John Doe"
      userSecondaryText="john.doe@example.com"
      [open]="true"
      [primaryContent]="scenario2Template"
    ></goabx-work-side-menu>
  </div>

  <ng-template #scenario2Template>
    <goabx-work-side-menu-group heading="Features" icon="star">
      <goabx-work-side-menu-item label="1908" url="/features/1908" />
      <goabx-work-side-menu-item label="3398" url="/features/3398" />
    </goabx-work-side-menu-group>
    <goabx-work-side-menu-group heading="Bugs" icon="bug">
      <goabx-work-side-menu-item label="2152" url="/bugs/2152" />
      <goabx-work-side-menu-item label="2331" url="/bugs/2331" />
    </goabx-work-side-menu-group>
  </ng-template>
</div>
