// apps/react-demo/src/routes/dropdown.tsx
import * as React from "react";
import {
  GoAButton,
  GoADropdown,
  GoADropdownItem,
} from "@abgov/react-components";
import { useState } from "react";

export default function Dropdown() {
  const [selectedColor, setSelectedColor] = useState("green");
  function noop(_name: string, _value: string | string[]) {
    // do nothing
  }

  const provinces: string[] = [
    "BC",
    "Alberta",
    "Saskatchewan",
    "Manitoba",
    "Ontario",
    "Quebec",
  ];

  const cities: Record<string, string[]> = {
    BC: ["Vancouver", "Kelowna", "Fernie"],
    Alberta: ["Edmonton", "Calgary"],
    Saskatchewan: ["Regina", "Saskatoon"],
    Manitoba: ["Winnipeg"],
    Ontario: ["Toronto", "Ottawa"],
    Quebec: ["Montreal", "Quebec City"],
  };

  const [pcities, setPcities] = useState<string[]>([]);

  function selectProvince(_name: string, value: string | string[]) {
    if (typeof value === "string") setPcities(cities[value]);
  }

  function onChange(name: string, value: string | string[]) {
    setSelectedColor(value as string);
  }

  return (
    <>
      <h1>Dropdown</h1>

      <h2>Default</h2>
      <h4>Not Filterable</h4>
      <GoADropdown name="colors" placeholder="Select a color" onChange={noop}>
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>
      <h4>Filterable</h4>
      <GoADropdown
        filterable
        name="colors"
        placeholder="Select a color"
        onChange={noop}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>

      <h2>Disabled</h2>
      <h4>Not Filterable</h4>
      <GoADropdown
        name="colors"
        placeholder="Select a color"
        onChange={noop}
        disabled={true}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>
      <h4>Filterable</h4>
      <GoADropdown
        name="colors"
        filterable
        placeholder="Select a color"
        onChange={noop}
        disabled={true}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>
      <h2>
        Reactive Binding
        <GoAButton onClick={() => setSelectedColor("red")} type="tertiary">
          Change to red
        </GoAButton>
      </h2>
      <h4>Not Filterable</h4>
      <div>Selected Color: {selectedColor}</div>
      <br />
      <GoADropdown
        name="colors"
        placeholder="Select a color"
        onChange={onChange}
        value={selectedColor}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>
      <h4>Not Filterable</h4>
      <GoADropdown
        name="colors"
        placeholder="Select a color"
        onChange={onChange}
        value={selectedColor}
        filterable
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="value" value="blue" label="Blue" />
      </GoADropdown>

      <h2>Native</h2>
      <h4>Not Filterable</h4>
      <GoADropdown
        name="colors-native"
        placeholder="Select a user"
        value="green"
        native={true}
        onChange={noop}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>
      <h4>Filterable</h4>
      <GoADropdown
        name="colors-native"
        placeholder="Select a user"
        value="green"
        native={true}
        filterable
        onChange={noop}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>

      <h2>Error</h2>
      <h4>Not Filterable</h4>
      <GoADropdown
        name="colors2"
        placeholder="Select a user"
        error={true}
        value="green"
        onChange={noop}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>
      <h4>Filterable</h4>
      <GoADropdown
        name="colors2"
        placeholder="Select a user"
        error={true}
        filterable
        value="green"
        onChange={noop}
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>

      <h2>Dynamic</h2>
      <h4>Not Filterable</h4>
      <GoADropdown name="province" onChange={selectProvince}>
        {provinces.map((p) => (
          <GoADropdownItem key={p} value={p} label={p} />
        ))}
      </GoADropdown>

      <GoADropdown name="city" onChange={noop} placeholder="City">
        {pcities.map((p) => (
          <GoADropdownItem key={p} value={p} label={p} />
        ))}
      </GoADropdown>
      <h4>Filterable</h4>
      <GoADropdown name="province" filterable onChange={selectProvince}>
        {provinces.map((p) => (
          <GoADropdownItem key={p} value={p} label={p} />
        ))}
      </GoADropdown>

      <GoADropdown name="city" filterable onChange={noop} placeholder="City">
        {pcities.map((p) => (
          <GoADropdownItem key={p} value={p} label={p} />
        ))}
      </GoADropdown>

      <h2>Aria Label</h2>
      <h4>Not Filterable</h4>
      <GoADropdown
        name="aria"
        placeholder="Select a user"
        value="blue"
        onChange={noop}
        ariaLabel="Some random aria label"
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>
      <h4>Filterable</h4>
      <GoADropdown
        name="aria"
        placeholder="Select a user"
        value="blue"
        filterable
        onChange={noop}
        ariaLabel="Some random aria label"
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>

      <h2>Margin Spacing</h2>
      <h4>Not Filterable</h4>
      <GoADropdown
        name="colors"
        placeholder="Select a user"
        value="blue"
        onChange={noop}
        mt="m"
        mb="xs"
        ml="xl"
        mr="2xl"
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>

      <h4>Filterable</h4>
      <GoADropdown
        name="colors"
        placeholder="Select a user"
        value="blue"
        onChange={noop}
        mt="m"
        mb="xs"
        ml="xl"
        mr="2xl"
        filterable
      >
        <GoADropdownItem key="red" value="red" label="Red" />
        <GoADropdownItem key="green" value="green" label="Green" />
        <GoADropdownItem key="blue" value="blue" label="Blue" />
      </GoADropdown>
    </>
  );
}

// apps/angular-demo/src/app/dropdown/dropdown.component.ts
import { Component } from "@angular/core";
import { FormControl } from "@angular/forms";

@Component({
  selector: "abgov-dropdown",
  templateUrl: "./dropdown.component.html",
  styleUrls: ["./dropdown.component.css"],
})
export class DropdownComponent {
  colors: string[] = ["red", "green", "blue"];
  selectedColor = "red";
  boundVal = "";
  reactiveFormCtrl = new FormControl({ value: "green", disabled: true });

  color = new FormControl("green");

  provinces: string[] = [
    "BC",
    "Alberta",
    "Saskatchewan",
    "Manitoba",
    "Ontario",
    "Quebec",
  ];

  /* eslint-disable @typescript-eslint/naming-convention */
  cities: Record<string, string[]> = {
    BC: ["Vancouver", "Kelowna", "Fernie"],
    Alberta: ["Edmonton", "Calgary"],
    Saskatchewan: ["Regina", "Saskatoon"],
    Manitoba: ["Winnipeg"],
    Ontario: ["Toronto", "Ottawa"],
    Quebec: ["Montreal", "Quebec City"],
  };

  pcities: string[] = [];

  isMobile = window.matchMedia("(any-pointer:coarse)").matches;
  disabled = false;

  groups = [
    {
      name: "Fruits",
      value: "banana",
      items: [{ value: "apple" }, { value: "orange" }, { value: "banana" }],
    },
    {
      name: "Vegetables",
      value: "carrot",
      items: [{ value: "brocolli" }, { value: "carrot" }, { value: "spinach" }],
    },
  ];

  constructor() {}

  selectColor(event: any) {
    console.log("Select Color", event);
    this.selectedColor = event.detail.value;
  }

  selectProvince(event: any) {
    this.pcities = this.cities[event.detail.value];
  }

  handleSelectChange(event: any) {
    console.log("select change", event.detail.value, event);
  }
}

<h1>Dropdown</h1>

<h2>Mobile</h2>
<h4>Not Filter</h4>
<goa-dropdown [native]="isMobile" value="green">
  <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
  <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
  <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
</goa-dropdown>

<h4>Filterable</h4>
<goa-dropdown [native]="isMobile" filterable="true" value="green">
  <goa-dropdown-item value="red" label="Red"></goa-dropdown-item>
  <goa-dropdown-item value="green" label="Green"></goa-dropdown-item>
  <goa-dropdown-item value="blue" label="Blue"></goa-dropdown-item>
</goa-dropdown>

<hr />
<h2>Others</h2>
<h4>Not Filter</h4>
<goa-dropdown native="true">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="colors1" native="true" value="">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="colors1" placeholder="Select">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="colors1" value="red">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<h4>Filterable</h4>
<goa-dropdown native="true" filterable="true">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="colors1" native="true" value="" filterable="true">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="colors1" placeholder="Select" filterable="true">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="colors1" value="red" filterable="true">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>

<hr />
<h2>Dynamic</h2>
<h4>Not Filter</h4>
<goa-dropdown name="province" (_change)="selectProvince($event)">
  <goa-dropdown-item
    *ngFor="let name of provinces"
    [attr.name]="name"
    [value]="name"
    [label]="name"
  >
  </goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="city" placeholder="Select a city">
  <goa-dropdown-item
    *ngFor="let name of pcities"
    [attr.name]="name"
    [value]="name"
    [label]="name"
  >
  </goa-dropdown-item>
</goa-dropdown>

<hr />
<h4>Filterable</h4>
<goa-dropdown
  name="province"
  (_change)="selectProvince($event)"
  filterable="true"
>
  <goa-dropdown-item
    *ngFor="let name of provinces"
    [attr.name]="name"
    [value]="name"
    [label]="name"
  >
  </goa-dropdown-item>
</goa-dropdown>

<goa-dropdown name="city" placeholder="Select a city" filterable="true">
  <goa-dropdown-item
    *ngFor="let name of pcities"
    [attr.name]="name"
    [value]="name"
    [label]="name"
  >
  </goa-dropdown-item>
</goa-dropdown>

<hr />
<h2>Binding</h2>
<h4>Not Filterable</h4>
<div>Selected Color: {{ boundVal }}</div>
<goa-dropdown
  goaValue
  name="boundColor"
  [(ngModel)]="boundVal"
  [value]="selectedColor"
  placeholder="Select a color"
>
  <goa-dropdown-item
    value="red"
    name="boundColor"
    label="Red"
  ></goa-dropdown-item>
  <goa-dropdown-item
    value="green"
    name="boundColor"
    label="Green"
  ></goa-dropdown-item>
  <goa-dropdown-item
    value="blue"
    name="boundColor"
    label="Blue"
  ></goa-dropdown-item>
</goa-dropdown>

<h4>Filterable</h4>
<div>Selected Color: {{ boundVal }}</div>
<goa-dropdown
  goaValue
  name="boundColor"
  [(ngModel)]="boundVal"
  [value]="selectedColor"
  filterable="true"
  placeholder="Select a color"
>
  <goa-dropdown-item
    value="red"
    name="boundColor"
    label="Red"
  ></goa-dropdown-item>
  <goa-dropdown-item
    value="green"
    name="boundColor"
    label="Green"
  ></goa-dropdown-item>
  <goa-dropdown-item
    value="blue"
    name="boundColor"
    label="Blue"
  ></goa-dropdown-item>
</goa-dropdown>

<hr />
<h1>Margin Spacing</h1>
<h4>Not Filterable</h4>
<goa-dropdown
  name="colors"
  placeholder="Select a user"
  [value]="selectedColor"
  (_change)="selectColor($event)"
  mt="m"
  mb="xs"
  ml="xl"
  mr="2xl"
>
  <goa-dropdown-item
    name="colors"
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  >
  </goa-dropdown-item>
</goa-dropdown>
<h4>Filterable</h4>
<goa-dropdown
  name="colors"
  placeholder="Select a user"
  [value]="selectedColor"
  (_change)="selectColor($event)"
  mt="m"
  mb="xs"
  ml="xl"
  mr="2xl"
  filterable="true"
>
  <goa-dropdown-item
    name="colors"
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  >
  </goa-dropdown-item>
</goa-dropdown>

<hr />
<h2>Reactive Binding</h2>
<h4>Not Filterable</h4>
<div>Selected Color: {{ reactiveFormCtrl.value }}</div>
<goa-button (_click)="reactiveFormCtrl.setValue('red')" type="tertiary"
  >Update to red</goa-button
>
<br />
<goa-dropdown
  goaValue
  native="true"
  name="boundColors2"
  [formControl]="reactiveFormCtrl"
  [value]="reactiveFormCtrl.value"
>
  <goa-dropdown-item
    name="boundColors2"
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  >
  </goa-dropdown-item>
</goa-dropdown>
&nbsp;

<goa-dropdown goaValue name="colors123" [formControl]="reactiveFormCtrl">
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>
<br />

<h4>Filterable</h4>
<div>Selected Color: {{ reactiveFormCtrl.value }}</div>
<goa-button (_click)="reactiveFormCtrl.setValue('red')" type="tertiary"
  >Update to red</goa-button
>
<br />
<goa-dropdown
  goaValue
  native="true"
  name="boundColors2"
  [formControl]="reactiveFormCtrl"
  [value]="reactiveFormCtrl.value"
  filterable="true"
>
  <goa-dropdown-item
    name="boundColors2"
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  >
  </goa-dropdown-item>
</goa-dropdown>
&nbsp;

<goa-dropdown
  goaValue
  name="colors123"
  [formControl]="reactiveFormCtrl"
  filterable="true"
>
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>
<br />

<hr />
<h2>Disabled</h2>
<h4>Not Filterable</h4>
<goa-dropdown
  goaValue
  name="colors123"
  [formControl]="reactiveFormCtrl"
  [attr.disabled]="true"
>
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>
<h4>Filterable</h4>

<goa-dropdown
  goaValue
  name="colors123"
  [formControl]="reactiveFormCtrl"
  [attr.disabled]="true"
  filterable="true"
>
  <goa-dropdown-item
    *ngFor="let color of colors"
    [value]="color"
    [label]="color"
  ></goa-dropdown-item>
</goa-dropdown>
