// apps/prs/angular/src/routes/docs/side-menu/side-menu.component.ts
import { Component } from "@angular/core";
import {
  GoabSideMenu,
  GoabSideMenuGroup,
  GoabSideMenuHeading,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-side-menu",
  templateUrl: "./side-menu.component.html",
  imports: [GoabSideMenu, GoabSideMenuGroup, GoabSideMenuHeading],
})
export class DocsSideMenuComponent {}

<h2>Side menu</h2>

<h3>Basic side menu</h3>
<div style="width: 200px">
  <nav>
    <goab-side-menu>
      <a href="/overview">Overview</a>
      <a href="/details">Details</a>
      <a href="/settings">Settings</a>
    </goab-side-menu>
  </nav>
</div>

<h3>With sections</h3>
<div style="width: 200px">
  <nav>
    <goab-side-menu>
      <goab-side-menu-heading>Main</goab-side-menu-heading>
      <a href="/dashboard">Dashboard</a>
      <a href="/reports">Reports</a>
      <goab-side-menu-heading>Settings</goab-side-menu-heading>
      <a href="/profile">Profile</a>
      <a href="/preferences">Preferences</a>
    </goab-side-menu>
  </nav>
</div>

<h3>With groups</h3>
<div style="width: 200px">
  <nav>
    <goab-side-menu>
      <goab-side-menu-group heading="Applications">
        <a href="/apps/active">Active</a>
        <a href="/apps/pending">Pending</a>
        <a href="/apps/archived">Archived</a>
      </goab-side-menu-group>
      <goab-side-menu-group heading="Reports">
        <a href="/reports/monthly">Monthly</a>
        <a href="/reports/annual">Annual</a>
      </goab-side-menu-group>
    </goab-side-menu>
  </nav>
</div>

// apps/prs/react/src/routes/docs/side-menu/side-menu.tsx
import {
  GoabSideMenu,
  GoabSideMenuGroup,
  GoabSideMenuHeading,
} from "@abgov/react-components";

export function DocsSideMenuRoute() {
  return (
    <div>
      <h2>Side menu</h2>

      <h3>Basic side menu</h3>
      <div style={{ width: "200px" }}>
        <nav>
          <GoabSideMenu>
            <a href="/overview">Overview</a>
            <a href="/details">Details</a>
            <a href="/settings">Settings</a>
          </GoabSideMenu>
        </nav>
      </div>

      <h3>With sections</h3>
      <div style={{ width: "200px" }}>
        <nav>
          <GoabSideMenu>
            <GoabSideMenuHeading>Main</GoabSideMenuHeading>
            <a href="/dashboard">Dashboard</a>
            <a href="/reports">Reports</a>
            <GoabSideMenuHeading>Settings</GoabSideMenuHeading>
            <a href="/profile">Profile</a>
            <a href="/preferences">Preferences</a>
          </GoabSideMenu>
        </nav>
      </div>

      <h3>With groups</h3>
      <div style={{ width: "200px" }}>
        <nav>
          <GoabSideMenu>
            <GoabSideMenuGroup heading="Applications">
              <a href="/apps/active">Active</a>
              <a href="/apps/pending">Pending</a>
              <a href="/apps/archived">Archived</a>
            </GoabSideMenuGroup>
            <GoabSideMenuGroup heading="Reports">
              <a href="/reports/monthly">Monthly</a>
              <a href="/reports/annual">Annual</a>
            </GoabSideMenuGroup>
          </GoabSideMenu>
        </nav>
      </div>
    </div>
  );
}
