// libs/react-components/src/experimental/drawer/drawer.tsx
import { ReactNode, useEffect, useRef, type JSX } from "react";
import { GoabDrawerPosition, GoabDrawerSize } from "@abgov/ui-components-common";

interface WCProps {
  position: GoabDrawerPosition;
  open?: boolean;
  heading?: string;
  maxsize?: GoabDrawerSize;
  testid?: string;
  ref: React.RefObject<HTMLElement | null>;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-drawer": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabxDrawerProps {
  /**
   * The position of the drawer.
   * @required
   */
  position: GoabDrawerPosition;
  /**
   * Whether the drawer is open.
   * @default false
   */
  open?: boolean;
  /**
   * The heading text displayed at the top of the drawer.
   * @default ""
   */
  heading?: string | ReactNode;
  /** Sets max height on bottom position, sets width on left and right position. */
  maxSize?: GoabDrawerSize;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default "drawer"
   */
  testId?: string;
  /** TO REVIEW: Action buttons or elements displayed in the component's action area. */
  actions?: ReactNode;
  /**
   * TO REVIEW: The content rendered inside the drawer body.
   * @required
   */
  children: ReactNode;
  onClose: () => void;
  version?: string;
}

export function GoabxDrawer({
  position,
  open,
  heading,
  maxSize,
  testId,
  actions,
  children,
  onClose,
  version = "2",
}: GoabxDrawerProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el?.current || !onClose) {
      return;
    }
    el.current?.addEventListener("_close", onClose);
    return () => {
      el.current?.removeEventListener("_close", onClose);
    };
  }, [el, onClose]);

  return (
    <goa-drawer
      ref={el}
      position={position}
      open={open ? true : undefined}
      heading={typeof heading === "string" ? heading : undefined}
      maxsize={maxSize}
      testid={testId}
      version={version}
    >
      {heading && typeof heading !== "string" && <div slot="heading">{heading}</div>}
      {actions && <div slot="actions">{actions}</div>}
      {children}
    </goa-drawer>
  );
}

export default GoabxDrawer;

// libs/angular-components/src/experimental/drawer/drawer.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  booleanAttribute,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  EventEmitter,
  Input,
  Output,
  TemplateRef,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";
import { GoabDrawerPosition, GoabDrawerSize } from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "goabx-drawer",
  imports: [NgTemplateOutlet],
  template: `@if (isReady) {
    <goa-drawer
      [open]="open"
      [attr.position]="position"
      [attr.heading]="getHeadingAsString()"
      [attr.maxsize]="maxSize"
      [attr.testid]="testId"
      [attr.version]="version"
      (_close)="_onClose()"
    >
      <ng-content></ng-content>
      <div slot="heading">
        <ng-container [ngTemplateOutlet]="getHeadingAsTemplate()"></ng-container>
      </div>
      <div slot="actions">
        <ng-container [ngTemplateOutlet]="actions"></ng-container>
      </div>
    </goa-drawer>
  } `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabxDrawer implements OnInit {
  version = "2";

  /**
   * Whether the drawer is open.
   * @required
   */
  @Input({ required: true, transform: booleanAttribute }) open!: boolean;
  /**
   * The position of the drawer.
   * @required
   */
  @Input({ required: true }) position!: GoabDrawerPosition;
  /**
   * The heading text displayed at the top of the drawer.
   */
  @Input() heading!: string | TemplateRef<any>;
  /** Sets max height on bottom position, sets width on left and right position. */
  @Input() maxSize?: GoabDrawerSize;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default "drawer"
   */
  @Input() testId?: string;
  /**
   * TO REVIEW: Action buttons or elements displayed in the component's action area.
   */
  @Input() actions!: TemplateRef<any>;
  @Output() onClose = new EventEmitter();

  isReady = false;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    // For Angular 20, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }

  _onClose() {
    this.onClose.emit();
  }

  getHeadingAsString(): string {
    return this.heading instanceof TemplateRef ? "" : this.heading;
  }

  getHeadingAsTemplate(): TemplateRef<any> | null {
    if (!this.heading) return null;
    return this.heading instanceof TemplateRef ? this.heading : null;
  }
}
