// apps/prs/react/src/routes/bugs/bug3743.tsx
import {
  GoabButton,
  GoabButtonGroup,
} from "@abgov/react-components";

export function Bug3743Route() {

  return (
    <>
    <div>
      <h1>3743 - Tertiary button background color on mobile</h1>
      <h2>Version 1</h2>
      <GoabButtonGroup alignment="start">
        <GoabButton>Submit</GoabButton>
        <GoabButton type="secondary">Cancel</GoabButton>
        <GoabButton type="tertiary">Tertiary</GoabButton>
      </GoabButtonGroup>
    </div>
    <div style={{ backgroundColor: "var(--goa-color-greyscale-700)", padding: "var(--goa-space-l)" }}>
      <GoabButton variant="inverse">Primary inverse</GoabButton>
      <GoabButton variant="inverse" type="secondary">Secondary inverse</GoabButton>
      <GoabButton variant="inverse" type="tertiary">Tertiary inverse</GoabButton>
    </div>
    </>
  );
}

// apps/prs/angular/src/routes/bugs/3743/bug3743.component.ts
import { Component } from "@angular/core";
import { GoabButton, GoabButtonGroup } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug3743",
  templateUrl: "./bug3743.component.html",
  imports: [GoabButton, GoabButtonGroup],
})
export class Bug3743Component {}

<div>
  <h1>3743 - Tertiary button background color on mobile</h1>
  <goab-button-group>
    <goab-button>Submit</goab-button>
    <goab-button type="secondary">Cancel</goab-button>
    <goab-button type="tertiary">Tertiary</goab-button>
  </goab-button-group>
  <div style="background-color: var(--goa-color-greyscale-700); padding: var(--goa-space-l);">
    <goab-button-group>
      <goab-button variant="inverse">Primary inverse</goab-button>
      <goab-button variant="inverse" type="secondary">Secondary inverse</goab-button>
      <goab-button variant="inverse" type="tertiary">Tertiary inverse</goab-button>
    </goab-button-group>
  </div>
</div>
