// libs/angular-components/src/lib/components/file-upload-card/file-upload-card.ts
import {
  GoabFileUploadOnCancelDetail,
  GoabFileUploadOnDeleteDetail,
} from "@abgov/ui-components-common";
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  EventEmitter,
  Input,
  Output,
  numberAttribute,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-file-upload-card",
  template: ` @if (isReady) {
    <goa-file-upload-card
      [attr.filename]="filename"
      [attr.size]="size"
      [attr.type]="type"
      [attr.progress]="progress"
      [attr.error]="error"
      [attr.testid]="testId"
      (_cancel)="_onCancel($event)"
      (_delete)="_onDelete($event)"
    >
    </goa-file-upload-card>
  }`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabFileUploadCard implements OnInit {
  /**
   * The name of the uploaded file to display.
   * @required
   */
  @Input({ required: true }) filename!: string;
  /**
   * The file size in bytes. Displayed in a human-readable format (KB, MB).
   */
  @Input({ transform: numberAttribute }) size?: number;
  /**
   * The MIME type of the file. Used to determine the file type icon.
   * @default ""
   */
  @Input() type?: string;
  /** Upload progress percentage from 0-100. Use -1 to indicate upload is complete. */
  @Input({ transform: numberAttribute }) progress?: number;
  /**
   * Error message to display. When set, the card shows an error state with a cancel button.
   * @default ""
   */
  @Input() error?: string;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  @Input() testId?: string;

  @Output() onCancel = new EventEmitter<GoabFileUploadOnCancelDetail>();
  @Output() onDelete = new EventEmitter<GoabFileUploadOnDeleteDetail>();

  isReady = false;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    // For Angular 20, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }

  _onCancel(event: Event) {
    this.onCancel.emit({ filename: this.filename, event });
  }

  _onDelete(event: Event) {
    this.onDelete.emit({ filename: this.filename, event });
  }
}

// libs/vue-components/src/lib/file-upload-card/file-upload-card.vue
<script setup lang="ts">
import type {
  GoabFileUploadOnCancelDetail,
  GoabFileUploadOnDeleteDetail,
} from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required The name of the uploaded file to display. */
  filename: string;
  /** @required The file size in bytes. Displayed in a human-readable format (KB, MB). */
  size: number;
  /** The MIME type of the file. Used to determine the file type icon. */
  type?: string;
  /** Upload progress percentage from 0-100. Use -1 to indicate upload is complete. @default -1 */
  progress?: number;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Error message to display. When set, the card shows an error state with a cancel button. */
  error?: string;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  /** Callback fired when the user clicks the remove button on an uploaded file. */
  onDelete: [detail: GoabFileUploadOnDeleteDetail & { event: Event }];
  /** Callback fired when the user clicks the cancel button during file upload. */
  onCancel: [detail: GoabFileUploadOnCancelDetail & { event: Event }];
}>();

const wcProps = useWcProps(props);
</script>

<template>
  <goa-file-upload-card
    v-bind="wcProps"
    @_delete="emit('onDelete', { filename: props.filename, event: $event })"
    @_cancel="emit('onCancel', { filename: props.filename, event: $event })"
  />
</template>
