// libs/vue-components/src/lib/spacer/spacer.vue
<script setup lang="ts">
import type {
  GoabSpacerHorizontalSpacing,
  GoabSpacerVerticalSpacing,
} from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  hSpacing?: GoabSpacerHorizontalSpacing;
  vSpacing?: GoabSpacerVerticalSpacing;
  testId?: string;
}

const props = defineProps<Props>();

const wcProps = useWcProps(props);
</script>

<template>
  <goa-spacer v-bind="wcProps" />
</template>

// libs/angular-components/src/lib/components/spacer/spacer.ts
import { GoabSpacerHorizontalSpacing, GoabSpacerVerticalSpacing } from "@abgov/ui-components-common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input } from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-spacer",
  template: `
    <goa-spacer
      [attr.hspacing]="hSpacing"
      [attr.vspacing]="vSpacing"
      [attr.testid]="testId"
    >
    </goa-spacer>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabSpacer {
  @Input() hSpacing?: GoabSpacerHorizontalSpacing;
  @Input() vSpacing?: GoabSpacerVerticalSpacing;
  @Input() testId?: string;
}
