// libs/vue-components/src/lib/radio-group/radioGroup.vue
<template>
  <div class="goa-radio-group">
    <span class="radio-group-title">{{title}}</span>
    <span v-if="required" class="required-label">(Required)</span>
    <div v-if="helperText" class="helper-text">{{helperText}}</div>

    <label>
      <div v-for="(option, index) in items" :key="option.text">
        <Radio
          v-model="selectedValue"
          :options="items[index]"
          :disabled="disabled"
          :required="hasError()"
          :labelPosition="labelPosition"
          :value="value"
          :defaultValue="value"
          label="Example question one"
          @change="onChangeResponse"
        />
      </div>
    </label>
    <div v-if="hasError()" class="error-text">
      {{ requiredErrorMessage }}
    </div>
  </div>
</template>

<script lang="ts">
  import Radio from "./radio.vue";

  export default {
    components: {
      Radio,
    },
    props: {
      /**
       * Title of the radio item
       */
      title: {
        type: String,
        required: true,
      },
      /**
       * Help text of the radio item
       */
      helperText: {
        type: String,
        required: true,
      },
      /**
       * Error messages
       */
      requiredErrorMessage: {
        type: String,
        required: false,
        default: null,
      },
      /**
       * Disable radio buttons
      */
      disabled: {
        type: Boolean,
        default: false,
      },
      /**
       * Is the radio button selection required.
      */
      required: {
        type: Boolean,
        default: false,
      },
      /**
       * List of radio buttons to select
       */
      items: {
        type: [Array],
        required: true,
      },
      /**
       * where is the label Positioned
       */
      labelPosition: {
        type: String,
        required: false,
        default: 'before',
        validator: (prop) => [
        'before', 'after'
        ].includes(prop)
      },
      onChange: {
        type: Function,
        required: false,
      },
      value: {
        type: String,
        required: false,
        default: "",
      },
    },
    methods: {
      hasError() {
        return this.requiredErrorMessage && this.required && !this.selectedValue;
      },
      onChangeResponse(event) {
        this.selectedValue = event
      }
    },
    data() {
      return {
        selectedValue: null,
      };
    },
  };
</script>
<style lang="scss" scoped>
  @import './radio-group.scss';
</style>

// libs/react-components/src/lib/radio-group/radio-group.tsx
import React, { Children, useState, ReactNode, FC } from 'react';
import GoARadio, { Data as RadioItem, LabelPosition } from './radio/radio';
import './radio-group.scss';

export * from './radio/radio';

interface Props {
  children?: ReactNode;

  /**
   * Name of the form value
   */
  name: string;

  /**
   * Help text of the radio item
   */
  helperText?: string;

  /**
   * List of radio buttons to select
   */
  items?: RadioItem[];

  /**
   * Is the radio button selection required.
   */
  required?: boolean;

  /**
   * Error messages
   */
  requiredErrorMessage?: string;

  /**
   * Title of the radio item
   */
  title?: string;

  /**
   * Initial data value
   */
  value?: string;

  /**
   * Where is the label positioned
   */
  labelPosition?: LabelPosition;

  /**
   * Disable radio buttons
   */
  disabled?: boolean;

  /**
   * Callback function containing the newly selected value
   */
  onChange: (value: string) => void;
}

export const RadioContext = React.createContext<string>('');
export const RadioUpdateContext = React.createContext<(value: string) => void>(
  // eslint-disable-next-line @typescript-eslint/no-empty-function
  () => { }
);

export const GoARadioGroup: FC<Props> = ({
  helperText,
  onChange,
  required,
  requiredErrorMessage,
  title,
  value,
  items,
  children,
  ...childAttrs
}) => {
  const [selectedValue, setSelectedValue] = useState<string>(value);

  function handleOnChange(val: string) {
    setSelectedValue(val);
    onChange(val);
  }

  function hasError(): boolean {
    return required && !selectedValue;
  }

  function getChildren() {
    if (children) {
      return Children.map(children, (child: any) => {
        const key = `${childAttrs.name}-${child.props.value}`;
        return React.cloneElement(child, {
          ...childAttrs,
          key,
          required,
        });
      });
    }

    return items.map((item: RadioItem) => {
      return (
        <GoARadio
          key={`${childAttrs.name}-${item.value}`}
          labelPosition={childAttrs.labelPosition}
          name={childAttrs.name}
          disabled={childAttrs.disabled}
          value={item.value}
          children={item.text}
          required={required}
        />
      );
    });
  }

  return (
    <div className="goa-radio-group">
      {title && <span className="radio-group-title">{title}</span>}
      {required && <span className="required-label">(Required)</span>}
      {helperText && <div className="helper-text">{helperText}</div>}
      <RadioContext.Provider value={selectedValue}>
        <RadioUpdateContext.Provider value={handleOnChange}>
          <div className="goa-radios">{getChildren()}</div>
        </RadioUpdateContext.Provider>
      </RadioContext.Provider>

      {hasError() && <div className="error-text">{requiredErrorMessage}</div>}
    </div>
  );
};

export default GoARadioGroup;
