// apps/prs/react/src/app/routes.tsx/bugs/bug2408.tsx
import { useState } from "react";
import {
  GoabFormStepper,
  GoabFormStep,
  GoabBlock,
  GoabText,
  GoabButton,
} from "@abgov/react-components";
import { GoabFormStepperOnChangeDetail } from "@abgov/ui-components-common";

export const Bug2408Route = () => {
  const [currentStep, setCurrentStep] = useState(1);

  const handleStepChange = (details: GoabFormStepperOnChangeDetail) => {
    console.log("Step changed:", details);
    setCurrentStep(details.step);
  };

  return (
    <main>
      <GoabText tag="h1">Bug 2408: Form Stepper "Incomplete" Status Fix</GoabText>
      <GoabText tag="p">
        Testing the fix for Form Stepper where "incomplete" status was being rendered as
        "Partially complete" instead of "Incomplete".
      </GoabText>

      <GoabBlock gap="l" direction="column">
        <section>
          <GoabText tag="h2">Form Stepper with Different Status Types</GoabText>
          <GoabText tag="p">
            This demonstrates the corrected status display for each step status type.
          </GoabText>

          <GoabFormStepper step={currentStep} onChange={handleStepChange}>
            <GoabFormStep text="Personal Information" status="complete" />
            <GoabFormStep text="Employment History" status="incomplete" />
            <GoabFormStep text="Education Details" status="not-started" />
            <GoabFormStep text="Review & Submit" status="not-started" />
          </GoabFormStepper>
        </section>

        <section>
          <GoabText tag="h2">Status Test Controls</GoabText>
          <GoabText tag="p">
            Use these buttons to test different step combinations:
          </GoabText>

          <GoabBlock gap="s" direction="row">
            <GoabButton type="secondary" size="compact" onClick={() => setCurrentStep(1)}>
              Step 1 (Complete)
            </GoabButton>
            <GoabButton type="secondary" size="compact" onClick={() => setCurrentStep(2)}>
              Step 2 (Incomplete)
            </GoabButton>
            <GoabButton type="secondary" size="compact" onClick={() => setCurrentStep(3)}>
              Step 3 (Not Started)
            </GoabButton>
            <GoabButton type="secondary" size="compact" onClick={() => setCurrentStep(4)}>
              Step 4 (Not Started)
            </GoabButton>
          </GoabBlock>
        </section>

        <section>
          <GoabText tag="h2">Test Results</GoabText>
          <GoabBlock gap="s" direction="column">
            <GoabText tag="p">
              <strong>Current Step:</strong> {currentStep}
            </GoabText>
            <GoabText tag="p">
              <strong>Expected Status Display:</strong>
            </GoabText>
            <ul>
              <li>
                Step 1: <strong>Complete</strong> (green checkmark)
              </li>
              <li>
                Step 2: <strong>Incomplete</strong> (red X - was previously showing
                "Partially complete")
              </li>
              <li>
                Step 3: <strong>Not Started</strong> (gray circle - new status type)
              </li>
              <li>
                Step 4: <strong>Not Started</strong> (gray circle - new status type)
              </li>
            </ul>
          </GoabBlock>
        </section>

        <section>
          <GoabText tag="h2">Bug Description</GoabText>
          <GoabBlock gap="s" direction="column">
            <GoabText tag="p">
              <strong>Issue:</strong> The "incomplete" status was being incorrectly
              rendered as "Partially complete" in the Form Stepper component.
            </GoabText>
            <GoabText tag="p">
              <strong>Fix:</strong> Updated the status display logic to properly show
              "Incomplete" for the "incomplete" status.
            </GoabText>
            <GoabText tag="p">
              <strong>Additional:</strong> Added new "not-started" status option to
              replace "unstarted" for better clarity.
            </GoabText>
          </GoabBlock>
        </section>

        <section>
          <GoabText tag="h2">Accessibility Testing</GoabText>
          <GoabText tag="p">
            Screen readers should announce steps in the format: "Step X of Y, Step name:
            [Name], Status: [Status]"
          </GoabText>
          <GoabText tag="p">
            When clicking step navigation buttons, the screen reader should announce the
            step change immediately.
          </GoabText>
        </section>
      </GoabBlock>
    </main>
  );
};

// apps/prs/angular/src/app/bugs/2408/bug2408.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  GoabFormStepper,
  GoabFormStep,
  GoabBlock,
  GoabText,
  GoabButton,
  GoabFormStepperOnChangeDetail,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-bug2408",
  templateUrl: "./bug2408.component.html",
  imports: [CommonModule, GoabFormStepper, GoabFormStep, GoabBlock, GoabText, GoabButton],
})
export class Bug2408Component {
  currentStep = 1;

  handleStepChange(details: GoabFormStepperOnChangeDetail) {
    console.log("Step changed:", details);
    this.currentStep = details.step;
  }

  setStep(step: number) {
    this.currentStep = step;
  }
}

<goab-text tag="h1">Bug 2408: Form Stepper "Incomplete" Status Fix</goab-text>
<goab-text tag="p">
  Testing the fix for Form Stepper where "incomplete" status was being rendered as
  "Partially complete" instead of "Incomplete".
</goab-text>

<goab-block gap="l" direction="column">
  <section>
    <goab-text tag="h2">Form Stepper with Different Status Types</goab-text>
    <goab-text tag="p">
      This demonstrates the corrected status display for each step status type.
    </goab-text>

    <goab-form-stepper [step]="currentStep" (onChange)="handleStepChange($event)">
      <goab-form-step text="Personal Information" status="complete"></goab-form-step>
      <goab-form-step text="Employment History" status="incomplete"></goab-form-step>
      <goab-form-step text="Education Details" status="not-started"></goab-form-step>
      <goab-form-step text="Review & Submit" status="not-started"></goab-form-step>
    </goab-form-stepper>
  </section>

  <section>
    <goab-text tag="h2">Status Test Controls</goab-text>
    <goab-text tag="p">Use these buttons to test different step combinations:</goab-text>

    <goab-block gap="s" direction="row">
      <goab-button type="secondary" size="compact" (onClick)="setStep(1)">
        Step 1 (Complete)
      </goab-button>
      <goab-button type="secondary" size="compact" (onClick)="setStep(2)">
        Step 2 (Incomplete)
      </goab-button>
      <goab-button type="secondary" size="compact" (onClick)="setStep(3)">
        Step 3 (Not Started)
      </goab-button>
      <goab-button type="secondary" size="compact" (onClick)="setStep(4)">
        Step 4 (Not Started)
      </goab-button>
    </goab-block>
  </section>

  <section>
    <goab-text tag="h2">Test Results</goab-text>
    <goab-block gap="s" direction="column">
      <goab-text tag="p"><strong>Current Step:</strong> {{ currentStep }}</goab-text>
      <goab-text tag="p"><strong>Expected Status Display:</strong></goab-text>
      <ul>
        <li>Step 1: <strong>Complete</strong> (green checkmark)</li>
        <li>
          Step 2: <strong>Incomplete</strong> (red X - was previously showing "Partially
          complete")
        </li>
        <li>Step 3: <strong>Not Started</strong> (gray circle - new status type)</li>
        <li>Step 4: <strong>Not Started</strong> (gray circle - new status type)</li>
      </ul>
    </goab-block>
  </section>

  <section>
    <goab-text tag="h2">Bug Description</goab-text>
    <goab-block gap="s" direction="column">
      <goab-text tag="p">
        <strong>Issue:</strong> The "incomplete" status was being incorrectly rendered as
        "Partially complete" in the Form Stepper component.
      </goab-text>
      <goab-text tag="p">
        <strong>Fix:</strong> Updated the status display logic to properly show
        "Incomplete" for the "incomplete" status.
      </goab-text>
      <goab-text tag="p">
        <strong>Additional:</strong> Added new "not-started" status option to replace
        "unstarted" for better clarity.
      </goab-text>
    </goab-block>
  </section>

  <section>
    <goab-text tag="h2">Accessibility Testing</goab-text>
    <goab-text tag="p">
      Screen readers should announce steps in the format: "Step X of Y, Step name: [Name],
      Status: [Status]"
    </goab-text>
    <goab-text tag="p">
      When clicking step navigation buttons, the screen reader should announce the step
      change immediately.
    </goab-text>
  </section>
</goab-block>
