// apps/prs/angular/src/routes/docs/linear-progress/linear-progress.component.ts
import { Component } from "@angular/core";
import { GoabLinearProgress } from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-linear-progress",
  templateUrl: "./linear-progress.component.html",
  imports: [GoabLinearProgress],
})
export class DocsLinearProgressComponent {}

<h2>Linear progress indicator</h2>

<h3>Basic progress</h3>
<goab-linear-progress [progress]="50" percentVisibility="hidden"></goab-linear-progress>

<h3>Progress levels</h3>
<goab-linear-progress [progress]="0"></goab-linear-progress>
<goab-linear-progress [progress]="25"></goab-linear-progress>
<goab-linear-progress [progress]="50"></goab-linear-progress>
<goab-linear-progress [progress]="75"></goab-linear-progress>
<goab-linear-progress [progress]="100"></goab-linear-progress>

<h3>Indeterminate</h3>
<goab-linear-progress percentVisibility="hidden"></goab-linear-progress>

<h3>With percentage</h3>
<goab-linear-progress [progress]="65"></goab-linear-progress>

// apps/prs/react/src/routes/docs/linear-progress/linear-progress.tsx
import { GoabLinearProgress } from "@abgov/react-components";

export function DocsLinearProgressRoute() {
  return (
    <div>
      <h2>Linear progress indicator</h2>

      <h3>Basic progress</h3>
      <GoabLinearProgress progress={50} percentVisibility="hidden" />

      <h3>Progress levels</h3>
      <GoabLinearProgress progress={0} />
      <GoabLinearProgress progress={25} />
      <GoabLinearProgress progress={50} />
      <GoabLinearProgress progress={75} />
      <GoabLinearProgress progress={100} />

      <h3>Indeterminate</h3>
      <GoabLinearProgress percentVisibility="hidden" />

      <h3>With percentage</h3>
      <GoabLinearProgress progress={65} />
    </div>
  );
}
