// apps/prs/angular/src/routes/bugs/2404/bug2404.component.ts
import { Component } from "@angular/core";
import { GoabInput, GoabIcon } from "@abgov/angular-components";
import { FormControl } from "@angular/forms";

@Component({
  selector: "abgov-bug2404",
  standalone: true,
  templateUrl: "./bug2404.component.html",
  imports: [GoabInput, GoabIcon],
})
export class Bug2404Component {
  firstName = new FormControl("");
  lastName = new FormControl("");

  trailingIconClick() {
    console.log("Trailing Icon Clicked");
  }
}

<goab-input name="firstName" formControlName="firstName" trailingIcon="add" mb="l" />
<br />
<goab-input
  name="lastName"
  formControlName="lastName"
  trailingIcon="accessibility"
  (onTrailingIconClick)="trailingIconClick()"
  mb="xl"
/>
<br />
<goab-icon type="warning" size="large" theme="outline" fillcolor="black" />

// apps/prs/react/src/app/routes.tsx/bugs/bug2404.tsx
import { GoabInput } from "@abgov/react-components";

export const Bug2404Route = () => {
  function noop() {}
  function trailingIconClick() {
    console.log("Trailing Icon Clicked");
  }

  return (
    <main>
      <GoabInput
        name="firstName"
        type="text"
        value=""
        onChange={noop}
        trailingIcon="add"
        mb="l"
      />
      <br />
      <GoabInput
        name="lastName"
        type="text"
        value=""
        onChange={noop}
        trailingIcon="accessibility"
        onTrailingIconClick={() => trailingIconClick()}
      />
    </main>
  );
};
