// apps/prs/react/src/routes/docs/drawer/drawer.tsx
import { useState } from "react";
import {
  GoabButton,
  GoabButtonGroup,
  GoabCheckbox,
  GoabCheckboxList,
  GoabDatePicker,
  GoabDrawer,
  GoabDropdown,
  GoabDropdownItem,
  GoabFormItem,
  GoabInput,
  GoabRadioGroup,
  GoabRadioItem,
} from "@abgov/react-components";

export function DocsDrawerRoute() {
  const [basicOpen, setBasicOpen] = useState(false);
  const [bottomOpen, setBottomOpen] = useState(false);
  const [leftOpen, setLeftOpen] = useState(false);
  const [actionsOpen, setActionsOpen] = useState(false);
  const [narrowOpen, setNarrowOpen] = useState(false);
  const [wideOpen, setWideOpen] = useState(false);
  const [recordOpen, setRecordOpen] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);

  return (
    <div>
      <h2>Drawer</h2>

      <h3>Basic drawer</h3>
      <GoabButton onClick={() => setBasicOpen(true)}>Open drawer</GoabButton>
      <GoabDrawer
        heading="Application details"
        position="right"
        open={basicOpen}
        onClose={() => setBasicOpen(false)}
      >
        <p>
          Use a drawer to display supplementary content or actions without navigating away
          from the current page.
        </p>
        <p>Drawers are useful for:</p>
        <ul>
          <li>Viewing detailed information about a selected item</li>
          <li>Editing settings or preferences</li>
          <li>Completing a quick task related to the main content</li>
        </ul>
      </GoabDrawer>
      <h3>Bottom position</h3>
      <GoabButton onClick={() => setBottomOpen(true)}>Open bottom drawer</GoabButton>
      <GoabDrawer
        heading="Bottom drawer"
        position="bottom"
        open={bottomOpen}
        onClose={() => setBottomOpen(false)}
      >
        <p>Opens from the bottom of the screen.</p>
      </GoabDrawer>

      <h3>Left position</h3>
      <GoabButton onClick={() => setLeftOpen(true)}>Open left drawer</GoabButton>
      <GoabDrawer
        heading="Navigation"
        position="left"
        open={leftOpen}
        onClose={() => setLeftOpen(false)}
      >
        <p>Opens from the left side of the screen.</p>
      </GoabDrawer>

      <h3>With actions</h3>
      <GoabButton onClick={() => setActionsOpen(true)}>
        Open drawer with actions
      </GoabButton>
      <GoabDrawer
        heading="Edit settings"
        position="right"
        open={actionsOpen}
        onClose={() => setActionsOpen(false)}
        actions={
          <GoabButtonGroup alignment="end">
            <GoabButton size="compact" onClick={() => setActionsOpen(false)}>
              Save
            </GoabButton>
            <GoabButton
              type="tertiary"
              size="compact"
              onClick={() => setActionsOpen(false)}
            >
              Cancel
            </GoabButton>
          </GoabButtonGroup>
        }
      >
        <p>Make changes to your settings here.</p>
      </GoabDrawer>

      <h3>Narrow size</h3>
      <GoabButton onClick={() => setNarrowOpen(true)}>Open narrow drawer</GoabButton>
      <GoabDrawer
        heading="Narrow drawer"
        position="right"
        maxSize="240px"
        open={narrowOpen}
        onClose={() => setNarrowOpen(false)}
      >
        <p>Narrow width for simple content.</p>
      </GoabDrawer>

      <h3>Wide size</h3>
      <GoabButton onClick={() => setWideOpen(true)}>Open wide drawer</GoabButton>
      <GoabDrawer
        heading="Wide drawer"
        position="right"
        maxSize="600px"
        open={wideOpen}
        onClose={() => setWideOpen(false)}
      >
        <p>Wide width for more complex content.</p>
      </GoabDrawer>

      <h2>Examples</h2>

      <h3>Add a record using a drawer</h3>
      <GoabButton leadingIcon="add" onClick={() => setRecordOpen(true)}>
        Add Record
      </GoabButton>
      <GoabDrawer
        maxSize="429px"
        open={recordOpen}
        heading="Add Record"
        position="right"
        onClose={() => setRecordOpen(false)}
        actions={
          <GoabButtonGroup alignment="start">
            <GoabButton
              type="primary"
              size="compact"
              onClick={() => setRecordOpen(false)}
            >
              Add record
            </GoabButton>
            <GoabButton
              type="tertiary"
              size="compact"
              onClick={() => setRecordOpen(false)}
            >
              Cancel
            </GoabButton>
          </GoabButtonGroup>
        }
      >
        <GoabFormItem label="Level of education">
          <GoabDropdown onChange={() => { /* no-op */ }} name="education" value="university">
            <GoabDropdownItem value="high-school" label="High School Diploma" />
            <GoabDropdownItem value="college" label="College Diploma" />
            <GoabDropdownItem value="university" label="University Degree" />
            <GoabDropdownItem value="masters" label="Master's Degree" />
            <GoabDropdownItem value="doctorate" label="Doctorate" />
          </GoabDropdown>
        </GoabFormItem>
        <GoabFormItem label="Educational institution" mt="l">
          <GoabInput name="education" type="text" onChange={() => { /* no-op */ }} />
        </GoabFormItem>
        <GoabFormItem label="Field of study" requirement="optional" mt="l">
          <GoabInput name="fieldOfStudy" type="text" onChange={() => { /* no-op */ }} />
        </GoabFormItem>
        <GoabFormItem label="Is the person currently attending?" mt="l">
          <GoabRadioGroup
            name="attendTraining"
            orientation="horizontal"
            onChange={() => { /* no-op */ }}
          >
            <GoabRadioItem value="yes" label="Yes" />
            <GoabRadioItem value="no" label="No" />
          </GoabRadioGroup>
        </GoabFormItem>
        <GoabFormItem label="Start date" mt="l">
          <GoabDatePicker onChange={() => { /* no-op */ }} value={new Date("2022-09-01")} />
          <GoabCheckbox
            name="startDateApproximate"
            text="Approximate date"
            value="y"
            mt="s"
          />
        </GoabFormItem>
        <GoabFormItem label="Credential received?" mt="l">
          <GoabRadioGroup
            name="credentialReceived"
            orientation="horizontal"
            onChange={() => { /* no-op */ }}
          >
            <GoabRadioItem value="yes" label="Yes" />
            <GoabRadioItem value="no" label="No" />
          </GoabRadioGroup>
        </GoabFormItem>
      </GoabDrawer>

      <h3>Add and edit lots of filters</h3>
      <GoabButton onClick={() => setFiltersOpen(true)}>Filters</GoabButton>
      <GoabDrawer
        heading="Filters"
        open={filtersOpen}
        onClose={() => setFiltersOpen(false)}
        position="right"
        actions={
          <GoabButtonGroup alignment="start">
            <GoabButton type="primary" size="compact" onClick={() => setFiltersOpen(false)}>
              Apply filters
            </GoabButton>
            <GoabButton type="tertiary" size="compact" onClick={() => setFiltersOpen(false)}>
              Cancel
            </GoabButton>
          </GoabButtonGroup>
        }
      >
        <GoabFormItem label="Entry status">
          <GoabCheckboxList name="entryStatus" onChange={() => { /* no-op */ }}>
            <GoabCheckbox name="draft" text="Draft" value="draft" />
            <GoabCheckbox name="published" text="Published" value="published" />
          </GoabCheckboxList>
        </GoabFormItem>
        <GoabFormItem label="Assigned to - Region" mt="l">
          <GoabCheckboxList name="region" onChange={() => { /* no-op */ }}>
            <GoabCheckbox name="calgary" text="Calgary" value="calgary" />
            <GoabCheckbox name="central" text="Central" value="central" />
            <GoabCheckbox name="edmonton" text="Edmonton" value="edmonton" />
            <GoabCheckbox name="north" text="North" value="north" />
            <GoabCheckbox name="south" text="South" value="south" />
          </GoabCheckboxList>
        </GoabFormItem>
        <GoabFormItem label="Assigned to" mt="l">
          <GoabDropdown name="assignedTo" onChange={() => { /* no-op */ }}>
            <GoabDropdownItem value="1" label="Person 1" />
            <GoabDropdownItem value="2" label="Person 2" />
          </GoabDropdown>
        </GoabFormItem>
        <GoabFormItem label="Date taken" mt="l">
          <GoabRadioGroup name="dateTaken" onChange={() => { /* no-op */ }}>
            <GoabRadioItem value="24" label="Last 24 hours" />
            <GoabRadioItem value="72" label="Last 72 hours" />
          </GoabRadioGroup>
        </GoabFormItem>
      </GoabDrawer>
    </div>
  );
}

// apps/prs/angular/src/routes/docs/drawer/drawer.component.ts
import { Component } from "@angular/core";
import {
  GoabButton, GoabButtonGroup, GoabCheckbox, GoabCheckboxList, GoabDatePicker, GoabDrawer,
  GoabDropdown, GoabDropdownItem, GoabFormItem, GoabInput, GoabRadioGroup, GoabRadioItem,
} from "@abgov/angular-components";

@Component({
  standalone: true,
  selector: "abgov-docs-drawer",
  templateUrl: "./drawer.component.html",
  imports: [
    GoabButton, GoabButtonGroup, GoabCheckbox, GoabCheckboxList, GoabDatePicker, GoabDrawer,
    GoabDropdown, GoabDropdownItem, GoabFormItem, GoabInput, GoabRadioGroup, GoabRadioItem,
  ],
})
export class DocsDrawerComponent {
  basicOpen = false;
  bottomOpen = false;
  leftOpen = false;
  actionsOpen = false;
  narrowOpen = false;
  wideOpen = false;
  recordOpen = false;
  filtersOpen = false;
  assignedTo = "";

  openBasic(): void {
    this.basicOpen = true;
  }

  closeBasic(): void {
    this.basicOpen = false;
  }

  openBottom(): void {
    this.bottomOpen = true;
  }

  closeBottom(): void {
    this.bottomOpen = false;
  }

  openLeft(): void {
    this.leftOpen = true;
  }

  closeLeft(): void {
    this.leftOpen = false;
  }

  openActions(): void {
    this.actionsOpen = true;
  }

  closeActions(): void {
    this.actionsOpen = false;
  }

  openNarrow(): void {
    this.narrowOpen = true;
  }

  closeNarrow(): void {
    this.narrowOpen = false;
  }

  openWide(): void {
    this.wideOpen = true;
  }

  closeWide(): void {
    this.wideOpen = false;
  }

  openRecord(): void {
    this.recordOpen = true;
  }

  closeRecord(): void {
    this.recordOpen = false;
  }

  dropdownOnChange(event: any): void {
    console.log(event);
  }

  inputOnChange(event: any): void {
    console.log(event);
  }

  radioOnChange(event: any): void {
    console.log(event);
  }

  dateOnChange(event: any): void {
    console.log(event);
  }

  openFilters(): void {
    this.filtersOpen = true;
  }

  closeFilters(): void {
    this.filtersOpen = false;
  }

  onCheckboxChange(event: any): void {
    console.log(event);
  }

  onChangeAssignedTo(e: any): void {
    this.assignedTo = e.value as string;
  }
}

<h2>Drawer</h2>

<h3>Basic drawer</h3>
<goab-button (onClick)="openBasic()">Open drawer</goab-button>
<goab-drawer
  heading="Application details"
  position="right"
  [open]="basicOpen"
  (onClose)="closeBasic()"
>
  <p>
    Use a drawer to display supplementary content or actions without navigating
    away from the current page.
  </p>
  <p>Drawers are useful for:</p>
  <ul>
    <li>Viewing detailed information about a selected item</li>
    <li>Editing settings or preferences</li>
    <li>Completing a quick task related to the main content</li>
  </ul>
</goab-drawer>

<h3>Bottom position</h3>
<goab-button (onClick)="openBottom()">Open bottom drawer</goab-button>
<goab-drawer
  heading="Bottom drawer"
  position="bottom"
  [open]="bottomOpen"
  (onClose)="closeBottom()"
>
  <p>Opens from the bottom of the screen.</p>
</goab-drawer>

<h3>Left position</h3>
<goab-button (onClick)="openLeft()">Open left drawer</goab-button>
<goab-drawer
  heading="Navigation"
  position="left"
  [open]="leftOpen"
  (onClose)="closeLeft()"
>
  <p>Opens from the left side of the screen.</p>
</goab-drawer>

<h3>With actions</h3>
<goab-button (onClick)="openActions()">Open drawer with actions</goab-button>
<goab-drawer
  heading="Edit settings"
  position="right"
  [open]="actionsOpen"
  (onClose)="closeActions()"
  [actions]="actionsTpl"
>
  <ng-template #actionsTpl>
    <goab-button-group alignment="end">
      <goab-button size="compact" (onClick)="closeActions()">Save</goab-button>
      <goab-button type="tertiary" size="compact" (onClick)="closeActions()"
        >Cancel</goab-button
      >
    </goab-button-group>
  </ng-template>
  <p>Make changes to your settings here.</p>
</goab-drawer>

<h3>Narrow size</h3>
<goab-button (onClick)="openNarrow()">Open narrow drawer</goab-button>
<goab-drawer
  heading="Narrow drawer"
  position="right"
  maxSize="240px"
  [open]="narrowOpen"
  (onClose)="closeNarrow()"
>
  <p>Narrow width for simple content.</p>
</goab-drawer>

<h3>Wide size</h3>
<goab-button (onClick)="openWide()">Open wide drawer</goab-button>
<goab-drawer
  heading="Wide drawer"
  position="right"
  maxSize="600px"
  [open]="wideOpen"
  (onClose)="closeWide()"
>
  <p>Wide width for more complex content.</p>
</goab-drawer>

<h2>Examples</h2>

<h3>Add a record using a drawer</h3>
<goab-button leadingIcon="add" (onClick)="openRecord()">Add Record</goab-button>
<goab-drawer
  maxSize="492px"
  [open]="recordOpen"
  heading="Add Record"
  position="right"
  (onClose)="closeRecord()"
  [actions]="recordActions"
>
  <goab-form-item label="Level of education">
    <goab-dropdown
      (onChange)="dropdownOnChange($event)"
      name="education"
      value="university"
    >
      <goab-dropdown-item value="high-school" label="High School Diploma"></goab-dropdown-item>
      <goab-dropdown-item value="college" label="College Diploma"></goab-dropdown-item>
      <goab-dropdown-item value="university" label="University Degree"></goab-dropdown-item>
      <goab-dropdown-item value="masters" label="Master's Degree"></goab-dropdown-item>
      <goab-dropdown-item value="doctorate" label="Doctorate"></goab-dropdown-item>
    </goab-dropdown>
  </goab-form-item>
  <goab-form-item label="Educational institution" mt="l">
    <goab-input name="education" type="text" (onChange)="inputOnChange($event)"></goab-input>
  </goab-form-item>
  <goab-form-item label="Field of study" requirement="optional" mt="l">
    <goab-input name="fieldOfStudy" type="text" (onChange)="inputOnChange($event)"></goab-input>
  </goab-form-item>
  <goab-form-item label="Is the person currently attending?" mt="l">
    <goab-radio-group name="attendTraining" orientation="horizontal" (onChange)="radioOnChange($event)">
      <goab-radio-item value="yes" label="Yes"></goab-radio-item>
      <goab-radio-item value="no" label="No"></goab-radio-item>
    </goab-radio-group>
  </goab-form-item>
  <goab-form-item label="Start date" mt="l">
    <goab-date-picker (onChange)="dateOnChange($event)"></goab-date-picker>
    <goab-checkbox name="startDateApproximate" text="Approximate date" value="y" mt="s"></goab-checkbox>
  </goab-form-item>
  <goab-form-item label="Credential received?" mt="l">
    <goab-radio-group name="credentialReceived" orientation="horizontal" (onChange)="radioOnChange($event)">
      <goab-radio-item value="yes" label="Yes"></goab-radio-item>
      <goab-radio-item value="no" label="No"></goab-radio-item>
    </goab-radio-group>
  </goab-form-item>
  <ng-template #recordActions>
    <goab-button-group alignment="start">
      <goab-button type="primary" size="compact" (onClick)="closeRecord()">Add record</goab-button>
      <goab-button type="tertiary" size="compact" (onClick)="closeRecord()">Cancel</goab-button>
    </goab-button-group>
  </ng-template>
</goab-drawer>

<h3>Add and edit lots of filters</h3>
<goab-button (onClick)="openFilters()">Filters</goab-button>
<goab-drawer
  heading="Filters"
  [open]="filtersOpen"
  (onClose)="closeFilters()"
  position="right"
  [actions]="filtersActions"
>
  <goab-form-item label="Entry status">
    <goab-checkbox-list name="entryStatus" (onChange)="onCheckboxChange($event)">
      <goab-checkbox name="draft" text="Draft" value="draft"></goab-checkbox>
      <goab-checkbox name="published" text="Published" value="published"></goab-checkbox>
    </goab-checkbox-list>
  </goab-form-item>
  <goab-form-item label="Assigned to - Region" mt="l">
    <goab-checkbox-list name="region" (onChange)="onCheckboxChange($event)">
      <goab-checkbox name="calgary" text="Calgary" value="calgary"></goab-checkbox>
      <goab-checkbox name="central" text="Central" value="central"></goab-checkbox>
      <goab-checkbox name="edmonton" text="Edmonton" value="edmonton"></goab-checkbox>
      <goab-checkbox name="north" text="North" value="north"></goab-checkbox>
      <goab-checkbox name="south" text="South" value="south"></goab-checkbox>
    </goab-checkbox-list>
  </goab-form-item>
  <goab-form-item label="Assigned to" mt="l">
    <goab-dropdown [value]="assignedTo" name="assignedToData" (onChange)="onChangeAssignedTo($event)">
      <goab-dropdown-item value="1" label="Person 1"></goab-dropdown-item>
      <goab-dropdown-item value="2" label="Person 2"></goab-dropdown-item>
    </goab-dropdown>
  </goab-form-item>
  <goab-form-item label="Date taken" mt="l">
    <goab-radio-group name="dateTaken" (onChange)="radioOnChange($event)">
      <goab-radio-item value="24" label="Last 24 hours"></goab-radio-item>
      <goab-radio-item value="72" label="Last 72 hours"></goab-radio-item>
    </goab-radio-group>
  </goab-form-item>
  <ng-template #filtersActions>
    <goab-button-group alignment="start">
      <goab-button type="primary" size="compact" (onClick)="closeFilters()">Apply filters</goab-button>
      <goab-button type="tertiary" size="compact" (onClick)="closeFilters()">Cancel</goab-button>
    </goab-button-group>
  </ng-template>
</goab-drawer>
