// libs/react-components/src/experimental/page-loader/page-loader.tsx
import React from "react";
import PropTypes from 'prop-types';
import styled, { keyframes } from "styled-components";

export interface PageLoaderProps {
  message?: string;
  visible?: boolean;
};

const spinner = keyframes`
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(360deg);
    }
`;

export const GoAPageLoader = ({ loading=false, message }) => {
  return loading &&
    <Container onKeyDown={(event) => {event.preventDefault()}}>
      <Loader></Loader>
      <Message>{message}</Message>
    </Container>;
};

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  background: rgba(255,255,255,90);
`;

const Message = styled.span`
  margin-top: 24px;
  font-style: normal;
  font-weight: normal;
  font-size: 18px;
  color: #000;
`;

const Loader = styled.div`
  margin-top: 16px;
  border-top: 7px solid #0070c4;
  border-right: 7px solid #0070c4;
  border-bottom: 7px solid #0070c4;
  border-left: 7px solid rgba(10,129,162, 0.2);
  border-radius: 50%;
  animation: ${spinner} 0.9s linear infinite;
  width: 65px;
  height: 65px;
  padding-right: 56px;
  padding-right: 56px;
  padding-top: 56px;
`;

GoAPageLoader.propTypes = {
  loading: PropTypes.bool,
  message: PropTypes.string
};

// libs/web-components-orig/src/PageLoader.wc.svelte
<svelte:options tag="goa-page-loader" />

<!-- Script -->
<script lang="ts">
import { fade } from "svelte/transition";

  import noScroll from "./common/no-scroll";
  import type { SpinnerType } from "./Spinner.wc.svelte";

  export let type: SpinnerType;
  export let show: boolean = false;
  export let message: string;
  export let progress: number = 0;
  export let fullscreen: boolean = false;

  $: ready = type && show;
</script>

<!-- HTML -->
{#if ready}
  <div use:noScroll={{enable: fullscreen}}
    class:fullscreen
    class:inline={!fullscreen}
  >
    <goa-spinner type={type} size="xlarge" progress={progress} />
    <div class="message">{message}</div>
  </div>
{/if}

<!-- Style -->
<style>
  .fullscreen {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 9999;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    background-color: rgba(255, 255, 255, 0.9);
  }

  .inline {
    margin: 3.5rem;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .message {
    margin-top: 1rem;
    font-size: 1.2rem;
  }
</style>
