// libs/angular-components/src/lib/components/multi-select/multi-select.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  EventEmitter,
  Input,
  Output,
  booleanAttribute,
  forwardRef,
  OnInit,
  ChangeDetectorRef,
  inject,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";

import { GoabDropdownOnChangeDetail, GoabDropdownSize } from "@abgov/ui-components-common";
import { GoabControlValueAccessor } from "../base.component";

@Component({
  standalone: true,
  selector: "goab-multi-select",
  template: `
    @if (isReady) {
      <goa-multi-select
        #goaComponentRef
        [attr.version]="version"
        [attr.name]="name"
        [value]="value"
        [attr.arialabel]="ariaLabel"
        [attr.arialabelledby]="ariaLabelledBy"
        [disabled]="disabled"
        [attr.error]="error"
        [attr.filterable]="filterable"
        [attr.maxheight]="maxHeight"
        [attr.mb]="mb"
        [attr.ml]="ml"
        [attr.mr]="mr"
        [attr.mt]="mt"
        [attr.placeholder]="placeholder"
        [attr.testid]="testId"
        [attr.width]="width"
        [attr.maxwidth]="maxWidth"
        [attr.size]="size"
        [id]="id"
        (_change)="_onChange($event)"
      >
        <ng-content />
      </goa-multi-select>
    }
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      multi: true,
      useExisting: forwardRef(() => GoabMultiSelect),
    },
  ],
})
export class GoabMultiSelect extends GoabControlValueAccessor implements OnInit {
  private cdr = inject(ChangeDetectorRef);

  @Input() name?: string;
  @Input() ariaLabel?: string;
  @Input() ariaLabelledBy?: string;
  @Input({ transform: booleanAttribute }) filterable?: boolean;
  @Input() maxHeight?: string;
  @Input() placeholder?: string;
  @Input() width?: string;
  @Input() maxWidth?: string;
  @Input() size?: GoabDropdownSize = "default";
  @Output() onChange = new EventEmitter<GoabDropdownOnChangeDetail>();

  isReady = false;
  version = "2";

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }

  _onChange(e: Event) {
    const detail = { ...(e as CustomEvent<GoabDropdownOnChangeDetail>).detail, event: e };
    this.onChange.emit(detail);
    this.markAsTouched();
    if (detail.values !== undefined) {
      this.value = JSON.stringify(detail.values);
      this.fcChange?.(detail.values);
    } else {
      this.value = detail.value || null;
      this.fcChange?.(detail.value || "");
    }
  }

  protected override convertValueToString(value: unknown): string {
    if (Array.isArray(value)) {
      return JSON.stringify(value);
    }
    return super.convertValueToString(value);
  }

  public override writeValue(value: unknown): void {
    const stringValue = this.convertValueToString(value);
    this.value = stringValue || null;
    const el = this.goaComponentRef?.nativeElement as HTMLElement | undefined;
    if (el) {
      this.renderer.setAttribute(el, "value", stringValue);
    }
  }
}

// libs/react-components/src/lib/multi-select/multi-select.tsx
import {
  GoabDropdownOnChangeDetail,
  GoabDropdownSize,
  Margins,
  DataAttributes,
} from "@abgov/ui-components-common";
import { useEffect, useRef, type JSX } from "react";
import { transformProps, lowercase } from "../common/extract-props";

interface WCProps extends Margins {
  arialabel?: string;
  arialabelledby?: string;
  disabled?: string;
  error?: string;
  filterable?: string;
  maxheight?: string;
  name?: string;
  placeholder?: string;
  value?: string;
  width?: string;
  maxwidth?: string;
  testid?: string;
  size?: GoabDropdownSize;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface
    interface IntrinsicElements {
      "goa-multi-select": WCProps &
        React.HTMLAttributes<HTMLElement> & {
          ref: React.RefObject<HTMLElement | null>;
        };
    }
  }
}

export interface GoabMultiSelectProps extends Margins, DataAttributes {
  name?: string;
  value?: string[];
  onChange?: (detail: GoabDropdownOnChangeDetail) => void;

  // optional
  ariaLabel?: string;
  ariaLabelledBy?: string;
  children?: React.ReactNode;
  disabled?: boolean;
  error?: boolean;
  filterable?: boolean;
  maxHeight?: string;
  placeholder?: string;
  testId?: string;
  width?: string;
  maxWidth?: string;
  size?: GoabDropdownSize;
}

export function GoabMultiSelect({
  value,
  onChange,
  disabled,
  error,
  filterable,
  children,
  size = "default",
  ...rest
}: GoabMultiSelectProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  const _props = transformProps<WCProps>({ size, ...rest }, lowercase);

  useEffect(() => {
    if (!el.current) return;
    const current = el.current;
    const handler = (e: Event) => {
      const detail = (e as CustomEvent<GoabDropdownOnChangeDetail>).detail;
      onChange?.({ ...detail, event: e });
    };
    if (onChange) {
      current.addEventListener("_change", handler);
    }
    return () => {
      if (onChange) {
        current.removeEventListener("_change", handler);
      }
    };
  }, [el, onChange]);

  return (
    <goa-multi-select
      ref={el}
      value={value ? JSON.stringify(value) : ""}
      disabled={disabled ? "true" : undefined}
      error={error ? "true" : undefined}
      filterable={filterable ? "true" : undefined}
      {..._props}
      version="2"
    >
      {children}
    </goa-multi-select>
  );
}

export default GoabMultiSelect;
