// libs/angular-components/src/lib/components/popover/popover.ts
import { GoabPopoverPosition } from "@abgov/ui-components-common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input, TemplateRef, OnInit, ChangeDetectorRef } from "@angular/core";
import { NgTemplateOutlet, CommonModule } from "@angular/common";
import { GoabBaseComponent } from "../base.component";

@Component({
  standalone: true,
  selector: "goab-popover",
  imports: [NgTemplateOutlet, CommonModule],
  template: `
    <goa-popover
      *ngIf="isReady"
      [attr.maxwidth]="maxWidth"
      [attr.minwidth]="minWidth"
      [attr.padded]="padded"
      [attr.position]="position"
      [attr.relative]="relative"
      [attr.testid]="testId"
      [attr.mt]="mt"
      [attr.mb]="mb"
      [attr.ml]="ml"
      [attr.mr]="mr"
    >
      <ng-content></ng-content>
      <div slot="target">
        <ng-container [ngTemplateOutlet]="target"></ng-container>
      </div>
    </goa-popover>
  `,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabPopover extends GoabBaseComponent implements OnInit {
  isReady = false;
  @Input() maxWidth = "320px";
  @Input() minWidth?: string;
  @Input() padded = true;
  @Input() position?: GoabPopoverPosition;
  /***
   * @deprecated This property has no effect and will be removed in a future version
   */
  @Input() relative?: boolean;
  @Input({ required: true }) target!: TemplateRef<any>;

  constructor(private cdr: ChangeDetectorRef) {
    super();
  }

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    });
  }
}

// libs/react-components/src/lib/popover/popover.tsx
import { GoabPopoverPosition } from "@abgov/ui-components-common";
import { ReactNode } from "react";
import { Margins } from "../../common/types";

interface WCProps extends Margins {
  maxwidth?: string;
  minwidth?: string;
  padded?: boolean;
  position?: GoabPopoverPosition;
  relative?: boolean;
  testid?: string;
}

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-popover": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabPopoverProps extends Margins {
  target?: ReactNode;
  testId?: string;
  maxWidth?: string;
  minWidth?: string;
  padded?: boolean;
  position?: GoabPopoverPosition;
  children: ReactNode;
  /***
   * @deprecated This property has no effect and will be removed in a future version
   */
  relative?: boolean;
}

export function GoabPopover({
  target,
  testId,
  maxWidth,
  minWidth,
  padded,
  position,
  relative,
  children,
  mt,
  mr,
  mb,
  ml,
}: GoabPopoverProps): JSX.Element {
  return (
    <goa-popover
      testid={testId}
      maxwidth={maxWidth}
      minwidth={minWidth}
      padded={padded}
      position={position}
      relative={relative}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
    >
      {children}
      {target && <div slot="target">{target}</div>}
    </goa-popover>
  );
}

export default GoabPopover;
