// libs/react-components/src/experimental/footer/footer.tsx
import { ReactNode, type JSX } from "react";
import { DataAttributes } from "@abgov/ui-components-common";
import { transformProps, lowercase } from "../../lib/common/extract-props";

interface WCProps {
  maxcontentwidth?: string;
  testid?: string;
  url?: string;
  version?: string;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-app-footer": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

/* eslint-disable-next-line */
export interface GoabxAppFooterProps extends DataAttributes {
  /**
   * The maximum width of the main content area
   * @default ""
   */
  maxContentWidth?: string;
  children?: ReactNode;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  testId?: string;
  /**
   * URL for the Government of Alberta logo link. Set to empty string to disable the link.
   * @default "https://alberta.ca"
   */
  url?: string;
  version?: string;
}

export function GoabxAppFooter({ children, ...rest }: GoabxAppFooterProps): JSX.Element {
  const _props = transformProps<WCProps>(rest, lowercase);

  return (
    <goa-app-footer {..._props} version={"2"}>
      {children}
    </goa-app-footer>
  );
}

export default GoabxAppFooter;

// libs/angular-components/src/experimental/footer/footer.ts
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";

@Component({
  standalone: true,
  selector: "goabx-app-footer",
  template: `@if (isReady) {
    <goa-app-footer
      [attr.maxcontentwidth]="maxContentWidth"
      [attr.url]="url"
      [attr.testid]="testId"
      [attr.version]="version"
    >
      <ng-content select="[slot=nav]" />
      <ng-content select="goabx-app-footer-meta-section"></ng-content>
      <ng-content></ng-content>
    </goa-app-footer>
  }`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabxAppFooter implements OnInit {
  /**
   * The maximum width of the main content area
   * @default ""
   */
  @Input() maxContentWidth?: string;
  /**
   * Sets a data-testid attribute for automated testing.
   * @default ""
   */
  @Input() testId?: string;
  /**
   * URL for the Government of Alberta logo link. Set to empty string to disable the link.
   * @default "https://alberta.ca"
   */
  @Input() url?: string;

  isReady = false;
  version = 2;

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    // For Angular 20, we need to delay rendering the web component
    // to ensure all attributes are properly bound before the component initializes
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    }, 0);
  }
}
