// apps/angular-tests/src/app/app-header/app-header.component.ts
import { GoABAppHeader, GoABAppHeaderMenu } from "@abgov/angular-components";
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-app-header",
  templateUrl: "./app-header.component.html",
  imports: [
    GoABAppHeader,
    GoABAppHeaderMenu,
  ],
})
export class AppHeaderComponent {
  constructor() { }
}

<goab-app-header url="https://example.com" heading="Ticket and Fine Payments">
  <a href="#">Support</a>
  <goab-app-header-menu heading="Tickets" leadingIcon="ticket">
    <a href="#">Cases</a>
    <a href="#">Payments</a>
    <a href="#">Outstanding</a>
  </goab-app-header-menu>
  <a href="#" class="interactive">Sign in</a>
</goab-app-header>

// apps/react-demo/src/routes/appHeader.tsx
import { GoAAppHeader, GoAAppHeaderMenu } from "@abgov/react-components";
import * as React from "react";

export default function AppHeader() {
  return (
    <>
      <h1>App Header</h1>

      <h2>Basic</h2>
      <GoAAppHeader url="https://example.com" />

      <h2>Title</h2>
      <GoAAppHeader
        url="https://example.com"
        heading="Ticket and Fine Payments"
      ></GoAAppHeader>

      <h2>Custom Content</h2>
      <GoAAppHeader
        url="https://example.com"
        heading="Ticket and Fine Payments"
      >
        <a href="app-header#aboutus">About Us</a>
        <a title="loginUrl" href="app-header#login" className="interactive">
          Login
        </a>
      </GoAAppHeader>
    </>
  );
}
