// apps/angular-demo/src/app/app-header/app-header.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "abgov-app-header",
  templateUrl: "./app-header.component.html",
  styleUrls: ["./app-header.component.css"],
})
export class AppHeaderComponent {
  constructor() {}
}

<h1>Header</h1>

<h2>Basic</h2>
<goa-app-header url="example.com"></goa-app-header>

<h2>Heading</h2>
<goa-app-header
  url="https://example.com"
  heading="Ticket and Fine Payments"
></goa-app-header>

<h2>Custom Content</h2>
<goa-app-header url="https://example.com" heading="Ticket and Fine Payments">
  <a title="loginUrl" href="#">Login</a>
</goa-app-header>

// apps/react-demo/src/routes/appHeader.tsx
import { GoAAppHeader } from "@abgov/react-components";
import * as React from "react";

export default function AppHeader() {
  return (
    <>
      <h1>App Header</h1>

      <h2>Basic</h2>
      <GoAAppHeader url="https://example.com" />

      <h2>Title</h2>
      <GoAAppHeader
        url="https://example.com"
        heading="Ticket and Fine Payments"
      ></GoAAppHeader>

      <h2>Custom Content</h2>
      <GoAAppHeader
        url="https://example.com"
        heading="Ticket and Fine Payments"
      >
        <a title="loginUrl" href="#">
          Login
        </a>
      </GoAAppHeader>
    </>
  );
}
