// _templates/angular/src/app/button-component/button.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "goab-button-component",
  templateUrl: "./button.component.html",
})
export class ButtonComponent {
  constructor() {}

  onClick() {
    console.log("clicked");
  }
}

<h1>Button</h1>

<h2>Types</h2>
<goab-button (onClick)="onClick()" type="submit">Submit</goab-button>
<goab-button (onClick)="onClick()" type="secondary">Secondary</goab-button>
<goab-button (onClick)="onClick()" type="submit" ml="xl" mr="xl" mb="xl" mt="l">
  Get Started here
</goab-button>
<goab-button (onClick)="onClick()" type="tertiary">Tertiary</goab-button>
<goab-button (onClick)="onClick()" type="start">Get Started</goab-button>

<goab-button-group gap="compact" align="left">
  <goab-button (onClick)="onClick()" type="submit"> Get Started </goab-button>
  <goab-button (onClick)="onClick()" type="tertiary">Tertiary</goab-button>
  <goab-button (onClick)="onClick()" type="start">Get Started</goab-button>
</goab-button-group>

<h2>Disabled</h2>
<goab-button (onClick)="onClick()" type="primary" [disabled]="true">Primary</goab-button>
<goab-button (onClick)="onClick()" type="secondary" [disabled]="true">
  Secondary
</goab-button>
<goab-button (onClick)="onClick()" type="tertiary" [disabled]="true">Tertiary</goab-button>
<goab-button (onClick)="onClick()" type="start" [disabled]="true">Get Started</goab-button>

<h2>Sizes</h2>
<goab-button size="compact" (onClick)="onClick()" type="primary">
  Compact Primary
</goab-button>
<goab-button size="compact" (onClick)="onClick()" type="secondary">
  Compact Secondary
</goab-button>
<goab-button size="compact" (onClick)="onClick()" type="tertiary">
  Compact Tertiary
</goab-button>

<h2>Icons</h2>
<goab-button-group gap="relaxed" align="left">
  <goab-button leadingicon="airplane" (onClick)="onClick()" type="primary">
    Leading
  </goab-button>
  <goab-button trailingIcon="airplane" (onClick)="onClick()" type="primary">
    Trailing
  </goab-button>
  <goab-button leadingicon="archive" trailingicon="airplane" (onClick)="onClick()" type="primary">
    Both
  </goab-button>
</goab-button-group>

<h2>Margin Spacing</h2>

<goab-button mt="m" mb="xs" ml="xl" mr="2xl" (onClick)="onClick()" type="submit">Submit</goab-button>

// apps/react-demo/src/routes/button.tsx
import * as React from "react";
import { GoAButton } from "@abgov/react-components";

export default function Button() {
  function onClick() {
    console.log("clicked");
  }

  return (
    <>
      <h1>Button</h1>
      <h2>Types</h2>
      <GoAButton onClick={() => onClick()} type="primary">
        Primary
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="submit">
        Submit
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="secondary">
        Secondary
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="tertiary">
        Tertiary
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="start">
        Get Started
      </GoAButton>

      <h2>Disabled</h2>
      <GoAButton onClick={() => onClick()} type="primary" disabled>
        Primary
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="secondary" disabled={true}>
        Secondary
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="tertiary" disabled>
        Tertiary
      </GoAButton>
      <GoAButton onClick={() => onClick()} type="start" disabled>
        Get Started
      </GoAButton>

      <h2>Sizes</h2>
      <GoAButton size="compact" onClick={() => onClick()} type="primary">
        Compact Primary
      </GoAButton>
      <GoAButton size="compact" onClick={() => onClick()} type="secondary">
        Compact Secondary
      </GoAButton>
      <GoAButton size="compact" onClick={() => onClick()} type="tertiary">
        Compact Tertiary
      </GoAButton>

      <h2>Icons</h2>
      <GoAButton
        leadingIcon="airplane"
        onClick={() => onClick()}
        type="primary"
      >
        Leading
      </GoAButton>
      <GoAButton
        trailingIcon="airplane"
        onClick={() => onClick()}
        type="primary"
      >
        Trailing
      </GoAButton>
      <GoAButton
        leadingIcon="archive"
        trailingIcon="airplane"
        onClick={() => onClick()}
        type="primary"
      >
        Both
      </GoAButton>

      <h2>Margin Spacing</h2>
      <GoAButton
        mt="m"
        mb="xs"
        ml="xl"
        mr="2xl"
        size="compact"
        onClick={() => onClick()}
        type="primary"
      >
        Compact Primary
      </GoAButton>
    </>
  );
}
