// apps/angular-tests/src/app/callout/callout.component.ts
import { GoABCallout } from "@abgov/angular-components";
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-callout",
  templateUrl: "./callout.component.html",
  imports: [
    GoABCallout,
  ]
})
export class CalloutComponent {
  constructor() { }
}

<h1>Callout</h1>

<h2>Emergency</h2>
<goab-callout type="emergency" heading="Emergency callout">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Important</h2>
<goab-callout type="important" heading="Important callout">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Information</h2>
<goab-callout type="information" heading="Information callout">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Success</h2>
<goab-callout type="success" heading="Success callout">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Events</h2>
<goab-callout type="event" heading="Event callout">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Emergency</h2>
<goab-callout type="emergency">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Important</h2>
<goab-callout type="important">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Information</h2>
<goab-callout type="information">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Success</h2>
<goab-callout type="success">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Events</h2>
<goab-callout type="event">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Margin Spacing</h2>
<goab-callout type="emergency" mt="m" mb="xs" ml="xl" mr="2xl" heading="Emergency callout">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

<h2>Medium Callout</h2>

<h3>Information</h3>
<goab-callout type="information" heading="Heading" size="medium">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</goab-callout>

// apps/react-demo/src/routes/callout.tsx
import { GoACallout } from '@abgov/react-components';
import * as React from 'react';

export default function Callout() {
  return (
    <>
      <h3>Emergency</h3>
      <GoACallout type="emergency" heading="Emergency callout">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </GoACallout>

      <br />
      <h3>Important</h3>
      <GoACallout type="important" heading="Important callout">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </GoACallout>

      <br />
      <h3>Information</h3>
      <GoACallout type="information" heading="Information callout">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </GoACallout>

      <br />
      <h3>Success</h3>
      <GoACallout type="success" heading="Success callout">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </GoACallout>

      <br />
      <h3>Events</h3>
      <GoACallout type="event" heading="Event callout">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </GoACallout>
    </>
  );
}
