// _templates/angular/src/app/divider/divider.component.ts
import { GoABDivider } from "@abgov/angular-components";
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-divider",
  templateUrl: "./divider.component.html",
  imports: [
    GoABDivider,
  ]
})
export class DividerComponent {
  constructor() { }
}

<h1>Spacing</h1>
<h2>Small</h2>
<goab-divider mt="s" mb="s"></goab-divider>
<h2>Medium</h2>
<goab-divider mt="m" mb="m"></goab-divider>
<h2>Large</h2>
<goab-divider mt="l" mb="l"></goab-divider>
<h2>None</h2>
<goab-divider></goab-divider>

// apps/react-demo/src/routes/divider.tsx
import { GoADivider } from "@abgov/react-components";

export default function Divider() {
  return (
    <>
      <h1>Divider</h1>

      <h2>Small</h2>
      <GoADivider spacing="small"></GoADivider>
      <h2>Medium</h2>
      <GoADivider spacing="medium"></GoADivider>
      <h2>Large</h2>
      <GoADivider spacing="large"></GoADivider>
      <h2>None</h2>
      <GoADivider spacing="none"></GoADivider>
    </>
  );
}
