// apps/angular-demo/src/app/form-item/form-item.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'abgov-form-item',
  templateUrl: './form-item.component.html',
  styleUrls: ['./form-item.component.css']
})
export class FormItemComponent {

  constructor() { }

}

<h3>Basic</h3>
<goa-form-item label="First name">
  <goa-input type="text"></goa-input>
</goa-form-item>

<br />
<h3>Optional</h3>
<goa-form-item label="First name" optional>
  <goa-input type="text"></goa-input>
</goa-form-item>

<br />
<h3>Help text</h3>
<goa-form-item label="First name" helptext="Help text">
  <goa-input type="text"></goa-input>
</goa-form-item>

<br />
<h3>Required</h3>
<goa-form-item
  label="First name"
  error="First name is required"
  helptext="Help text"
>
  <goa-input type="text" error></goa-input>
</goa-form-item>

<br />
<h3>Form row</h3>
<goa-form-row gap="small">
  <goa-form-item
    label="First name"
    error="First name is required"
    helpText="Help text"
  >
    <goa-input
      name="firstName"
      error
      width="100%"
      showCounter="true"
      maxCharCount="20"
    ></goa-input>
  </goa-form-item>
  <goa-form-item
    label="Last name"
    error="Last name is required"
    helpText="Help text"
  >
    <goa-input name="lastName" error width="100%"></goa-input>
  </goa-form-item>
</goa-form-row>

// apps/react-demo/src/routes/formItem.tsx
import { GoAFormItem, GoAFlexRow, GoAInput } from '@abgov/react-components';
import * as React from 'react';

export default function FormItem() {
  return (
    <>
      <h3>Basic</h3>
      <GoAFormItem label="First name">
        <GoAInput name="firstName" value="" onChange={() => void 0} type="text"></GoAInput>
      </GoAFormItem>

      <br />
      <h3>Optional</h3>
      <GoAFormItem label="First name" optional>
        <GoAInput name="firstName2" value="" onChange={() => void 0} type="text"></GoAInput>
      </GoAFormItem>

      <br />
      <h3>Help text</h3>
      <GoAFormItem label="First name" helpText="Help text">
        <GoAInput name="firstName3" value="" onChange={() => void 0} type="text"></GoAInput>
      </GoAFormItem>

      <br />
      <h3>Required</h3>
      <GoAFormItem
        label="First name"
        error="First name is required"
        helpText="Help text"
      >
        <GoAInput name="firstName4" value="" onChange={() => void 0} type="text" error></GoAInput>
      </GoAFormItem>

      <br />
      <h3>Form row</h3>
      <GoAFlexRow gap="small">
        <GoAFormItem
          label="First name"
          error="First name is required"
          helpText="Help text"
        >
          <GoAInput
            name="firstName5" value="" onChange={() => void 0}
            type="text"
            error
            width="100%"
            showCounter={true}
            maxCharCount={20}
          ></GoAInput>
        </GoAFormItem>
        <GoAFormItem
          label="Last name"
          error="Last name is required"
          helpText="Help text"
        >
          <GoAInput name="lasstName" value="" onChange={() => void 0} type="text" error width="100%"></GoAInput>
        </GoAFormItem>
      </GoAFlexRow>
    </>
  );
}
