// _templates/angular/src/app/notification-banner/notification-banner.component.ts
import { GoABNotificationBanner } from "@abgov/angular-components";
import { Component } from "@angular/core";

@Component({
  standalone: true,
  selector: "abgov-notification-banner",
  templateUrl: "./notification-banner.component.html",
  imports: [
    GoABNotificationBanner,
  ]
})
export class NotificationBannerComponent {
  constructor() { }

  onDismiss() {
    console.log("dismissed");
  }
}

<h1>Notification Banner</h1>

<h2>Information</h2>
<goab-notification type="information" (onDismiss)="onDismiss()" arialive="polite">Lorem ipsum dolor
  <a href="https://example.com">Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor
    sit amet, consectetur adipiscing elit.</a>
  Lorem ipsum dolor</goab-notification>
<h2>Important</h2>
<goab-notification type="important" (onDismiss)="onDismiss()" arialive="assertive"><a href="https://example.com">Lorem
    ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor
    sit amet, consectetur adipiscing elit.</a></goab-notification>
<h2>Emergency</h2>
<goab-notification type="emergency" (onDismiss)="onDismiss()" arialive="assertive"><a href="https://example.com">Lorem
    ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum dolor
    sit amet, consectetur adipiscing elit.</a></goab-notification>
<h2>Event</h2>
<goab-notification type="event" (onDismiss)="onDismiss()" arialive="off">Lorem ipsum dolor sit amet, consectetur
  adipiscing elit.</goab-notification>

// apps/react-demo/src/routes/notificationBanner.tsx
import { GoANotification } from "@abgov/react-components";

export default function NotificationBanner() {
  function onDismiss() {
    console.log("dismissed");
  }

  return (
    <>
      <h1>Notification Banner</h1>

      <h2>Information</h2>
      <GoANotification type="information" onDismiss={() => onDismiss()}>
        Lorem ipsum dolor{" "}
        <a href="https://example.com">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum
          dolor sit amet, consectetur adipiscing elit.
        </a>{" "}
        Lorem ipsum dolor
      </GoANotification>
      <h2>Important</h2>
      <GoANotification type="important" onDismiss={() => onDismiss()}>
        <a href="https://example.com">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum
          dolor sit amet, consectetur adipiscing elit.
        </a>
      </GoANotification>
      <h2>Emergency</h2>
      <GoANotification type="emergency" onDismiss={() => onDismiss()}>
        <a href="https://example.com">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum
          dolor sit amet, consectetur adipiscing elit.
        </a>
      </GoANotification>
      <h2>Event</h2>
      <GoANotification type="event" onDismiss={() => onDismiss()}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit Lorem ipsum
        dolor sit amet, consectetur adipiscing elit.
      </GoANotification>
    </>
  );
}
