// apps/angular-demo/src/app/popover/popover.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "abgov-popover",
  templateUrl: "./popover.component.html",
})
export class PopoverComponent {
  constructor() {}

  onClick() {
    console.log("clicked");
  }
}

<h2>Popover</h2>
<h3>Basic</h3>
<goa-popover>
  <h3>interactable content</h3>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi tempora optio
    illum iste consectetur harum vel voluptatem eos quos deleniti, sequi
    sapiente porro culpa repellendus eligendi in architecto natus omnis. Lorem
    ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, nam
    corporis. Omnis tempora non aspernatur nostrum pariatur quibusdam magni eum
    vitae similique, laboriosam reiciendis repellat sapiente. Nobis laudantium
    facilis incidunt!
  </p>
  <goa-button-group>
    <goa-button type="primary" (_click)="onClick()">Primary</goa-button>
    <goa-button type="submit" (_click)="onClick()">Submit</goa-button>
    <goa-button type="secondary" (_click)="onClick()">Secondary</goa-button>
  </goa-button-group>
  <div slot="target" style="white-space: nowrap">
    <goa-button type="secondary" size="compact">Open Popover</goa-button>
  </div>
</goa-popover>

<h3>Dynamic Positioning</h3>
<goa-block direction="column" gap="4xl">
  <goa-block style="width: 100%">
    <goa-popover>
      <span>This</span>
      <div slot="target" style="white-space: nowrap">
        <goa-button type="secondary" size="compact">Click me</goa-button>
      </div>
    </goa-popover>
    <goa-spacer hspacing="fill"></goa-spacer>
    <goa-popover maxwidth="500px">
      <span
        >Lorem ipsum dolor sit amet consectetur, adipisicing elit. Obcaecati
        sapiente natus, asperiores qui eligendi reiciendis. Porro placeat qui
        laboriosam minus nihil nam aliquam necessitatibus! Doloremque corrupti
        quia ex eligendi deserunt.</span
      >
      <div slot="target" style="white-space: nowrap">
        <goa-button type="secondary" size="compact">Click me</goa-button>
      </div>
    </goa-popover>
  </goa-block>
  <goa-block style="width: 100%">
    <goa-spacer hspacing="fill"></goa-spacer>
    <goa-popover>
      <h3>This is a popover</h3>
      <p>It can be used for a number of different contexts.</p>
      <div slot="target" style="white-space: nowrap">
        <goa-button type="secondary" size="compact">Click me</goa-button>
      </div>
    </goa-popover>
    <goa-spacer hspacing="fill"></goa-spacer>
  </goa-block>
  <goa-block style="width: 100%">
    <goa-popover>
      <h3>This is a popover</h3>
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas optio
        debitis, dicta sequi dignissimos odio quis aliquam voluptatibus nihil
        officiis iusto nobis consequuntur quia non ducimus totam ratione? Earum,
        mollitia.
      </p>
      <div slot="target" style="white-space: nowrap">
        <goa-button type="secondary" size="compact">Click me</goa-button>
      </div>
    </goa-popover>
    <goa-spacer hspacing="fill"></goa-spacer>
    <goa-popover maxwidth="500px">
      <h3>This is a popover</h3>
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus eligendi
        consectetur ullam recusandae! Eveniet, earum sequi aut iure et quia?
        Hic, ipsa perferendis. Et reprehenderit consequatur quod minus illo
        amet!
      </p>
      <div slot="target" style="white-space: nowrap">
        <goa-button type="secondary" size="compact">Click me</goa-button>
      </div>
    </goa-popover>
  </goa-block>
</goa-block>

// apps/react-demo/src/routes/popover.tsx
import {
  GoAPopover,
  GoAButtonGroup,
  GoAButton,
  GoASpacer,
  GoABlock,
} from "@abgov/react-components";

export default function Popover() {
  return (
    <>
      <h2>Popover</h2>
      <h3>Basic</h3>
      <GoAPopover>
        <h3>interactable content</h3>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi tempora
          optio illum iste consectetur harum vel voluptatem eos quos deleniti,
          sequi sapiente porro culpa repellendus eligendi in architecto natus
          omnis. Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Repudiandae, nam corporis. Omnis tempora non aspernatur nostrum
          pariatur quibusdam magni eum vitae similique, laboriosam reiciendis
          repellat sapiente. Nobis laudantium facilis incidunt!
        </p>
        <GoAButtonGroup alignment="start">
          <GoAButton type="primary">Primary</GoAButton>
          <GoAButton type="submit">Submit</GoAButton>
          <GoAButton type="secondary">Secondary</GoAButton>
        </GoAButtonGroup>
        <div slot="target" style={{ whiteSpace: "nowrap" }}>
          <GoAButton type="secondary" size="compact">
            Open Popover
          </GoAButton>
        </div>
      </GoAPopover>

      <h3>Dynamic Positioning</h3>
      <GoABlock direction="column" gap="4xl">
        <div style={{ width: "100%", display: "flex" }}>
          <GoAPopover>
            <span>This</span>
            <div slot="target" style={{ whiteSpace: "nowrap" }}>
              <GoAButton type="secondary" size="compact">
                Click me
              </GoAButton>
            </div>
          </GoAPopover>
          <GoASpacer hSpacing="fill"></GoASpacer>
          <GoAPopover maxWidth="500px">
            <span>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Obcaecati sapiente natus, asperiores qui eligendi reiciendis.
              Porro placeat qui laboriosam minus nihil nam aliquam
              necessitatibus! Doloremque corrupti quia ex eligendi deserunt.
            </span>
            <div slot="target" style={{ whiteSpace: "nowrap" }}>
              <GoAButton type="secondary" size="compact">
                Click me
              </GoAButton>
            </div>
          </GoAPopover>
        </div>
        <div style={{ width: "100%", display: "flex" }}>
          <GoASpacer hSpacing="fill"></GoASpacer>
          <GoAPopover>
            <h3>This is a popover</h3>
            <p>It can be used for a number of different contexts.</p>
            <div slot="target" style={{ whiteSpace: "nowrap" }}>
              <GoAButton type="secondary" size="compact">
                Click me
              </GoAButton>
            </div>
          </GoAPopover>
          <GoASpacer hSpacing="fill"></GoASpacer>
        </div>
        <div style={{ width: "100%", display: "flex" }}>
          <GoAPopover>
            <h3>This is a popover</h3>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quas
              optio debitis, dicta sequi dignissimos odio quis aliquam
              voluptatibus nihil officiis iusto nobis consequuntur quia non
              ducimus totam ratione? Earum, mollitia.
            </p>
            <div slot="target" style={{ whiteSpace: "nowrap" }}>
              <GoAButton type="secondary" size="compact">
                Click me
              </GoAButton>
            </div>
          </GoAPopover>
          <GoASpacer hSpacing="fill"></GoASpacer>
          <GoAPopover maxWidth="500px">
            <h3>This is a popover</h3>
            <p>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Minus
              eligendi consectetur ullam recusandae! Eveniet, earum sequi aut
              iure et quia? Hic, ipsa perferendis. Et reprehenderit consequatur
              quod minus illo amet!
            </p>
            <div slot="target" style={{ whiteSpace: "nowrap" }}>
              <GoAButton type="secondary" size="compact">
                Click me
              </GoAButton>
            </div>
          </GoAPopover>
        </div>
      </GoABlock>
    </>
  );
}
