// libs/react-components/src/lib/checkbox-list/checkbox-list.tsx
import {
  GoabCheckboxListOnChangeDetail,
  Margins,
  Spacing,
} from "@abgov/ui-components-common";
import { useEffect, useRef, type JSX } from "react";

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-checkbox-list": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

interface WCProps extends Margins {
  ref: React.RefObject<HTMLElement | null>;
  name: string;
  selectedvalues?: string[];
  disabled?: string;
  error?: string;
  testid?: string;
  arialabel?: string;
  description?: string;
  orientation?: "vertical" | "horizontal";
  maxwidth?: string;
  showselectall?: string;
  selectalltext?: string;
  // child margins (applied to child checkboxes if they don't already declare that side)
  mlchild?: Spacing | string | null;
  mrchild?: Spacing | string | null;
  mtchild?: Spacing | string | null;
  mbchild?: Spacing | string | null;
}

export interface GoabCheckboxListProps extends Margins {
  name: string;
  value?: string[];
  disabled?: boolean;
  error?: boolean;
  testId?: string;
  ariaLabel?: string;
  description?: string | React.ReactNode;
  orientation?: "vertical" | "horizontal";
  maxWidth?: string;
  showSelectAll?: boolean;
  selectAllText?: string;
  children?: React.ReactNode;
  onChange?: (detail: GoabCheckboxListOnChangeDetail) => void;
  // child margins
  mlChild?: Spacing | null;
  mrChild?: Spacing | null;
  mtChild?: Spacing | null;
  mbChild?: Spacing | null;
}

export function GoabCheckboxList({
  name,
  value = [],
  disabled,
  error,
  testId,
  ariaLabel,
  description,
  orientation = "vertical",
  maxWidth,
  showSelectAll,
  selectAllText = "Select All",
  children,
  onChange,
  mt,
  mr,
  mb,
  ml,
  // child margins
  mlChild,
  mrChild,
  mtChild,
  mbChild,
}: GoabCheckboxListProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el.current) return;

    const current = el.current;
    const listener = (e: Event) => {
      try {
        const detail = (e as CustomEvent<GoabCheckboxListOnChangeDetail>).detail;
        onChange?.(detail);
      } catch (error) {
        console.error("Error handling checkbox list change:", error);
      }
    };

    try {
      current.addEventListener("_change", listener);
    } catch (error) {
      console.error("Failed to attach checkbox list listener:", error);
    }

    return () => {
      try {
        current.removeEventListener("_change", listener);
      } catch (error) {
        console.error("Failed to remove checkbox list listener:", error);
      }
    };
  }, [onChange]);

  return (
    <goa-checkbox-list
      ref={el}
      name={name}
      selectedvalues={value}
      disabled={disabled ? "true" : undefined}
      error={error ? "true" : undefined}
      testid={testId}
      arialabel={ariaLabel}
      description={typeof description === "string" ? description : undefined}
      orientation={orientation}
      maxwidth={maxWidth}
      showselectall={showSelectAll ? "true" : undefined}
      selectalltext={selectAllText}
      mt={mt}
      mr={mr}
      mb={mb}
      ml={ml}
      mlchild={mlChild as string | undefined}
      mrchild={mrChild as string | undefined}
      mtchild={mtChild as string | undefined}
      mbchild={mbChild as string | undefined}
    >
      {children}
      {typeof description !== "string" && description && (
        <div slot="description">{description}</div>
      )}
    </goa-checkbox-list>
  );
}

export default GoabCheckboxList;

// libs/angular-components/src/lib/components/checkbox-list/checkbox-list.ts
import { GoabCheckboxListOnChangeDetail } from "@abgov/ui-components-common";
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  EventEmitter,
  Input,
  Output,
  forwardRef,
  TemplateRef,
} from "@angular/core";
import { NG_VALUE_ACCESSOR } from "@angular/forms";
import { NgIf, NgTemplateOutlet } from "@angular/common";
import { GoabControlValueAccessor } from "../base.component";
// no direct child control syncing; wrapper is a thin bridge

@Component({
  standalone: true,
  selector: "goab-checkbox-list",
  template: ` <goa-checkbox-list
    [attr.name]="name"
    [attr.value]="getValueAsString()"
    [disabled]="disabled"
    [attr.error]="error"
    [attr.orientation]="orientation"
    [attr.testid]="testId"
    [attr.arialabel]="ariaLabel"
    [attr.description]="getDescriptionAsString()"
    [id]="id"
    [attr.maxwidth]="maxWidth"
    [attr.mt]="mt"
    [attr.mb]="mb"
    [attr.ml]="ml"
    [attr.mr]="mr"
    [attr.mlchild]="mlChild"
    [attr.mrchild]="mrChild"
    [attr.mbchild]="mbChild"
    [attr.mtchild]="mtChild"
    [attr.showselectall]="showSelectAll ? 'true' : undefined"
    [attr.selectalltext]="selectAllText"
    (_change)="_onChange($event)"
  >
    <ng-content />
    <div slot="description">
      <ng-container [ngTemplateOutlet]="descriptionTemplate"></ng-container>
    </div>
  </goa-checkbox-list>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      multi: true,
      useExisting: forwardRef(() => GoabCheckboxList),
    },
  ],
  imports: [NgTemplateOutlet, NgIf],
})
export class GoabCheckboxList extends GoabControlValueAccessor {
  @Input() name?: string;
  @Input() orientation: "vertical" | "horizontal" = "vertical";
  @Input() ariaLabel?: string;
  @Input() description!: string | TemplateRef<unknown>;
  @Input() maxWidth?: string;
  @Input() showSelectAll?: boolean;
  @Input() selectAllText?: string = "Select All";
  // Child margins applied to slotted checkboxes (if not explicitly set on individual child)
  @Input() mlChild?: string; // left
  @Input() mrChild?: string; // right
  @Input() mtChild?: string; // top
  @Input() mbChild?: string; // bottom

  // Override value to handle string arrays consistently
  @Input() override value?: string[];

  @Output() onChange = new EventEmitter<GoabCheckboxListOnChangeDetail>();

  private getSelectedValuesArray(): string[] {
    if (Array.isArray(this.value)) {
      return this.value;
    }
    return [];
  }

  getValueAsString(): string {
    const selectedValues = this.getSelectedValuesArray();
    return selectedValues.join(",");
  }

  getDescriptionAsString(): string {
    return typeof this.description === "string" ? this.description : "";
  }

  get descriptionTemplate(): TemplateRef<unknown> | null {
    if (this.description && typeof this.description !== "string") {
      return this.description;
    }
    return null;
  }

  _onChange(e: Event) {
    try {
      const detail = (e as CustomEvent<GoabCheckboxListOnChangeDetail>).detail;
      this.onChange.emit(detail);
      this.markAsTouched();

      // Update the form control with the selected values
      const selectedValues = detail.selectedValues || [];
      this.value = selectedValues;
      this.fcChange?.(selectedValues);
    } catch (error) {
      console.error("Error handling checkbox list change:", error);
    }
  }

  // Override writeValue to handle array inputs consistently
  override writeValue(value: string[] | string | null): void {
    try {
      if (Array.isArray(value)) {
        this.value = value;
      } else if (typeof value === "string" && value) {
        // Support legacy string format for backward compatibility
        this.value = value
          .split(",")
          .map((v) => v.trim())
          .filter(Boolean);
      } else {
        this.value = [];
      }
    } catch (error) {
      console.error("Error setting checkbox list value:", error);
      this.value = [];
    }
  }
}
