// libs/vue-components/src/lib/date-picker/date-picker.vue
<script setup lang="ts">
import type {
  GoabDatePickerInputType,
  GoabDatePickerOnChangeDetail,
  Spacing,
} from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  type?: GoabDatePickerInputType;
  name?: string;
  value?: string;
  error?: boolean;
  min?: string;
  max?: string;
  testId?: string;
  disabled?: boolean;
  width?: string;
  mt?: Spacing;
  mr?: Spacing;
  mb?: Spacing;
  ml?: Spacing;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  onChange: [detail: GoabDatePickerOnChangeDetail & { event: Event }];
}>();

const wcProps = useWcProps(props, { booleanProps: ["error", "disabled"] });
</script>

<template>
  <goa-date-picker v-bind="wcProps" @_change="emit('onChange', { ...$event.detail, event: $event })" />
</template>

// libs/angular-components/src/lib/components/date-picker/date-picker.ts
import { GoABDatePickerOnChangeDetail, Spacing } from "@abgov/ui-components-common";
import { CUSTOM_ELEMENTS_SCHEMA, Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
  standalone: true,
  selector: "goab-datepicker",
  template: `
    <goa-date-picker
      [name]="name"
      [value]="value"
      [min]="min"
      [max]="max"
      [testid]="testId"
      [mt]="mt"
      [mb]="mb"
      [ml]="ml"
      [mr]="mr"

      (_change)="_onChange($event)"
    >
    </goa-date-picker>`,
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class GoABDatePicker {
  @Input() name?: string;
  @Input() value?: Date | string;
  @Input() min?: Date | string;
  @Input() max?: Date | string;
  @Input() testId?: string;
  @Input() mt?: Spacing;
  @Input() mb?: Spacing;
  @Input() ml?: Spacing;
  @Input() mr?: Spacing;

  @Output() onChange = new EventEmitter<GoABDatePickerOnChangeDetail>();

  _onChange(e: Event) {
    const detail = (e as CustomEvent<GoABDatePickerOnChangeDetail>).detail;
    this.onChange.emit(detail)
  }
}
