// apps/react-demo/src/routes/appFooter.tsx
import {
  GoAAppFooter,
  GoAAppFooterMetaSection,
  GoAAppFooterNavSection,
} from "@abgov/react-components";
import * as React from "react";

export default function AppFooter() {
  return (
    <>
      <h1>Footer</h1>

      <h2>Default </h2>
      <GoAAppFooter />

      <h2>Footer with links to meta information</h2>
      <GoAAppFooter>
        <GoAAppFooterMetaSection>
          <a href="privacy.html">Privacy</a>
          <a href="disclaimer.html">Disclaimer</a>
          <a href="accessibility.html">Accessibility</a>
          <a href="using-alberta.html">Using Alberta.ca</a>
        </GoAAppFooterMetaSection>
      </GoAAppFooter>

      <h2>Footer with secondary navigation</h2>
      <GoAAppFooter>
        <GoAAppFooterNavSection maxColumnCount={3}>
          <a href="a.html">Arts and culture</a>
          <a href="b.html">Education and training</a>
          <a href="c.html">Family and social supports</a>
          <a href="d.html">Housing and community</a>
          <a href="e.html">Life events</a>
          <a href="instagram.html">Instagram</a>
          <a href="youtube.html">YouTube</a>
          <a href="facebook.html">Facebook</a>
          <a href="snapchat.html">Snapchat</a>
          <a href="twitter.html">Twitter</a>
        </GoAAppFooterNavSection>
      </GoAAppFooter>

      <h2>Footer with secondary navigation with multiple sections</h2>
      <GoAAppFooter>
        <GoAAppFooterNavSection heading="All Services">
          <a href="a.html">Arts and culture</a>
          <a href="b.html">Education and training</a>
          <a href="c.html">Family and social supports</a>
          <a href="d.html">Housing and community</a>
          <a href="e.html">Life events</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterNavSection heading="Social Media">
          <a href="instagram.html">Instagram</a>
          <a href="youtube.html">YouTube</a>
          <a href="facebook.html">Facebook</a>
          <a href="snapchat.html">Snapchat</a>
          <a href="twitter.html">Twitter</a>
        </GoAAppFooterNavSection>
      </GoAAppFooter>

      <h2>Footer with secondary navigation with multi column section</h2>
      <GoAAppFooter>
        <GoAAppFooterNavSection heading="All Services" maxColumnCount={2}>
          <a href="a.html">Arts and culture</a>
          <a href="b.html">Education and training</a>
          <a href="c.html">Family and social supports</a>
          <a href="d.html">Housing and community</a>
          <a href="e.html">Life events</a>
          <a href="f.html">Business and economy</a>
          <a href="g.html">Emergencies and public safety</a>
          <a href="h.html">Government</a>
          <a href="i.html">Jobs and employment</a>
          <a href="j.html">Moving to Alberta</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterNavSection heading="Social Media">
          <a href="instagram.html">Instagram</a>
          <a href="youtube.html">YouTube</a>
          <a href="facebook.html">Facebook</a>
          <a href="snapchat.html">Snapchat</a>
          <a href="twitter.html">Twitter</a>
        </GoAAppFooterNavSection>
      </GoAAppFooter>

      <h2>Footer with secondary navigation and links to meta information</h2>
      <GoAAppFooter>
        <GoAAppFooterNavSection maxColumnCount={2}>
          <a href="a.html">Arts and culture</a>
          <a href="b.html">Education and training</a>
          <a href="c.html">Family and social supports</a>
          <a href="d.html">Housing and community</a>
          <a href="e.html">Life events</a>
          <a href="instagram.html">Instagram</a>
          <a href="youtube.html">YouTube</a>
          <a href="facebook.html">Facebook</a>
          <a href="snapchat.html">Snapchat</a>
          <a href="twitter.html">Twitter</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterMetaSection>
          <a href="privacy.html">Privacy</a>
          <a href="disclaimer.html">Disclaimer</a>
          <a href="accessibility.html">Accessibility</a>
          <a href="using-alberta.html">Using Alberta.ca</a>
        </GoAAppFooterMetaSection>
      </GoAAppFooter>

      <h2>
        Footer with secondary navigation with multiple sections and links to
        meta information
      </h2>
      <GoAAppFooter>
        <GoAAppFooterNavSection heading="All Services">
          <a href="a.html">Arts and culture</a>
          <a href="b.html">Education and training</a>
          <a href="c.html">Family and social supports</a>
          <a href="d.html">Housing and community</a>
          <a href="e.html">Life events</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterNavSection heading="Social Media">
          <a href="instagram.html">Instagram</a>
          <a href="youtube.html">YouTube</a>
          <a href="facebook.html">Facebook</a>
          <a href="snapchat.html">Snapchat</a>
          <a href="twitter.html">Twitter</a>
        </GoAAppFooterNavSection>
        <GoAAppFooterMetaSection>
          <a href="privacy.html">Privacy</a>
          <a href="disclaimer.html">Disclaimer</a>
          <a href="accessibility.html">Accessibility</a>
          <a href="using-alberta.html">Using Alberta.ca</a>
        </GoAAppFooterMetaSection>
      </GoAAppFooter>
    </>
  );
}

// apps/angular-demo/src/app/app-footer/app-footer.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "abgov-app-footer",
  templateUrl: "./app-footer.component.html",
  styleUrls: ["./app-footer.component.css"],
})
export class AppFooterComponent {
  constructor() {}
}

<h3>Default Footer</h3>
<goa-app-footer id="default"></goa-app-footer>

<br />
<h3>Footer with links to meta information</h3>
<goa-app-footer id="meta-only">
  <goa-meta-link
    footerId="meta-only"
    url="privacy.html"
    title="Privacy"
  ></goa-meta-link>
  <goa-meta-link
    footerId="meta-only"
    url="disclaimer.html"
    title="Disclaimer"
  ></goa-meta-link>
  <goa-meta-link
    footerId="meta-only"
    url="accessibility.html"
    title="Accessibility"
  ></goa-meta-link>
  <goa-meta-link
    footerId="meta-only"
    url="using-alberta.html"
    title="Using Alberta.ca"
  ></goa-meta-link>
</goa-app-footer>

<br />
<h3>Footer with secondary navigation</h3>
<goa-app-footer id="navigation-only">
  <goa-navigation-link
    footerId="navigation-only"
    url="a.html"
    title="Arts and culture"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="b.html"
    title="Education and training"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="c.html"
    title="Family and social supports"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="d.html"
    title="Housing and community"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="e.html"
    title="Life events"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="instagram.html"
    title="Instagram"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="youtube.html"
    title="YouTube"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="facebook.html"
    title="Facebook"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="snapchat.html"
    title="Snapchat"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only"
    url="twitter.html"
    title="Twitter"
  ></goa-navigation-link>
</goa-app-footer>

<br />
<h3>Footer with secondary navigation with multiple sections</h3>
<goa-app-footer id="navigation-only-multisection">
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="All Services"
    url="a.html"
    title="Arts and culture"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="All Services"
    url="b.html"
    title="Education and training"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="All Services"
    url="c.html"
    title="Family and social supports"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="All Services"
    url="d.html"
    title="Housing and community"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="All Services"
    url="e.html"
    title="Life events"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="Social Media"
    url="instagram.html"
    title="Instagram"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="Social Media"
    url="youtube.html"
    title="YouTube"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="Social Media"
    url="facebook.html"
    title="Facebook"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="Social Media"
    url="snapchat.html"
    title="Snapchat"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection"
    section="Social Media"
    url="twitter.html"
    title="Twitter"
  ></goa-navigation-link>
</goa-app-footer>

<br />
<h3>Footer with secondary navigation with multi column section</h3>
<goa-app-footer
  multicolumnsectionnames="All Services"
  id="navigation-only-multisection-multicolumn"
>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="a.html"
    title="Arts and culture"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="b.html"
    title="Education and training"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="c.html"
    title="Family and social supports"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="d.html"
    title="Housing and community"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="e.html"
    title="Life events"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="f.html"
    title="Business and economy"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="g.html"
    title="Emergencies and public safety"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="h.html"
    title="Government"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="i.html"
    title="Jobs and employment"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="All Services"
    url="j.html"
    title="Moving to Alberta"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="Social Media"
    url="instagram.html"
    title="Instagram"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="Social Media"
    url="youtube.html"
    title="YouTube"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="Social Media"
    url="facebook.html"
    title="Facebook"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="Social Media"
    url="snapchat.html"
    title="Snapchat"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation-only-multisection-multicolumn"
    section="Social Media"
    url="twitter.html"
    title="Twitter"
  ></goa-navigation-link>
</goa-app-footer>

<br />
<h3>Footer with secondary navigation and links to meta information</h3>
<goa-app-footer id="navigation and meta">
  <goa-meta-link
    footerId="navigation and meta"
    url="privacy.html"
    title="Privacy"
  ></goa-meta-link>
  <goa-meta-link
    footerId="navigation and meta"
    url="disclaimer.html"
    title="Disclaimer"
  ></goa-meta-link>
  <goa-meta-link
    footerId="navigation and meta"
    url="accessibility.html"
    title="Accessibility"
  ></goa-meta-link>
  <goa-meta-link
    footerId="navigation and meta"
    url="using-alberta.html"
    title="Using Alberta.ca"
  ></goa-meta-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="a.html"
    title="Arts and culture"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="b.html"
    title="Education and training"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="c.html"
    title="Family and social supports"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="d.html"
    title="Housing and community"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="e.html"
    title="Life events"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="instagram.html"
    title="Instagram"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="youtube.html"
    title="YouTube"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="facebook.html"
    title="Facebook"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="snapchat.html"
    title="Snapchat"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="navigation and meta"
    url="twitter.html"
    title="Twitter"
  ></goa-navigation-link>
</goa-app-footer>

<br />
<h3>
  Footer with secondary navigation with multiple sections and links to meta
  information
</h3>
<goa-app-footer id="meta-and-navigation-multisection">
  <goa-meta-link
    footerId="meta-and-navigation-multisection"
    url="privacy.html"
    title="Privacy"
  ></goa-meta-link>
  <goa-meta-link
    footerId="meta-and-navigation-multisection"
    url="disclaimer.html"
    title="Disclaimer"
  ></goa-meta-link>
  <goa-meta-link
    footerId="meta-and-navigation-multisection"
    url="accessibility.html"
    title="Accessibility"
  ></goa-meta-link>
  <goa-meta-link
    footerId="meta-and-navigation-multisection"
    url="using-alberta.html"
    title="Using Alberta.ca"
  ></goa-meta-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="All Services"
    url="a.html"
    title="Arts and culture"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="All Services"
    url="b.html"
    title="Education and training"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="All Services"
    url="c.html"
    title="Family and social supports"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="All Services"
    url="d.html"
    title="Housing and community"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="All Services"
    url="e.html"
    title="Life events"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="Social Media"
    url="instagram.html"
    title="Instagram"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="Social Media"
    url="youtube.html"
    title="YouTube"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="Social Media"
    url="facebook.html"
    title="Facebook"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="Social Media"
    url="snapchat.html"
    title="Snapchat"
  ></goa-navigation-link>
  <goa-navigation-link
    footerId="meta-and-navigation-multisection"
    section="Social Media"
    url="twitter.html"
    title="Twitter"
  ></goa-navigation-link>
</goa-app-footer>
