// libs/vue-components/src/lib/skeleton/skeleton.vue
<script setup lang="ts">
import type { GoabSkeletonSize, GoabSkeletonType, Spacing } from "@abgov/ui-components-common";
import { useWcProps } from "../common/useWcProps";

interface Props {
  /** @required Sets the skeleton shape to represent your content.  @default (required) */
  type: GoabSkeletonType;
  /** Size can affect either the height, width or both for different skeleton types. @default "1" */
  size?: GoabSkeletonSize;
  /** Sets the maximum width. Currently only used in card skeleton type. @default "300px" */
  maxWidth?: string;
  /** Used within components that contain multiple lines. Currently only used in card skeleton type. @default 3 */
  lineCount?: number;
  /** Sets a data-testid attribute for automated testing.  @default "" */
  testId?: string;
  /** Sets the mt.  @default null */
  mt?: Spacing;
  /** Sets the mr.  @default null */
  mr?: Spacing;
  /** Sets the mb.  @default null */
  mb?: Spacing;
  /** Sets the ml.  @default null */
  ml?: Spacing;
}

const props = defineProps<Props>();
const wcProps = useWcProps(props);
</script>

<template>
  <goa-skeleton v-bind="wcProps" />
</template>

// libs/angular-components/src/lib/components/skeleton/skeleton.ts
import { GoabSkeletonSize, GoabSkeletonType, Spacing } from "@abgov/ui-components-common";
import {
  CUSTOM_ELEMENTS_SCHEMA,
  Component,
  Input,
  numberAttribute,
  OnInit,
  ChangeDetectorRef,
} from "@angular/core";

import { GoabBaseComponent } from "../base.component";

@Component({
  standalone: true,
  selector: "goab-skeleton",
  template: `
    @if (isReady) {
      <goa-skeleton
        [attr.maxwidth]="maxWidth"
        [attr.size]="size"
        [attr.linecount]="lineCount"
        [attr.type]="type"
        [attr.testid]="testId"
        [attr.mt]="mt"
        [attr.mb]="mb"
        [attr.ml]="ml"
        [attr.mr]="mr"
      >
      </goa-skeleton>
    }
  `,

  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class GoabSkeleton extends GoabBaseComponent implements OnInit {
  isReady = false;
  /** Sets the skeleton shape to represent your content. */
  @Input({ required: true }) type!: GoabSkeletonType;
  /**
   * Sets the maximum width. Currently only used in card skeleton type.
   * @default "300px"
   */
  @Input() maxWidth = "300px";
  /**
   * Size can affect either the height, width or both for different skeleton types.
   * @default "1"
   */
  @Input() size?: GoabSkeletonSize;
  /**
   * Used within components that contain multiple lines. Currently only used in card skeleton type
   * @default 3
   */
  @Input({ transform: numberAttribute }) lineCount?: number;

  constructor(private cdr: ChangeDetectorRef) {
    super();
  }

  ngOnInit(): void {
    setTimeout(() => {
      this.isReady = true;
      this.cdr.detectChanges();
    });
  }
}
