// apps/react-demo/src/routes/modal.tsx
import * as React from "react";
import {
  GoAButton,
  GoAModal,
  GoAButtonGroup,
  ModalTransition,
  CalloutVariant
} from "@abgov/react-components";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function Modal() {
  const navigate = useNavigate();

  const [showModal, setShowModal] = useState(false);
  const [showModal2, setShowModal2] = useState(false);
  const [showModal3, setShowModal3] = useState(false);
  const [speed, setSpeed] = useState<ModalTransition>("none");
  const [calloutVariant, setCalloutVariant] = useState<CalloutVariant>();
  
  function showCallout(calloutVariant: CalloutVariant) {
    setCalloutVariant(calloutVariant);
    setShowModal(true);
  }

  function show(speed: ModalTransition) {
    setSpeed(speed);
    setShowModal3(true);
  }

  return (
    <>
    <h2>Basic</h2>
      <GoAButton onClick={() => setShowModal(true)}>Open Basic Modal</GoAButton>
      <GoAModal
        heading="Do you agree?"
        open={showModal}
        onClose={() => setShowModal(false)}
      >
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia
          obcaecati id molestiae, natus dicta, eaque qui iusto similique, libero
          explicabo eligendi eius laboriosam! Repellendus ducimus officia
          asperiores. Eos, eius numquam.
        </p>
      </GoAModal>

      <br />
    <h2>Modal with Actions</h2>
      <GoAButton onClick={() => setShowModal2(true)}>
        {" "}
        Open Modal with actions
      </GoAButton>
      <GoAModal heading="Do you agree?" open={showModal2} transition="fast">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia
          obcaecati id molestiae, natus dicta, eaque qui iusto similique, libero
          explicabo eligendi eius laboriosam! Repellendus ducimus officia
          asperiores. Eos, eius numquam.
        </p>
        <GoAButtonGroup alignment="end">
          <GoAButton type="secondary" onClick={() => setShowModal2(false)}>
            Secondary
          </GoAButton>
          <GoAButton onClick={() => setShowModal2(false)}> Primary</GoAButton>
        </GoAButtonGroup>
      </GoAModal>

      <br />
    <h2>Transitions</h2>
      <GoAButtonGroup alignment="start">
        <GoAButton type="tertiary" onClick={() => show("none")}>
          None
        </GoAButton>
        <GoAButton type="tertiary" onClick={() => show("slow")}>
          {" "}
          Slow
        </GoAButton>
        <GoAButton type="tertiary" onClick={() => show("fast")}>
          {" "}
          Fast
        </GoAButton>
      </GoAButtonGroup>
      <GoAModal
        heading="Do you agree?"
        open={showModal3}
        onClose={() => setShowModal2(false)}
        transition={speed}
      >
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia
          obcaecati id molestiae, natus dicta, eaque qui iusto similique, libero
          explicabo eligendi eius laboriosam! Repellendus ducimus officia
          asperiores. Eos, eius numquam.
        </p>

        <GoAButton
          type="primary"
          onClick={() => {
            setShowModal3(false);
            // setTimeout(() => navigate("/input"), 300) } // will allow any modal animations to be run
            navigate("/input");
          }}
        >
          Click
        </GoAButton>
      </GoAModal>
      
      <br/>
    <h2>Callout Variants</h2>
      <GoAButtonGroup alignment="start">
        <GoAButton onClick={() => showCallout("information")}>Information Callout</GoAButton>
        <GoAButton onClick={() => showCallout("important")}>Important Callout</GoAButton>
        <GoAButton onClick={() => showCallout("success")}>Success Callout</GoAButton>
        <GoAButton onClick={() => showCallout("emergency")}>Emergency Callout</GoAButton>
        <GoAButton onClick={() => showCallout("event")}>Event Callout</GoAButton>
      </GoAButtonGroup>
      <GoAModal
        type="callout"
        calloutVariant={calloutVariant}
        heading="Do you agree?"
        open={showModal}
        onClose={() => setShowModal(false)}
        actions={
          <GoAButtonGroup alignment="end">
            <GoAButton type="secondary" onClick={() => setShowModal(false)}>
              Secondary
            </GoAButton>
            <GoAButton type="primary" onClick={() => setShowModal(false)}>
              Primary
            </GoAButton>
          </GoAButtonGroup>
        }
      >
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia
          obcaecati id molestiae, natus dicta, eaque qui iusto similique, libero
          explicabo eligendi eius laboriosam! Repellendus ducimus officia
          asperiores. Eos, eius numquam.
        </p>
      </GoAModal>

      {/* To show scrollbars */}
      <div style={{ height: "100vh" }}></div>
    </>
  );
}

// apps/angular-demo/src/app/modal/modal.component.ts
import { Component } from "@angular/core";
import { Router } from "@angular/router";

@Component({
  selector: "abgov-modal",
  templateUrl: "./modal.component.html",
  styleUrls: ["./modal.component.css"],
})
export class ModalComponent {
  constructor(private router: Router) {}

  transition: "fast" | "slow" | "none" = "fast";
  
  calloutVariant: "information" | "important" | "success" | "emergency" | "event" = "information";

  isOpen = false;
  isOpen2 = false;
  isOpen3 = false;
  isOpen4 = false;
  isOpen5 = false;
  
  openModal() {
    this.isOpen = true;
  }

  closeModal() {
    this.isOpen = false;
  }

  openModal2() {
    this.isOpen2 = true;
  }

  closeModal2() {
    this.isOpen2 = false;
  }

  closeModal3() {
    this.isOpen3 = false;
  }

  closeModal4() {
    this.isOpen4 = false;
    setTimeout(() => this.router.navigate(["/input"]), 0);
  }
  
  closeModal5() {
    this.isOpen5 = false;
  }

  showModal(transition: "fast" | "slow" | "none") {
    this.transition = transition;
    this.isOpen3 = true;
  }
          
  showCalloutModal(calloutVariant: "information" | "important" | "success" | "emergency" | "event") {
    this.calloutVariant = calloutVariant;
    this.isOpen5 = true;
  }
}

<goa-button id="button" (_click)="openModal()">Open Basic Modal</goa-button>
<goa-modal
  id="modal"
  heading="Do you agree?"
  [open]="isOpen"
  (_close)="closeModal()"
  closable
>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia obcaecati
    id molestiae, natus dicta, eaque qui iusto similique, libero explicabo
    eligendi eius laboriosam! Repellendus ducimus officia asperiores. Eos, eius
    numquam.
  </p>
</goa-modal>

<goa-button id="button2" (_click)="openModal2()"
  >Open Modal with actions</goa-button
>
<goa-modal id="modal2" heading="Do you agree?" [open]="isOpen2">
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia obcaecati
    id molestiae, natus dicta, eaque qui iusto similique, libero explicabo
    eligendi eius laboriosam! Repellendus ducimus officia asperiores. Eos, eius
    numquam.
  </p>
  <goa-button-group alignment="end" slot="actions">
    <goa-button type="secondary" (_click)="closeModal2()">Secondary</goa-button>
    <goa-button type="primary" (_click)="closeModal2()">Primary</goa-button>
  </goa-button-group>
</goa-modal>

<goa-button-group>
  <goa-button type="tertiary" (_click)="showModal('none')">None</goa-button>
  <goa-button type="tertiary" (_click)="showModal('slow')">Slow</goa-button>
  <goa-button type="tertiary" (_click)="showModal('fast')">Fast</goa-button>
</goa-button-group>
<goa-modal
  id="modal3"
  heading="Do you agree?"
  [open]="isOpen3"
  (_close)="closeModal3()"
  closable
  [transition]="transition"
>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia obcaecati
    id molestiae, natus dicta, eaque qui iusto similique, libero explicabo
    eligendi eius laboriosam! Repellendus ducimus officia asperiores. Eos, eius
    numquam.
  </p>
</goa-modal>

<goa-button type="tertiary" (_click)="isOpen4 = true">Route Change</goa-button>
<goa-modal heading="Do you agree?" [open]="isOpen4">
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia obcaecati
    id molestiae, natus dicta, eaque qui iusto similique, libero explicabo
    eligendi eius laboriosam! Repellendus ducimus officia asperiores. Eos, eius
    numquam.
  </p>
  <goa-button-group alignment="end" slot="actions">
    <goa-button type="primary" (_click)="closeModal4()">Primary</goa-button>
  </goa-button-group>
</goa-modal>

<goa-button-group>
  <goa-button (_click)="showCalloutModal('information')">Information Callout</goa-button>
  <goa-button (_click)="showCalloutModal('important')">Important Callout</goa-button>
  <goa-button (_click)="showCalloutModal('success')">Success Callout</goa-button>
  <goa-button (_click)="showCalloutModal('emergency')">Emergency Callout</goa-button>
  <goa-button (_click)="showCalloutModal('event')">Event Callout</goa-button>
</goa-button-group>
<goa-modal type="callout" heading="Do you agree?" [open]="isOpen5" (_close)="closeModal5()" [calloutvariant]="calloutVariant" closable>
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia obcaecati id molestiae,
    natus dicta, eaque qui iusto similique, libero explicabo eligendi eius laboriosam!
    Repellendus ducimus officia asperiores. Eos, eius numquam.
  </p>
  <goa-button-group alignment="end" slot="actions">
    <goa-button (_click)="closeModal5()">Secondary</goa-button>
    <goa-button (_click)="closeModal5()">Primary</goa-button>
  </goa-button-group>
</goa-modal>

<!-- To show scrollbars -->
<div style="height: 100vh"></div>
