// apps/prs/angular/src/app/features/feat2682/feat2682.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  GoabFormItem,
  GoabDatePicker,
  GoabBlock,
  GoabText,
} from "@abgov/angular-components";
import { GoabDatePickerOnChangeDetail } from "@abgov/ui-components-common";

@Component({
  standalone: true,
  selector: "abgov-feat2682",
  templateUrl: "./feat2682.component.html",
  imports: [CommonModule, GoabFormItem, GoabDatePicker, GoabBlock, GoabText],
})
export class Feat2682Component {
  // Calculate min and max dates (one month before and after today)
  today = new Date();
  minDate = new Date(
    this.today.getFullYear(),
    this.today.getMonth() - 1,
    this.today.getDate(),
  );
  maxDate = new Date(
    this.today.getFullYear(),
    this.today.getMonth() + 1,
    this.today.getDate(),
  );

  handleDateChange(detail: GoabDatePickerOnChangeDetail): void {
    console.log("DatePicker onChange event:", detail);
  }
}

<goab-block direction="column" gap="l">
  <goab-text tag="h1" size="heading-l"
    >Feature 2682 - DatePicker Manual Testing</goab-text
  >

  <goab-text tag="p" size="body-m">
    This test demonstrates various DatePicker configurations with FormItem wrappers. Check
    the browser console for onChange events.
  </goab-text>

  <!-- Test 1: Default DatePicker -->
  <goab-form-item label="Test 1: Default DatePicker (no special properties)">
    <goab-date-picker
      name="default-datepicker"
      value="2025-10-15"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 2: Disabled DatePicker -->
  <goab-form-item label="Test 2: Disabled DatePicker">
    <goab-date-picker
      name="disabled-datepicker"
      [disabled]="true"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 3: Input type DatePicker -->
  <goab-form-item label="Test 3: Input type DatePicker">
    <goab-date-picker
      name="input-type-datepicker"
      type="input"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 4: Input type and disabled DatePicker -->
  <goab-form-item label="Test 4: Input type and disabled DatePicker">
    <goab-date-picker
      name="input-disabled-datepicker"
      type="input"
      [disabled]="true"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 5: DatePicker with min and max dates -->
  <goab-form-item label="Test 5: DatePicker with min/max dates (one month range)">
    <goab-date-picker
      name="min-max-datepicker"
      [min]="minDate"
      [max]="maxDate"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 6: Input type DatePicker with min and max dates -->
  <goab-form-item label="Test 6: Input type DatePicker with min/max dates">
    <goab-date-picker
      name="input-min-max-datepicker"
      type="input"
      [min]="minDate"
      [max]="maxDate"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 7: DatePicker with error=false -->
  <goab-form-item label="Test 7: DatePicker with error=true">
    <goab-date-picker
      name="error-false-datepicker"
      [error]="true"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>

  <!-- Test 8: Input type DatePicker with error=false -->
  <goab-form-item label="Test 8: Input type DatePicker with error=true">
    <goab-date-picker
      name="input-error-false-datepicker"
      type="input"
      [error]="true"
      (onChange)="handleDateChange($event)"
    >
    </goab-date-picker>
  </goab-form-item>
</goab-block>

// apps/prs/react/src/app/routes.tsx/features/feat2682.tsx
import React from "react";
import { GoabFormItem } from "@abgov/react-components";
import { GoabDatePicker } from "@abgov/react-components";
import { GoabBlock } from "@abgov/react-components";
import { GoabText } from "@abgov/react-components";
import { GoabDatePickerOnChangeDetail } from "@abgov/ui-components-common";

export function Feat2682Route() {
  const handleDateChange = (detail: GoabDatePickerOnChangeDetail) => {
    console.log("DatePicker onChange event:", detail);
  };

  // Calculate min and max dates (one month before and after today)
  const today = new Date();
  const minDate = new Date(today.getFullYear(), today.getMonth() - 1, today.getDate());
  const maxDate = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());

  return (
    <GoabBlock direction="column" gap="l">
      <GoabText tag="h1" size="heading-l">
        Feature 2682 - DatePicker Manual Testing
      </GoabText>

      <GoabText tag="p" size="body-m">
        This test demonstrates various DatePicker configurations with FormItem wrappers.
        Check the browser console for onChange events.
      </GoabText>

      {/* Test 1: Default DatePicker */}
      <GoabFormItem label="Test 1: Default DatePicker (no special properties)">
        <GoabDatePicker name="default-datepicker" onChange={handleDateChange} />
      </GoabFormItem>

      {/* Test 2: Disabled DatePicker */}
      <GoabFormItem label="Test 2: Disabled DatePicker">
        <GoabDatePicker
          name="disabled-datepicker"
          disabled={true}
          onChange={handleDateChange}
        />
      </GoabFormItem>

      {/* Test 3: Input type DatePicker */}
      <GoabFormItem label="Test 3: Input type DatePicker">
        <GoabDatePicker
          name="input-type-datepicker"
          type="input"
          onChange={handleDateChange}
        />
      </GoabFormItem>

      {/* Test 4: Input type and disabled DatePicker */}
      <GoabFormItem label="Test 4: Input type and disabled DatePicker">
        <GoabDatePicker
          name="input-disabled-datepicker"
          type="input"
          disabled={true}
          onChange={handleDateChange}
        />
      </GoabFormItem>

      {/* Test 5: DatePicker with min and max dates */}
      <GoabFormItem label="Test 5: DatePicker with min/max dates (one month range)">
        <GoabDatePicker
          name="min-max-datepicker"
          min={minDate}
          max={maxDate}
          onChange={handleDateChange}
        />
      </GoabFormItem>

      {/* Test 6: Input type DatePicker with min and max dates */}
      <GoabFormItem label="Test 6: Input type DatePicker with min/max dates">
        <GoabDatePicker
          name="input-min-max-datepicker"
          type="input"
          min={minDate}
          max={maxDate}
          onChange={handleDateChange}
        />
      </GoabFormItem>

      {/* Test 7: DatePicker with error=true */}
      <GoabFormItem label="Test 7: DatePicker with error=true">
        <GoabDatePicker
          name="error-false-datepicker"
          error={true}
          onChange={handleDateChange}
        />
      </GoabFormItem>

      {/* Test 8: Input type DatePicker with error=true */}
      <GoabFormItem label="Test 8: Input type DatePicker with error=true">
        <GoabDatePicker
          name="input-error-false-datepicker"
          type="input"
          error={true}
          onChange={handleDateChange}
        />
      </GoabFormItem>
    </GoabBlock>
  );
}
