// libs/react-components/src/lib/push-drawer/push-drawer.tsx
import { ReactNode, useEffect, useRef, type JSX } from "react";

interface WCProps {
  open?: boolean;
  heading?: string;
  width?: string;
  testid?: string;
  version?: string;
  ref: React.RefObject<HTMLElement | null>;
}

declare module "react" {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace JSX {
    interface IntrinsicElements {
      "goa-push-drawer": WCProps & React.HTMLAttributes<HTMLElement>;
    }
  }
}

export interface GoabPushDrawerProps {
  /** @required Content rendered inside the push drawer body. */
  children: ReactNode;
  /** @required Callback fired when the push drawer is closed. */
  onClose: () => void;
  /** Controls the open/closed state of the push drawer. */
  open?: boolean;
  /** Sets the heading text or custom heading content. */
  heading?: string | ReactNode;
  /** Sets the width of the push drawer panel. @default "492px" */
  width?: string;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
  /** Content rendered in the actions slot, typically action buttons. */
  actions?: ReactNode;
}

/** A panel that pushes the main page content aside on desktop, falling back to an overlay drawer on smaller screens. */
export function GoabPushDrawer({
  open,
  heading,
  width,
  testId,
  actions,
  children,
  onClose,
}: GoabPushDrawerProps): JSX.Element {
  const el = useRef<HTMLElement>(null);

  useEffect(() => {
    if (!el?.current || !onClose) {
      return;
    }
    const current = el.current;
    const listener = (e: Event) => {
      if (e.target !== current) {
        return;
      }
      onClose();
    };
    current.addEventListener("_close", listener);
    return () => {
      current.removeEventListener("_close", listener);
    };
  }, [el, onClose]);

  return (
    <goa-push-drawer
      ref={el}
      open={open ? true : undefined}
      heading={typeof heading === "string" ? heading : undefined}
      width={width}
      testid={testId}
      version="2"
    >
      {heading && typeof heading !== "string" && <div slot="heading">{heading}</div>}
      {actions && <div slot="actions">{actions}</div>}
      {children}
    </goa-push-drawer>
  );
}

export default GoabPushDrawer;

// libs/vue-components/src/lib/push-drawer/push-drawer.vue
<script setup lang="ts">
import { useSlots } from "vue";
import { useWcProps } from "../common/useWcProps";

interface Slots {
  default?: () => unknown;
  /** Content rendered in the "actions" named slot. */
  actions?: () => unknown;
  /** Content rendered in the "heading" named slot. */
  heading?: () => unknown;
}

interface Props {
  /** Sets the heading text or custom heading content. */
  heading?: string;
  /** Controls the open/closed state of the push drawer.  @default false */
  open?: boolean;
  /** Sets the width of the push drawer panel. @default "492px" */
  width?: string;
  /** Sets a data-testid attribute for automated testing. */
  testId?: string;
}

const props = withDefaults(defineProps<Props>(), {
  open: false,
});
const emit = defineEmits<{
  /** @required Callback fired when the push drawer is closed. */
  onClose: [];
}>();

const wcProps = useWcProps(props, { booleanProps: ["open"] });
const slots = useSlots() as Slots;

function onClose(e: Event) {
  if (e.target !== e.currentTarget) return;
  emit("onClose");
}
</script>

<template>
  <goa-push-drawer v-bind="wcProps" @_close="onClose">
    <div v-if="slots.heading" slot="heading">
      <slot name="heading" />
    </div>
    <div v-if="slots.actions" slot="actions">
      <slot name="actions" />
    </div>
    <slot />
  </goa-push-drawer>
</template>
